### ISSUE TITLE
WynnCraft Forums VIP

### ISSUE THREAD

**Issue by TheCelo** [Wynncraft/Issues#1432]
Hello, i just bought VIP some days ago, when i do /forum TheCelo(My Username) It says "We can't autrhorize this account, Try Again Later" i did it again some days later and it still doesn't Work, says the same thing ...

**Comment by flyingsheep1433** [comment]
The same thing for me... I have no idea what to do.

**Comment by TheCelo** [comment]
T-T

**Comment by Trixter313** [comment]
Are your Minecraft usernames (Not your forum usernames) set to exactly your Minecraft username (Capital letters count)

**Comment by TheCelo** [comment]
Yaph, Capital "T" and Capital "C" , btw i use the same name in minecraft and on the Forums..

**Comment by flyingsheep1433** [comment]
Literally the exact same problem for me. But if you go into your forum user settings does it say "Minecraft: TheCelo"? Because mine says it has my mc account but it isn't because it doesn't show my rank and it also says that error in game not something like it probably says when your account actually gets linked. If it says that in your page then I bet I know what our problem is. Best of luck solving it though 

-flyingsheep1433

**Comment by TheCelo** [comment]
Yap, same problem ..

**Comment by Tama63** [comment]
Duplicate
