### ISSUE TITLE
Losing my items in a safezone

### ISSUE THREAD

**Issue by mythic-bob** [Wynncraft/Issues#1439]
i had my Reaper of soul and all my good gear on me when i went into the bank of almuj.
i went AFK for a while, and when i came back i had lost my items.
i'd call that a glitch so please give me back at least my shears

**Comment by TheCelo** [comment]
How many Soul Points did you have ? ._.

**Comment by Trixter313** [comment]
I'm pretty sure theres no where that says inside of towns are "safe zones" and there are people who purposely bring high level mobs in to towns to kill AFK people, which is what most likely happened so I wouldn't consider it a glitch really. I suggest going AFK in harder to get places for mobs, which is what I do because I happened to get back to my computer as someone was trying to do this to me before.

**Comment by epicman739** [comment]
If you want to stay really safe, just log off or do /class whenever you go away, or perhaps have a friend watch you.
