### ISSUE TITLE
Old Emerald not recognized

### ISSUE THREAD

**Issue by d1ckl3mcp1ckl3** [Wynncraft/Issues#1534]
The emeralds i had from before the value update do not stack with the ones from afterwards. They also cannot pay for anything.
NO idea how to recreate this problem.
-linuxminer

**Comment by Jamdog** [comment]
Downgrade your client to 1.7.10.

This 'bug' was fixed in the 1.8 pre 3 release of the minecraft client.  If you use any client from before then, it should allow you to use old emeralds.  Convert them down/up until you have all new emeralds at the emerald merchants, then you can switch back to 1.8 if you prefer...

**Comment by d1ckl3mcp1ckl3** [comment]
Thank you very much. Oh and by the way, I love your last name.
