### ISSUE TITLE
Item Bombs dropping items that are unable to be picked up..?

### ISSUE THREAD

**Issue by hamsterben5** [Wynncraft/Issues#1541]
So, tonight I bought 100 GC from the Shop to get some item bombs or whatever. I bought one item bomb, then used it in Detlas. I waited for the items to drop (nobody else came around) and two items dropped, a chain and a gold helmet. I walked over to try and pick them up, (also from all directions, sometimes it 'rubber-bands' through other places) and I couldn't. The server eventually went down and I went to bed. Can this get fixed, or can I have a refund? :frowning: 
![gold](https://cloud.githubusercontent.com/assets/6598846/5868231/ba34d476-a274-11e4-8472-c2ddf46cffba.png)
![chain](https://cloud.githubusercontent.com/assets/6598846/5868232/ba3791d4-a274-11e4-937d-c7fb9160ebfa.png)

**Comment by MrBattleHammer** [comment]
well, the problem is, you can't pick up your own item bomb items

**Comment by Jamdog** [comment]
You're not supposed to be able to pick them up.  Item Bombs are designed so that only other players can pick up the items.  This prevents players from going to secluded locations to claim all the loot for themselves.  It encourages sharing and community spirit.  If you set off an item bomb in a busy location, then maybe someone else will also set one off, allowing you to get something.

Note that the items thrown out by the bomb are proportional to the number of nearby players, and their levels.  If there are a lot of high-level players near the bomb, then a lot of high-level items will be thrown out...

**Comment by Trixter313** [comment]
I thought the item depended on the person who picks it up, not the players near the bomb, right?
Like if I pick up an item that looks like a golden item, I actually get a diamond item on pickup.
