### ISSUE TITLE
Wynncraft glitch when I walk up to a jungle slime

### ISSUE THREAD

**Issue by sovietalpaca** [Wynncraft/Issues#1610]
My minecraft goes into freeze mode and it wont let me do anything tell me how to fix this!

**Comment by Trixter313** [comment]
How does your Minecraft run normally? Good, bad? What is your general FPS? The slimes have a <strong>really</strong> fast and repetitive attack so it could lag your game so much that it freezes. If this is the case All I can recommend is that you try Optifine, a speed enhancing mod. http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1272953-1-8-1-optifine-hd-c7-fps-boost-hd-textures-aa-af is the thread for it and it has the downloads on it. You will have to mess with the settings to get an even bigger performance boost, hold your mouse over a setting to learn more about it and commonly it will tell you the fastest choice. And if you're using a high resolution resource pack or shaders, those will decrease performance also. 99% sure that this is only a problem with your client and not Wynncraft since you're the only one seeing the issue and it's just slimes. Good luck!
