### ISSUE TITLE
Maltic's Hidden Place Bug & Glitch.

### ISSUE THREAD

**Issue by 8MeGusta8** [Wynncraft/Issues#1772]
There is a little hidden place with soulsand and mushroom, plus a sign that said "The Escape Is Death" When you press the button to open the piston again., the water doesn't drop and you're stuck there forever. I glitched out to a place with sign that said "This Is RS Latch" and "To Timing V" and can't get out. Please fix it and tp my account out of that place so I can play again. The coordinate is -563 37 -1915.  -PeteWheeler

![2015-04-04_13 25 12](https://cloud.githubusercontent.com/assets/11794227/6991714/8cb117ba-dacf-11e4-907c-74e88327af4c.png)
![2015-04-04_13 24 44](https://cloud.githubusercontent.com/assets/11794227/6991717/9124adca-dacf-11e4-8069-9dab3ae33eb8.png)
![2015-04-04_13 24 43](https://cloud.githubusercontent.com/assets/11794227/6991718/929e1826-dacf-11e4-8a72-139593b98597.png)

**Comment by Trixter313** [comment]
Type /kill into chat with 3+ soul points and you will respawn at the nearest visited town.

**Comment by Jamdog** [comment]
There is an issue on the live servers with flowing water controlled by moving pistons - when the piston moves to allow the water to flow, it doesn't.  It works fine on the build server - only the live servers are affected, I guess because it just doesn't allow changes to blocks.  

As Trixter said though, you can simply type **/kill** to be teleported to the nearest city (possibly Nemract from there, if you've visited it at least once) - you will lose 2 Soul Points, but as you have 10, this won't be an issue.

**Comment by 8MeGusta8** [comment]
thanks :smiley:
