### ISSUE TITLE
Website forums/stat glitch

### ISSUE THREAD

**Issue by JustRoks** [Wynncraft/Issues#1798]
On the website, I want to see my stats.  So, I go to my guild on the guild leaderboard, go into my guild's roster, click on myself, and I get forwarded back to the main screen of wynncraft.com.  Same thing happens when I do www.wynncraft.com/players/Just_Roks.  I have other evidence of this glitch.  Whenever I go onto the forms, I do not see my VIP+ tag, and I am steve instead of my normal skin when I post.  I do not have my class stats or anything else.  But, it can detect when I am online.  Same for on my guild roster.  It is like I exist ingame, but not on the website.
http://prntscr.com/6v3iz0
http://prntscr.com/6v3j84

**Comment by Tama63** [comment]
Apparently you don't exist - will investigate when I have the time.

**Comment by JustRoks** [comment]
@Tama63 make sure that you are spelling my name correctly, Just_Roks.  Not rocks.  Roks.  If not that, work your magic.

**Comment by epicman739** [comment]
I think it's the underscore.

**Comment by Tama63** [comment]
The underscore is fine I think, it might be an issue with uuids

**Comment by Moe-Ronickah** [comment]
I have a nearly identical issue, close enough to not open a new ticket.  I am not in a guild.  My stats have disappeared, and the "/forums" command fails, saying that my account cannot be confirmed.  In my case, it started after I changed my MineCraft, and then my WynnCraft, user name.  On the forums, neither my VIP nor my VIP+ have ever showed, however, my skin is fine.

**Comment by tama00222** [comment]
The underscores are not fine. I'm having the same problem too. I also tested it out with a few more other players with underscores in their usernames. None of them viewed their player info, instead, it just redirects you to the stats page.

@JustRoks Also, I believe the 'players' in the link should be spelled 'player'.

**Comment by Tama63** [comment]
Fixes

**Comment by JustRoks** [comment]
@Tama63 Nope, it still sends me back to the stat page.

**Comment by Jor2001** [comment]
@Tama63 I don't know exactly what you fixed, but the player stats pages for players with an underscore still don't work. When I logged on to the forums, it showed this as my skin.
![screen shot 2015-05-07 at 11 34 00](https://cloud.githubusercontent.com/assets/10878977/7512404/062a6f6e-f4ad-11e4-849c-bb57da70a19d.png)
This isn't my skin, but the skin of a player with the IGN "Jor". It seems that instead of fixing the issue, you might have removed the underscore and everything behind it from our names, which could be the reason why the player stats pages still don't work.
