### ISSUE TITLE
Animal Boss Keep Re spawning 

### ISSUE THREAD

**Issue by TigerJolt** [Wynncraft/Issues#1823]
When i do the Animal Dungeon, once i get to the boss i can kill it no problem but when it dies it doesn't say that i completed it and it keeps me there until it re spawn again and there is nothing i can do to complete the dungeon. When i try it with other people it goes ok but solo it never ends. *IGN - TigerJolt*

**Comment by Trixter313** [comment]
Whenever this happened to me the boys was near a wall/away from the center. Killing the boss in the center of the room should fix this issue.

**Comment by TigerJolt** [comment]
It Still keeps going i just tried it It is impossible for me to do this. I killed it in the exact middle ant it did the same thing.

**Comment by Moe-Ronickah** [comment]
TigerJolt, I have found that if my inventory is full, some of the dungeons and mini-dungeons do not complete, because I can't get the reward.  I don't know if this is what is happening to you, however, would you confirm whether or not you have two or more inventory slots open when you complete the Animal Dungeon?

**Comment by EnderMan123PvPz** [comment]
This has happened not to only me, but many other people attempting to beat the Animal Boss. It's pretty frustrating because I killed the boss in exact middle, and I had 10+ inventory slots empty. If you want some proof then here: https://www.youtube.com/watch?v=fCEVDTG_jFY

**Comment by Moe-Ronickah** [comment]
It's not that I wanted proof, EnderMan123PvPz, I'm just another player on WynnCraft, and I was trying to help, however, that video may be of interest to @Tama63 .

**Comment by Moe-Ronickah** [comment]
I ran through the animal dungeon, yesterday, on my Mage, in order to check this.  I killed the lava cow, and was instantly teleported out.  Would you try the dungeon again, and see if it works for you, now, please?  It may have been a server problem at the time, if it works, now, or the update may have changed something.  I hope that it works for you, now.
