### ISSUE TITLE
Disappearing Ghostly Helmet

### ISSUE THREAD

**Issue by Ghost88788** [Wynncraft/Issues#1828]
I just got done with The House Of Twain quest (Ar=24, Ma=22, Wa=16, As=50) and I got the Ghostly Helmet. Since it is my lvl and better than anything I had, I decided that this is my main helm until I get better. So after I don't know how long but around a month, I was already farming in the Dernal Jungle. So I am farming alright, my regular place at lvl 49. Then the next day, I farmed a bit more and it seems that I leveled up and my Ghostly Helmet is GONE. At least I got the Relic Helmet (My previous Main Helmet) and put it on. I worked on that le for so so long. As soon as I found out that it was missing, I really wanted to rage quit Wynncraft (For Rage Quit for me, it is either for a very long period or never play it again). I took soooo long for me to get the le for it, I just want it back. My Un iDent, Thorns II Ghostly Helmet. Is there any way that I can get it back without spending my time again? If anyone can give it back to me (or at least 48 eb) just because of this, thank you thank you thank you. Also, Since my MC name is Ghost88788 and this is the ghostly set, I am going to treasure it when I'm done and use it for other classes. Though, I already used up the 2 le from the quest for the Ghostly Boots.

**Comment by Ghost88788** [comment]
I got another one, I hope it doesn't vanish again. Can anyone just tell me what happened?

**Comment by Trixter313** [comment]
The helmet probably went missing before the level up happened but you just noticed it at that time. There's no reason for a level up to remove a helmet.

The only cause I can think of that makes sense is maybe you accidentally dropped it without noticing. It's happened to me before. I don't think there's really anything else that would make that happen.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thanks and we hope you enjoy your time playing Wynncraft! :)
