### ISSUE TITLE
teleportation damage hurts me

### ISSUE THREAD

**Issue by lilacsilver020** [Wynncraft/Issues#1876]
As a mage, i had the teleport spell upgraded to the point where u hurt mobs when u teleport through them,but when i teleported past a mob, i teleported to the mob and i died instantly.

**Comment by Moe-Ronickah** [comment]
You were most likely not damaged by teleporting, unless a glitch occurred.  What probably did happen is that when you teleported, you landed immediately next to an active hostile mob, or inside of one, in the case of slimes and magma cubes.  If there are enough mobs, or if the mob is of high enough level, they can, and will, kill you before you even have time to react.  So, instead of teleporting through the mob or mobs that killed you, you probably teleported TO them.
