### ISSUE TITLE
I can't get items out of my bank

### ISSUE THREAD

**Issue by TheMusicGuy** [Wynncraft/Issues#1883]
Hello there, the title says it, i can't get items out of my bank account (wich contains quest items, armour and money), i am actually stuck in the game when it is about quests. i have already send an email a while ago (i think like 7 months) with the same issue and someone said you will try your best to fix it, wich it still hasn't happened.
So hopefully via this it will be fixed a.s.a.p., i would really appreciate it if it finnaly could bix fixed <3

If you need my ign: The_Music_Guy

Thank you for taking your time on it.
-The_Music_Guy

**Comment by musicwolf** [comment]
I'm stuck in the game because my bank is broken. I cant my items out of the bank And i cant redo quests. If i click on an item in my bank it will throw me out of the bank menu. I'm an older player on the server that why i thought that it was because the older items but i put a red powder II in my bank and i didnt work. (I have putted it in the bank with shift+left click. But you can't get your item with it out of your bank).
