### ISSUE TITLE
Animal Dungeon- Lava Cow vanish glitch?

### ISSUE THREAD

**Issue by EnderMan123PvPz** [Wynncraft/Issues#1944]
So today I was farming my lvl 30 assassin in the animal dungeon to unlock some later quests, and I went all the way to the boss room. I did alot of damage but I vanished so I can regenerate health, and all of a sudden I see an explosion and he disappears & respawns. What is this? Please help. This glitch is quite annoying. 
P.S: He regenerates back to full health and I do not complete the dungeon.

**Comment by EnderMan123PvPz** [comment]
Here is a quick video to show proof of this bug. https://www.youtube.com/watch?v=fCEVDTG_jFY

**Comment by Moe-Ronickah** [comment]
I ran through the animal dungeon, yesterday, on my Mage, in order to check this.  I killed the lava cow, and was instantly teleported out.  Would you try the dungeon again, and see if it works for you, now, please?  It may have been a server problem at the time, if it works, now, or the update may have changed something.  I hope that it works for you, now.
