### ISSUE TITLE
Unable to find server to connect to.

### ISSUE THREAD

**Issue by megaxlr** [Wynncraft/Issues#1946]
Can't connect to any server. when I press "join server" in the multiplayer menu of Minecraft it gives me the error: Unable to find a server to connect to. please report.

Well here it is. I know your team is horrible at solving issues and mostly closes the thread before it is solved. You wanted me to report it. Have fun,

I don't know anything about this issue and do NOT WANT A REPLY. just close the bloody thread like you always do.

**Comment by epicman739** [comment]
Please don't be so mean to the staff members. They work hard to keep Wynncraft running as well as possible, so you should probably be thanking them instead of insulting them. The threads that are closed are either duplicates, temporary issues that are solved with relogging, or not detailed enough to be useful. @Tama63 doesn't just close threads because he feels like it.
As for this specific issue, it has happened to quite a few people recently. According to Wynncraft's Twitter feed, they are experiencing technical difficulties with their host, so all they can do is wait until the host fixes the issues. https://twitter.com/Wynncraft/status/603919263779422208
