### ISSUE TITLE
Temple of Legends Villager bug

### ISSUE THREAD

**Issue by Raxcu** [Wynncraft/Issues#1970]
There are some villagers at the training area that wont die and becomes immortal and They're really annoying when I can't kill them 
![2015-06-07_21 00 13](https://cloud.githubusercontent.com/assets/12630429/8025290/ffaaec58-0d58-11e5-92c4-d9f04d14a077.png)
please get this fixed asap

**Comment by Jamdog** [comment]
This happens because they have a high regen rate, and regain some health while dying, so actually stop dying, but in this state, they no longer attack or cast spells.

If this gets too much, simply return to the lobby (type /hub or /lobby) and log back in to the server - if no-one else is in the ToL, then they should despawn.

**Comment by Raxcu** [comment]
I tried to walk away from ToL but the villagers didn't despawn but they started standing...
![2015-06-11_20 00 23](https://cloud.githubusercontent.com/assets/12630429/8113432/af9471d2-1076-11e5-8baa-8c58218cb068.png)

**Comment by Trixter313** [comment]
If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thanks and we hope you enjoy your time playing Wynncraft! :)
