### ISSUE TITLE
Stuck (AGAIN!!?) Doing the Mansion Delivery Quest -- Trapped in a Block?

### ISSUE THREAD

**Issue by Vacive** [Wynncraft/Issues#1993]
I actually wish I was suffocating in the block because then I would die and respawn elsewhere (Nemract) but I'm not. No idea what happened, maybe sudden lag with the redstone, but I talked to the guy at the end of the Mansion Delivery quest, hit the button to walk out of the iron door and next thing I knew my screen was basically black and I was glitched in the ground or something. My cords are still the same, so I didn't get moved much at all if any, and I'm not taking damage. PLEASE HELP!!!

**Comment by Trixter313** [comment]
Typing /kill into chat will teleport you too the nearest visited town, consuming 2 of your soul points.
If you issue is solved by this, it would be appreciated if you closed this issue. Have a fun time playing!

**Comment by Moe-Ronickah** [comment]
If you are stuck in the ground, there is another possible way out.  I've found that if I jump servers, while holding down either my forward (W) or back (S) key, that sometimes I can move enough to get out of wherever I am.  Remember that MC always drop a player into the game either one or two blocks above their position, in order to prevent trapping a player in ground.  I hope this works for you.
