### ISSUE TITLE
Not Getting Skill Points? Help ;-;

### ISSUE THREAD

**Issue by Vacive** [Wynncraft/Issues#1996]
As shown in the provided screenshot, I have 37 levels (adding up to a total of 74 skill points), yet I have only been given 68 total in use/available. For the past 3 levels I have been hoping that it would just fix itself and kept adding them to my Dexterity attribute, but they continuously fail to account for themselves, so while grinding for level 38 I thought I'd make a quick bug report on it. This, however, I think is quite a serious issue as skill points are quite a large part of the game; and I would hate to have to spend my one and only Liquid Emerald to reset my skill points because of this. If an administrator in game could fix this for me by adding 6 skill points to my Dexterity trait or giving me 6 skill points to use in general it would be much appreciated. Thanks in advance :)
![4ac94b2bb74bced09f19402cee28f990](https://cloud.githubusercontent.com/assets/12857309/8146820/3b4634ca-1213-11e5-828e-a1d74ce655cf.png)

**Comment by Jamdog** [comment]
This is actually due to a minecraft restriction which means that a 'stack' cannot have more than 64 in it.  You will find that where it shows 64, you actually have 70 (the max possible) in that stat - it just cannot show that graphically, but should report the right number if you hover your mouse pointer over it.

You have not lost 6 skill points, they are there...

**Comment by Trixter313** [comment]
If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thanks and we hope you enjoy your time playing Wynncraft! :)
