### ISSUE TITLE
Guild Battles Teleporting Crazy

### ISSUE THREAD

**Issue by thatswhatido** [Wynncraft/Issues#2003]
I have no Idea how this happened or why it happened but very rarely guild battles will start teleporting you around crazily

https://youtu.be/jAVF4jI2GxE

**Comment by Trixter313** [comment]
I've personally never been in a guild battle so I might not be of much help but I'll try. Are you using any mods? If so, I'd recommend trying to use vanilla Minecraft 1.8 and seeing if the issue still occurs. If not, maybe try removing/adding mods one by one until you find the one causing it. Also making sure that any mods you have are up to date would probably be a good idea.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thanks and we hope you enjoy your time playing Wynncraft! :)

**Comment by Trixter313** [comment]
If this does turn out to be an issue on Wynncraft's side, all we can do is wait for a comment from someone on the Wynncraft team. :)

**Comment by thatswhatido** [comment]
I was useing optifine 1.8 but I had other people in that guild battle haveing the same issues

**Comment by thatswhatido** [comment]
Might aswell close it it seems rare to have happen
