### ISSUE TITLE
Stuck in the class selection area

### ISSUE THREAD

**Issue by hakim05480** [Wynncraft/Issues#2005]
hi my archer and mage is glitched and is stuck in class selection area. If you could send a staff to help me that will be great
Thank you
my in-game name is hakim05480

**Comment by Trixter313** [comment]
Typing /kill into chat will teleport you to the nearest visited town. This will take 2 soul points.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thanks and we hope you enjoy your time playing Wynncraft! :)
