### ISSUE TITLE
WynnExcavation Site B Glitch (TheGoldenKitten)

### ISSUE THREAD

**Issue by TheGoldenKitten** [Wynncraft/Issues#2007]
Hello there! So I have a glitch that I am not sure is happening to anyone else, but it is happening to me. So I have completed the quest WynnExcavation Site A already, yet, when I talk to the person at Site B, he suggest I go to site a and talk to him, yet, I already finished the quest there. I believe that it just glitched and it still believes that I haven't completed it yet, when I have. Please message me back as soon as possible. I have been trying to figure this out for a few months now and I just want to play properly.

**Comment by Trixter313** [comment]
Do you have the shards that you got from site A in your inventory? If not, go get them and try again.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thanks and we hope you enjoy your time playing Wynncraft! :)

**Comment by TheRex94** [comment]
bien qu'il n'y ait pas rapporter nécessairement qu'il est super importan /! \ je créais ma bouteille et il a été lâché sur le sol au moment du redémarrage de telle sorte que je perdais liquide 5bouteille Emeraude vous aider, je suis suppli

**Comment by Trixter313** [comment]
French:
Malheureusement Wynncraft a une très strict aucune politique de remboursement de sorte qu'il n'y a pas beaucoup qui peut être fait. Tout ce que je peux suggérer, est d'essayer d'être conscient de si un redémarrage se produit dès la prochaine fois que vous tradez rien. Aussi, si vous devez signaler tous les problèmes à l'avenir, de créer une nouvelle émission plutôt que de spamming sur les questions non liées. :)

English:
Unfortunately Wynncraft has a very strict no refund policy so there's not much that can be done. All i can suggest is to try to be mindful of whether a restart is happening soon next time you're trading anything. Also, if you have to report any issues in the future, create a new issue rather than spamming on unrelated issues. :)

**Comment by TheGoldenKitten** [comment]
What might the shard be called and where might I find it?

**Comment by TheGoldenKitten** [comment]
Alright. I tried keeping the yellow crystal in my inventory while talking to him, and he still says, "Hello there! We are working very hard here at this excavation site! We have one in Almuj as well, I think you should check it out!". Do you have any idea why he is saying this? I already completed the one in Almuj, so I am not sure why he is still saying this. Please help me as soon as possible.

**Comment by epicman739** [comment]
Are you sure you have the right Yellow Crystal Shards? There are two types: one labelled "untradeable item", which you get from killing the Pharoh, and one labelled "quest item", which you get after the quest is finished. Make sure you have the "quest item" version.

**Comment by TheGoldenKitten** [comment]
Alright. Thanks. I thought that my account glitched and I had to fix it. Thanks for the help.

**Comment by TheRex94** [comment]
thanks and excuse me
