### ISSUE TITLE
Guild owner glitch

### ISSUE THREAD

**Issue by poepser132** [Wynncraft/Issues#2008]
I got a guild with a few people but when i came back online i was no owner anymore no one was owner this was very weird that's why i created this post

additional information:
Guild name is: Wynn Raiders
Guild tag is: VIO (Victory is ours)
My name is: poepser132

Hope you can fix this

**Comment by Trixter313** [comment]
Visiting https://wynncraft.com/guild/Wynn%20Raiders confirms that the guild doesn't have a leader defined.

From what you have said, I believe you are supposed to be the owner. Is this correct?

Have you changed your MC username recently?

**Comment by poepser132** [comment]
im supposed to be owner and i changed my username 2 times at the begin of the username change update

**Comment by poepser132** [comment]
i changed it first to xXAce_LiquidXx
and then back to poepser132

**Comment by poepser132** [comment]
i got first removed and added to guild and then i got recruit

**Comment by TheRex94** [comment]
bien qu'il n'y ait pas rapporter nécessairement qu'il est super importan /! \ je créais ma bouteille et il a été lâché sur le sol au moment du redémarrage de telle sorte que je perdais liquide 5bouteille Emeraude vous aider, je suis suppli

**Comment by Trixter313** [comment]
French:
Malheureusement Wynncraft a une très strict aucune politique de remboursement de sorte qu'il n'y a pas beaucoup qui peut être fait. Tout ce que je peux suggérer, est d'essayer d'être conscient de si un redémarrage se produit dès la prochaine fois que vous tradez rien. Aussi, si vous devez signaler tous les problèmes à l'avenir, de créer une nouvelle émission plutôt que de spamming sur les questions non liées. :)

English:
Unfortunately Wynncraft has a very strict no refund policy so there's not much that can be done. All i can suggest is to try to be mindful of whether a restart is happening soon next time you're trading anything. Also, if you have to report any issues in the future, create a new issue rather than spamming on unrelated issues. :)

**Comment by epicman739** [comment]
@poepser132 guilds are known to have issues with name changes. Hopefully a Dev will be able to fix this for you.

**Comment by poepser132** [comment]
where can i contact a dev?

**Comment by Trixter313** [comment]
Devs check this bug tracker periodically so one should comment on here soon. You might be able to get a speedier response by emailing support@wynncraft.com
