### ISSUE TITLE
Guild xp not working

### ISSUE THREAD

**Issue by grimenderdragon** [Wynncraft/Issues#2027]
My guild is having a problem with guild xp. The game says we are getting xp but none goes to our guild and we do not have guild xp set to zero. Our guild name is Azure Drakes

**Comment by Trixter313** [comment]
It usually takes a few hours for the stats to update with any new XP so I
suggest to see if it still hasn't updated by tomorrow and report back. :)

**Comment by grimenderdragon** [comment]
It has been this way for a few days now

**Comment by Moe-Ronickah** [comment]
It appears, from talk in-game, that there is a problem with guild XP since this past weekend, when the servers crashed.  I can only presume that it is affecting every guild's XP equally, however, I am not certain of this as I have not heard it from every guild.  As Trixter313 asked, please let us know if it updates or not in another day.

**Comment by grimenderdragon** [comment]
Nope the guild xp hasn't moved

**Comment by ltvuong** [comment]
My guild is having the same problem.

**Comment by kristan100** [comment]
i also have that problem
