### ISSUE TITLE
Bug with Milking Cows?

### ISSUE THREAD

**Issue by otakugirl1279** [Wynncraft/Issues#2034]
https://www.youtube.com/watch?v=9KL-oc2PQrg&feature=youtu.be

The quest told me to buy a bucket from the bucket merchant to milk the cows in, or north of, the village with. I bought the bucket but why the flip can't I milk the cows?  If the quest says I am able to milk cows, I should be able to milk cows. :/

**Comment by Trixter313** [comment]
You actually get the milk by trading with a villager. He's in the same area, next to the milk item frame.
![2015-06-25_04 22 51](https://cloud.githubusercontent.com/assets/7178055/8350278/faf84da8-1af1-11e5-98a9-4d07ae14e185.png)

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thanks and we hope you enjoy your time playing Wynncraft! :)

**Comment by otakugirl1279** [comment]
Okay, but I'd prefer it if either the quest could be reworded or milk could be allowed to be drawn from cows with a bucket.  The quest claimed to allow you to milk cows, yet you can't actually milk the cow. In my humble opinion, that breaks with immersion just a teency bit. Message me on your forum when you have a response please. Username there is same as here, @otakugirl1279
