### ISSUE TITLE
Stuck inside a block

### ISSUE THREAD

**Issue by Darwid** [Wynncraft/Issues#2038]
Hello, I'm not even sure if this is the right place, but the mage's teleport spell apparently allows you to get stuck inside blocks. The coordinates where this happened are at 1010, 30, -2538. Moving doesn't do anything, Teleport scrolls don't do anything, teleport spell doesn't do anything. I was just trying to find a way out of the dungeon cause i stayed there for too long (got a quest to kill 25 Oni zombies). I'd at least appreciate a teleport ou of those blocks. Thank you for reading!

**Comment by Darwid** [comment]
used /kill, now I'm out. Either way, is there no button to leave that dungeon?

**Comment by Trixter313** [comment]
You never actually mentioned what dungeon you were on but I've completed every one so yes, there is a way to get out of whichever you're talking about, by killing the boss at the end. Unless you mean is there a button to leave early, which doesn't exist.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thanks and we hope you enjoy your time playing Wynncraft! :)

**Comment by Darwid** [comment]
I'm sorry for using the word dungeon, it just seemed like the best one. I was in the Oni Temple in Half-moon island. There used to be a button but then there was an update to that temple and i can't see a button anywhere, and therefor no actual way out without scrolls.

**Comment by Trixter313** [comment]
Well, now that you're out, I suggest either renaming this to the new issue that you've stumbled upon (There being no button) or closing this one and creating a new one about the button. :)
Thanks!
