### ISSUE TITLE
World Map Cut

### ISSUE THREAD

**Issue by Rikipalooza99** [Wynncraft/Issues#2088]
I was just back from a quest that also bugged, but I was able to go back to Ragni with /kill when walking towards Detlas there's a sudden lag pike, and then I'm in a flatland again. I look behind me and there's a giant wall, with the path before Emerald Trail up there, and down here a huge hole in the wall. It looks like an Admin area, filled with Quest chests, mobs chests. I'm going to /kill again, but I wanted to report this. I did get a screenshot though. Here it is. 
![2015-07-12_18 57 21](https://cloud.githubusercontent.com/assets/8294733/8639144/739e3ce8-28c8-11e5-8f3d-5dc1b5b366ef.png)

**Comment by Rikipalooza99** [comment]
So I /killed, respawned in maltic, walked a few blocks and I fell again. The same thing happent.

**Comment by TrashcanMan** [comment]
This could be a lag problem, where the chunks aren't loading fast enough to keep up with your movement.

**Comment by Rikipalooza99** [comment]
I did relog, same thing. So I changed servers.
But this happent to everyone, I guess everyone would have to relog or restart so the map could fix.

**Comment by Trixter313** [comment]
There was an issue earlier similar to this but it was only affecting one
world (World 17 I believe.) The issue should be fixed when the world
restarts.

If your issue is now resolved, we'd appreciate it if you closed this issue.
If it's not, we'd be happy to continue to assist you as much as possible.
Thanks and we hope you enjoy your time playing Wynncraft! :)

**Comment by Trixter313** [comment]
Also, just for reference, what world were you on when this was happening?

**Comment by Rikipalooza99** [comment]
I was on 16
