### ISSUE TITLE
Quest Excavation Site C is teleporting me to various locations in superflat

### ISSUE THREAD

**Issue by BattlingApollo** [Wynncraft/Issues#2090]
On my first run through of the quest, I reached the part where you talk to Traitor Amadel. I followed the black portal where you were supposed to delve deeper in the cave, but ended up teleporting to the superflat world. I did /kill to end up in Almuj, so I could go back to the Volcanic Island to start the quest again. The same thing happened; I ended up in Almuj once I followed the black portal. So, I used /kill again, spawned in Almuj, and went back to the island. However this time, when I tried to "escape" the meeting room to reach the Traitor Amadel dialogue, I spawned outside the room.
![2015-07-12_12 32 34](https://cloud.githubusercontent.com/assets/3614512/8639921/1231d612-289c-11e5-9c86-386bd69f8bbd.png)
![2015-07-12_12 32 46](https://cloud.githubusercontent.com/assets/3614512/8639923/1464b26a-289c-11e5-9839-f5dcdb94c60c.png)
![2015-07-12_12 33 08](https://cloud.githubusercontent.com/assets/3614512/8639924/15b043a0-289c-11e5-8fef-edeec392deeb.png)

**Comment by Trixter313** [comment]
What world were you on? One of the worlds appeared to have corrupt chunks
earlier today but should be fixed by now by the world restarting.

If your issue is now resolved, we'd appreciate it if you closed this issue.
If it's not, we'd be happy to continue to assist you as much as possible.
Thanks and we hope you enjoy your time playing Wynncraft! :)

**Comment by BattlingApollo** [comment]
Yes, I logged in later and the quest worked. Thank you!
