### ISSUE TITLE
Wynncraft servers broken?

### ISSUE THREAD

**Issue by BateauSD** [Wynncraft/Issues#2114]
Server connect work but hunger not regen, command no works, skill menu not works, spells to. http://prntscr.com/7tm5nf What this? Problem only in Server 1
UPD mobs not spawning to.

**Comment by BateauSD** [comment]
now fixed. Close.

**Comment by Trixter313** [comment]
Typing /class should fix the issue for you whenever this happens. Or you can just switch to another world and that usually fixes it too.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thanks and we hope you enjoy your time playing Wynncraft! :)

**Comment by Trixter313** [comment]
Oops, I was a few seconds too late xD

**Comment by BateauSD** [comment]
I say what commands no works in server ..

**Comment by Trixter313** [comment]
That's why I also suggested switching worlds :)

To actually close the issue, next to the button you click to send your comment you should see a button to close it. Thanks!
