### ISSUE TITLE
Stuck in a black wool box?!?!?!

### ISSUE THREAD

**Issue by xThad** [Wynncraft/Issues#2122]
So I was playing Wynncraft perfectly fine as an archer, then decided to switch to knight for a while. When i switched back to archer I was stuck in a box. I could shoot and do my powers and stuff but not leave it... Please help. http://gyazo.com/1e650044e68275b22cd75deaefedcc02

**Comment by Trixter313** [comment]
![stuck](https://cloud.githubusercontent.com/assets/7178055/8790452/3a5c3f70-2f1c-11e5-9b59-06cde546428e.png)

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thanks and we hope you enjoy your time playing Wynncraft! :)

**Comment by xThad** [comment]
Thanks :)
