### ISSUE TITLE
Wynncraft Excavation Site C Bugged Teleporting

### ISSUE THREAD

**Issue by CheesePrince13** [Wynncraft/Issues#2139]
Perhaps someone else has already posted this and i just missed it, but after "Infiltrating the meeting", when the final line was given as I stepped into the black room to teleport, I was instead teleported into a superflat area surrounding the meeting area. I know this because I could see the "Guard Klerodor" and "Chief Excavator Dranfor". I know I can /kill to get out, but this doesn't help me with completing the quest. I did find the coal/obsidian blocks from my side and attempted to teleport using them, but it dropped me in the same spot in the superflat? Was this a problem with the server I was on, or is this a current bug in the quest? Thanks in advance for any help I receive with this issue.
![2015-07-24_13 04 12](https://cloud.githubusercontent.com/assets/13487814/8881613/e42a5e78-3206-11e5-9a07-39900fd269a7.png)
![2015-07-24_13 05 56](https://cloud.githubusercontent.com/assets/13487814/8881618/ef353a7c-3206-11e5-81ff-2be9e506efcd.png)
![2015-07-24_13 08 21](https://cloud.githubusercontent.com/assets/13487814/8881623/f2541c28-3206-11e5-8bc8-03464bfeacff.png)

**Comment by Trixter313** [comment]
Switching to another server and doing the quest should fix your issue. There have been a few reports of this on here and switching servers fixed it for everyone I believe.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thanks and we hope you enjoy your time playing Wynncraft! :)

**Comment by CheesePrince13** [comment]
My friend helped me figure this out since then actually, but thank you very much!
