### ISSUE TITLE
Emerlads and Emerlads Blocks don't stack and i can't get the compass out of my bank

### ISSUE THREAD

**Issue by EDOGAR1** [Wynncraft/Issues#2143]
Hey, my username is EDOGAR1 and I didn't play alot of time and now when i came back to play i saw that my emerlads and the enerlads blocks that i had have white name and the emerlads and the emerlads blocks that i got now have green name so they don't stack. if you can plz check my bank because all my old emerlads and emerlads blocks in there. In the bank i have compass that is just taking me place in the bank and if you can get it out from there is will be great.

Thank you.

**Comment by Trixter313** [comment]
For the emeralds, there's 2 ways you can fix it. The easiest is to just log on Wynncraft using 1.7.10  and trade the old emeralds with emerald merchants to get the new emeralds. If you want every single emerald though, even the single emeralds you have less than 64 of, you'll have to go to Selchar, the ocean city. There is a villager in the bank there called the converter merchant that will convert the old emeralds to new ones, no matter what version you're logged on with. If you need help finding it you can use map.wynncraft.com to guide you.

As for the compass there's nothing I can think of that you can do so that will probably require a staff member to manually remove it.
