### ISSUE TITLE
Quest not giving the right amount of emeralds.

### ISSUE THREAD

**Issue by littlelawyer** [Wynncraft/Issues#2146]
I finished the "Troubled Tribesman" quest and I was given 150,000 xp but only 512 emeralds instead of the 2048 emeralds. I have no idea how to reproduce the issue.
![2015-07-26_23 05 55](https://cloud.githubusercontent.com/assets/13516516/8899760/454d64a6-33ed-11e5-94b9-6a5a9758314c.png)

**Comment by Trixter313** [comment]
How are you sure you're supposed to get more than that? It's a possibility that they changed the reward amount since you last did it if you did it on another class. Usually when there's a reward issue it will display the correct amount in chat but won't give you the correct amount.
Also, did you have any emerald blocks on you right before the quest finished? If not, 32 blocks is equal to 2048 emeralds.

**Comment by littlelawyer** [comment]
Oh, I didnt know 2048 emeralds was equal to 32 blocks, thank you.
