### ISSUE TITLE
I need to get rid of some quest items

### ISSUE THREAD

**Issue by Navilence** [Wynncraft/Issues#2154]
I'm not sure if this counts as a bug, but it is a small issue. As the title states, there are quest items that I need to get rid of, simply for the sake of space. I use multiple classes, so I have multiple Breathing helmets, climbing helmets, and slime scoopers that I don't need. I do intend to keep one of each, but having multiple takes up space. I'm not aware of any way to get rid of them, so sorry if there is.
In order to fix it, see if you can create a way to delete quest items. I get that dropping it by mistake is why they can't be dropped in the first place, so perhaps you could create a command to delete any item in your hand?
![2015-07-28_16 29 49](https://cloud.githubusercontent.com/assets/13546679/8946604/99bf7cb8-3546-11e5-95b7-5113955c1e3b.png)

**Comment by Trixter313** [comment]
There's really no way around this except to add quests that take the items away but then they can't be used at all and that closes off opportunities for future quests. Giving people the option to get rid of quest items would just cause more issues with all of the issue reports about them getting rid of items they didn't know they needed for future quests and now need. And as of right now there's no way to automatically just get rid of a quest item because you have one already. I'm pretty sure there's no way to implement that into Minecraft either.

**Comment by Trixter313** [comment]
Although, I guess there could be a quest that takes the items and if they even needed to be used again for a future quest there could be some story to give it back to the player like a NPC found it or purchased it from someone. But that would be the only solution I can think of.
