### ISSUE TITLE
Disconnecting From The Server

### ISSUE THREAD

**Issue by drutr123** [Wynncraft/Issues#2191]
I changed my profile name in Minecraft and I cant get in Wynncraft server. When I search my old name in the leaderboard at the website, I find him without skin and more strange things, and when I write my new name it finds nothing.
Please fix that problem because I still want to play on your server and I was level 75 in warrior class.
So please fix this bug,
DrDrutr (my old name: drutr123)

**Comment by Trixter313** [comment]
This is most likely because Wynncraft is using a name-based system instead of a UUID based system. Your name can be changed and cause issues with it but a player's UUID never changes. I believe they already know about some issues with name changes and are working on it so hopefully it will get fixed soon. Until it does, I recommend trying to change your name back whenever possible and see if that fixes things.
