### ISSUE TITLE
Liquified Emerald and Emerald Blocks are no longer worth anything

### ISSUE THREAD

**Issue by HaloSM** [Wynncraft/Issues#2205]
Hello! So, basically I haven't played Wynncraft in a while. But when Iogged back on to my Warrior Class, some of my Emerald Blocks didn't have the colored name, and the worth lore underneath. The same thing goes for my Liquified Emerald. If anyone could help me with this, please do say. I think it may be a bug, as they still have the name and I know for a fact that when I used to play, all the emeralds and Emerald Blocks I had were fine.
![2015-08-14_19 40 57](https://cloud.githubusercontent.com/assets/13796817/9273223/1074dfa0-42bd-11e5-90f6-8aff98aa56c5.png)

![2015-08-14_19 40 59](https://cloud.githubusercontent.com/assets/13796817/9273246/3b5908c2-42bd-11e5-8630-a1bba229186b.png)

![2015-08-14_19 41 00](https://cloud.githubusercontent.com/assets/13796817/9273247/45fc7340-42bd-11e5-9895-0c89b13b8419.png)

![2015-08-14_19 41 02](https://cloud.githubusercontent.com/assets/13796817/9273237/234d5850-42bd-11e5-9812-4e81e187f9bc.png)

**Comment by Trixter313** [comment]
If you log into Wynncraft using 1.7.10 you can trade the old emeralds to get the new emeralds. Or if you think it would be easier, there is a villager in Selchar's bank that I believe is called a "Converter Merchant" or something similar that will do it in 1.8.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
