### ISSUE TITLE
Emerald Blocks have no NBT Data

### ISSUE THREAD

**Issue by VisualPixels** [Wynncraft/Issues#2207]
I cannot use my 25 emerald blocks to trade, because i see that there is no NBT data on the blocks. If i could get them back that would be fantastic. BTW I use to play Wynncraft before all the new stuff came out.
![2015-08-15_15 50 13](https://cloud.githubusercontent.com/assets/13813459/9290819/3fbaeb2a-4366-11e5-9baf-5f7c0e72c32a.png)

**Comment by Trixter313** [comment]
If you log into Wynncraft using 1.7.10 you can trade the old emeralds to get the new emeralds. Or if you think it would be easier, there is a villager in Selchar's bank that I believe is called a "Converter Merchant" or something similar that will do it in 1.8.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
