### ISSUE TITLE
I LOST ALL MY STUFF BECAUSE OF A BUG

### ISSUE THREAD

**Issue by ZefengPlayz** [Wynncraft/Issues#2208]
I went to the guild master, and created a guild, than on the way back, i only have one soul point left, and i didnt know i have one left. After that, i accidentally fell into the void, and got stuck in the void for about 1 minute, so i did /kill, AND I LOST ALL MY STUFF! Can i have my stuff back and can u guy fix the bug?
![y9t 11ckn4s_k_0 pual9](https://cloud.githubusercontent.com/assets/13813974/9291086/802a7ea4-4362-11e5-8413-81d2363c82eb.png)

**Comment by ZefengPlayz** [comment]
I WANT MY STUFF BACK

**Comment by TrashcanMan** [comment]
Unfortunately it's your own fault that you did /kill with only 1 soul point. Wynncraft has a strict no-refund policy, so you can't get any of your items back.
Next time, remember that soul points regenerate even when offline, so just come back in an hour or so and then do /kill.

**Comment by ZefengPlayz** [comment]
@TrashcanMan but i have no way of getting out of the void, as u can see on the picture, i was -7000+ down in thw void and im trying really hard to get out, i didnt notice that i only have 1 soul point left!

**Comment by Trixter313** [comment]
We can't do anything about you not noticing how many soul points you had, unfortunately as this is a user mistake and as TrashcanMan said, Wynncraft has a very strict no refund policy. Hopefully you will be more careful and cautious of your soul points next time you ever do /kill.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by ZefengPlayz** [comment]
@Trixter313 but did u guy patch the void?

**Comment by ZefengPlayz** [comment]
@Trixter313 can i at less get my black horse back, thats the most expensive thing out of my inventory
