### ISSUE TITLE
Huge Teleporting Glitch 

### ISSUE THREAD

**Issue by adent76** [Wynncraft/Issues#2246]
Was doing the Hallowynn 2014 quest and right as a walked in the cave and failed the parkour purposefully because I did the quest before and I knew that is how you do it and I feel into the build world. Walked around and found a cave that I could escape into and went to the top to check it out, I think it was Gavel! (and if it was im really excited!) I was in world 1

![2015-08-24_19 52 36](https://cloud.githubusercontent.com/assets/13954975/9457047/12554760-4a9c-11e5-8876-b646aba6e46b.png)

^ Image

If this is Gavel, you guys did a great job, super excited for this to come to the real game!
-TooLong

**Comment by adent76** [comment]
Tried to finish quest on world 3, worked no problem

**Comment by Trixter313** [comment]
Typing /kill with 3+ soul points should teleport you back to the nearest town.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

If this happens again in the same place, you don't need to close the issue as it would be more than a one time issue.
