### ISSUE TITLE
Useless Emerald Blocks instead of Block f Emerald

### ISSUE THREAD

**Issue by Ritherlas** [Wynncraft/Issues#2251]
So ive bean on Wynncrat for a while now. Originally instead of the remained "Block of Emerald" as a form of currency it used to be just emerald blocks. Now ive got a stack of 15 Emerald blocks that I cant spend in my bank and I kinda dont want to bin them my account is tgoacher if you can help me but if not just say so :smile_cat:

**Comment by Trixter313** [comment]
There are two ways you can go about converting the emeralds into the new type.

The first, and probably most easy, is to log into Wynncraft using 1.7.10. Once logged in simply trade the old emeralds with emerald merchants and you will receive the updated currency.

If you'd prefer, you can also go to the ocean village, Selchar, and trade the old emeralds with a special converter merchant. This method works no matter what version you are logged in with.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
