### ISSUE TITLE
Emerald Blocks not working

### ISSUE THREAD

**Issue by blueblood01** [Wynncraft/Issues#2262]
so after an update a long time ago, the emerald blocks were changed, i now have 32 emerald blocks that i cannot stack or turn into liquid emerald.

**Comment by Trixter313** [comment]
There are two ways you can go about converting the emeralds into the new type.

The first, and probably most easy, is to log into Wynncraft using 1.7.10. Once logged in simply trade the old emeralds with emerald merchants and you will receive the updated currency.

If you'd prefer, you can also go to the ocean village, Selchar, and trade the old emeralds with a special converter merchant. This method works no matter what version you are logged in with.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
