### ISSUE TITLE
A glitch wherein I got stuck under the floor...

### ISSUE THREAD

**Issue by SmallFrostGaming** [Wynncraft/Issues#2263]
Help! I got stuck under a floor! I got a tele scroll but just then, WHAM! Used My tele scroll but still stuck under the floor. I know you guys are busy, But, I really need help! I'll attach an image for you guys. I loved Wynncraft so much and I don't just wanna give up! And I've gone far already from the beginning, So please, understand this. Thank You.

The Class where in I got stuck is my Warrior. My username is DiamondmodMC. I don't wanna use other Classes cuz I've wasted time levelling my warrior and I've levelling it for a YEAR! So yeah. Fix This and Teleport me to the nearest Town Please. I am near Merloni, a quest npc, so just teleport me to Nemract.

**Comment by Trixter313** [comment]
Typing /die with 3+ soul points should resolve your issue and bring you to the nearest visited town.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by SmallFrostGaming** [comment]
Thanks so much!
