### ISSUE TITLE
Stuck in Spider Dungeon

### ISSUE THREAD

**Issue by NotYou42** [Wynncraft/Issues#2287]
Hello, a friend and I are currently grinding in the spider dungeon. He is a mage and blinked, as mages do. When he did so, he found himself stuck inside a wall. He can't blink out, he also can't use a scroll to leave. Is there anything anyone can do to help/fix this?

**Comment by Trixter313** [comment]
Typing /kill with 3+ soul points should bring your friend either to the entrance of the dungeon or the nearest visited town. (Possibly Selchar because all dungeons are actually located outside of the regular Wynn map.)

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by NotYou42** [comment]
Thank you!
