### ISSUE TITLE
Unbann me pls :( me name is: HURKA144 me not use hack :(

### ISSUE THREAD

**Issue by HURKA144** [Wynncraft/Issues#2306]

**Comment by Trixter313** [comment]
If you'd like to attempt to be unbanned, please make an appeal in the ban appeal section of the Wynncraft forums at https://forums.wynncraft.com/forums/ban-appeals.84/create-thread

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
