### ISSUE TITLE
Bank items disappearing

### ISSUE THREAD

**Issue by Cotey** [Wynncraft/Issues#2308]
Earlier I was rearranging my bank and I suddenly got stuck on the 'loading chunks' page and I left it for 2 minutes but nothing happened so I restarted minecraft and when I got back on I was missing from my bank a pair of boots (I don't know the name, and they aren't very important), quest items (which i got back doing /questfix) and 3LE and 40EB approx. This happened at around 8PM and I was on server 3. Please tell me if you can get my emeralds back!

**Comment by Dukeattack** [comment]
I as well was moving my Bob's Mythic Bow from my archer (75) into my bank to show a friend, when i opened my bank as my knight it was not there. This happened at 9pm CST, server 9. That bow means a lot to me it was fully IDed and my first Mythic after 2yrs (not the whole time lol) of playing Wynn, Please see what you could do about this, thank you

**Comment by Dukeattack** [comment]
Today at 4:45pm CST, i had a 4x IDed Cour De Lion in my inventory, i started a trade with the intent of selling it, the trade was canceled because he was going to offer a price. i had the item after the trade was canceled in my 2nd slot on my hotbar. we initiated the trade again and it did not appear in my inventory, or his, so it just vanished it seems

**Comment by Dukeattack** [comment]
Great, just noticed my full ID ghostly cap is also missing, im guessing this happened yesterday
