### ISSUE TITLE
I'm bugged

### ISSUE THREAD

**Issue by zneh3AC** [Wynncraft/Issues#2325]
I buguei and entered into leaf blocks , I 'm teleporting magician and was in the woods and just teleporting highest and went inside the leaves . I can not use scrolls and even teleport out of here . someone please help me.

**Comment by Trixter313** [comment]
Typing /kill into chat with 3+ soul points should respawn you at the nearest visited town.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
