### ISSUE TITLE
My Archer clothing does not change in my skin. (1.8.8)

### ISSUE THREAD

**Issue by VanisherS9** [Wynncraft/Issues#2326]
My Archer clothing does not change in my skin. I need help. Nick: VanisherS9

**Comment by Trixter313** [comment]
If the skin is correct when you take your armor off, you just have to wait a little bit for the custom armor skin system to update to your new skin.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by VanisherS9** [comment]
Sorry, but your answer did not help me. My skin is still only the look of the helmet.
I appreciate other help.
Thank you.
