### ISSUE TITLE
Guild Purchase Bug

### ISSUE THREAD

**Issue by breezyfeather** [Wynncraft/Issues#2338]
[img]http://i.imgur.com/vXLUhFc.png[/img]

Today when I was playing on Wynncraft, I went to the Guild Master to create a guild. I picked out a name: Eternity and the prefix: ETI. When I went to invite a player, it said I was not apart of a guild and took my 5 LE. Please help! SOS
-Thank you,
breezyfeather

**Comment by Trixter313** [comment]
This is usually fixed just by waiting a bit. Give it a few hours to a day and it should work correctly.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by breezyfeather** [comment]
Thank you, I will close this issue when it does work.
