### ISSUE TITLE
Darkness Glitch

### ISSUE THREAD

**Issue by EPICB3N** [Wynncraft/Issues#2352]
Im stuck under the ground and a guy is having the same as me his name is PhantomSlayer_MC im xX_EPICB3N_Xx anyways the images below show the problem i am having.
![2015-09-29_21 42 51](https://cloud.githubusercontent.com/assets/14899119/10182524/2f07f1be-66f3-11e5-8232-26e3bee78315.png)
![2015-09-29_21 42 53](https://cloud.githubusercontent.com/assets/14899119/10182531/370ec02c-66f3-11e5-87b7-e26518193633.png)
![2015-09-29_21 42 59](https://cloud.githubusercontent.com/assets/14899119/10182533/3b34e79e-66f3-11e5-8bcd-cc739f9f2e21.png)
![2015-09-29_21 43 02](https://cloud.githubusercontent.com/assets/14899119/10182535/3e31cc96-66f3-11e5-8de9-8deb9640aef4.png)

**Comment by Trixter313** [comment]
Simply typing /kill with 3+ soul points will teleport you to the nearest visited town.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
