### ISSUE TITLE
I Can't Play The Wyncraft Game

### ISSUE THREAD

**Issue by KevinLinGod** [Wynncraft/Issues#2382]
When i join a server im blind and in the ground and when i chose a class the class menu just goes away and i get disconected and then it say's try to reconnect but it doesn't work i just can't play the game, can you reset my player data maby?

**Comment by Submonsterine** [comment]
If you are stuck in a black box when you join Wynncraft and have more than 2 soul points, do /kill to get yourself out. Resetting player data is highly unlikely to fix this issue, as it is most likely something in your network, not Wynncraft's. If you keep disconnecting, you may want to try again later, since disconnections will occur sometimes.
