### ISSUE TITLE
Weapons / Armor Rest But Items still in inventory?

### ISSUE THREAD

**Issue by JayStarMC** [Wynncraft/Issues#2384]
I logged off yesterday with 13 soul points and I was in a secure village with no mods near. when I came on the next morning all the armor I was wearing was gone and my [ Sage / Wand ]  is now an [ Oak Wood / Wand ] Wile 2 of my quest items [ Bob's Crushed Soul ] & [ Yellow Crystal Shard ] along with a single [ Emerald ] Were still in my inventory. Please help resolve this issue. I talked to another friend of mine and said another peer of his had the same problem.

**Comment by Shadowzombie115** [comment]
sounds like the same issue i had. logged off yesterday and came back online this morning and my fully id'ed bow with  sharpness 2 was just gone. and i was not my fault for losing it in any way because I didn't drop it and i don't have the drop key enabled so your not going to be getting any thing back from them for their servers problems sadely.
