### ISSUE TITLE
I cannt me connect to the serv

### ISSUE THREAD

**Issue by zutetflute** [Wynncraft/Issues#2387]

**Comment by zutetflute** [comment]
i cannt me connect to the server

**Comment by Submonsterine** [comment]
Are you sure you have the right IP? The IP is play.wynncraft.com. Check that you are on versions 1.7.10 to 1.8.8 and are not using a cracked account. The Wynncraft Servers will be down sometimes, and sometimes mojang login authentication servers will be down as well, so that may be the cause of your problem.

**Comment by commandhat** [comment]
Actually, Wynncraft requires 1.8.6 at least, 1.7.10 no longer works. Keep the launcher log up while trying to connect with 1.7.10, you'll see a "you need version x x x to connect!"
