### ISSUE TITLE
Guilds Are Broken

### ISSUE THREAD

**Issue by BuddGaming** [Wynncraft/Issues#2481]
I just created my guild (A Derpy Clan) (ADC) And Its not leting me use the guild features. Please help!
My IGN is BuddGaming

**Comment by Trixter313** [comment]
Guilds just take a little time to fully register after being purchased. Wait a few hours and you should be able to.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
