### ISSUE TITLE
Requesting character rollback due to a bug.

### ISSUE THREAD

**Issue by qlpwii** [Wynncraft/Issues#2491]
Hi my name is Giantlobstah and I died recently losing all of my items due to a bug with the Zombie dungeon boss. I killed the dungeon boss but i was not teleported out of the room and was basically trapped in a room with monsters everywhere. The boss respawned and killed me but it shouldn't have had the chance to kill me since i was supposed to be teleported out after the first boss fight. I feel like i should get a character roll back unless the boss is supposed to spawn twice and i'm just a dweebus.

**Comment by eldarkolinko** [comment]
This bug happen sometimes, you just have to kill the boss again to get out of the dungeon. It's your own fault, you shouldn't get into anything with no soul point or only 1.
Now what you can do is playing with another class until you get items for this level and then, use your enderchest ( put the items in it ) in order to be able to play with this class :(
Sorry.

**Comment by TrashcanMan** [comment]
If you're stuck in the boss room, just do /kill and you should get out. Sometimes killing the boss doesn't teleport you out, you might have to kill it twice.

**Comment by Trixter313** [comment]
We'd appreciate it if you closed this issue. Thanks!
