### ISSUE TITLE
Lost 7 LE due glitch with Jungle Fever quest.

### ISSUE THREAD

**Issue by Creepaaaaa** [Wynncraft/Issues#2493]
Today I was doing the jungle fever quest with my assassin class, and when I gave the Almuj's liquified emerald to Worid, it took my 7 regular LE and left 7 Almuj's LE in my inventory.
![2015-11-07_13 46 55](https://cloud.githubusercontent.com/assets/15703354/11015232/808451d2-8556-11e5-97a3-3fbb28d8714b.png)
![2015-11-07_13 47 53](https://cloud.githubusercontent.com/assets/15703354/11015235/858063a6-8556-11e5-83ba-221fad7c8cf5.png)
![2015-11-07_13 48 43](https://cloud.githubusercontent.com/assets/15703354/11015237/88cc83dc-8556-11e5-9748-a0bc89168e19.png)

Ingame name: Creepaaaaa

thanks for reading.

**Comment by skillerfox3** [comment]
If you have read the wiki page you would have known this.

The LE given in stage 6 cannot be spent, but when giving them to Worid, ensure you don't have any normal LE in your inventory, as there is a glitch which may cause him to take the wrong ones, leaving you with worthless LE.

**Comment by TrashcanMan** [comment]
You might be able to email support@wynncraft.com and ask them to exchange the quest LE for regular LE, but I'm not sure.

**Comment by Trixter313** [comment]
Are you still experiencing this since the Gavel update? You could try trading the LE with the converter merchant in Selchar.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
