### ISSUE TITLE
A quest item has been deleted from my inventory

### ISSUE THREAD

**Issue by Gameshot65** [Wynncraft/Issues#2511]
I was in a dungeon of Ancient Nemract to do the quest Lost Tower, and to take some items in front of me I started to drop other items from my inventory to make space. Accidentally I dropped the quest item Maltic Recommendation Letter, but it hasn't been replaced in my inventory and has been deleted although there were other free spaces. Since it is a fundamental object to complete a future quest, I would like to have it back if possible.

**Comment by brainscript** [comment]
@Gameshot65  `/fixquests`

**Comment by Trixter313** [comment]
If your problem is now resolved we'd appreciate it if you closed the issue. Thanks!

**Comment by DarkDemonDragon** [comment]
This is actually kinda desirable since Quest items simply take up space for a long time. My mage is currently holding most of my quest items and I had to wait til I was lvl 50 to get the final Bank upgrade before I could start lvling up a 3rd class since I know that I'll need some space for my future Breathing Helms, Creeper Masks, etc. -3- Some quest items don't even get consumed during the future quests and then end up being REALLY annoying. Would be nice for a future update if a quest NPC could say after you get the materials for a quest item you have that doesn't get consumed: "Oh it seems you already have one, but I'll still take the materials" and then progress from there without needing additional space for unstackable quest items.
