### ISSUE TITLE
Lord Of The Clock quest - Frudo

### ISSUE THREAD

**Issue by PumpkinPie74** [Wynncraft/Issues#2529]
Hi,

I was doing the quest "Lord Of The Clock" and I was at Frudo (You have to let him throw the clock into the lava) and when I rightclicked him (He took the clock) The server restarted. When I logged back in nothing happened.I think because I right-clicked on Frudo and the server restarted, the quest bugged. Because now every time I right-click on Frudo, an empty bar appears in the chatbox. I cant really do anything about this because the other 2 NPC's in the quest just tell me to go to Frudo.. but I already did and he took the clock..

Could someone please fix this for me?
IGN: PumpkinPie74

Thanks!

**Comment by DarkDemonDragon** [comment]
As a general tip don't do important things like completing dungeons and quests up until the last second since things like this can happen.

Anyways what does your quest book say? If it says something like give Frudo the clock or something to indicate you should have the clock just do /fixquests. However, if it says the quest was completed then the game registered the fact you've completed the quest.

**Comment by Trixter313** [comment]
Are you still experiencing this since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
