### ISSUE TITLE
Broken Server Select

### ISSUE THREAD

**Issue by ThePastryMaster** [Wynncraft/Issues#2537]
So you know how, when you log on to Wynncraft, you use the compass to connect to a server... well my compass is broken. Whenever I try to select a server, it just exits me out of the compass screen and nothing happens. And this isn't the first time this has happened, but I could usually fix it by logging off then logging back on. But now nothing is working.

**Comment by DarkDemonDragon** [comment]
Ask the players around you if they can get in because sometimes servers are down and no one at all can get in. This is also happen if you're in the middle of something and you leave because the server resets and then the server still registers you as "logged in" as in your character is still there. Timing out also causes this error occasionally.

**Comment by LivingShadowWof** [comment]
A way to fix this I found was to restart the launcher and by that I mean closing minecraft and then closing the launcher as well if this doesn't work then just wait for a bit it should fix it's self

**Comment by Trixter313** [comment]
Are you still experiencing this since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
