### ISSUE TITLE
24400 character limit on forums glitched

### ISSUE THREAD

**Issue by CookedPelvis** [Wynncraft/Issues#2548]
Hi, my name is CookedPelvis. I am the co-owner of the Wynncraft trading business Lusuco Item Supply Co. and due to the 24400 character limit, I cannot update my thread with new items. Please help fix this. I pasted everything that was on the thread into a word document on my computer and it counted the characters as around 6,000. Please fix this, it really degrades from the quality and quantity of the items in the store. 
![wynn bug proof](https://cloud.githubusercontent.com/assets/11055356/11347535/c048d7ac-91d6-11e5-9835-d01875af4733.PNG)
![wynncraft bug](https://cloud.githubusercontent.com/assets/11055356/11347537/c4e35788-91d6-11e5-93f9-49da3b9cae78.PNG)

**Comment by Moe-Ronickah** [comment]
Unless I'm mistaken, each and every one of your [TAGS] is counted as a character in the message.  So, every [COLOR] and every [FONT SIZE] counts.  Further, if you are centering your text by using blank spaces, instead of the [CENTER] text command, every one of those spaces counts, too.  Word, on the other hand, only counts the number of human readable characters.

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
