### ISSUE TITLE
old version liquid emerald

### ISSUE THREAD

**Issue by AlmightyTato** [Wynncraft/Issues#2555]
I had liquid emerald from the old versions of the server and now they arent worth anything and cant do anything with them.I asked some players what i should do and they told me to go to Selchar. And i did, and when i came to the exchange guy, it didnt work. emeralds and emerald blocks did work but not liquid emerald. please fix this cause i cant do anything with them.

![2015-11-25_12 33 05](https://cloud.githubusercontent.com/assets/16015890/11396349/160edc72-9371-11e5-831f-7e188ae381fa.png)

**Comment by DarkDemonDragon** [comment]
I heard that switching back to 1.7 and trading them normally may solve the issue, so try that.

**Comment by AlmightyTato** [comment]
can't join the server when im in 1.7

**Comment by SkySaito** [comment]
I guess you'll have to wait for the next update then.

**Comment by Trixter313** [comment]
There's a merchant in the ocean city Selchar that will convert your old LE's to the new type.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
