### ISSUE TITLE
item dissapearing

### ISSUE THREAD

**Issue by counto1** [Wynncraft/Issues#2565]
I just made my lvl 65 legendary help have thorns 2 when it disspeared and looked around and even relogged but it disspeared please give my lvl 65 legendary helm back it cost 2 le to buy.  Thank you

**Comment by Moe-Ronickah** [comment]
[DUPLICATE]
I'm sorry, counto1, but WynnCraft has a strict no-refunds policy due to previous instances of players being less than honest.  You aren't alone in having items disappear, and I know that that is no consolation to you, however, it does happen, every now and then.  At Lv65, if you go farming int he Herb Cave, and selling spare rare and legendary items in Detlas, you should be able to make up the lose fairly quickly.

Would you please close this issue?  Thanks, in advance.
