### ISSUE TITLE
Player Going Into Void AGAIN and it is still DARK MAGE....

### ISSUE THREAD

**Issue by LockeC** [Wynncraft/Issues#2571]
and well title explains this has happened a long itme ago and also the person told me to restart character i know its a lvl like 15 but i wanna restart him also wanna get out..... so plz someone tell me the command

**Comment by Trixter313** [comment]
If you type /kill into chat with 3+ soul points you will respawn at the nearest visited town.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by LockeC** [comment]
i want to restart my whole character and there is a command just forgot it.

**Comment by SkySaito** [comment]
There's no command for that yet. The person lied to you. For restarting a character you must wait the next update.

**Comment by LockeC** [comment]
SkySaito ive done that command and have it worked... he was not lying

**Comment by TrashcanMan** [comment]
Do you mean /fixstart? That one just teleports you back to spawn, it doesn't reset any data.

**Comment by SkySaito** [comment]
Sorry, but it must have been in another server or such.
In the Gavel QnA by Grian, he said the update will feature a way of restarting, meaning there's nothing yet for that. Maybe it's Trashcan idea but I assure you that no command yet can restart a character, since after such a long time, people would have discovered it.

**Comment by Trixter313** [comment]
You should be able to restart a character now.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
