### ISSUE TITLE
GUild battle disconnect

### ISSUE THREAD

**Issue by darklord646** [Wynncraft/Issues#2574]
I was joining a battle and when i got in the water a few seconds ( 10, 20 ) i was pushed to the ocean and i got disconnected, so i lost the battle

**Comment by Trixter313** [comment]
Has the issue occurred since then? If not, it was most likely just a one time issue.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
