### ISSUE TITLE
Guild bug (name changed)

### ISSUE THREAD

**Issue by MisterShinigami** [Wynncraft/Issues#2593]
I changed my minecraft name last week and now I can't see the guild chat etc.

**Comment by TrashcanMan** [comment]
Name changes are known to mess up guilds, just get re-invited.

**Comment by MisterShinigami** [comment]
I can't leave I'm the owner ...

**Comment by TrashcanMan** [comment]
That's unfortunate...
I'm not really sure what you can do about that.

**Comment by Trixter313** [comment]
Are you still experiencing this issue since the Gavel update? The only thing I can suggest is maybe trying to change your name back and see if that returns leadership.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
