### ISSUE TITLE
Unballanced missions.

### ISSUE THREAD

**Issue by GamerGamerFTW** [Wynncraft/Issues#2600]
This is what i sometimes see - 
http://prntscr.com/9b0lvl
So please balance out missions (or add 100k xp to that mission :P)

**Comment by SkySaito** [comment]
Just kill these Charon, worth the 31 Xp.
(And since it take in account the last mob you killed, dunno if there's a way to fix this. However you have /dismiss for this)

**Comment by Trixter313** [comment]
Missions are random and depend on mobs nearby/recently killed. Just ignoring it shouldn't be too hard when something odd like this happens.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
