### ISSUE TITLE
I Can't Gain / Lose Player Xp!!!

### ISSUE THREAD

**Issue by joejoetheminer** [Wynncraft/Issues#2609]
In This Server I Can Even Try To Do The Silverfish Dungeon, Succeed And Stull Not Get Any Xp At All And Also I Don't Lose Any Xp When I Donate To My Guild Ether! Please Fix This As Soon as Possible, Thank You For Reading This Bug Report!
P.S: If You Need It My Minecraft Name Is joejoetheminer And If You Need To Find Me Most Of The Time I Will Be On Server 2!

**Comment by SkySaito** [comment]
Lose Xp ? You can't lose Xp, you can just modify the amount of experience your guild gains when you kill a mob or finish a quest, because it will take a percentage of this Xp.
And for the Silverfish Dungeon, they still are buggy for what I remember, so wait for the next update about that.

**Comment by joejoetheminer** [comment]
I Have Tried Every Way Of Getting Xp: Mobs, Dungeons, quests, missions...
Please Fix This!

**Comment by DarkDemonDragon** [comment]
@joejoetheminer you would need some video proof for anything to be done. In the video first in the class menu hover over one of your classes to show the current xp %. Then do something substantial like the Silverfish dungeon. After gaining a good amount of xp do /class again to show if the xp % changed. Xp may not seem in increase in-game at higher levels because the you need a lot more xp to level up so 1000 xp at Lv 5 might be a bunch of xp, but 1000 xp at Lv 50 is not much. You would do the same thing to prove that your xp is truly decreasing at times.

**Comment by Seberichsen** [comment]
Try ro do /guild xp 0

**Comment by Trixter313** [comment]
Are you still experiencing this since the Gavel update?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
