### ISSUE TITLE
Mt. fuij portal

### ISSUE THREAD

**Issue by JustBeMyself00G3tR3ktM4t3** [Wynncraft/Issues#2615]
i thought it would be fun to go in the portal that is located in mt. fuij but now im stuck in the end, with no stuff plz help me

**Comment by DarkDemonDragon** [comment]
What do you mean no stuff? If you have no item just do /kill and you'll be sent to the nearest town.

**Comment by ThunderRemix** [comment]
Huh, what are you talking about?

**Comment by TrashcanMan** [comment]
I don't think we have a Mount Fuji...

**Comment by DarkDemonDragon** [comment]
I think he may be on the wrong server github... @JustBeMyself00G3tR3ktM4t3 confirm this is a Wynncraft issue, because at Wynncraft there is not Mt. Fuji, there is no access to the End at this time, and it is impossible to get anywhere like that without some armor of some kind. Also, this is a coding issue page meaning that you should only post issues like bugs and such that the developers may try to fix. Issues like I'm stuck somewhere because I'm surrounded by Lv 70 mobs and I'm only Lv 30 should not be posted here as in Wynncraft dying is not that punishing until you lose all your soul points. Even then it's your own responsibility to watch the recommended levels in each area.

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
