### ISSUE TITLE
Items disappearing 

### ISSUE THREAD

**Issue by Jacoblouis13** [Wynncraft/Issues#2655]
I happen to own 8 stacks of roses (obtained legitimately via hiring people to get them for me) I use to have 10/11 stacks of them though. when i would take all of them out of my bank to show people in the trade menu, they would be there but when i exited out of the trade menu i lost a whole stack. i noticed when i shift-clicked the items into the trade menu, it would leave open a space where an item should go. normally they fill up the whole screen from the top left going onward. but this time it skipped a slot which was strange. after i closed the menu i got all my roses back except for one whole stack. i checked the ground all around me and asked the people but no one had the roses. this happened a number of months ago and it was because of the same reason. any way you guys could fix this strange bug?
Thanks

**Comment by Trixter313** [comment]
Are you still having this issue since the Gavel update? Wynncraft has a strict no refund policy so that stack probably can't be returned to you.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
