### ISSUE TITLE
bugging in a block

### ISSUE THREAD

**Issue by Bernidina** [Wynncraft/Issues#2661]
My friend (ingamename: CookieSuchti) is bugging in a block. He can't get out.

**Comment by Bernidina** [comment]
with his mage

**Comment by Trixter313** [comment]
Sorry it took so long to respond! Tell you friend to type /kill with 3+ soul points and they should be respawned at the nearest visited town.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
