### ISSUE TITLE
Defense skill not registering

### ISSUE THREAD

**Issue by WillZdeKIllr99** [Wynncraft/Issues#2668]
After the new Gavel update, I restored my skills. I am unable to equip my leggings because they require a defense skill of 20+, though my defense skill is currently at 25.
![2015-12-20_21 43 29](https://cloud.githubusercontent.com/assets/16378720/11924214/d102b27e-a762-11e5-929e-451f2e264aa0.png)
![2015-12-20_21 43 40](https://cloud.githubusercontent.com/assets/16378720/11924216/d459a45a-a762-11e5-806f-648e225b233a.png)

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes these things are fixed by a little time passing.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
