### ISSUE TITLE
Agility Skill not letting me equip armor

### ISSUE THREAD

**Issue by Akamito** [Wynncraft/Issues#2669]
http://imgur.com/a/AQEPT

Says I need lvl 10, but I have it...

**Comment by WillZdeKIllr99** [comment]
I had a similar issue with defense

**Comment by Trixter313** [comment]
Are you still experiencing this issue? Sometimes a little time resolves things like this.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by RusTy-TCat** [comment]
Check your armour, some items have -agility and that means you cannot use certain things
