### ISSUE TITLE
Keep getting kicked from game servers trying to hand in quest

### ISSUE THREAD

**Issue by Thegamerplus1** [Wynncraft/Issues#2680]
Trying to hand in the Heart of levigar quest when My internet died, now I get kicked whenever I try to logon to  game server. (hub works fine.) Username=Thegamerplus1

**Comment by Trixter313** [comment]
Are you still experiencing this issue? Sometimes this is fixed by a little time passing.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
