### ISSUE TITLE
Disconnection Glitch

### ISSUE THREAD

**Issue by cmt600** [Wynncraft/Issues#2681]
Periodicly, the server tends to kick me off the server for no reason.
'There has been an error. Please log back in!'
Please fix.

**Comment by Thegamerplus1** [comment]
Same here. When I join a server it puts 2 lines of "thank you for downloading Wynnpack" or something, and then 2 blank lines. it then kicks me to hub.

**Comment by Trixter313** [comment]
Are you still experiencing this issue? A little bit of time usually resolves things like this. Additionally, the addition of Gavel is still really recent so they are trying to cope with the added lag.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by Thegamerplus1** [comment]
This is fixed by a little bit of time, or sometimes trying to rejoin a server, but allways recurs after a length of time

**Comment by Trixter313** [comment]
It's most likely just because of all of the returning players who stopped playing but came back for Gavel overloading the servers. After a few days it'll probably resolve itself.
