### ISSUE TITLE
This isnt really a bug, but i dont know where i need to post it..

### ISSUE THREAD

**Issue by ITheWolfyzI** [Wynncraft/Issues#2693]
I just logged in, and i saw i had 50 skillpoints, i thought spending them all onto strength was smart, but when i tried to use my bow, it said i needed another skill, so can i maybe get a skillpoint reset or something like that ?

**Comment by Trixter313** [comment]
There is a way to reset skill points in-game. You have to do the "Tower of Amnesia" quest and then, at the top of the tower, there's a merchant who sells skill reset scrolls for 1 LE. Other than that I don't think there's any other way. Sorry!

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
