### ISSUE TITLE
Mage: Ice Snake

### ISSUE THREAD

**Issue by Exvhius** [Wynncraft/Issues#2702]
Ice Snake used to freeze enemies...

I don't know if this was purposely changed, but now it just does a fraction of the damage mages already (don't) do. It doesn't slow, freeze, or really anything outside a tiny bit of damage.

**Comment by EPICB3N** [comment]
lol ur lucky i cant use spells all together

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
