### ISSUE TITLE
[Resource Pack] Can't connect to any server

### ISSUE THREAD

**Issue by RobinBressoud** [Wynncraft/Issues#2704]
Hi, 
I recently tried to connect to one of the server. Unfortunatly, I missclicked "No" when I was asked if I wanted to install the server's ressource pack. I was then kicked from the server with the information : "Connexion lost : You must have the pack to play Wynncraft".
The problem is that even after reconnecting, the ressource pack message is not shown anymore, so I'm instantly disconnected.

![connexionlost](https://cloud.githubusercontent.com/assets/16384043/11930410/59f70884-a7e3-11e5-8d66-8d49720dc1bf.PNG)

**Comment by Trixter313** [comment]
Click once on the server and then click edit. Change "Server Resource Packs" to enabled. The pack should download next time you login. =)

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by RobinBressoud** [comment]
Thank you very much. :)
