### ISSUE TITLE
Mob Tags do Not Show.

### ISSUE THREAD

**Issue by Deestinyer** [Wynncraft/Issues#2708]
The health, level and name of each mob does not show in the game. 
I am using the wynncraft texturepack. 
http://prntscr.com/9grgyg

**Comment by Trixter313** [comment]
Is the issue still occurring? It's working properly for me. Sometimes things like this just need a little bit of time to fix themselves.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by Trixter313** [comment]
If you can't see name tags, please update your Minecraft to the latest version. Thanks!

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
