### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by elmochu** [Wynncraft/Issues#2713]
I can not use my arrow spell im not sure why i have tried everyth

**Comment by Trixter313** [comment]
Do any spells work for you? Make sure you meet all of the requirements to use the bow you're holding.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
