### ISSUE TITLE
Endgame armor lost ?

### ISSUE THREAD

**Issue by itsoumi** [Wynncraft/Issues#2714]
Hello,

My problem is different in my mage and assasin.
In my mage, Crystal has been replaced by Dalam without any action of me and stalagmite has been replaced by bloudil.
In my assasin, I wanted to take crystal from myself to put it in my inventory and instead of just taking it, it took all the armor parts but I only had 2 free spaces on my inventory. As a result: I lost stalagmite and adamantite.

To resume, I lost Adamantite, crystal and two times stalagmite.

I hope that you will be able to check if I lied because it's not the case and I would like to discover Gavel (I didn't have the time because of that).

Thank you by advance for your help.

itsoumi.

PS: is it possible to play without the official texture pack ? I don't like it.

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a very strict no refund policy so not much can be done about this. Also, as of right now, there's no way to not use the resource pack. Even if you didn't, things wouldn't really make sense because they re-textured different items to look like weapons such as leaves etc. We'd appreciate it if you closed this issue. Thanks!
