### ISSUE TITLE
Dungeon Keys

### ISSUE THREAD

**Issue by Philosophunculist** [Wynncraft/Issues#2718]
I don't know if this is a glitch or a intentional change, but after completing the skelleton dungeon multiple times i have recieved no Spider dungeon keys, dispite the fact that it says in chat:       "[+Spider Key]" EDIT: on my 6th atempt it finaly gave me 1 spider key.

In addition sometimes no emeralds or gear drop.

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
