### ISSUE TITLE
Broken Weapon

### ISSUE THREAD

**Issue by Mdowg123** [Wynncraft/Issues#2719]
I have identified my Broken Harp, but when I try to use it, it says I need an intelligence level of at least 10. My intelligence is currently set at 12.

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
