### ISSUE TITLE
Missing boat merchants

### ISSUE THREAD

**Issue by 2000Polas** [Wynncraft/Issues#2720]
I travelled to Ice Islands and discovered that there is no Boat merchant. I tried to restart Minecraft and join different server but still no merchant.

**Comment by Jaguar11891** [comment]
They are also missing on Zhight Island and the Bear Island

**Comment by Trixter313** [comment]
Thanks for the bug report! An admin should see this soon and hopefully will be able to help.

Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
