### ISSUE TITLE
Arrow Storm not working

### ISSUE THREAD

**Issue by MCSpeed86** [Wynncraft/Issues#2724]
So my brother is an Archer, but when we dueled the Arrow storm didn't work.
But it does take away the mana though, and it also says it used the spell, but didn't show or damaged.

Any help?

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
