### ISSUE TITLE
Spells not working on mage 

### ISSUE THREAD

**Issue by EPICB3N** [Wynncraft/Issues#2726]
I cannot use my spells 
-basic attack not working
-meteor spell not working
-Ice Snake not working
-teleport not working 
on mage, its probably because i cant click the combinations for some reason, you know the 
Right-Right-Left 
pls help

**Comment by Trixter313** [comment]
Make sure you meet all of the new requirements to use your weapon. To see the requirements, mouse over the wand.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by EPICB3N** [comment]
Ok so after experimentation I realized that the weapon was glitched, the weapon called
the "Devoruse". Because then I used my other weapon the "curse" and it was fine I could use it. But the other problem was that I was doing less damage then I had been doing before the update, I know this because I tested it on the mad cows outside of Detlas, it used to be a 1 shot kill with basic attack now its 2 shots with basic attack and I'm level 45 using the curse.

**Comment by Trixter313** [comment]
Several things did get nerfed in the update so doing less damage is probably to be expected. Also you might have done your skill points in a different way that does less damage. As for the glitched weapon, that would be this issue here: #2679 

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
