### ISSUE TITLE
Names of npcs and mobs not showing up

### ISSUE THREAD

**Issue by JulieDoesMC** [Wynncraft/Issues#2728]
When joining Wynncraft last night with the Gavel update, I was running around when I realized I was unable to see the names of any npcs or mobs. Occasionally the damage delt will pop up (in yellow I think) but only for a split second. I was wondering if this is a wynncraft issue. I've played around with my video settings to see if that could be a cause if this. Nothing seemed to work. I've tried removing any resource pack I've had undernethe the wynn resource pack. This is the only thing that has been bugging me about the update and I want to enjoy it to the fullest. It's a bit scary to run around unfamiliar lands without being able to see what mob I'm fighting and what level it is. 
Thanks 
~Auxiliary_

**Comment by ChaosDunkFTW** [comment]
Same for me dude

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by Tobyshaggs** [comment]
For me, this problem has been occurring contentiously since the update. and is still happening. I would like some assistance please.

**Comment by JulieDoesMC** [comment]
I've figured out the problem. All you need to do is update your minecraft to the newest one.
