### ISSUE TITLE
green gloop quest not doable

### ISSUE THREAD

**Issue by sambam138** [Wynncraft/Issues#2732]
i think the green gloop quest is not possible to do becouse of the new update where you bottle disapear when you drink them you need to give 5 glass bottles i tried evrything i can think of like going to the potion merchant but they dont sel glass bottles, and i tried emptying a water bottle in a bruwing thingy but thet didnt work (srry for my english i hope you'l understand xD)

**Comment by TheLeirbag** [comment]
Exactly! Same thing is happening with me. Someone please support this!

**Comment by Trixter313** [comment]
Now you have to to to the water bottle merchant in Ragni and drink the water in them, resulting in empty bottles.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
