### ISSUE TITLE
World 49 is Vanilla

### ISSUE THREAD

**Issue by Xyntak** [Wynncraft/Issues#2734]
World 49 is not Wynncraft but a vanilla generation with quest npc's

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
