### ISSUE TITLE
TExture pack Glitch

### ISSUE THREAD

**Issue by ChaosDunkFTW** [Wynncraft/Issues#2736]
I cant see the names of villigers guards mobs etc... And i cant see their helt and dmg i am doing pls help me i reloged like 10times and restarted my pc 2 times idk what else 2 try :(

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
