### ISSUE TITLE
Found a few bugs

### ISSUE THREAD

**Issue by GhastlyFlame** [Wynncraft/Issues#2737]
Some are builder mistakes, like exposed command blocks, others are game breaking, i have links
https://www.youtube.com/watch?v=lEkDqE3Dx8k
https://www.youtube.com/watch?v=vQMNms6tQGg
https://youtu.be/ik8YjEUkP8g

**Comment by Trixter313** [comment]
Are these issue still occurring? Sometimes things like this just need a little time to sort themselves out. Also, for future reference, it's best to post separate issues if you have more than one bug to report. Thansk!

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
