### ISSUE TITLE
Every Player Is spawning In a Vanilla world in every server.

### ISSUE THREAD

**Issue by MythicalEntity** [Wynncraft/Issues#2738]
Whenever anyone in wynncraft tries to join a server, it spawns them in a vanilla minecraft world. NPC's and loot chests are still there. but the actual map itself is gone.  please fix!

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
