### ISSUE TITLE
Requirements Not Working

### ISSUE THREAD

**Issue by wizardboy07** [Wynncraft/Issues#2746]
![screenshot 2015-12-21 10 39 49](https://cloud.githubusercontent.com/assets/7107070/11938412/8669ce92-a7cf-11e5-90c5-773fedfb8c79.png)
![screenshot 2015-12-21 10 40 14](https://cloud.githubusercontent.com/assets/7107070/11938422/92563f92-a7cf-11e5-9d23-4fdacf51c146.png)

I have the defensive, level, agility correct, but it still says I haven't fulfilled the requirements for agility.
I have tried relogging, but it still didn't work.
![screenshot 2015-12-21 10 41 04](https://cloud.githubusercontent.com/assets/7107070/11938454/ca5f618e-a7cf-11e5-972c-b77a52a54542.png)

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by wizardboy07** [comment]
Don't worry it's all good now
