### ISSUE TITLE
No Dungeon Loot

### ISSUE THREAD

**Issue by Philosophunculist** [Wynncraft/Issues#2752]
After completing dungeons, 90% of the time you get no loot, including no key to the next dungeon.

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
