### ISSUE TITLE
Archers dont get xp only on arrow storm

### ISSUE THREAD

**Issue by 0Illegaldanish** [Wynncraft/Issues#2753]
every time i shoot an arrow i dont get xp but when i use arrow stom / bolt blizzerd i can get xp

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
