### ISSUE TITLE
Potion Names When Buying Potions

### ISSUE THREAD

**Issue by awemanrank100** [Wynncraft/Issues#2759]
Upon buying a potion, any old potions in your inventory will have their name changed to "HEALING X" (X being a number of whatever potency is on your potion) and their lore changed to "{'remaining':X}" (X being however many uses on it you have left; it does not display if you have not drank from it).

**Comment by mirajhall** [comment]
I saw also, but when I looked later they were fine. Not sure what happened.

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by awemanrank100** [comment]
The names remain for a few seconds after closing the shop window.
