### ISSUE TITLE
Not being able to log in

### ISSUE THREAD

**Issue by Zoee64** [Wynncraft/Issues#2771]
Everytime I log into a server I time out or something else appears (screenshot will be down below) I fixed the issues of timing out by making the texture pack prompt not give it to me instantly. If it doesn't time out the server will show me the screen for a split second then this shows up:

Connection Lost:
Internal Exception: java.io.IOException: An established connection was aborted by the software in your host machine

as it says there it has something to do with my computer but idk what. I really want to play Gravel so if I could have some help please.

EDIT: If I enable the texture pack instead of prompt I'll time out. Also sometimes if I do have it enabled the same thing shows up.

(Copied from my thread: https://forums.wynncraft.com/threads/help.98080/  If you wanna see the screenshot its on there)

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
