### ISSUE TITLE
EXP Bug

### ISSUE THREAD

**Issue by DAV1DCRE8R** [Wynncraft/Issues#2772]
When I kill enemies in one hit, I do not receive any EXP even if the death hologram states [+(x) XP].

IGN (if needed): DayVyd

**Comment by skillerfox3** [comment]
What is your level? When you are a higher level you don't see your XP increasing fast.

**Comment by DAV1DCRE8R** [comment]
At the time of this post, I had just started a new character. When I one-hit killed the chickens, there was no "ding" sound when you gain EXP and my EXP bar did not move, even though the hologram stated I gained XP. However, when it took more than one hit to kill the chickens, there was always that sound and my EXP bar always increased.

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by DAV1DCRE8R** [comment]
Patch 14.0.3 has fixed this bug. :)
