### ISSUE TITLE
Rise of The Quartron Boss Battle problems.

### ISSUE THREAD

**Issue by annoyingenderman** [Wynncraft/Issues#2773]
The mecha boss battle of the quest does not work. I've met several other people with the exact same problem.Issue; Nothing happends after you defeat the boss and collect all the cores. The guy doesn't say anything, the endermite keep spawning and nothing really happends.

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
