### ISSUE TITLE
Calo says nothing for Flight In Distress quest

### ISSUE THREAD

**Issue by MedievalBladeRPG** [Wynncraft/Issues#2778]
When I attempt to talk to Calo as part of the Flight In Distress quest, he doesn't respond, but instead creates a blank line in the chat. This prevents me from completing the quest and receiving rewards from it.

![2015-12-21_17 41 03](https://cloud.githubusercontent.com/assets/16379066/11943317/df985b88-a80a-11e5-99ca-3fc92eee454b.png)
![2015-12-21_17 40 54](https://cloud.githubusercontent.com/assets/16379066/11943316/df975f30-a80a-11e5-9044-294c53caa3af.png)
![2015-12-21_17 41 05](https://cloud.githubusercontent.com/assets/16379066/11943319/e1a0cc26-a80a-11e5-9bb0-9adf650b3b87.png)

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
