### ISSUE TITLE
[Bug] Cannot see Mob names and levels

### ISSUE THREAD

**Issue by John0696** [Wynncraft/Issues#2783]
When i am playing wynncraft, i cannot see mob names or quest names. do not know if this is client related or server related
![2015-12-21_14 54 10](https://cloud.githubusercontent.com/assets/16392906/11943496/2b31e93c-a7f3-11e5-9413-72dd11b133e2.png)

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by Trixter313** [comment]
If you can't see name tags, please update your Minecraft to the latest version. Thanks!

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by John0696** [comment]
Thanks for helping me, i really appreciate it :)

**Comment by John0696** [comment]
But how do i close one of these again?
