### ISSUE TITLE
My skill points won't let me put points on defense: all 23 of the points disappeared and transferred to i believe agility.  Help?

### ISSUE THREAD

**Issue by kingds321** [Wynncraft/Issues#2789]
In the update room, I was adding skill points to my character.  When clicking on defense for the first 23 time, it showed up fine.  After closing it out and putting on a pair of pants that required 15 defense, 2 minutes after putting them on it said that my defense wasn't high enough.  I checked and it said 22 (or so) so I added another point to see if that would make it work.  It showed 23 so i thought OK and tried to put it on again, but it didn't work.  Apparently now over an hour later it shows that all of my defense points were switched to my agility skill points.  I don't want to spend a LE fixing this and this may be an issue with other people.

Thanks

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
