### ISSUE TITLE
The beast of the shadows

### ISSUE THREAD

**Issue by HackingDonor** [Wynncraft/Issues#2790]
The Ancient Monster Code isn't working, i tried everything that i got told, i solved the mystery, and it will still not work!

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out. I just did the quest successfully so I think it's fixed.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by HackingDonor** [comment]
Oh ok ty, but maybe it is my fault.. Is the Code Pink,Light blue,Green Yellow?

**Comment by HackingDonor** [comment]
IT WORKED ALL I HAD IS TO PRESS THEM SLOWLY LOL. Ty for the help <3!
