### ISSUE TITLE
Right-Click to upgrade

### ISSUE THREAD

**Issue by RiceSensei** [Wynncraft/Issues#2791]
When you want to use your points on an upgrade, you can right-click and use 5 on 1 skill. But when I did this it just took away 5 of my points without upgrading anything

http://youtu.be/abikVZQyGh8?hd=1

**Comment by TheGamingReaver** [comment]
It could be you have gear on that lowers your agility by more than 5 so if you took that off or raised your agility enough it would then go above zero.

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out. Or it could be like TheGamingReaver said.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
