### ISSUE TITLE
Can't change class in the update room

### ISSUE THREAD

**Issue by SpectralPuppy** [Wynncraft/Issues#2794]
I'm not sure if this is intended or not, but the /class command doesn't work in the update room. I was trying to switch from assassin to archer but I couldn't.

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
