### ISSUE TITLE
Can't see nametags

### ISSUE THREAD

**Issue by CryteriaPlugins** [Wynncraft/Issues#2798]
Can't even see the nametags of entities, only players. This is a wynn only problem

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
