### ISSUE TITLE
Corrupted/Glitched Chunks

### ISSUE THREAD

**Issue by AncientPancakes** [Wynncraft/Issues#2802]
there a quite a few chunks that have glitched out and removed the whole chunk, and some interfere with quests such as the basement of the ruined house in the 'Lazarus Pit' Quest

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by AncientPancakes** [comment]
It was fixed in the latest patch, tnx :D, ill close it now
