### ISSUE TITLE
BUG FLAT LAND

### ISSUE THREAD

**Issue by CHENS85** [Wynncraft/Issues#2804]
![2015-12-21_21 09 37](https://cloud.githubusercontent.com/assets/5460820/11946340/6a3c4ce2-a80e-11e5-953c-3fad0cbc6145.png)

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
