### ISSUE TITLE
[Star Thief Quest] Trunan Not Accepting Star

### ISSUE THREAD

**Issue by CookedPelvis** [Wynncraft/Issues#2807]
Me and my cousin were doing the quest "Star Thief" in the Gavel Province, and we both got the Star of Transcendence and were about to give it to Trunan, but he didn't accept it.

When I right click on him (even with the star in my hand) his dialogue is what you would expect to see if you returned to him without the star.

He says: "I SAID GET THE STAR BACK!!" as if I don't have the star. 
Please fix this, I would really like to finish this quest.
![2015-12-21_18 04 30](https://cloud.githubusercontent.com/assets/11055356/11946667/dba50484-a811-11e5-9dd2-e004eded9967.png)

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
