### ISSUE TITLE
Can't leave guild

### ISSUE THREAD

**Issue by C-O-O-K-I-E** [Wynncraft/Issues#2812]
When i try to leave my guild it doesn't allow me. I type /guild leave and the message comes up:

"WARNING you will lose 3 soul points for leaving the guild. You will need to be re-invited to rejoin the guild. Are you sure you want to leave?"

and the sign where you type 'yes' also appears however, the soul points are not taken and i do not leave the guild. 

IGN: C_O_O_K_I_E

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
