### ISSUE TITLE
Witherhead broken in Skeleton Dungeon

### ISSUE THREAD

**Issue by TheGamingReaver** [Wynncraft/Issues#2817]
I went and did the skeleton dungeon on my new character for Gavel and when I got to the end Witherhead didn't have a wither skull on plus he never shot at me. He would try to use his skill and it would make the sound of shooting arrows but there weren't any. The only damage I took in that fight was from the rats. I would have tried it a second time just to make sure but I don't have enough money at the moment to buy a key. If I do get the money and try it I will put my results here. I would have put a picture but I pressed the wrong key to take a screenshot...

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
