### ISSUE TITLE
ALL MY PRE-GAVEL ENDGAME IS GONE

### ISSUE THREAD

**Issue by mcbobby123** [Wynncraft/Issues#2826]
The title says it all. i am stuck in gavel like this.
http://prntscr.com/9h39bd
someone plas halp

**Comment by Trixter313** [comment]
It appears you died with less that 3 soul points at some point. Nothing much can be done about this.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
