### ISSUE TITLE
Problems/Glitches with /class

### ISSUE THREAD

**Issue by GlacierExplorer** [Wynncraft/Issues#2830]
After I turned off the auto-join feature, I found that everytime i logged into the WC servers, I can only see a Key Collector in a floating stone house, then I'm falling into void. I can't use any commands except /hub which teleport me back to the main lobby.
Before this, if I try to use /class after a normal log-in, all my weapons and armours turned into a useless item which has very long, purple words in its lore, also, I can't interact anyting in the world since then. But after a relog, everything went back to normal and i'm able to use spells again.
Cant you help me to fix this?

P.S.: I'm wondering that was it only me who has this problem/glitch?

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out. So you can't use /kill?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by GlacierExplorer** [comment]
I‘m afraid still not solved ._.
Today I tried again, still no commands are allowed to be used except /hub. :(

Thanks for your reply :D

**Comment by Trixter313** [comment]
Hmm, odd indeed. An admin should see this soon and hopefully will be able to help.
