### ISSUE TITLE
Can't Use Arrow Storm w/ Bob's Mythic Bow

### ISSUE THREAD

**Issue by FectyFTW** [Wynncraft/Issues#2831]
I try to use Left-Right-Left (arrow storm) with my bob's mythic bow, but all it does is use up mana (no arrows). Is this a bug?

**Comment by Supercrafter55** [comment]
Yea I'm having the same issue

**Comment by ResistanceGaming** [comment]
Same here...

**Comment by mirajhall** [comment]
I've heard that arrow storm breaks if you drop your bow.

**Comment by FectyFTW** [comment]
Yeah, I did drop my bow, but have you heard of a way to fix this?

**Comment by mirajhall** [comment]
I have not, sorry.

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
