### ISSUE TITLE
Didn't recieve Xp from Zombie Dungeon

### ISSUE THREAD

**Issue by Chri630** [Wynncraft/Issues#2833]
So I saw that there was a new update on wynncraft so I decided to go on and check it out. It had been a long time since I played and I noticed that there was some dungeon keys in my INV so I decided to go do the dungeon. But unfortunatley when I finished I had realized the game had not given me my rewards after I finished it. I didn't recieve any xp and I didn't recieve my silverfish key in my INV. 

![2015-12-22_01 14 41](https://cloud.githubusercontent.com/assets/16396890/11949160/3659e92a-a84a-11e5-90d0-7541b79431c2.png)
![2015-12-22_01 14 53](https://cloud.githubusercontent.com/assets/16396890/11949159/36581c44-a84a-11e5-9f4f-bf23945d312e.png)
![2015-12-22_01 14 57](https://cloud.githubusercontent.com/assets/16396890/11949161/3659fd2a-a84a-11e5-8208-4e5a3abe7f70.png)

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
