### ISSUE TITLE
Bow bugs

### ISSUE THREAD

**Issue by PikachuPals** [Wynncraft/Issues#2838]
1. Don't drop your bow. 

 Upon dropping and repicking up my infinity, arrow storm on that bow has broke. 

 2. Don't open any chests with the broken bow. 

 You'll find that the loot chests you open whilst holding the bow will be empty!

**Comment by ResistanceGaming** [comment]
I accidentally dropped my Mythic and my Maelstrom... ;-;

**Comment by Alayathekid** [comment]
yeah can the developers fix this bug and like fix our bows. I really don't like this :+1:

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
