### ISSUE TITLE
Can't play

### ISSUE THREAD

**Issue by Dragons21** [Wynncraft/Issues#2847]
If i try to join a server i can play like 10sec on the server and then i get kicked with the message 
''There has been an error. Please log back in! Already connecting to this server!

i tried everything ! IGN: Dragons_21 | pls Help!

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
