### ISSUE TITLE
Mobs/NPC lagging

### ISSUE THREAD

**Issue by ProloProlo** [Wynncraft/Issues#2849]
Mobs lagging so much i cant even hit them but they always hitting me! I don't have lags i have 200+ fps and is not sense to exp anymore beacuse i can't hit them (I can but sometimes, also they always hitting me) Can you do something with these mobs? Also horse lagging so much i cant travelling on it. Please fix it.

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
