### ISSUE TITLE
Quest Flight in Distress crash

### ISSUE THREAD

**Issue by darklord646** [Wynncraft/Issues#2850]
I need to enter a code by pressing buttons on colors and listen how many times it says it but every time when i try to press a color my game freezes and i can't do anything anymore

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
