### ISSUE TITLE
Missing Chunk #Gavel Update

### ISSUE THREAD

**Issue by Bercike10** [Wynncraft/Issues#2851]
There's a missing chunk near the new gavel province
![2015-12-23_13 07 03](https://cloud.githubusercontent.com/assets/16400844/11954956/640bc2c2-a8ad-11e5-83b4-9c0ef063724f.png)

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
