### ISSUE TITLE
Spawning on a super flat world

### ISSUE THREAD

**Issue by TheMGRF** [Wynncraft/Issues#2853]
So, I connected to Wynncraft as usual and I have already explored some of Gavel, but when spawning I was greeted with a super flat world containing the NPC's. No idea what happened! xD

![gavel glitch](https://cloud.githubusercontent.com/assets/16401884/11956526/cd20412a-a8b2-11e5-84f4-3206a3a649f3.png)

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
