### ISSUE TITLE
stuck in a superflat world

### ISSUE THREAD

**Issue by KiriKorn** [Wynncraft/Issues#2858]
Apparently wynncraft decided to glitch out and now I'm stuck here, in a superflat world, where emeralds and lizard scales pop out of the ground, and I don't even have a way to die.
![2015-12-22 22 39 44](https://cloud.githubusercontent.com/assets/14042617/11957435/018ea2a6-a8ec-11e5-8512-295fac421ba8.png)

**Comment by Zaper8** [comment]
You can do /kill to kill your player. This will remove 2 soul points and hopefully teleport you to the nearest city.

**Comment by KiriKorn** [comment]
Yes, I did that, however, I am now stuck in ragni, this means that ragni is separated from the province. Now me and these other guys can't get out of ragni. Great update guys. 
![2015-12-23 00 11 35](https://cloud.githubusercontent.com/assets/14042617/11959632/9dd89624-a8f8-11e5-8311-7c6e0e78e79a.png)

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
