### ISSUE TITLE
Villager Interacting Glitched.

### ISSUE THREAD

**Issue by Lukiwoki** [Wynncraft/Issues#2859]
If you stand close to a villager and use an item, with use I mean click with an item or step on a pressure plate or so, if you do this close to the villager, then it will be registered as clicking the villager, so you sometimes might take a quest you didn't want to take, or see your char get spammed by NPCs talking to you. If you stand on a pressure plate close to a villager NPC, then your chat will get spammed a lot.

**Comment by brainscript** [comment]
This happens for all Mobs, also for horses. For example if you want to cast a arrow storm onto a "Llevigar Wild Horse", you will "interact" with it and turn into the other direction, because the event is cancelled.

I would use an `PlayerInteractEntityEvent` here and then get the entity using `e.getRightClicked()`. I don't know why they changed this, before the Gavel Update it worked perfectly.

**Comment by Lukiwoki** [comment]
I think one of the reasons they changed it was to avoid it being to hard to click baby villagers.

**Comment by brainscript** [comment]
@Lukiwoki Yes, but they could check **IF** there is a baby villager beneath to the player ...
