### ISSUE TITLE
Can't equip any new armor

### ISSUE THREAD

**Issue by WeaponsMaster309** [Wynncraft/Issues#2863]
While in Almuj I needed some new armor and i tried to buy some the buying process went through well but when I tried to equip the armor it would be on for a couple seconds then it would pop off.

**Comment by Trixter313** [comment]
Is there any message in chat when it pops off? Make sure you meet all of the requirements to wear the armor.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by WeaponsMaster309** [comment]
There were no messages but after logging out and re-logging I was able to
equip it.

**Comment by Trixter313** [comment]
Great to hear! Have a wonderful day =)
