### ISSUE TITLE
Archer class spell not working

### ISSUE THREAD

**Issue by baileyboy125** [Wynncraft/Issues#2867]
When I LEFT-RIGHT-LEFT it says I cast the Arrow Storm Spell but nothing happens?! It even uses up my mana too

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by baileyboy125** [comment]
Here are some screenshots:
https://gyazo.com/ddbd0856def1d0dca516a483d08db9db
https://gyazo.com/03858bfe87bd15e8bfae8bfadb6aa53e

**Comment by baileyboy125** [comment]
Ahh It seems to work now, thanks for the assistance.
