### ISSUE TITLE
I can't complete the quest "Heart of Llevigar"

### ISSUE THREAD

**Issue by RedMorcus** [Wynncraft/Issues#2874]
During the stage of he quest in which one has to go push the reset button, the server I was on restarted. When I logged back in on another server, I spawned outside the map, so I did /kill to teleport back to Llevigar. Now whenever I go back to the sewer and enter the hole at the top of the stairs leading to the reset button, I get teleported out of the map and have to /kill again, so the quest cannot be completed.

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
