### ISSUE TITLE
Flat World

### ISSUE THREAD

**Issue by Spiker988** [Wynncraft/Issues#2877]
I logged onto Wynncraft and hopped into a server only to find out that the entire world is flat, most of the npcs are bouncing up and down, and I can't do much of anything. Here is some of what I am seeing. If this could be looked into then please do. Thank you very much, Spiker988.
![2015-12-22_12 13 03](https://cloud.githubusercontent.com/assets/16404113/11961264/767b8e54-a8a5-11e5-9021-a6215dcd9338.png)
![2015-12-22_12 13 06](https://cloud.githubusercontent.com/assets/16404113/11961265/77c0ff1a-a8a5-11e5-8854-491a67c92e48.png)

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
