### ISSUE TITLE
All Players Spawn In A Flat World

### ISSUE THREAD

**Issue by DevilZen** [Wynncraft/Issues#2881]
All Players or Some Spawns in flatworld why its happening to us

**Comment by Pigwidgeon33** [comment]
It happened to me I spawned on a flat land that should have ben nemract. Now I'm stuck in the ground at nemract on my only leveled character, a level 25 mage

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by Pigwidgeon33** [comment]
Thank you for responding. I don't normally check my email so I didn't see
your response. I did do /help eventually to figure out there was a /kill.
Thank you for running Wynncraft and responding to people's problems.
