### ISSUE TITLE
Flat World

### ISSUE THREAD

**Issue by BenjaminPlayz** [Wynncraft/Issues#2884]
I went into a server and it spawned me in a flat world 
![2015-12-22_13 11 48](https://cloud.githubusercontent.com/assets/10838491/11962481/1cbe71fc-a8ae-11e5-8fd2-cfc1bb826c3f.png)

**Comment by BenjaminPlayz** [comment]
It spawned me at like Y 100 also

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
