### ISSUE TITLE
Got to rymek then got kicked

### ISSUE THREAD

**Issue by Chri630** [Wynncraft/Issues#2886]
Was going to rymek to purchase some pink wool but when I was about to enter it stopped me, saying it was downloading terrain then kicked me from the server, now I cant join back and it's repeatedly saying "Disconnected."

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
