### ISSUE TITLE
Uncharged chunk

### ISSUE THREAD

**Issue by MarioMine** [Wynncraft/Issues#2892]
Well, I was trying to do a quest, and then, I find this:
![2015-12-22_13 33 56](https://cloud.githubusercontent.com/assets/16405534/11964362/be92e13a-a8b2-11e5-9613-236daa100fd7.png)
![2015-12-22_13 34 03](https://cloud.githubusercontent.com/assets/16405534/11964361/be925fd0-a8b2-11e5-899c-72e1fc7307b5.png)

I hope this could help :)

**Comment by mirajhall** [comment]
I had a couple chunk errors also.

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
