### ISSUE TITLE
Archer Arrow Storm Doesn't Work with Fast Attack Speed

### ISSUE THREAD

**Issue by Icedmanta** [Wynncraft/Issues#2899]
It's exactly as the title says. When I use the Arrow storm ability with a fast attack speed bow, the spell does not work.

**Comment by ResistanceGaming** [comment]
The reason arrow storm wont work is because you have dropped your bow.

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
