### ISSUE TITLE
Server 21 map broken

### ISSUE THREAD

**Issue by grecolons** [Wynncraft/Issues#2900]
![2015-12-22_20 20 13](https://cloud.githubusercontent.com/assets/16406272/11965960/bde12c74-a8f8-11e5-9118-afda441d9a07.png)
![2015-12-22_20 20 27](https://cloud.githubusercontent.com/assets/16406272/11965961/bde55a24-a8f8-11e5-983d-fab92d1830e1.png)
![2015-12-22_20 20 31](https://cloud.githubusercontent.com/assets/16406272/11965962/bde9e56c-a8f8-11e5-985b-b6e24e738218.png)
As you can see in the image, in server 21, there's a map (coords in image) which has felt.

**Comment by grecolons** [comment]
Coords -2040 -5010 (Thought I've putted f3 screen)

**Comment by Trixter313** [comment]
Is it still broken even after the server restarts? If not, it might just be a one time issue.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by grecolons** [comment]
I think that happens in all servers, today I passed by there and there was a piece of map missing.
