### ISSUE TITLE
Guild Bugs

### ISSUE THREAD

**Issue by bnwilliams** [Wynncraft/Issues#2902]
This is about the guild leader of the guild I'm in, he doesn't have an account for GitHub.
The guild is very very old, I have no clue if that's part of it, but the guild master, eman2000, recently changed his name to Eman2000. He now has no control over the guild and the guild basically has no owner now. We tried everything we can except making a new guild.

This is also about one of my friends since he doesn't have a GitHub account too :P 
He wanted to leave his present guild but when the sign comes up for you to type "yes", it won't let him leave. Please help, and thank you. :)

**Comment by Trixter313** [comment]
Name changing is known to cause some issues with Wynn because they haven't fully updated to use player UUIDs instead. The only thing I can suggest for now is for the owner to try to change their name back once they can and hope they have control again. Anything else will require an admin's assistance.

As for the player who can't leave, that's odd indeed. Have they changed their username at all also? That might cause it to not work. As for that, all I can suggest is once someone gets control of the guild, having them kick the player.

I hope your issues get resolved soon!

**Comment by bnwilliams** [comment]
Thanks, but the problem to that is the whole guild doesn't come on anymore so there isn't anyone to kick him. ._.
