### ISSUE TITLE
Unidentifiable, strangely named armor piece

### ISSUE THREAD

**Issue by Hasteful** [Wynncraft/Issues#2905]
I had a nice upgrade in my bank, just waiting until I was able to get to the proper level and use said upgrade. I am unable to view the name, as depicted in the attached image.  I am unsure of what exact piece of armor it was, all I know is that it was a rare chest plate with a level minimum in the low 60's.  Glancing through the item list for rare chest plates, I believe that it was "Montéfioré", but I am not entirely certain.  It would make sense if it were due to the unique characters in the name, as they were causing issues beforehand for other items of mine.  IGN is Hasteful.  Any assistance would be greatly appreciated.  Thanks!

![glitched item](https://cloud.githubusercontent.com/assets/16406717/11967333/eb3d3394-a8cf-11e5-8552-d5e9c3c21b64.png)

**Comment by DarkDemonDragon** [comment]
That's a bug... definitely a bug O_O Also all special character items still have the old can't be IDed bug as my Relic Dagger Montéfioré and a spear (I think Fierte but I have to check) have the old format and still can't ID so that shouldn't be Montéfioré unless they just tried to fix the bug and this happen. Have you tried equiping this? Take off the rest of your armor and check what stats the chestplate gives if possible.

**Comment by Hasteful** [comment]
As per requested, I went ahead and unequipped my chestplate, replacing it with the bugged item.  With a side by side comparison of the defensive and ID stats in my character info, I was able to determine that there is literally not a single benefit to wearing the bugged armor.  It did not change a single stat compared to not wearing a chest plate.

**Comment by DarkDemonDragon** [comment]
Strange. I'm guessing that the actual stats of the armor became the name for some reason. You can see a few ID stats like Mana steal and Health regen, so clearly you IDed it, but something went horribly wrong. I suggest holding onto it since it offers no benefits making it an extremely rare collectible item that shouldn't be illegal to trade. Since Montéfioré is a Lv 64 item, the armor seems to have become Vanilla with stats, but it's naming doesn't make it a Vanilla item. If the staff here can't fix your issue make a post about it on the forums and start the bidding at 1 Stack of LE :smiley:

**Comment by Trixter313** [comment]
I believe this is related to #2679

**Comment by DarkDemonDragon** [comment]
@Trixter313 this is actually a remnant of the bug of #1312 . Should I refer duplicates to #2679 or #1312 ?

**Comment by Trixter313** [comment]
I'm not really sure. The new one feels more right to me because it has changed a little bit. Maybe it's time to let the old one rest in peace?

**Comment by DarkDemonDragon** [comment]
The problem is that this is a direct result the first one. It's literally the same issue just carried over to gavel.
1312: All items with special characters and Relic Dagger can't be IDed
2679: All items with special characters and Relic Daggers can't be IDed

Either the GM/Devs messed up trying to fix the issue, or they forgot about fixing it and this is just the same exact problem that is just getting worse because something that wasn't even compatible with Pre-Gavel is now being used in Gavel where it didn't have a chance of being able to work.
