### ISSUE TITLE
Wynnexcavation Site B Bugged

### ISSUE THREAD

**Issue by Pegasusmeteo** [Wynncraft/Issues#2910]
During the quest you go to the Purple crystal room and at that room there is a Wormhole/portal to get you somewhere but its not working as of right now. Could this be fixed?

**Comment by Trixter313** [comment]
Have you tried switching to a different server? Something like this usually solves itself with a little time. Is it still happening?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by Pegasusmeteo** [comment]
I tried switching servers several times and nothing happend.

**Comment by Trixter313** [comment]
Thanks for the bug report! An admin should see this soon and hopefully will be able to help.
