### ISSUE TITLE
auto kick bug.

### ISSUE THREAD

**Issue by thecoolkogut4** [Wynncraft/Issues#2919]
so i join the server it says loading pack, thank you for using the  texture pack, there has been an error please log back in. about every server i try to join this happens. i join get kicked then join get kicked etc. its a pretty annoying bug.

if i type it says you cant  use commands right now. (im not in the hub when i typed it)

im pretty sure it has something to do with the texturepack but im not sure. and yes im using the pack.

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by thecoolkogut4** [comment]
every so often it happens. i goes on for an hour, then stops, hour, stops etc

**Comment by Trixter313** [comment]
Hmm, odd indeed! Hopefully an admin will see this soon and help!

**Comment by thecoolkogut4** [comment]
fixed in .3 update

**Comment by Trixter313** [comment]
Great to hear!
