### ISSUE TITLE
Green Gloop

### ISSUE THREAD

**Issue by PinkWool** [Wynncraft/Issues#2929]
You can no longer obtain glass bottles from water bottles etc. therefore i cannot complete the Green Gloop quest.

**Comment by MegaSlowbro** [comment]
Zombies by ragni sometimes drop empty glass bottles

**Comment by Trixter313** [comment]
Are you sure you can't get them from water bottles? I just tested it and drank a water bottle and got an empty bottle. The instant drink doesn't apply to water bottles. You also have to get the water bottles from a merchant in Ragni now.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by PinkWool** [comment]
the bottles convert back to water bottle in a few seconds or when you move them in your inventory. ill try ragni though. thanks.

**Comment by Trixter313** [comment]
Ah, I didn't notice that it changed back to a water bottle after a few seconds. I guess it really is an overlooked bug then. Hopefully an admin sees this soon and fixes it.

**Comment by Trixter313** [comment]
@MegaSlowbro seems to have it correct.

You get empty bottles as drops from some mobs now. I know for sure the zombies near the identifier on the emerald trail drop them, I've gotten a few from them.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
