### ISSUE TITLE
Wynncraft excavation site C is glitched

### ISSUE THREAD

**Issue by dogelord117** [Wynncraft/Issues#2932]
After you finish the quest and report back to receive the rewards, Excavator Placardus asks for 2 purple shards from excavation site B again, instead of finishing up the quest. Note, I already started and finished the quest.

**Comment by Trixter313** [comment]
Are you sure you don't have any purple shards in your bank or any other classes? If not, maybe try typing /fixquests and see if it gives you some to finish the quest.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by dogelord117** [comment]
I've watched a video tutorial, and when the person returned, he was able to finish the quest. When I returned, it kept asking for the purple shard to begin the quest, which I already finished. I've gone to the bank, used /fixquests, and nothing worked.
