### ISSUE TITLE
Can't see Name Tags (NPC's) , XP, or HP Bars

### ISSUE THREAD

**Issue by TheWiseDisorder** [Wynncraft/Issues#2962]
Title pretty much explains it. xD please help

**Comment by Trixter313** [comment]
If you can't see name tags, please update your Minecraft to the latest version. Thanks!

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
