### ISSUE TITLE
Glass Bottle

### ISSUE THREAD

**Issue by mvcuijk** [Wynncraft/Issues#2965]
So for the Quest Green Gloop u need 5 glass bottles but i can't find them i have water bottles but i cant drink them i  hope someone can help me.

**Comment by robinkip4** [comment]
i got the same problem

**Comment by TheWiseDisorder** [comment]
u could just farm lvl 3 zombies? or buy potions and drink 'em :3

**Comment by mvcuijk** [comment]
if i drink pots i dont get the bottles they disapear

**Comment by Trixter313** [comment]
You get empty bottles as drops from some mobs now. I know for sure the zombies near the identifier on the emerald trail drop them, I've gotten a few from them.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
