### ISSUE TITLE
Hole in the ground

### ISSUE THREAD

**Issue by zenandreas** [Wynncraft/Issues#2975]
So here i am walking around in Levigar :)
![2015-12-23_17 28 25](https://cloud.githubusercontent.com/assets/16415899/11979323/1bcec8c6-a99b-11e5-9165-f35a2920d3a1.png)

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out and a world restart almost always fixes chunk errors.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by skillerfox3** [comment]
This is just a chunk loading issue. Pressing _F3 + A_ will fix this. If not relog.

__This issue can be closed!__
