### ISSUE TITLE
Skill points bug

### ISSUE THREAD

**Issue by FuriousSniper** [Wynncraft/Issues#2978]
When I entered the game, I had to consume my skill points. I've done it, but I lost a few points per every skill. To 'activate' adding points to my skill, firstly, I had to use 5 points, not 1. After doing this, I had 3, not 5 points. Is there any way to reset my skill points and fix this bug? Without it I can't play on my main classes.

MC nick: PulZerStoker

**Comment by TheDerpyMan** [comment]
You'll have to use 1 LE for a Reset Scroll (Check Tower Of Amnesia on Wynncraft's Wiki) Maybe you lost Skill points because some items affect your stats.

**Comment by Trixter313** [comment]
Like TheDerpyMan said, check all your armor to make sure it isn't affecting your skill points. Also at the bottom of the skill point text it should say if armor is affecting it.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by FuriousSniper** [comment]
I hope this will help. Thanks for both :)
