### ISSUE TITLE
Skill points glitched!!

### ISSUE THREAD

**Issue by fandrus** [Wynncraft/Issues#2999]
So I haven't played Wynncraft in awhile, but when I decided to play I was introduced to the new update. I saw that I had a bunch of skill points to use, but I couldn't use them on the agility (so I gave 20+ points to everything else) When I took my armor off to identify it again, my strength points turned into 7 and My agility points turned into 10! since my strength points are 7, I am unable to wear ANY of my armor!! I ran out of skill points too and I REALLY want to play again! Is there a way to get skill points without leveling up?

**Comment by fandrus** [comment]
Oh, and I am a level 45 Archer

**Comment by Trixter313** [comment]
Check the armor to see if it affected your skill points. Some armors will add or subtract skill points and because the armor was on it might have done that. Taking it off reset the skills to the appropriate amount and then the game realized you actually don't have enough skill points to wear it.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by fandrus** [comment]
the whole thing is confusing, so I really don't know... Is there a way to reset all of my skill points and get them back?

**Comment by Trixter313** [comment]
Yes, there is. You must do the quest "Tower of Amnesia" and once that is done, there is a merchant on the top of that tower who will trade you a skill reset scroll for 1 LE.

**Comment by fandrus** [comment]
Oh yea! thanks ^^
