### ISSUE TITLE
Lost my armor

### ISSUE THREAD

**Issue by Forcellrus** [Wynncraft/Issues#3002]
I had only one slot empty in my inventory and I was wearing full unidentified armor which I equipped before update. Now I unequipped my chestplate and it automatically uneqipped other parts of armor which means I lost helmet, shoes and leggings because there was no space in inventory. I want them back!

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a very strict no refund policy so not much can be done about this. We'd appreciate it if you closed this issue. Thanks!

**Comment by Forcellrus** [comment]
This is just rude, at least you could put some kind of warning to be careful about these kind of stuff... Shame.

**Comment by Forcellrus** [comment]
If you would appreciate me to close this issue, I would also appreciate to get back my hard earned armor. Is this how you solve issues? Telling people to close issues. It is your job to help people, not telling them to ignore this issue posting thing, that's why it exists.

**Comment by Trixter313** [comment]
This actually doesn't happen to be my job at all. Also, there was a warning titled, "Pre-gavel Warnings [please Read]" located here: https://forums.wynncraft.com/threads/pre-gavel-warnings-please-read.97667/

I'm not asking people to ignore the bug tracker at all, it's a wonderful tool! This just isn't the place to ask for your items back and re-report an already reported issue. No matter what the case, no ingame items are ever refunded. All I can do is suggest asking players nearby if you can buy some armor off of them.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by Forcellrus** [comment]
Those warnings need to be made so everyone can see them on server. Not everyone goes to forum first before joining a server, as I did and I'm sure that I'm not the only one.

**Comment by Forcellrus** [comment]
Update is great, but problem prevention and warning distrubution is horrible.

**Comment by Trixter313** [comment]
You can post suggestions here: https://forums.wynncraft.com/forums/general-suggestions.69/ =)
