### ISSUE TITLE
Error Login

### ISSUE THREAD

**Issue by FredoXXX** [Wynncraft/Issues#3003]
http://imgur.com/74aYSRl

Can not connect.

**Comment by Trixter313** [comment]
I'm getting the same error message.

**Comment by TheDerpyMan** [comment]
I tried changing Server's Adress from play.wynncraft.net to .com ... Sometimes It works, but you'll have or to restart the minecraft client, or to wait, because I saw that this happens just sometimes and gets fixed over time.

The thingy about changing adresses works most of the time.

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
