### ISSUE TITLE
Connection lost

### ISSUE THREAD

**Issue by Zap1337** [Wynncraft/Issues#3021]
I get this error when ever I try joining Wynncraft. 
Exception Connecting:RuntimeException : Server is online mode! @ net.md_5.bungee.ServerConnecter:261
Help anyone?

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
