### ISSUE TITLE
Unable to get Quest specific bottles 

### ISSUE THREAD

**Issue by immattfoss** [Wynncraft/Issues#3026]
As we all know, glass bottles are needed for the goo quest and also as we all know the only way to get normal bottles WERE from the potion bottles but since the update there is no way to get empty bottles making this quest unfinishable. please help thank you :)

**Comment by TrashcanMan** [comment]
There's a Water Bottle merchant somewhere in Ragni, I think that's where you're supposed to get bottles from now.

**Comment by Trixter313** [comment]
Actually the water bottles turn back to water bottles a few seconds after drinking them. You now get plain empty bottles as mob drops. A location i've had them drop some is near the identifier on the emerald trail.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
