### ISSUE TITLE
Gert Helmet In The Hunger of Gerts Quest Chain

### ISSUE THREAD

**Issue by ltvuong** [Wynncraft/Issues#3103]
So after I did the Hunger of Gerts Part 1, I decided to throw away my Gert helmet because I thought that I was not needed anymore. Now In the Hunger of Gerts Part 2 I learn that I DO need it, but now I don't have it anymore. The helmet was an untradable item, not quest item, so /fixquests does not work. Please help me.

**Comment by Monkeysz** [comment]
Do you mean the Gert Mask because this item is actually a quest item and not an untradable one. I have no idea how you might have thrown it away. The quests connect with each other and give you reward items or items you need in future quests. Such as the Mummies Rags. Sorry I couldn't help, but here's an explanation of quest items. Good luck.

**Comment by ltvuong** [comment]
Problem has been solved
