### ISSUE TITLE
Hunger of the Gert part 2 Big Butch bug.

### ISSUE THREAD

**Issue by littlelawyer** [Wynncraft/Issues#3141]
![2015-12-24_22 32 26](https://cloud.githubusercontent.com/assets/13516516/12004422/0c3229da-ab0d-11e5-94dd-7341bfcdfb51.png)
![2015-12-24_22 32 37](https://cloud.githubusercontent.com/assets/13516516/12004423/100471bc-ab0d-11e5-8b2e-30e406348666.png)
![2015-12-24_22 38 21](https://cloud.githubusercontent.com/assets/13516516/12004425/12b69336-ab0d-11e5-8d09-0e316230cf6d.png)
![2015-12-24_22 40 20](https://cloud.githubusercontent.com/assets/13516516/12004426/151dc4d2-ab0d-11e5-8a4e-0a1ff8bcde63.png)

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
