### ISSUE TITLE
Memory Paranoia quest glitching

### ISSUE THREAD

**Issue by TRTX** [Wynncraft/Issues#3167]
The level 67 quest Memory Paranoia will not let me use the rift to exit after defeating Mr Caritat's ghost. It teleports me to a black box with nothing inside and no dialogue appears. It had done this before so I went back to try again and it happened again.

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by shacharss** [comment]
it happens to me right now too, i cant get out!
