### ISSUE TITLE
Hive is broken

### ISSUE THREAD

**Issue by ohyeah1357** [Wynncraft/Issues#3169]
I beat Mistress Qira, but talking to Yansur won't trigger any dialogue.

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by Trixter313** [comment]
I'm assuming the issues is now resolved because there hasn't been a response for 14 days and closing the issue. If it's still occuring simply comment that it isn't and I'll reopen the issue. Thanks!
