### ISSUE TITLE
[Broken Quest] Lost in the jungle.

### ISSUE THREAD

**Issue by W-Schnee** [Wynncraft/Issues#3172]
I was doing the quest 'Lost in the jungle'. I had to make sure Aryn is all right before leaving. He was in middle of his dialogue when server closed.
![untitled](https://cloud.githubusercontent.com/assets/16443012/12005824/974d5e18-abc1-11e5-8588-da5f3d4384e1.jpg) 
Now every time I talk to him again he just asks who am I. I can't progress the quest because quest book still says I have to make sure he is all right and I can't leave the room because of the same reason. 
![untitled1](https://cloud.githubusercontent.com/assets/16443012/12005841/97e0e6aa-abc2-11e5-840b-2aa2b44efcf6.jpg)
![untitled2](https://cloud.githubusercontent.com/assets/16443012/12005843/a62ac2e4-abc2-11e5-91ba-f1e97eea2185.jpg)

**Comment by Trixter313** [comment]
Have you tried using the command /fixquests ?

It may or may not work but it's always a good place to start with quest issues. Hope this helps!

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by W-Schnee** [comment]
I tried to use /fixquests when it happened. But as expected it didn't work because my issue is not related to missing items. 
I recently had idea to go and talk to Gracen even if my quest book doesn't say so. I doubt it will work but I will report back as soon as possible.
