### ISSUE TITLE
[Quest] Hunger of gerts Part 2. Portal Not teleporting

### ISSUE THREAD

**Issue by Golpaus** [Wynncraft/Issues#3174]
Jitaks basement portal wont teleport players to the area needed 
at -177 23 -5467.

**Comment by Verret001** [comment]
:+1: Upvote

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
