### ISSUE TITLE
Bugs are unkillable

### ISSUE THREAD

**Issue by JavaBots** [Wynncraft/Issues#3178]
When doing the quest when you have to go down to the Power room in levighar you may encounter bugs that do a large amount of damage. the thing is that they are unkillable with all classes.

**Comment by Verret001** [comment]
What quest is this?

**Comment by Trixter313** [comment]
I believe this is the, "Heart of Llevigar" quest. I didn't have any issues with the bugs though. Is your issue still occurring?

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by DarkDemonDragon** [comment]
I've checked the bugs and they're killable.
