### ISSUE TITLE
Resource Pack failing to download

### ISSUE THREAD

**Issue by xXYogishPlayzXx** [Wynncraft/Issues#3183]
So i joined a world and it says downloading resource pack 100% then it says error to download it and how to fix it.
I enabled server resource pack i restarted my minecraft client i deleted the texture pack on my .minecraft folder and still nothing works this is because of the new patch because it only happened when the patch was released

**Comment by SpriteDew** [comment]
Same thing that happened to me too! It seems so weird to see a person hold slabs

**Comment by Suegerman** [comment]
SAME THING! It just wont work i dont really play wynncraft anymore because of it

**Comment by Dorpius** [comment]
I tried so hard for fixing... but it didn't work.
Is it me or is it a resource/server bug?

**Comment by Trixter313** [comment]
What version of Minecraft are you guys running? I suggest being on the latest version, 1.8.9. Hope this helps!

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by Trixter313** [comment]
I'm guessing your issue is now resolved due to no response. Have a great day!
