### ISSUE TITLE
Can't open the silverfish stage 1 door

### ISSUE THREAD

**Issue by vboyswag** [Wynncraft/Issues#3208]

**Comment by vboyswag** [comment]
Sorry about no description

This is the description

We were opening the door. We weighed down all the plates and now the door is still closed

**Comment by vboyswag** [comment]
Please help! Jackiplier and I are stuck in here!

**Comment by meatloaf4311** [comment]
If you really want to get out you can /kill if you have more than 3 soul points with out losing any thing

**Comment by vboyswag** [comment]
... ok

**Comment by 0Patrick0** [comment]
Silverfish dungeon has many different bugs/glitches. Most of the time it works though.

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out or the server was just lagging.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by DarkDemonDragon** [comment]
Please check that you truly placed items on all plates. The right side has 2 steps, not one. Just feeding the snake will NOT open the door. There is something to do RIGHT after that.
