### ISSUE TITLE
Craftmas Chaos

### ISSUE THREAD

**Issue by Skwiesel** [Wynncraft/Issues#3231]
When I defeated the crystal in the crystal cave a man says that I may escape behind him, but when I go in there I keep falling until I hit the ground and die. I've tried it 2 times, but I died both times.

**Comment by SioN-wynncraft** [comment]
Şans here that needs to be fixed

**Comment by SioN-wynncraft** [comment]
*same

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by AmariahStendarr** [comment]
I am still having this same issue; I would like advice on fixing it?

**Comment by Skwiesel** [comment]
Problem solved
