### ISSUE TITLE
Can't play server ! Admin help please !

### ISSUE THREAD

**Issue by Gregoryus** [Wynncraft/Issues#3278]
So basically when I come to play Wynncraft, I connect to Wynncraft then to a server, and at the class chosing step, I click on archer and nothing happens, I just get a message telling to try again, but no matter how much I try it just doesn't work. So I tried to logout and login and to close and run the game again but this time I can't connect to Wynncraft at all, I get this message: "ExceptionConnecting:RuntimeException : Server is online mode! @net.md_5.bungee.ServerConnector:261".
I just don't know what's going on, I've never been able to play Wynncraft NOT ONCE,If it can help I changed my pseudo from Gregorius78 to Gregoryus.
Hope you will find something to help, Gregoryus

**Comment by Gregoryus** [comment]
Well the can't connect server problem seem to be fixed but I still can't choose my class and play Wynncraft.

**Comment by Verret001** [comment]
Mind if I add yours in here?
https://github.com/Wynncraft/Issues/issues/3250

**Comment by Moe-Ronickah** [comment]
This is a generic message, to everyone affected by these issues.
I've discussed this with the admins, and it turns out, after a lot of investigation, that the 
problem lies within the saved data file created by Minecraft.  The data is corrupted.  For some
of you, your character data files are so badly corrupted that you cannot login and play on any
classes.  For some of you, only one, or maybe two, of your classes, are corrupted.

Well, here is what we can do, and you need to think seriously about the options that I am going
to tell you about, and what they mean.  First, our only possible fix for this is to WIPE your
character.  That means that ALL of your classes will be gone, along with ALL of your information.
That means EVERYTHING will be gone.  Any pets that you purchased, any unused item bombs, any
unused XP bombs, and any GC that you may have left, will be gone.  There is NO way that we
can recover that information before the wipe, so once it happens, there is absolutely no way
to go back and get it, either.  It just cannot be done.  The data file is corrupt.  We can,
however, go back through the store and recover your rank, if you have purchased one.  Your
VIP/VIP+ rank can, and will, be recovered.

So, here is your decision to make.  If you want to keep waiting to see if Minecraft ever will
make a tool to recover lost character information, and they haven't yet made one to recover
lost or corrupted worlds, you can keep on waiting.  Seriously, it's not a problem for us, as
it requires that we simply do nothing to your game account.  For those of you who have lost one
or two classes, the decision to wipe EVERYTHING means that you have to accept the fact that
you will lose ALL of your classes, ALL of your pets, if you purchased any, any bombs that
you may have, and any GC that you may have.  None of this is recoverable if your account is
wiped, however, you will be able to start over on all of your classes.

For those of you who cannot play on any class, you have the same decision to make for yourself.
  You can wait to see if Minecraft will ever make a tool to recover lost character data, with
the same considerations as above.  Minecraft has never made one, and there is nothing that
we have heard of to say that they ever will.  Or, you can choose to have all of your character
data wiped, with the same losses as explained, above, and we can, and will, recover your VIP/VIP+
rank.

So, for each of you, individually, let me know what you want us to do, and I'll pass along your
decisions to the admin, at the end of this week (Friday or Saturday).

**Comment by Gregoryus** [comment]
Hi,
I'm sending you this email because I wanted to say to you that I accept to have my character being deleted.
My minecraft username is Gregoryus.

Le 26 sept. 2016 à 02:11, Nathan Stolov <notifications@github.com<mailto:notifications@github.com>> a écrit :


This is a generic message, to everyone affected by these issues.
I've discussed this with the admins, and it turns out, after a lot of investigation, that the
problem lies within the saved data file created by Minecraft. The data is corrupted. For some
of you, your character data files are so badly corrupted that you cannot login and play on any
classes. For some of you, only one, or maybe two, of your classes, are corrupted.

Well, here is what we can do, and you need to think seriously about the options that I am going
to tell you about, and what they mean. First, our only possible fix for this is to WIPE your
character. That means that ALL of your classes will be gone, along with ALL of your information.
That means EVERYTHING will be gone. Any pets that you purchased, any unused item bombs, any
unused XP bombs, and any GC that you may have left, will be gone. There is NO way that we
can recover that information before the wipe, so once it happens, there is absolutely no way
to go back and get it, either. It just cannot be done. The data file is corrupt. We can,
however, go back through the store and recover your rank, if you have purchased one. Your
VIP/VIP+ rank can, and will, be recovered.

So, here is your decision to make. If you want to keep waiting to see if Minecraft ever will
make a tool to recover lost character information, and they haven't yet made one to recover
lost or corrupted worlds, you can keep on waiting. Seriously, it's not a problem for us, as
it requires that we simply do nothing to your game account. For those of you who have lost one
or two classes, the decision to wipe EVERYTHING means that you have to accept the fact that
you will lose ALL of your classes, ALL of your pets, if you purchased any, any bombs that
you may have, and any GC that you may have. None of this is recoverable if your account is
wiped, however, you will be able to start over on all of your classes.

For those of you who cannot play on any class, you have the same decision to make for yourself.
You can wait to see if Minecraft will ever make a tool to recover lost character data, with
the same considerations as above. Minecraft has never made one, and there is nothing that
we have heard of to say that they ever will. Or, you can choose to have all of your character
data wiped, with the same losses as explained, above, and we can, and will, recover your VIP/VIP+
rank.

So, for each of you, individually, let me know what you want us to do, and I'll pass along your
decisions to the admin, at the end of this week (Friday or Saturday).

-

**Comment by Gregoryus** [comment]
Hi,
It's Gregoryus again,
Just wanted to say that my character data might be on my last username too which in that case is Gregorius78.
So check for both my username pls.

Envoyé de mon iPhone

Le 26 sept. 2016 à 02:11, Nathan Stolov <notifications@github.com<mailto:notifications@github.com>> a écrit :


This is a generic message, to everyone affected by these issues.
I've discussed this with the admins, and it turns out, after a lot of investigation, that the
problem lies within the saved data file created by Minecraft. The data is corrupted. For some
of you, your character data files are so badly corrupted that you cannot login and play on any
classes. For some of you, only one, or maybe two, of your classes, are corrupted.

Well, here is what we can do, and you need to think seriously about the options that I am going
to tell you about, and what they mean. First, our only possible fix for this is to WIPE your
character. That means that ALL of your classes will be gone, along with ALL of your information.
That means EVERYTHING will be gone. Any pets that you purchased, any unused item bombs, any
unused XP bombs, and any GC that you may have left, will be gone. There is NO way that we
can recover that information before the wipe, so once it happens, there is absolutely no way
to go back and get it, either. It just cannot be done. The data file is corrupt. We can,
however, go back through the store and recover your rank, if you have purchased one. Your
VIP/VIP+ rank can, and will, be recovered.

So, here is your decision to make. If you want to keep waiting to see if Minecraft ever will
make a tool to recover lost character information, and they haven't yet made one to recover
lost or corrupted worlds, you can keep on waiting. Seriously, it's not a problem for us, as
it requires that we simply do nothing to your game account. For those of you who have lost one
or two classes, the decision to wipe EVERYTHING means that you have to accept the fact that
you will lose ALL of your classes, ALL of your pets, if you purchased any, any bombs that
you may have, and any GC that you may have. None of this is recoverable if your account is
wiped, however, you will be able to start over on all of your classes.

For those of you who cannot play on any class, you have the same decision to make for yourself.
You can wait to see if Minecraft will ever make a tool to recover lost character data, with
the same considerations as above. Minecraft has never made one, and there is nothing that
we have heard of to say that they ever will. Or, you can choose to have all of your character
data wiped, with the same losses as explained, above, and we can, and will, recover your VIP/VIP+
rank.

So, for each of you, individually, let me know what you want us to do, and I'll pass along your
decisions to the admin, at the end of this week (Friday or Saturday).

-
