### ISSUE TITLE
Death Whistle Bug

### ISSUE THREAD

**Issue by ChiefInferno** [Wynncraft/Issues#3295]
when ever I'm on the top of the mountain and try to get tped to the cave it dosent tp and "/" keeps showing up in the chat

**Comment by Verret001** [comment]
Can we have screenshots or videos?
What mountain?

**Comment by Forcellrus** [comment]
Same thing happened to me, you probably teleported up and that is the way to get out, not in mountain, you must follow the path because that is the place you shall end up outside to pick up flower.

**Comment by Trixter313** [comment]
I believe Forcellrus is correct, you have to go through the black teleport part instead of getting to the top on your own.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by Trixter313** [comment]
I'm guessing your issue is now resolved due to no response. Have a great day!
