### ISSUE TITLE
Can't connect to any world ! "You are already logged in!"

### ISSUE THREAD

**Issue by ImSickPT** [Wynncraft/Issues#3302]
When I try to join any world at any time, this message appears in the chat followed by a ReadTimeoutException or a ConnectTimeoutException  : "You are already logged in! Try again in a few seconds.". 
![screenshot_1](https://cloud.githubusercontent.com/assets/13498603/12026920/2fdf897a-adb7-11e5-8132-667a21bd423e.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/13498603/12026921/2fe4bc7e-adb7-11e5-87f8-112f2ea5ec6a.png)
![screenshot_13](https://cloud.githubusercontent.com/assets/13498603/12026922/2fe7d5b2-adb7-11e5-86ba-ea1b9901c31c.png)

**Comment by trollunderbridg** [comment]
Hello, I believe that this is because world 13 is broken. Everybody that shouldn't be on, are always on world 13. It's like the graveyard world. World 13 seems to have been hella broken since the past couple of days. For example, my guildies and a friend were in a group on world 13, and I joined world 16, and I somehow joined world 13, and it seemed like I was on the same world as them. Another one is that my friend is supposed to be gone for vacation but he has been on world 13 for the last 2 days.

I think the world 13 has a relation to this as maybe wynncraft still views you as logged in because it thinks you are on world 13.

**Comment by slendersir739** [comment]
Server 13 is bugged, try a different one.

**Comment by ImSickPT** [comment]
@slendersir739 Can't you read the title. "any world".

**Comment by ImSickPT** [comment]
After one day, the promblem got fixed ! Thanks to every one who helped.

**Comment by ImSickPT** [comment]
The bug started happening again...

**Comment by ImSickPT** [comment]
I am getting tired ! -.-

**Comment by ImSickPT** [comment]
@Jumla @Verret001 Do you know what is causing this ?

**Comment by ImSickPT** [comment]
Even tho the problem is gone, there are lots of people with the same bug ! I am proposing a new solution to the problem: do (/server) multiple times(about 20 times) and then try to enter a world !

**Comment by ImSickPT** [comment]
The bug started happening again... @Jumla Since you are the lead developer, try to fix it !

**Comment by ImSickPT** [comment]
Actually, my solution works !

**Comment by Trixter313** [comment]
Great to hear! =)
