### ISSUE TITLE
I need to be reset... (Staff please)

### ISSUE THREAD

**Issue by SketchyKB** [Wynncraft/Issues#3307]
So here the problem.. My friend told me to put all my skill points into strength so I did then when I wnet to use my weapon I need  20 agility skill.. So I would like to know if you could reset my skill point and I did not know where to post this so sorry if it in the wrong place. Any help would be great thanks.

https://gyazo.com/4f74d7013de8f59dfe4c078268a03621

**Comment by Trixter313** [comment]
There is only one way to reset skill points that I know of. You have to do the quest, "Tower of Amnesia" and once that's done you can buy a skill points reset scroll from a merchant at the top of the tower for a LE.

Because that requires a decent amount of time and money to do, I'd just suggest using a different weapon temporarily that you can use until you have enough skill points. Also armor can add to certain skills so I'd be on the lookout for armor that does that to agility. After at most 10 levels, you'll have enough skill points to use the weapon. Although by then there will probably be a better weapon to use. Hope this helps!

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by SketchyKB** [comment]
I mean like is there a way for a wynncraft staff to give me the points back and reset all the skill points for me if so how would I get somebody to do that...

**Comment by slendersir739** [comment]
Sketchy, you might not want to buy the scroll yet, according to #3308, it is bugged.

**Comment by Trixter313** [comment]
I used a skill reset scroll recently, and it worked fine for me. That issues is most likely an isolated issue or the creator just misunderstanding something.

Because there is a way in-game it wouldn't really be fair to make you not have to do the quest and pay the LE but everyone else does. You see what I mean? Unfortunately either leveling and getting different weapons or doing that quest seem to be your only options.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by SketchyKB** [comment]
Alright was just seeing if I could get it reset back because at the start of gravel everyone had there skill points reset and giving back and I was clueless at the time did not know that I needed things for stuff so it is my fault for not reading up on it thank you tho..

**Comment by Trixter313** [comment]
I hope it doesn't turn out to be too much of an inconvenience. Good luck!
