### ISSUE TITLE
Cant log in to any of worlds, i can connect to lobby tho

### ISSUE THREAD

**Issue by xHuanPL** [Wynncraft/Issues#3310]
As in title, i cannot connect to any WC's, it says "You are already logged in, please try again in a few seconds". It happened yesterday but today it still says same thing.

**Comment by Trixter313** [comment]
Is the issue still occurring? Sometimes things like this just need a little time to sort themselves out.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by ImSickPT** [comment]
I already opened a bug report on this. The solution I created(and that should be used by mods, gms and by the owners of this repository) tells you to do /server until appears "You are already connected to this server." on the chat. Then you will be able to connect to any server. If I was helpful please close the bug report else tell me.
