### ISSUE TITLE
Disappearing Armour

### ISSUE THREAD

**Issue by MidgetPokemon** [Wynncraft/Issues#3320]
My armour disappeared I had a full inventory and wearing unidentified armour (I logged in for the first time since the update) I took one piece of the armour off and the entire set of endgame legendary armour disappeared

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/3153

Unfortunately Wynncraft has a very strict no refund policy so not much can be done about the already lost armor but we are working on fixing the fact that armor gets plain deleted instead of dropping on the ground like it's supposed to.

Please direct any further comments to the original thread. Thanks!
