### ISSUE TITLE
I found a way to log onto the Nether server

### ISSUE THREAD

**Issue by Sourpowerpete** [Wynncraft/Issues#3331]
If you hold a compass while circling the Nether signs, while holding the right mouse button down, eventually you will log onto the Nether (though nothing works there).

http://i.imgur.com/a4LwG2i.jpg

This isn't really a problem, since /hub seems to work, and you can obviously just disconnect, but I thought I would at least mention this.

**Comment by HeyloLP** [comment]
it's very interesting
and it's working

**Comment by Trixter313** [comment]
Hopefully the Nether will be back up for use soon and this won't be an issue anymore. Thanks for the bug report!

**Comment by Dar-krusos** [comment]
You can also access the Nether via the in-game Nether Portal.

**Comment by Trixter313** [comment]
Confirmed to still be working. A fix would be to remove the signs and put some explaining that the nether is currently being worked on. This would solve this issue and the confusion since many users don't get on the forums and I don't believe there's anywhere ingame stating that it's being worked on. Hopefully someone on build or an admin can fix soon. =)

**Comment by DarkDemonDragon** [comment]
Since the Nether has been officially opened for the public to join I think this issue should be closed.
