### ISSUE TITLE
Skill points

### ISSUE THREAD

**Issue by AndyE7** [Wynncraft/Issues#3334]
My leggings became un-equipped because they require agility level 20 when i had agility 20 and it has taken my down from 20 to 19 and ive also noticed some other skills are different

**Comment by Trixter313** [comment]
Armor can modify your skill points, which is most likely happening here. Make sure none of the armor was modifying your skill points. I suggest taking all armor off and verifying you have all of the skill points you should have.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by AndyE7** [comment]
it wasnt the armour, i dont know what it was but i went on the next day without changing anything and i had about 20 more skill points in agility and some more in other skills that had just dissapeared 

    On Tuesday, 29 December 2015, 22:32, Nick Cipriani <notifications@github.com> wrote:
 

 Armor can modify your skill points, which is most likely happening here. Make sure none of the armor was modifying your skill points. I suggest taking all armor off and verifying you have all of the skill points you should have.If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)—

**Comment by Trixter313** [comment]
So did the issue fix itself eventually? Or are some still messed up?

**Comment by AndyE7** [comment]
its fixed its self now but i still have no idea what happened

**Comment by Trixter313** [comment]
Some things like that just take a little time to register correctly and fix themselves. Glad to hear it's fixed =)
