### ISSUE TITLE
Shouts-I lost 2 shouts.

### ISSUE THREAD

**Issue by DemGreens** [Wynncraft/Issues#3335]
I pressed shout. I realised that I didn't want to use it so I though the way not to use them is to press shout again but apparently that just stacks 2 shouts. I then decided to go to hub an come back to a game world. I then saw my shouts had been taken away from me. I didn't actually globally say anything to me so as far as I'm concerned I should be given my shouts back. I asked a mod also but he/she completely ignored me.

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a very strict no refund policy so not much can be done about this, especially because this was just the game doing what it's intended to do. We'd appreciate it if you closed this issue. Thanks!

**Comment by DemGreens** [comment]
Wait the game intends on taking 2 shouts without me getting to use them that doesn't make much sense to me. Please explain.

**Comment by Trixter313** [comment]
You didn't get to use them because you left the game, if you would have stayed you would have gotten to use them. We can't really do much if the player purposefully left the game before using something they activated. I'll close the issue now but if you have any other replies I will still see them and respond. Have a great day!
