### ISSUE TITLE
Quest issue (The Maiden Tower)

### ISSUE THREAD

**Issue by superabel123** [Wynncraft/Issues#3346]
I'm going to get straight to the point:
I managed to get the black veil and return to the tower
and can even enter it when wearing it yet when I killed
the maiden,the NPC keeps saying "I can't enter"
and say "You should go get the black veil and return here
but I already have!
Hope you can fix this issue because /fixquests is'nt helping

**Comment by Trixter313** [comment]
You should get the item that the maiden drops and bring it back to Sherk I believe.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by superabel123** [comment]
Errr it's fine now after I completed a quest
Thx guys!,
Superabel123

**Comment by Trixter313** [comment]
Great to hear!
