### ISSUE TITLE
Wynncraft Texturepack is Bugging

### ISSUE THREAD

**Issue by Andinofuchs** [Wynncraft/Issues#3358]
This Auto installing texturepack is bugging i cant play anymore. pls fix it or delete the texturepack

**Comment by Trixter313** [comment]
If you'd like to disable the resourcepack just select Wynncraft in your server list and click edit then turn server resourcepacks off from there.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
