### ISSUE TITLE
Quest issue (Beneath The Depths)

### ISSUE THREAD

**Issue by superabel123** [Wynncraft/Issues#3380]
I got the faded map and when I talked to Javier,he says to talk to Dalben,
so I went there and Dalben just says hi....
Edit:The quest book tho,suggests that I get the map which i already had done
       and I do not wish to do another quest first to update the book
Re-edit: Nope doing a quest doesn't even update the book

**Comment by superabel123** [comment]
Why does no one reply?

**Comment by Trixter313** [comment]
I did see your issue but I don't have anything I can really suggest. The only thing I have is maybe something didn't register correctly and you can try doing the command /fixquests to see if it gives you an item back for the quest. Hope this helps!

**Comment by superabel123** [comment]
Hey Trixter thx for texting me but I've tried /fixquests and it only gives me more purple crystal shards

**Comment by DarkDemonDragon** [comment]
@Trixter313 /fixquests doesn't work with the maps from Beneath the Depths quest because the items aren't "untradeable". They can be dropped at any point throughout the quest.

@superabel123 if you need another Faded Map you have to go back to the Skull Cave on Pirate Island and get another one the same way you got the first one. Then head out to Dalben (make sure you have 20 EB).

**Comment by Trixter313** [comment]
If DarkDemonDragon's suggestion resolves your issue, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
