### ISSUE TITLE
Mana not regenerating.

### ISSUE THREAD

**Issue by mhammock17** [Wynncraft/Issues#3382]
My mana keeps going 0/20 then 4/20 over and over again when not moving/using spells

**Comment by superabel123** [comment]
What do you mean? Isn't 0/20 to 4/20 mana regen?

**Comment by Trixter313** [comment]
Are you sure none of your armor or weapons have negative mana regen? That might be causing it.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
