### ISSUE TITLE
Missing armor

### ISSUE THREAD

**Issue by bilala2001** [Wynncraft/Issues#3400]
I came on the server after not coming on for a while and when i tried to take off my armor it said it needed to be identified and proceeded to delete all the armor i was wearing please help thanks,

Bilala2001

**Comment by Trixter313** [comment]
Unfortunately, due to Wynncraft's very strict no refund policy, nothing can be done about the already lost armor but there is an issue open about this and it should get fixed soon. Please direct any future comments to the original thread, here: https://github.com/Wynncraft/Issues/issues/3153

Thank you very much!
