### ISSUE TITLE
joining servers

### ISSUE THREAD

**Issue by JustLyon** [Wynncraft/Issues#3401]
Everytime I try to join a Wynncraft server i fall through the map.
I`ve tried all versions of 1.8 and tried relogging multiple times.
I would be very happy if someone could give me tips on how to fix this problem.

**Comment by Trixter313** [comment]
Have you tried typing /kill with 3+ soul points after logging in and falling? It should bring you to the nearest visited town. I hope this helps!

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by JustLyon** [comment]
When I try joining any of the servers I instantly fall through the map and it won`t let me use commands other than /lobby. (/class doesn`t work either)

**Comment by JustLyon** [comment]
![2016-01-02_19 04 31](https://cloud.githubusercontent.com/assets/16503775/12075520/e758d5c8-b183-11e5-90aa-e0889ac41e37.png)
![2016-01-02_19 04 33](https://cloud.githubusercontent.com/assets/16503775/12075521/ec56c706-b183-11e5-95b8-881de0d482ef.png)

**Comment by Trixter313** [comment]
I believe this happens to some people when they disable the resource pack. Go to your servers list, select Wynncraft and click edit and enable the server resource pack.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
