### ISSUE TITLE
Beneath the Depths not taking emeralds

### ISSUE THREAD

**Issue by Hatchbird** [Wynncraft/Issues#3416]
So when I was doing the quest. I was at the stage to go and pay Dalben 20 emerald blocks to decipher the map. As I turned around to open a loot chest, It then moved on to the next staged, but I didn't have the payment on me.

- Hatchbird

**Comment by Trixter313** [comment]
So you're saying the quest continued even though you didn't have the money on you, correct? I believe I've experienced this also so I think I can confirm this.

**Comment by arneturuc** [comment]
I just experienced the same, though I didn't click Dalben again but travelled to Selchar in order to get 20 EB.
After returning he spoke of "everything being in order", gave me the disenchanted map and let me continue the quest, even though he didn't take the money (what I appreciate, but it's a bug nonetheless).
What I also notices was that I had still the old faded map.

**Comment by Moe-Ronickah** [comment]
This was modified in order to make it easier for players.  I don't know if the quest dialogue will be changed, or if it will change back to needing 20EB.

**Comment by Villageacules** [comment]
Maybe try doing /fixquests, I don't fully understand the situation but it seems that you didn't try to do it yet.  If nothing fixes, you may require admin assistance.  If you require this tag me @Villageacules
