### ISSUE TITLE
can't get red of the server's texture pack

### ISSUE THREAD

**Issue by Logan368** [Wynncraft/Issues#3433]
for some reason I can't get the texture pack for the server to stop re downloading it's self after I've deleted it  and I can't figure out how to remove it.

**Comment by Trixter313** [comment]
If you'd like to stop using the resource pack, just select Wynncraft in the server list and click edit then change server resource packs to disabled.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
