### ISSUE TITLE
Relic boots vanished

### ISSUE THREAD

**Issue by lolgotem** [Wynncraft/Issues#3442]
After I got my Relic Boots, I decided to go to an Item Identifier so I can well, identify it. Then someone shouted about fighting Bob in another World. I decided to go there but then, my boots were gone. Any way to get them back? I tried to get them back by going back to the Boots Relic but I didn't get them back.

**Comment by HeyloLP** [comment]
relics are useless right now untill the powder-update

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a very strict no refund policy so the only way you could get it back is trading other players or using another class to visit the shrine.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
