### ISSUE TITLE
Lost my armor because of the update and some quest items

### ISSUE THREAD

**Issue by key14** [Wynncraft/Issues#3463]
When i first logged in to the new updated server i needed to identify my gear and just when i checked my armor it disappeared and my quest item Abysso Galoshes. 
I really hope i can get my both armor and quest item back (most the quest item) so i can proceed in wynncraft.

/key_14

**Comment by ImSickPT** [comment]
Have you ever heard of a command called /fixquests?

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a very strict no refund policy so we can't do much about the lost regular armor but if /fixquests returns the boots it should fix the issue.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
