### ISSUE TITLE
Missing XP/No XP

### ISSUE THREAD

**Issue by ShanghaiStreeter** [Wynncraft/Issues#3465]
I've been trying to take advantage of the double XP boost and finished over 5 quests in Gavel. After doing "An Iron Heart II" I realized that I hadn't gained ANY experience throughout all of them, and also by killing mobs. I was still at 25% throughout. (Level 59 Archer). It applies to all my classes as well, as I had made a new one (another archer) and still received no XP. Thanks!

**Comment by Trixter313** [comment]
You're most likely giving all of your xp to your guild. Try typing "/guild xp 0" and see if that helps.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)
