### ISSUE TITLE
Can't connect to the server

### ISSUE THREAD

**Issue by Aviee** [Wynncraft/Issues#3468]
I can't join the server, it tries to ping it for 5 seconds but then it says its down. All my other servers I can join fine but wynncraft I can't, I've tried changing the ip to play.wynncraft.com/org/net but it still wont work. I've also tried using 1.7.10 instead of 1.8 but still wont work and I've also tried to restart my minecraft. It's been like this for 3 days now.

**Comment by Trixter313** [comment]
Try using the IP's listed in this thread to see if any work: https://forums.wynncraft.com/threads/all-possible-ips.100486/

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by Aviee** [comment]
I found out how to fix it. I made a new 1.8 version all fresh etc. but it didn't have the mods I want and couldn't be bothered to download them again so I used node7.wynncraft.com and it worked thanks! will also close this.
