### ISSUE TITLE
Not another resource pack bug!

### ISSUE THREAD

**Issue by RegalSnivy** [Wynncraft/Issues#3477]
So, I go on Wynncraft normally, get no error message, but when I get to the select class menu, the pack isn't working, and the chat keeps giving me not-too-helpful warnings. I have tried nearly every solution. Guess what? No luck. Please help

**Comment by Trixter313** [comment]
What are the messages shown in chat?

**Comment by RegalSnivy** [comment]
![image](https://cloud.githubusercontent.com/assets/16520368/12076543/71285ee2-b17d-11e5-92cd-cdf4708ae8f0.jpeg)
Here is an attached picture

**Comment by Trixter313** [comment]
Oh, I see. Just go to your server list and select Wynncraft then click edit. Enable server resourcepacks and you should be good. The message isn't too unhelpful because if you go to the link at the bottom it brings you here, telling you how to fix =) https://forums.wynncraft.com/threads/cant-play-wynncraft-because-of-the-pack-heres-how-to-fix.98023/

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by RegalSnivy** [comment]
Trust me, resource packs are enabled. Still no progress

**Comment by Trixter313** [comment]
Download the pack here then and use it like any other resourcepack: https://drive.google.com/open?id=0B1ONgNZTFXnwbU9senNwaXJaR3M

I'd recommend checking to see if the normal way works every once in awhile though because if you use this message any updates they make to the pack won't be seen to you.

**Comment by RegalSnivy** [comment]
I've been doing that. Thing is, the message still shows up.

**Comment by Trixter313** [comment]
Yeah, once the normal way starts working it will go away. It usually just takes a little time.

**Comment by Trixter313** [comment]
Try disabling the downloaded resourcepack and enabling the server version again. Report back whether it works or not now.

**Comment by Dar-krusos** [comment]
Delete the server from your server list (and the resource pack in the 'server-resource-pack' folder if you want) and re-add it. Then try thereafter.
