### ISSUE TITLE
Lost the Helmet you get from "Purple and Blue"

### ISSUE THREAD

**Issue by AshenKitty** [Wynncraft/Issues#3481]
First of, I do love the new Gavel update, but there is one huge issue with the servers crashing all the time.

Now I even lost the helmet you get from this quest mentioned in the title, along all the items I tried to identify, because right at this moment, the server crashed.

I don't really care much about the other items (except the helmet), but it's really bothersome to keep lose stuff all the time.

**Comment by Trixter313** [comment]
You can try the command /fixquests to see if it returns the helmet. If not the only other way I can see you getting it back is doing the quest on another class or trading with players (if possible). Wynncraft has a strict no refunds policy so I hope one of these suggestions help.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by AshenKitty** [comment]
I've tried using the command, but I suppose it won't return as it still has been unidentified.

Oh well, guess I have no choice as to wait to be able to do the quest again.
It's just sad as the crashes seem to get worse every day. (No offense though, I can imagine how hard keeping a server up can be, my old PC couldn't even keep up a simple vanilla MC server I had for me and my fiancé.)

Anyway, I guess it can't be helped, thank you anyway. I'll close the issue.
