### ISSUE TITLE
Nether

### ISSUE THREAD

**Issue by TGNebulA** [Wynncraft/Issues#3483]
cant access the nether, this is not a problem for pvp in my case but i cannot do the temple of legends quest! probably been noticed before but if it hasnt then im pointing it out :D

**Comment by Trixter313** [comment]
For the Temple of Legends quest you actually get the items from the area around the nether portal, not in the nether.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by TGNebulA** [comment]
even so the nether still doesnt work!

**Comment by Trixter313** [comment]
Yeah, the nether is being updated still and they said it would be back up soon after the Gavel release. It's been down since the update.

**Comment by TGNebulA** [comment]
ok thankyou sorry for the misunderstanding.
