### ISSUE TITLE
Glitched helm

### ISSUE THREAD

**Issue by Mario1230X** [Wynncraft/Issues#3563]
Level 9 rare helm, Drale's Hide was not updated to gavel version of armor. It shows up as a rare can not be identified and you find it only in chests :3

**Comment by Trixter313** [comment]
Could anyone please post a screenshot of the helmet's stats? Thanks!

**Comment by Moe-Ronickah** [comment]
Closed: no response from op.

**Comment by DebugMC** [comment]
@Moe-Ronickah that was me long ago (Just like on #3953 I had changed my account.) Anyway, I do not think this has been fixed, but I have not seen this item. Like, not from drops/chests at all recently, its like its been removed. Sorry for no reply, I didn't check github at all back then. 


Oh, I actually should check my alt which hasn't been on since pre-gavel. Ill check. (If I dont reply then I don't have it)

**Comment by DebugMC** [comment]
@Trixter313 fixed, as I checked item guide and it has ids + element defense that couldn't exist pre-gavel.

Drale's Hide
❤ Health: +38
✤ Earth Defense: 5
Lv. Min : 9
+2% to 6% Melee Damage
+1 to 4 Strength
+2% to 8% Speed
[0/1] Powder Slot
Rare Item
