### ISSUE TITLE
and now ma 300% loot and xp are not working i want my stuf back and soon to think i was gonna upgrade to vip+

### ISSUE THREAD

**Issue by magm4cube** [Wynncraft/Issues#3601]

**Comment by TrashcanMan** [comment]
Could you post some details?

**Comment by magm4cube** [comment]
Like wat I lost like a 70% of my emeralds no 300% xp or loot and no endgame
armor

**Comment by Trixter313** [comment]
Explaining what happened to your items would be good. Unfortunately Wynncraft has a very strict no refund policy so we can't do much in this situation. If it happened because you died while low on soul points, I recommend trying to keep a closer eye on your current amount. I hope this doesn't happen to you again.

**Comment by magm4cube** [comment]
Doesn't matter anymore salted is not responding to my conversation and so I
officially quit Wynncraft I got to lvl 75 lost everything important nobody
did anything donated for VIP guess that was a waste since I FUCKING
QUIIIIIIT

**Comment by TrashcanMan** [comment]
Salted doesn't actually read the Github, that's Tama's job.

**Comment by Trixter313** [comment]
I suggest asking around and seeing if some players will give you some items. Usually some people will. Other than that there's not much else we can do. Try having fun and enjoying all of the new quests to get back up to 75 maybe? =)

Have a great day!
