### ISSUE TITLE
Armor

### ISSUE THREAD

**Issue by xXSHAFTXx** [Wynncraft/Issues#3623]
Where is my Armor
You wipe server?
I join server and i didnt see my armor
![screenshot_1](https://cloud.githubusercontent.com/assets/16632263/12220978/21e63b34-b799-11e5-93d2-457d62152ade.png)

**Comment by Trixter313** [comment]
Is this your first time logging in since the Gavel update? In the update you have to re-identify all items and there is currently a bug where when your unidentified armor pops off of you, instead of it dropping, it just dissapears if your inventory is full. Wynncraft has a strict no refunds policy so not much can be done about the already lost items but we are working on getting the problem of them getting deleted fixed. Ask around and some nice players will probably give you some of their items. Hopefully this isn't too much of an inconvenience.
