### ISSUE TITLE
all my items are unidentified and lost some items because of that.

### ISSUE THREAD

**Issue by maccamoppy** [Wynncraft/Issues#3629]
please help? i was wearing two legendarys

**Comment by Trixter313** [comment]
Items will be unidentified when you first login since the Gavel update, but it is currently a bug where instead of dropping unidentified worn armor on the ground when the inventory is full, it just disappears. Due to Wynncraft's strict no refunds policy, not much can be done about the already lost armor but we are working on fixing the issue of them disappearing in the first place. Hopefully this wasn't too much of an inconvenience!
