### ISSUE TITLE
Class wipe

### ISSUE THREAD

**Issue by BoyMeetsGame** [Wynncraft/Issues#3656]
So I just got back into the game and was psyched for Gavel. But I'm kind of bummed knowing that I have no level 1 classes to do the whole thing. So I see that VIPs can have an extra class slot of their choosing. I do that as a warrior and get to level 16. At a certain point I'm switching classes a lot and when I go back to the new warrior, all my progress is gone!

tl;dr: I chose the new class slot, warrior and when I was lvl 16 it got wiped

Somebody please help if you can shed some light on this enormous problem. Just imagine if this happened to a much higher level?

**Comment by meatloaf4311** [comment]
You may have accidentally deleted it, right clicking it does this

**Comment by Trixter313** [comment]
What meatloaf said or it's possible you were hacked or someone besides you was using your account. If you think you might have been hacked I'd suggest changing your Minecraft password and associated email's password to prevent this from happening again. Due to Wynncraft's strict no refunds policy we can't get any of the items or experience back to you.
