### ISSUE TITLE
I Lost All My Armor!

### ISSUE THREAD

**Issue by Kettlekorn** [Wynncraft/Issues#3674]
I'm so damn frustrated! I just realized I lost it after I was killed 3 times by a werewolf. I don't care the glitch is fixed I JUST WANT MY ARMOR BACK!

**Comment by Kettlekorn** [comment]
I never died with 0 soul points or dropped it

**Comment by Kettlekorn** [comment]
If the staff just fix the bug and tell me to get the armor back I'll be more pissed off.

**Comment by TrashcanMan** [comment]
Unfortunately Wynncraft has a strict no-refunds policy in place, mainly due to people who abuse the system to get free items. This means that if you lose anything, the staff aren't allowed to give it back. I suppose you could go ask around for free stuff, there's usually somebody nice enough to give you something.
