### ISSUE TITLE
Still cannot access any servers

### ISSUE THREAD

**Issue by Mewnlight** [Wynncraft/Issues#3689]
This issue has been going on for 3 years and the last time I submitted a report, the closed it without fixing the issue. 

My IGN is Moonlight_Pixels
I am unable to access servers, but I'm able to go on the classes screen. 
https://gyazo.com/8e33ed9064d6cfc7799d41c9678e2c55
^This happens whenever i choose a class to play with. I can make new classes, with no problem, but completely unable to actually go on a server to play. 

Could you reset my account or my file completely? (I know it's server side because I can play on my alt with no problem, but I really rather play on my main account)

Thank you,
Moonlight_Pixels

**Comment by Mewnlight** [comment]
Also I've requested assistance about this issue twice before.
Once was an answer was to wait for the fixed, then it was closed.
As well as the second time it was closed with no reply.
https://github.com/Wynncraft/Issues/issues/1269
https://github.com/Wynncraft/Issues/issues/1300

**Comment by Dar-krusos** [comment]
This usually happens when you have a bad connection to Wynncraft. When I log into when, it forces me to choose a /class once every time, unless there are only like 5-10 people on the server. It all comes down to lag for me, which is affected by the connection.

If the problem isn't that, then I don't know what is going on.
If the problem is, in fact, that... well only thing you can do is let them make Wynncraft less laggier or improve your connection.

**Comment by Mewnlight** [comment]
No it's not, as I stated before, I can log on with my alternate minecraft account with no problem and play as any character. This issue is only with my main account, which is the one I want to play with.

**Comment by Dar-krusos** [comment]
Oh.. right. Look at this issue 3250

**Comment by Trixter313** [comment]
Please follow the original issue, linked above, for updates. Thanks!
