### ISSUE TITLE
Flight Full Of Anoyance!

### ISSUE THREAD

**Issue by aws404** [Wynncraft/Issues#3742]
Everytime you die in the "Flight In Distress" quest you are sen back to another city and are forced to star the quest over but with no guidance at all. You have to remember what to do until you get back to where you died.

**Comment by Dar-krusos** [comment]
Yeah, this is due to the airship locations being closer to those towns, and dying takes you to the closest town, which happens to be those ones. This is not really a bug, just misplacement. Cinfras is also in the middle of Gavel, so it is impossible to put structures outside of the map that teleport you to Cinfras. The only way they can counter this is by programming certain location boxes that will teleport you to a certain town when dying inside that box.

Right now, they can't do anything about this and I don't think it will be resolved soon. Sorry :(

**Comment by Trixter313** [comment]
Merged into #3617 

Thanks for the addition!

**Comment by aws404** [comment]
My issue was more of the having to start the quest again but with no guidance. After diving and returning to the airship it should take you back to the stage you died at not to the beginning of the quest.

**Comment by Dar-krusos** [comment]
I don't think there really is anyway to fix that, otherwise there might be a way other players could exploit, or it would be too difficult to code.

The only thing you can do is... Just not die. I know it's not a solution to this problem, but you'll just have to work around it for now.

**Comment by Trixter313** [comment]
The issue is about not respawning in the correct place which sounds like exactly what you want.

**Comment by aws404** [comment]
The issue sent about respawning in the cirrect place. It's about having to do the whole quest without guidance from the start.

**Comment by DarkDemonDragon** [comment]
If something like this happens with another quest I recommend looking at a youtube walkthrough for the quest if you're struggling to retrace the steps without guidance. Also, Flight in Distress does give some guidance through NPC chat. All NPCs still say what you're supposed to do like find the son, when to go to sleep, who to talk to when things happen, etc. While the quest book is helpful it isn't necessary to be honest. 

I believe this should be closed as what you are suggesting would be for the Quest book to go backwards.  Quest book mechanics are perfectly find and all that is required is for the respawning location to be fixed, which @Trixter313 has in #3617

**Comment by Trixter313** [comment]
I'd suggest making a suggestion thread on the forums for the quest book part.
