### ISSUE TITLE
Bob's Mythic Bow Vanishing

### ISSUE THREAD

**Issue by 4potatoes** [Wynncraft/Issues#3751]
When I died attempting Saving the Light, I respawned in Lexdale. I left the game, but when I came back, my Bob's Mythic wasn't in my first slot. Could this be an issue or did I somehow drop it?

**Comment by Trixter313** [comment]
There's no way to really tell what happened exactly but the most likely possibility is that you accidentally dropped it. Sometimes items disappear but are still in your inventory so you could try clicking the empty slots in your inventory and see if it pops up. Other than that there's not much we can do because Wynncraft has a very strict no refunds policy. If it was dropped, I suggest changing your drop key to something else that's harder to accidentally press to hopefully prevent this from happening again. Hopefully these suggestions help!
