### ISSUE TITLE
Iron Heart Part 1

### ISSUE THREAD

**Issue by slendersir739** [Wynncraft/Issues#3756]
I have started the quest but it will not let me near the mountain.
http://imgur.com/7NUowiF
http://imgur.com/A9uitRa
http://imgur.com/2IdgjbD

**Comment by Trixter313** [comment]
Could you post a screenshot of what it says in your quest book? Thanks!

**Comment by meatloaf4311** [comment]
I know you have to enter the cave a certain way so that the dialog can update.


If you have fixed the issue, please close the issue. If not gives us an update.

**Comment by TBlazeWarriorT** [comment]
I had a similar issue, so I'll try to detail it. That's the following: I talked to Duvale, then questbook asked me to "» Find the defective Guard Golem in the mountain. X -1705, Y 93, Z -5092". When at the coords, I got the red error message as in the screenshots from the guy above. The issue was the quest coordinates are confusing, as they do not properly point to the cave entrance, so if you get inside the cave from the right path, you won't get kicked out. Still, you get the red error message even when you are not on the cave entrance (-1705 -5092 does not look like the cave entrance and kicks you away), so I think that should be double-checked/fixed.
