### ISSUE TITLE
Bugged skill points

### ISSUE THREAD

**Issue by mfehmer** [Wynncraft/Issues#3805]
Hey there.
I just leveled up to 26 and all my skill points got reset.
After spending skill points again (in order to wear me stuff) "there was an error" and I got kicked into the lobby.
Now, all skill points are messed up as hell and i can't nearly wear anything.

Could this be fixed?
Thanks in advance
(Ingame name: derN3rd)

**Comment by Wozab** [comment]
You can try to reset your skill points in the tower of amnesia, it costs 1 LE but it should solve your issue.

**Comment by mfehmer** [comment]
@Wozab Yes, this would be possible, if I would have 1 LE...
But also, why should I spend something if it happend trough a bug?
I did send an email to the support. Let's see, if I get an answer

**Comment by Trixter313** [comment]
Could you post a screenshot of the skill points? It's not very descriptive, I just know that they are 'messed up' but in what way? Also make sure that any armor you are wearing isn't affecting your skill points.

**Comment by mfehmer** [comment]
@Trixter313 Can't take a Screenshot right now, but i choose something like 15 5 5 15 10 (without any armor on), but after the error it was something like 5 18 8 12 7
Like it was randomized or something..

**Comment by Trixter313** [comment]
Hmm, because you aren't actually missing any skill points there isn't really anything an admin can do because we have a very strict no refunds policy which would include resetting skill points for free. Were you using the method of adding skill points where if you left click it adds 5, because I think some users were doing that and it was buggy for them too. Adding them one by one seems to be the most reliable way. All I can suggest is bare with it for a while and do some quests to level up fast so you can even out your skill points to a decent state. It shouldn't take too long, hopefully. I'll close this issue since that's all that can really be done here but maybe your email will get you some more help. Good luck!
