### ISSUE TITLE
account deleted

### ISSUE THREAD

**Issue by ashsbulbasaur** [Wynncraft/Issues#3810]
my lvl 71 archer was found deleted on the 22/1/2016 can someone PLEASE get my account back 
my username is ashsbulbasaur

**Comment by Dar-krusos** [comment]
Try left-clicking it. It might be in countdown mode after you accidentally right-clicked it (and somehow accepted the deletion). Otherwise, if it was actually deleted, I don't know why it would show the deletion date or even that it was deleted.

**Comment by meatloaf4311** [comment]
I know the admin's dont do refunds, and you may have to reacquired everything lost, idk, maybe you'll get lucky

**Comment by Trixter313** [comment]
Unfortunately, due to Wynncraft's strict no refunds policy, there's nothing we can do about the lost class but it's possible that your account was hacked and someone else deleted it. I'd suggest changing your Minecraft and associated email's passwords if it's possible at all that you were hacked. Hopefully this helps prevent this from happening again!
