### ISSUE TITLE
Quest: Suspended Flowers

### ISSUE THREAD

**Issue by Jason0228** [Wynncraft/Issues#3825]
After giving the flowers to Ash, i accidentally clicked on a flower pot with the Aerolia Flowers, so i tried to break the pot to get back and it disappeared, making me left with 3 flowers, unable to finish the quest.

**Comment by Trixter313** [comment]
Was it the quest version of the flowers or the regular version, from the cave? If it's the regular version, you should be able to just go back to the cave and farm some more. If it's the quest version, you can try typing /fixquests and seeing if it returns the missing flower. What does the next NPC in the quest say when you try to give them the flowers?

**Comment by Jason0228** [comment]
"Have you obtained the flowers yet?"

**Comment by Trixter313** [comment]
Ah, what about when you try typing /fixquests

**Comment by Jason0228** [comment]
Didn't work

**Comment by Trixter313** [comment]
Hmm, the only other thing I can think of doing, but it's a little risky, is to drop the two flowers that you do have by filling your inventory completely and dropping them while standing on another item, then try /fixquests again. This could leave you with no flowers at all but it could also give you all three back because the command might not check for quantity but just if you have any, period. It's up to you if you'd like to try it. If you don't, it could take a long time or possibly never get fixed and if you do, the same could happen but there is at least a chance of getting them back. Hopefully this information helps you make a decision and your issue gets resolved soon!

**Comment by Jason0228** [comment]
K, i'll try it, i currently have 3 flowers

**Comment by Jason0228** [comment]
Thanks! I got 4 of them back!!!!!!!!!!!!! tytytytytytytytytytytytytytytyty

**Comment by Trixter313** [comment]
Good to hear!
