### ISSUE TITLE
Inventory Glitch

### ISSUE THREAD

**Issue by AdroThePVP** [Wynncraft/Issues#3827]
So first of all i try to move my Bow to my first slot its called i think Physician or something like that but the stats are fast shoot damage 20-32 i tried 4 times it keep coming back and when it stay still i run and suddenly the bow is gone i try reloading but its no use

**Comment by Dar-krusos** [comment]
Whenever I move weapons or items I click on empty slots just to make sure it doesn't drop out of my inventory. Then I close the inventory, open it again and see if it's still there.

**Comment by Trixter313** [comment]
All I can suggest is clicking on all of your empty inventory slots and see if it pops back up. If not, there's not much else that we can do due to Wynncraft's very strict no refunds policy but if you ask around a bit you'll most likely run into a player that could give you a bow to help you get back on your feet. Hopefully it isn't too much of an inconvenience and you get back to playing like normal soon!
