### ISSUE TITLE
I need alot of items in my e-chest/inventory cleared and or replaced [the taproot for quest, etc]

### ISSUE THREAD

**Issue by ttykox59** [Wynncraft/Issues#3829]
I have tried to use the /fixquests command to help me fix the taproot quest which I for some reason I can't start, even with the taproot item itself, which I think is glitches and because of the command, I have 6 purple shards, 1 yellow shard, and 1 healing water, these are all useless items because for both quests I have already used/gave them to the npc's. Can any admin/moderater/or anyone that can just fix this fix this please!

**Comment by Dar-krusos** [comment]
You need to have a Volt Goat Horn, alongside the Taproot, to start the Finding the Light quest.
If you want to get rid of unnecessary items (be. very. careful.), see my post in [this issue](#3818).

**Comment by Trixter313** [comment]
If you fill your inventory up completely and drop a quest item while standing on an item the quest item will disappear. You can use this on any items you feel that you shouldn't have but be careful because you will be responsible for the lost items. Make sure you are 100% sure that you won't need the items later on because it can be a lengthy process to get them back if /fixquests doesn't. Hope this helps! If so, please close this issue. Thanks!
