### ISSUE TITLE
/find

### ISSUE THREAD

**Issue by thecoolkogut4** [Wynncraft/Issues#3888]
no permission to do the command.

error: you do not have permission to execute this command!

**Comment by Odnod** [comment]
They removed it. Simple as that.

**Comment by Trixter313** [comment]
I'm not sure if it was removed or not but if I had to guess I'd say it isn't intended because if you try and use a command that doesn't exist it says, "Invalid command..." but instead we get a permission answer. I'm not gonna assume it was removed just because it stopped working, especially because there's no statement about it or obvious reason for it being removed. Hopefully it should be fixed soon!

**Comment by DarkDemonDragon** [comment]
@Odnod don't say things you don't have staff confirmation for. It just be bugged as for some reason there have been multiple bugs arising lately after the server went down. I assume that Admins attempted to update something that caused bugs to appear. Also, the friend system lets you find players just as well as /find.

**Comment by DarkDemonDragon** [comment]
This is confirmed to be a bug and is being worked on.
https://forums.wynncraft.com/threads/gavel-patch-14-0-7.108278/

**Comment by thecoolkogut4** [comment]
@Odnod your wrong, simple as that

Salted:
 "Upcoming patch
(most likely will come tomorrow or the day after)

- Fixing /find"
