### ISSUE TITLE
'You dont have permission for this area'

### ISSUE THREAD

**Issue by Shadoweagle5098** [Wynncraft/Issues#3902]
I've been experiencing this small yet extremely annoying glitch. So my bow, before the game re-textures it, is a dark oak wood slab. when i shoot downwards (or if i shoot near a block) i suspect the game thinks im trying to place the slab, so it says 'you dont have permission for this area.' when fighting an enemy in an enclosed space, this gets extremely annoying, very quickly, as it clogs my entire chat with 'you dont have permission for this area'. This also happens when opening loot chests. i cant open them unless i have an empty hand. the same even goes for pressing buttons... it has only happened to me today, never at all in the past, which is strange. If anyone knows how to deal with this, please tell me!

**Comment by DarkDemonDragon** [comment]
I can confirm this is an issue. Other than opening chest this doesn't hinder you other then giving you the red text though. Shooting at the ground still works, so just bear with it for now.

**Comment by ReyDeLosCreepers** [comment]
I have the same issue.

**Comment by brainscript** [comment]
Same issue.
**Please fix this!** :pray: 
*It's sooo annoying ...*

**Comment by DarkDemonDragon** [comment]
@brainscript it's too much effort to fix for too much risk. You could end up accidentally PLACING your weapon on the ground with no way to get it back. Would you rather lose a weapon or get harmless red text in the chat?

**Comment by brainscript** [comment]
@DarkDemonDragon Rly? They could just cancel the block place event **WITHOUT** sending the message. And by the way you can't actually place blocks in adventure mode ...

**Comment by DarkDemonDragon** [comment]
@brainscript just make a suggestion. I honestly don't fully understand how the bug happened, because beforehand it didn't do this and you would not get the red text. After the staff fixed a bug related to spells this happened. I don't know if they are connected or anything, but this definitely happened after an update and did not start randomly. If this resulted after a bug fix it may be difficult to fix this because they may undo their fixes and the old bug would return. 

Again, I'm not too sure how this works, so it could be simple or complicated to fix so make a suggestion on the forums if you feel strongly about it.

**Comment by brainscript** [comment]
@DarkDemonDragon This is 100% not "difficult to fix". There are different ways of "protecting" your world (preventing players from placing/breaking/interacting with blocks) than using WorldGuard. This message sounds like WorldGuard because I saw this message also on smaller servers and "*You don't have permission for this area.*" also makes no sense: You can't place blocks anywhere in the world, so why should the WynnCraft developers use this message in their own plugin? Because it's to difficult to code this on their own? **It's not.**

So? If this is the problem of their plugin, they could just **remove the message**. And if it's WorldGuard's fault, they could just **stop using WorldGuard**. And it's really not that difficult to code an alternative ...

**Comment by DarkDemonDragon** [comment]
Again if you feel strongly about it then make a suggestion on the forums.

**Comment by brainscript** [comment]
**NOTE:** The bug only occurs with the bow `Infinity` (for me), the bow `Olux's Prized Bow`, which is the same item (`wooden_slab`/`WOOD_STEP`), is not showing the message when right-clicking a block.

**Comment by DarkDemonDragon** [comment]
Yea not all weapons suffer from this bug. This is why I say it might not have a simple fix.

**Comment by Moe-Ronickah** [comment]
This is purely due to the Wynn Resource Pack re-assigning block textures as some weapons.  The fix is to change what you are holding in your right hand.

**Comment by GabrielMoose** [comment]
can you make it where if you give a glitched item to a item indicator he will fix it for free because you should not pay emeralds for pressing Q.

**Comment by YunoFGasai** [comment]
@GabrielMoose please open an issue, what you are describing doesn't have anything to do with this issue.

**Comment by TheDollarBill** [comment]
This issue is still alive. I'm getting the problem with this texture: http://i.imgur.com/TIICcGI.png
I'm sure there are more though.

**Comment by ende124** [comment]
Why is this issue closed? It's not fixed. Cannot open loot chests or open doors while holding this weapon. SHould be an easy fix as stated above.

**Comment by Moe-Ronickah** [comment]
@ende124 , see my post of Apr 20.  The issue is known to the developers, as far as I am aware, and it is on their radar.  The simple fix is to right click with something else in your hand, or nothing at all.
