### ISSUE TITLE
Character Deleted

### ISSUE THREAD

**Issue by cosmoswolf** [Wynncraft/Issues#3977]
I had a level 28 archer that was gone when I logged on today, is there anyway I can get it back?

**Comment by Trixter313** [comment]
Due to Wynncraft's strict no refunds policy there's nothing we can do about this. You or someone who uses your account most likely accidentally deleted it. Also, it's possible that you were hacked and the hacker deleted it. I'd reccomend changing your Minecraft and the associated email's passwords if you think it's a possibility at all. Hopefully this doesn't happen to you again!
