### ISSUE TITLE
Rings & Necklace don't work

### ISSUE THREAD

**Issue by bannana345543** [Wynncraft/Issues#3989]
The stats my rings and necklace "give" don't actually give me it. My jester necklace says 15%+ loot bonus and I have 1% loot bonus. My ring says +11% Loot bonus and my stats don't change, also giving 150 health and doesn't actually give me health. Can someone explain whats wrong.

**Comment by Dar-krusos** [comment]
For all accessories, it's just a bug with certain servers/other aspects. Just change servers for it to update.

For the Jester Set, this problem is more common, so I think it has something to do with just that set itself. If other peoples' Jester Sets work, then it's just the problem I stated above.

**Comment by Trixter313** [comment]
Is this still occurring? A recent patch supposedly fixed some set related issues. (https://forums.wynncraft.com/threads/gavel-patch-14-0-8.109965/) Thanks!

**Comment by Trixter313** [comment]
I'm going to assume that the issue is now fixed due to no response. If anyone is still experiencing it, simply comment and I'll reopen the issue. Thanks!
