### ISSUE TITLE
Lost my Armor and Staff

### ISSUE THREAD

**Issue by DaBigBiins** [Wynncraft/Issues#4046]
Hello dear Wynncrafters,
After a long period of time I decided to return to this server. It seemed that a lot had changed.
All my armor and weapons were UNINDENTIFIED. As soon as I interacted with my armor it disappeared leaving me "naked". I indentified my staff and became one that was rather disappointing.
I hope something can be done :)
btw my In game name is biins and I am a lvl 34 Mage.

**Comment by KeepoPrideHD** [comment]
It happened to everyone in the Gavel update, as almost all of the game mechanics have been changed, stats of the weapons and armor have been rebalanced and changed. No wonder why you're disappointed with your wand, as mage's damage was lowered due to the possibility of hitting multiple targets even through walls with basic attack. Therefore, mage is now the least as it comes to the basic-attack damage. As for the armor disappearing, if you remember the names of your armour parts, search them in wynncraft wiki (https://wiki.wynncraft.com/index.php?title=Main_Page) and read all about it, as in the game rebalance many items have been removed, and so might your armour.

**Comment by TrashcanMan** [comment]
Unfortunately Wynncraft has a no-refunds policy, so we can't give you your items back. However, you're only level 34, it shouldn't be too hard to grind some new armor. Ask around, maybe somebody will be nice enough to give you some free stuff.

**Comment by GlitchDoesMC** [comment]
You're better off buying some normal weapons from the merchants. You'll get better weapons later, trust me.

**Comment by DaBigBiins** [comment]
Sorry, the armor was unindentified at the moment when the disappeared.
The only thing I could remember was that I had excactly 770HP

Thank you for the reply
