### ISSUE TITLE
Mana Steal and Life Steal

### ISSUE THREAD

**Issue by yayRoku** [Wynncraft/Issues#4065]
Hi (Yes, I'm spanish '~')

Mana Steal and Life Steal it does not work, except seldom

Nothing more

Bye!

**Comment by Dar-krusos** [comment]
They only work effectively with poison and no-one is yet sure if this is intentional or not. I think somebody will have to try and get a comment on this topic from the admins.

**Comment by yayRoku** [comment]
No, this effect no work with poison. Only effect rarely times in first hits 
Like a bug

**Comment by DarkDemonDragon** [comment]
Have you tried **combining** Life Steal and Mana Steal with Poison? If this doesn't work, try switching worlds. Some worlds will have a bug and not work.

**Comment by TrunkMunkey** [comment]
i use mana steal and life steal, and yes i have poison as well. hes right, it doesnt work right now regardless of poison, which sucks since i built my character around life and mana steal. dont really have gear to regen mana, so im pretty much useless since i cant use spells. always drained on mana from running to wherever the quest is leading.

**Comment by yayRoku** [comment]
"Have you tried combining Life Steal and Mana Steal with Poison? If this doesn't work, try switching worlds. Some worlds will have a bug and not work"

I tried ALL
This bug affect ar all the persons (and friends: AlexDopico, Fermadrix, Joacle (a veteran player) etc...)

**Comment by yayRoku** [comment]
PD: I tried in all the worlds :/

**Comment by yayRoku** [comment]
"i use mana steal and life steal, and yes i have poison as well. hes right, it doesnt work right now regardless of poison, which sucks since i built my character around life and mana steal. dont really have gear to regen mana, so im pretty much useless since i cant use spells. always drained on mana from running to wherever the quest is leading."

Mana steal is one of the effects more importants in higher levels. 
This bug is very annoying

**Comment by DarkDemonDragon** [comment]
Ok for some reason all worlds seemed to have developed this issue... Hopefully the Admins take notice and do something about it.

**Comment by yayRoku** [comment]
"Ok for some reason all worlds seemed to have developed this issue... Hopefully the Admins take notice and do something about it"
Yay! Thanks for all the comments ^^

**Comment by Moe-Ronickah** [comment]
Mana steal and life steal now work by chance, over time, and are linked to your basic attack, only.  The effect that they had after the Gavel update was overpowered, and there is currently an issue with mana and life steal activating with spells that is related to the game code.  We have been told that when powders come out, that the apparent problems with mana steal and life steal should be fixed by the use of powders.
