### ISSUE TITLE
Im stuck inside of some sort of wall or mountain

### ISSUE THREAD

**Issue by 9XxDar-xX9** [Wynncraft/Issues#4072]
_[lvl33]Ma_ -I was in the lions den and I did the teleport spell, suddenly I couldn't see anything. I cant even use teleportation scrolls... I don't want to have to reset my character because I had a lot of legendary and rare items. Yeah, so if someone could tp me out that would be great. I am completely immobile in the blocks. This one is my best class.... Pleas

**Comment by 9XxDar-xX9** [comment]
Never mind, Im unstuck

**Comment by magmablock1999** [comment]
I was in the lions den and I did the teleport spell, suddenly I couldn't see anything. I cant even use teleportation scrolls... I don't want to have to reset my character because I had a lot of legendary and rare items. Yeah, so if someone could tp me out that would be great. I am completely immobile in the blocks. This one is my best class.... Pleas

**Comment by Odnod** [comment]
When in doubt, /kill

**Comment by magmablock1999** [comment]
thx
