### ISSUE TITLE
Items

### ISSUE THREAD

**Issue by batmonGamors** [Wynncraft/Issues#4156]
Hi i`ve been playing wynncraft for about a week now and have had a great time so far! But one day when i loged in, it said all my stats were the same but all my items were deleted. Instead, i have all wooden oak shears in my front bar. Anyway anyone can help me out?

**Comment by Odnod** [comment]
could you post a screenshot or elaborate on what is wrong?

**Comment by Pvpet** [comment]
he might've died without any soul points, anyways, I completed the quest a heart of iron part 2, identified the greviences of honor, was hype because of the bonus xp, but when I put them on I was kicked, and said "there has been an error...Try again" and I went back to my mage class, and they were gone, I still had my other leggings, but it was gone, and I can't get them back, could I get any help with this error?

**Comment by Dar-krusos** [comment]
I think maybe you took off your previous leggings, causing you to update your armor skin. This might have kicked you because of lag, so remember never to swap armor while holding another piece if you get kicked a lot.

**Comment by Pvpet** [comment]
I wasn't kicked before I put them on, I was kicked in the sense in that after the error message in chat, it had me choose my class again.

**Comment by Dar-krusos** [comment]
Yes, as I said, you tried changing armor and you were kicked as you did. Just don't swap armor; move them one at a time.

**Comment by ingmarv2** [comment]
.

**Comment by AmberTheFox** [comment]
All my items were deleted, I didn't do anything I was just playing and next time I looked at my screen everything was gone. I still have my lvls and everything but every item I had is gone ( emeralds, weapons armour .ect ) It shouldn't be because of my soul points because I was definitely sure that I had more than 2. I also checked the whole area to see if they were dropped or not (they would be if I died with no soul points) but nothing was there. I spawned about 5 seconds away (pretty much right next to where I was) so theres no way they could have depsawned in that amount of time. I had really good stuff like legendary and rare things. I spent ages getting this far, I play the server like, every day and it makes me a bit annoyed to just come on and have to start all over again. Is there a way that you could fix this or something and maybe get my items back, or at least some of my items back.
