### ISSUE TITLE
the shadow of the beast quest bug (can't be finished)

### ISSUE THREAD

**Issue by papione** [Wynncraft/Issues#4167]
in "the shadow of the beast quest" when we have the objective go deeper into the cave, we have to fight guardians that should give you wools and when we need 9 different wools to open a door. the yellow, the light blue, pink and green wools works perfectly but the 5 other wools cant be dropped.
plz help me if you cant fix that bug can you at least let the door open?

**Comment by TrashcanMan** [comment]
You don't actually need all 9 wools to open the door. I'm not going to spoil it here, but here's a hint: mouse over the wool in your inventory, the name tags should give you a clue. If you're still stuck go here: https://wiki.wynncraft.com/index.php?title=The_Shadow_of_the_Beast and scroll down to the Stage 11 spoilers.
Since this issue is now resolved, please hit the "Close Issue" button. Thanks!

**Comment by papione** [comment]
damn i'm so dumb i can't belive i missed that, sorry and thank you so much. now all is good i finished that quest thanks to you.
