### ISSUE TITLE
Unable to log into the server/into a world

### ISSUE THREAD

**Issue by GlitchedKnight** [Wynncraft/Issues#4204]
I've not been able to get on to the server for ages, this link is to a video of my repeated failures to get on: https://www.youtube.com/watch?v=JNh30qVbxuI

I'm not sure what causes it, but I really wanted to play again after my long hiatus from minecraft servers.  I've already reinstalled minecraft from scratch, there are no mods on, not even minecraft forge is installed, and I'm running 1.8.9.

**Comment by TrashcanMan** [comment]
I've had a similar thing before, usually it sorts itself out within a few hours/days.

**Comment by Moe-Ronickah** [comment]
If you have not played WynnCraft since Gavel came out, you should read the News, The Gavel Expansion Changelog, and the updated Rules, BEFORE you start playing again.

In any event, errors like this are usually the result of an error with the hosting server, and have nothing to do with WynnCraft.  How soon it gets fixed is nothing that anyone can predict.

If you're up and running, and back in WynnCraft, would you close this issue, please?  Thanks!
(I'm leaving it open for a couple of hours just in case it keeps happening, just to prevent a barrage of issues being posted.)

**Comment by GlitchedKnight** [comment]
I'm not up and running, and I've gotten the same issue for years- almost every time I log on

**Comment by Alexicon1** [comment]
Try the new MC launcher, clear all Wynn related files in your minecraft folder. Or uninstall and reinstall MC

**Comment by GlitchedKnight** [comment]
as I said in the initial post, I already uninstalled and reinstalled minecraft

**Comment by GlitchedKnight** [comment]
I'm giving up, it's fairly obvious that almost no one else has this issue.
