### ISSUE TITLE
Not regening al my health? as mage

### ISSUE THREAD

**Issue by ZzJarnozZ** [Wynncraft/Issues#4230]
I have been playing for 2 days now since the knew update but im not regening my health as a mage my max health is 2535 but it keeps going down by 7-9 every 2 sec i have tried healing my self but it then goes down again Here are some picks of my armor/health full iron
My helmet is not special
ChestPeace: http://prntscr.com/a6v9fm
Leggings: http://prntscr.com/a6v9t7
Boots: http://prntscr.com/a6v9xr
Wand: http://prntscr.com/a6va1s
health: http://prntscr.com/a6va9o
Hopefully someone can help me

**Comment by ingmarv2** [comment]
What accessory do u have?
Do u have one with - Health Regen ?

**Comment by DarkDemonDragon** [comment]
For one easy screenshot, just take a picture of your ID Stats which can be found in the compass GUI. You probably have a negative Health Regen if it happens consistently like that every 2 secs.

**Comment by ZzJarnozZ** [comment]
i found the mane regen it's -12 http://prntscr.com/a7ak92 :( how do i get rid of it

**Comment by DarkDemonDragon** [comment]
Look over your armor and see which armor is giving it. ALL of your stats comes from your gear, so quickly skim over all of your armor to see which is the source of the negative regen. After that it's your choice if you wish to keep the armor (You are a mage so it isn't too bad) or swap it out with something else. After that if your issue is resolved please close this. If you have any further questions related to the issue feel free to ask.

**Comment by Dar-krusos** [comment]
As @ingmarv2 said, check if your accessories give you negative health regen.

**Comment by Trixter313** [comment]
Your leggings specifically are giving you -16 health regen, so swapping those should fix it.
