### ISSUE TITLE
archer+button glitch

### ISSUE THREAD

**Issue by Ensho** [Wynncraft/Issues#4233]
hello I noticed if you shoot on buttons the arrow will stay and not disappear as normal. 
I found this not very bad as the arrows you got in inv disappear as soon as you shoot again 
altho just ago I shot at a button on a ship, and as the button got pressed by the arrow a piston next to the block the button was on went open and rekt the hull of the ship. Im not sure if this stays that way after a restart, so you might want to look at it. I put screenies with coordinates on this post. 
the arrows you shoot despawn after a certain amount of time, this isnt a problem. 
hope I helped, 
greetings Ensho
![2016-02-23_16 27 58](https://cloud.githubusercontent.com/assets/17433398/13257172/04d995e0-da4e-11e5-9f1f-aa540d116524.png)
![2016-02-23_16 27 49](https://cloud.githubusercontent.com/assets/17433398/13257175/0911b23c-da4e-11e5-85a1-a32c6c87bc50.png)

**Comment by Ensho** [comment]
here is 1 extra screenshot to show the arrow disappeared, I made it after posting this so the time is different sorry
![2016-02-23_16 54 49](https://cloud.githubusercontent.com/assets/17433398/13257219/3d58d66a-da4e-11e5-9c38-24c1313e13f2.png)

**Comment by Odnod** [comment]
Nah, when the server restarts this will be fixed.

**Comment by DarkDemonDragon** [comment]
This isn't that much of an issue. The server is VERY strict with arrows and manages them very well. All newly made arrows will despawn within 10-30 seconds no matter what. I tested this extensively. Since this is nearly impossible to exploit in anyway and already has a system that manages it made by the Admins, please close this as this is not really an issue.
