### ISSUE TITLE
Players are unable to join my guild. 

### ISSUE THREAD

**Issue by Geertforce** [Wynncraft/Issues#4245]
I started my own guild yesterday. So I invited some people. My friends where not online, but
this morning they were online, so I invited them. But when they tried to join the guild, they got
a message that they were not invited, although the saw my invitation. My guild can have 7 people, and there are 4 people in my guild now. How can they join?

**Comment by DarkDemonDragon** [comment]
Are you sure you can have 7 people? What level is your guild?

**Comment by Geertforce** [comment]
my guild lvl is 3

**Comment by Moe-Ronickah** [comment]
Is this still an active issue, or can you now get people in your guild?

**Comment by Arrowhawk5** [comment]
I cant join a guild either even though i was invited only 3 people in

**Comment by Arrowhawk5** [comment]
anyone?

**Comment by Verret001** [comment]
Can you provide screenshots?

**Comment by YunoFGasai** [comment]
did any o your members/you change your ign recently?
if you did can you do /guild list for me and tell me I any of your members show up twice?

**Comment by Arrowhawk5** [comment]
None of us changed our ign and I can provid screen shots, I will put them up in a day or two

**Comment by Villageacules** [comment]
30 day inactivity on thread, closed.

**Comment by Moe-Ronickah** [comment]
This is a generic message concerning guilds and guild issues:
Guild mechanics are slated to be re-written.  All issues involving guilds are on hold until guild mechanics are re-written, at which time ALL current guild issues will closed.  Current guild issues are being left open for reference purposes.

**Comment by Moe-Ronickah** [comment]
UPDATE:
This is a generic message concerning guilds and guild issues:
Guild mechanics are slated to be re-written.  All issues involving guilds will closed.  If you want to know if your guild issue has been reported already, please go back and do a search on "guilds".  From there, you will see all of the guild issues and you can check to see if your issue is known.
Only ONE current guild issue is being left open for reference purposes.  #3665
