### ISSUE TITLE
Skill points not working

### ISSUE THREAD

**Issue by ZzJarnozZ** [Wynncraft/Issues#4341]
So my friend has a problem when he wants to upgrade his defends skill his points will go down but the skill won't be upgraded i had the same bug before but it got fixed i don't know how. but on the other skills he spend his skill points on it just worked.
PS the bug also happend to me with defens skll

**Comment by Asa473** [comment]
can some 1 plz give my skill points back I am lvl 30 and they got reset ! how? 
idk plz give um back I had like 15 s , 13 d ,13 I ,15 d , I thin 14-15 a
plz can u give them back or give me 60 ponts back to upgrade my skillz again been as
I no longer have any! cuz it glitched and I lost them all

**Comment by ZzJarnozZ** [comment]
@Asa473 why did you comment that on my thing you can open up 1 yourself

**Comment by Moe-Ronickah** [comment]
First @ZzJarnozZ , your friend will have to post the issue himself, so that we can discuss it with him.  Second, we encourage multiple copies of the same issue to be posted on the same thread, as it makes tracking issues much easier.  In fact, we close Duplicates and refer them to the original post of the issue.

@Asa473, when you logged off, as you wrote your description 12 hours ago, have you logged back on?  Is the issue still present?

**Comment by ZzJarnozZ** [comment]
@Moe-Ronickah It got fixed some how so im gonna close this one
