### ISSUE TITLE
weird bow glitch

### ISSUE THREAD

**Issue by RedNightDragon** [Wynncraft/Issues#4405]
With Olux's Prized Bow (the one you get from trading in the bigfoot thing) whenever I try and open a chest or door or push a button or anything of that sort it says "You don't have permission for that area" but if I use any other bow or items it seems to work. so far. I was just wondering if think could be fixed.

**Comment by Odnod** [comment]
It probably has to do with whatever kind of item Olux's Prized Bow is under the texture.

**Comment by RedNightDragon** [comment]
I think it is a wood slab.

**Comment by Shadoweagle5098** [comment]
i actually made a thread on this. Odnod and Red are correct. the game thinks you're trying to place the slab. this happens for every textured bow. this also happens if you shoot at the ground or anywhere it'd be possible to place a block. so if you ever fight a monster in a cave.... be careful, the notification will flood your chat xD

**Comment by RedNightDragon** [comment]
lol I have found that out the hard way. but could the creators just use a different item or something? did they really run out?

**Comment by DarkDemonDragon** [comment]
Well they could use another item but it would take a LOT of effort to convert. Before this didn't happen as the server would stop you from placing a block down without giving you the red text. After an update to fix spells this happened as a side thing. It's not too bad as you don't get prevented from attacking or using a spell and you can just open doors/chests with your hand if necessary.

**Comment by RedNightDragon** [comment]
ok. thanks
