### ISSUE TITLE
Items dropped and lost

### ISSUE THREAD

**Issue by MonkeyPlayzMC** [Wynncraft/Issues#4412]
I had 11 souls the next day I come on 11 souls MY ITEMS ARE GONE AND I HAVE TO START OVER! IT MADE ME QUIT SO HARD I ALMOST CRACKED MY COMPUTER!!!!! PLZ FIX THIS NOW!!!
So basically what happened is I died for no reason when I was offline and my souls went under 1 and I dropped my items it despawned and I joined saw nothing quit went on mineplex.

**Comment by MonkeyPlayzMC** [comment]
Username : MonkeyPlayzMC_

**Comment by MonkeyPlayzMC** [comment]
FIX IT AND GIVE MY ITEMS BACK PLZ

**Comment by Odnod** [comment]
1. Could you please state in more detail what happened?
2. Wynncraft has a strict no refund policy, so you will have to farm your items back up or obtain them from other players.
3. Wynncraft has not existed for 7 years.
4. Please do not use so many caps next time, it makes your report somewhat annoying to read.

**Comment by MonkeyPlayzMC** [comment]
K I edited my comment

**Comment by DarkDemonDragon** [comment]
@MonkeyPlayzMC when you logged on the next day what was said in the chat? Here are some crucial details to mention:
Was there any red text?
How many Soul Points did the server say you recovered?

If you cannot remember do you remember exactly what day this happened or at least give or take a couple days? Minecraft saves all your chat logs (a recording of everything in chat) in a folder, so we could use that to see what the server said to you in chat when you logged in that day. If you need some directions to access the chat logs let me know if you're using PC or Mac so I'll know what directions to give you.

**Comment by MonkeyPlayzMC** [comment]
PC

On Mon, Mar 7, 2016 at 4:45 AM, DarkDemonDragon <notifications@github.com>
wrote:

> @MonkeyPlayzMC <https://github.com/MonkeyPlayzMC> when you logged on the
> next day what was said in the chat? Here are some crucial details to
> mention:
> Was there any red text?
> How many Soul Points did the server say you recovered?
>
> If you cannot remember do you remember exactly what day this happened or
> at least give or take a couple days? Minecraft saves all your chat logs (a
> recording of everything in chat) in a folder, so we could use that to see
> what the server said to you in chat when you logged in that day. If you
> need some directions to access the chat logs let me know if you're using PC
> or Mac so I'll know what directions to give you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Wynncraft/Issues/issues/4412#issuecomment-193234868>.
>



-- 
Regards,
Aryan .N

**Comment by DarkDemonDragon** [comment]
Click the Windows icon and find the search bar.
In the search bar type %Appdata% and press Enter. _This should open the Roaming Folder._
Next, open up ".minecraft"
Open up "logs" _This may take some time to load depending on how many logs and how fast your computer is_
Now you should see a bunch of .log files. They are all labelled by date, so just find the one when this happened. Since you said you quit after the bug happened just start around about 6 days ago or later (2016-03-02-1) and work you way until you find the last time you were on Wynncraft. 

Once you find it just drag the file into the box below and it'll attach. (You'll have to do this on Github, not by e-mail)

**Comment by MonkeyPlayzMC** [comment]
[2016-03-02-2.txt](https://github.com/Wynncraft/Issues/files/164592/2016-03-02-2.txt)

**Comment by MonkeyPlayzMC** [comment]
I changed it to .txt it was .log

**Comment by DarkDemonDragon** [comment]
Okay one of the things I suspected was correct:
[16:39:23] [Client thread/INFO]: [CHAT] [You have received 10 soul points while you were offline]
If you had 11 SP the day before this then this is fatal as dying makes people have 1 SP, so recovering 10 SP like this means that somehow you fully died before 03-02-2. Do you mind sending over 2016-03-02-1? Perhaps you thought you logged out or disconnected, but instead your character was in a hostile environment while AFK and died completely which may be seen in 2016-03-02-1.

**Comment by MonkeyPlayzMC** [comment]
[2016-03-02-1.log.gz](https://github.com/Wynncraft/Issues/files/170789/2016-03-02-1.log.gz)

**Comment by Trixter313** [comment]
The only scenario that I can think of is that your account was hacked and someone else logged on as you and killed your player multiple times.

I'd suggest you change your Minecraft password and the associated email password and also make sure no one who might have access to any computer you've ever logged into Minecraft with did this.

Other than that there's nothing we can really do due to the mentioned no refunds rule. I hope this doesn't happen to you again!

**Comment by DarkDemonDragon** [comment]
I think he just didn't log out properly.
