### ISSUE TITLE
Craftmas Chaos Quest Can't Finish QUest

### ISSUE THREAD

**Issue by CubixGamma** [Wynncraft/Issues#4448]
When I try to turn in the Craftmas Chaos quest I can't report to Santa to finish it. Is it a glitch with his skin or something?

**Comment by Trixter313** [comment]
Could you explain in a little more detail? What do you mean by you can't report? What does Santa say? Also, try doing it on another world to see if that helps at all. Thanks!

**Comment by Moe-Ronickah** [comment]
Santa's skin has had a bug in it in the resource pack, that is being fixed at this time.  I don't see how the skin bug should affect your interaction with Santa and his dialogue.  Please come back, before May 10th, if this issue was not resolved, otherwise, this issue will be closed on or anytime after May 10th.  Thanks.
