### ISSUE TITLE
SOMETHING BAD HAPPENED MOD PLEASE! (WHITE HORSE)

### ISSUE THREAD

**Issue by crazy0o07** [Wynncraft/Issues#4494]
I was breeding horses and i had my main horse on my bar! when i was breeding i had the brown horses that i bought in the inventory when i was done i only got a black one! so i put that horse also in my bar. I then got my white horse out rode it to detals and then got off it, as i got off it the game GLITCHED LIKE ALWAYS for me, screen got bad, and when i got it working again i saw that my white horse got replaced with the one next to it the BLACK ONE!! I had the white horse as 24/40, I DONT KNOW WHAT TO DO! I really need help!! Please any mod or anyone with power to solve this please do! Before you say that i might have breeder it NO I DIDNT 100% I DIDNT I RODE IT! and by that time had my white horse and another black one next to it and then a brown one in my inventory! Please please fix this!

Thank you,

**Comment by DarkDemonDragon** [comment]
What do you mean replaced?

**Comment by BlahBlah161616** [comment]
So your horse randomly turned into a black one?

**Comment by Moe-Ronickah** [comment]
@crazy0o07 , if your game is glitching as often as you say it is, then you need to re-install Minecraft.

WynnCraft has a strict no-refunds policy, so there is nothing, really, that we can do to help you to replace your lost horse.  I do have one other suggestion for you; when you are breeding horses, always put your best horse(s) into your enderchest, so that there is no way to accidentally breed it.
