### ISSUE TITLE
Lost Soles quest bug

### ISSUE THREAD

**Issue by Endertricity** [Wynncraft/Issues#4555]
I started Lost Soles today, went into the house to talk to to Grandon. Then I did the pressure plate on the guy's nose. After that, the quest started giving me the wrong lines. For example, my book says stand on the stone in the corner, and Grandon says throw behind themap, and I've already done both.

**Comment by TrashcanMan** [comment]
Can you continue with the quest?

**Comment by Endertricity** [comment]
no, no I can not.

**Comment by Moe-Ronickah** [comment]
@Endertricity , you can read and follow the Wiki description, here, https://wiki.wynncraft.com/index.php?title=Lost_Soles .  You can also try following along with any of the tutorials and descriptions about the quest on youtube.  I'll bet that you either missed a step, or you got caught in a temporary glitch.  Let us know what happens, so that we can continue to help you, if we need to.

**Comment by Endertricity** [comment]
I was using the wiki as a guide during the quest. I probably missed a step, but now I can't progress in any way.

**Comment by Endertricity** [comment]
Fixed it!
