### ISSUE TITLE
Gavel Update...

### ISSUE THREAD

**Issue by Blackyyyyyy** [Wynncraft/Issues#4575]
I had to buy a Skill Point reset scroll because of the Gavel Update. I used a legendary bow and first time i joined Wynncraft after the update i was still able to use it so i used my skillpoints how i needed to. But then they updatet again and suddenly i needed 20 Dexterity to use my bow. I had 0 because its totally trash to skill on a luck thing. After i complained about how silly this update was and that my legendary chestplate ist worse than every other chestplate in this planet just because I'm walking slow af, I bought for the half of all my hardly framed emeralds a skill point reset scroll. I used it and saw that it gave me 92 skill points allthought i am lvl 47 so I should get 94 skill points! So thats the first thing. Then I used my skill points again and some lags later i suddenly have 83 skill points used and 11 missing! Which is VERY fatal because these skill points would be lost FOREVER! So where are my skill points?! And who thought it is a good idea to add these minimum amount off a skill level to use certain gear?! Please help!

**Comment by Trixter313** [comment]
For the first part, 47x2=92 so that seems correct. For the second part, certain armors add or subtract from skills so make sure that all of your armor and accessories are unequipped when checking your skills. If your skills are being affected, it will say when you hover over the skill. Check all of your armor to see if it subtracts or adds skill points.

**Comment by wizardcheetah55** [comment]
This Skill Points issue keeps coming back for lots of people. Isn't there a
way Wynncraft can post something so that we can all learn about what causes
gains and loss; what the numbers mean on the screen; etc? It would help a
lot.

Stan Emert, Rainmakers.TV
www.rainmakers.tv
Seattle. 206-250-9839
Los Angeles. 424-272-6839
Skype: stan.emert

**Comment by Blackyyyyyy** [comment]
Well i tried without armor or weapons but it doesnt change and Trixter 47+47=94 :/ 7+7=14 not 12 but thank you for the help. a mod fixed my problem by setting my stats or something :)

**Comment by Trixter313** [comment]
Glad to hear and you always have 2 less skill points than double your level so 92 sounds about right because you start at level 1, not 0.
