### ISSUE TITLE
Using guild attack just as a guild captures the territory. 

### ISSUE THREAD

**Issue by Powerwan** [Wynncraft/Issues#4580]
# Delete this line if you've searched for a duplicate issue first

Hello I am powerwan today i have noticed that a bug has occurred a guild area got taken over but then a few seconds later the guild then said that my guild has retook the area

**Comment by Powerwan** [comment]
oh yeah and here is the proof http://prntscr.com/agpgal

**Comment by Creecreeprs** [comment]
I haved this bug too, he is here before the Gavel update and I think we can do nothing :/ 

PS: Wtf, did you play without the ressource pack ?

**Comment by thecoolkogut4** [comment]
this happens when another guild does /guild attack right when you win the land (they attack before you get a chance to buy mobs, so they insta take it from you)
a temporary solution for this would be to buy 1 mob right after you win the attack, then buy 999 after. (or 10 right away then 990 after etc...)

**Comment by Moe-Ronickah** [comment]
This is a generic message concerning guilds and guild issues:
Guild mechanics are slated to be re-written.  All issues involving guilds are on hold until guild mechanics are re-written, at which time ALL current guild issues will closed.  Current guild issues are being left open for reference purposes.

**Comment by Moe-Ronickah** [comment]
UPDATE:
This is a generic message concerning guilds and guild issues:
Guild mechanics are slated to be re-written.  All issues involving guilds will closed.  If you want to know if your guild issue has been reported already, please go back and do a search on "guilds".  From there, you will see all of the guild issues and you can check to see if your issue is known.
Only ONE current guild issue is being left open for reference purposes.  #3665
