### ISSUE TITLE
Lost my sage when i got out of a portal

### ISSUE THREAD

**Issue by TheSkaterBoy** [Wynncraft/Issues#4596]
# Delete this line if you've searched for a duplicate issue first
Okay as first i was doing the Green Skinned Trouble quest. I nearly finished it. I was killing the Orc leader Gregg`r. When i killed him you need to go through the portal. Before i got in the portal i still had my sage but when i came out i diddn't had it any more. So i was thinking like oh shit i dropped it. So i got all the way back to look for it but it wassn't there. I searched my hole inventory and the hole ground. But i couldn't find it. It just was away. Idk what to do so i desided to repport it. 

I hope you can give me back my sage ;( i also hope this bug will be fixed soon. 
IGN: Team_O
(I lost the wand on my mage account of lvl 48)
P.S don't look at my english i did my best to type it good ;)

**Comment by Trixter313** [comment]
Unfortunately Wynncraft has a strict no refunds policy so there's not anything we can do about the lost wand.

There is currently an issue where if a chunk is unloaded because there aren't any players nearby, items will instantly disappear. It is very likely this is what happened to your wand.

In an effort to prevent this from happening again, I'd suggest changing the drop hotkey to something that you are less likely to hit on accident.

The issue is https://github.com/Wynncraft/Issues/issues/3954 if you'd like to stay updated on the status of the issue.

Hopefully this information helps!
