### ISSUE TITLE
I have been in this guild for 1 yr. now

### ISSUE THREAD

**Issue by RockyPlayzMC** [Wynncraft/Issues#4624]
Can an administrator come on or something I have been in my guild for one year now and I can't leave because they don't play. Please I beg. Username: RockyPlayzMC, Guild: Frontiersmen
Please fix this or kick me from this guild

**Comment by TrashcanMan** [comment]
Do the commands not work?

**Comment by RockyPlayzMC** [comment]
No it doesn't it just takes my souls

**Comment by Moe-Ronickah** [comment]
No administrator, as of yet, has taken the time that it would take to fix all of the people with this same issue, due to other issues related to it.  Guilds are, and have been for a long while, bugged.  Until the guild update comes out, don't expect this to change, and no, none of us know when the update will be ready.
