### ISSUE TITLE
Cannot fight CoW for ToL

### ISSUE THREAD

**Issue by Endeh** [Wynncraft/Issues#4634]
I am wearing the right helmet to enter and fight corrupter of worlds, however, it still will not let me enter.
https://gyazo.com/99a8432366fa5959fffd121585314c05
https://gyazo.com/58ad051c45cbe3176c53f4d1cc116a76
https://gyazo.com/cd24a6ab636d48ebcea6296a131feb0e

**Comment by Odnod** [comment]
Why did you delete the old one and post a new one?

**Comment by Endeh** [comment]
For some reason I couldn't comment

**Comment by DarkDemonDragon** [comment]
@Endeh can you go into the cave? I think you accidentally went to fast to the hole. There's a point between the cave entrance and the hole. When you pass over it a dialogue will appear. However, if you go too faster say on a white horse, insane walk speed, or you teleport/ skip over the point then the server doesn't register your process. Try walking from the Cave Entrance to the hole on the path again. If a dialogue pops up then that means you accidentally missed it. This is usually the cause of most quest progression errors since many people rush to finish quests and pass these crucial points. They finally fix this in future quests by forcing you backwards if you skip over a part, but with most quest you have to be careful to make sure you feet is on the path and not to rush through too fast.

**Comment by Endeh** [comment]
@DarkDemonDragon Yes! I have teleported every time over the water, this must be why, thank you!

**Comment by DarkDemonDragon** [comment]
No problem! Glad I could help :)
