### ISSUE TITLE
Nagas

### ISSUE THREAD

**Issue by BasicallyNothing** [Wynncraft/Issues#4649]
The word Naga kinda looks like the "N Word". People may find that offensive. I accidentally msg'd my friend and said: "Swamp *****", instead of "Swamp Naga". I was wondering if you could change the name of them just a little.

Thanks.

- Nothing.

**Comment by Odnod** [comment]
I feel like it is kind of a stretch to connect these two terms, and I have no idea how you managed to accidentally type that word instead of Naga (which is an actual creature/symbol in certain religions as well as a race commonly found in fantasy games. I honestly don't see why the name would need to be changed.

**Comment by Trixter313** [comment]
This isn't an issue, I suggest you post this in the suggestions area on the forums instead. Thanks!
