### ISSUE TITLE
every time i die

### ISSUE THREAD

**Issue by picachuthefirst1** [Wynncraft/Issues#4680]
every time i die in wynncraft it kicks me for flying and then when im at hub and its glitches with my player going up and down so i have to disconnect and reconnect and it is just annoying can you tire anf fix this thanks

**Comment by picachuthefirst1** [comment]
and no i cant move when i glitch up and down

**Comment by Moe-Ronickah** [comment]
The issue with you "going up and down" is a MC mechanic, so, depending on what class you are playing, because you are stuck there by MC game rules, use whatever spell you have to move, be it Escape, Teleport, Charge, or Vanish.  This always works for me.  As to why you keep landing in the same "bad" spot, I have neither idea nor suggestion.

**Comment by Verret001** [comment]
No reply in more than two days; If this issue persists repost with a link to this thread.
