### ISSUE TITLE
Shattered Minds will not progress

### ISSUE THREAD

**Issue by Td193616** [Wynncraft/Issues#4691]
I am working on the quest Shattered minds and iv gotten to a point where i think that my quest book glitched out and wont progress.its stage 7 where you go and find the village and talk to likeru? and she tell you to go find the white rabbit,but my quest book did not update when i enter the village but i was still able to talk to her. is the a way i can get my quest book fix or restart the quest?

igm TD19

Here is a link to a video to here explain the proble better
https://youtu.be/qdds0t4Xooo

**Comment by Td193616** [comment]
Igm TD19

**Comment by Odnod** [comment]
1. I'm pretty sure this is happening because you do not have the bluecap mushrooms that I am fairly certain you need in order to progress here.

2. If you do have them (or if you don't, for that matter) Try going back through the quest (make very sure that you have the mushrooms) as sometimes you can miss areas that update the questbook by using transportation spells.

**Comment by Td193616** [comment]
Well i have the mushroom and i didn't miss it when i first got to the next part of the quest,is it possible to just restart the quest?

**Comment by Trixter313** [comment]
There is currently no way for players to restart a quest.

Have you tried the command /fixquests ? It might return a vital item to continue the quest that for some reason you never got.

**Comment by Td193616** [comment]
no that did not work,it just gave me items from quests i did not need

**Comment by Odnod** [comment]
Type /kill and run back through the whole quest.

**Comment by Td193616** [comment]
iv tried that like 10 times and it dose not work
