### ISSUE TITLE
Nemract Mansion Glitch

### ISSUE THREAD

**Issue by EyelessTenshi** [Wynncraft/Issues#4734]
Alright so. Id like to report this glitch with the Mansion Quest. So I was on my way, Looking for the guy you needed to find for his friend. I hit the stone button to open something ( I wasnt sure, Ive never done this quest ), and all the sudden I see this. http://prntscr.com/an7yp6

Basically I stopped near some pistons because I got stuck, and then it says "Quest Completed" even though I didnt find him. Has this happened to anyone else? Anyways, I hope this bug is fixed because its unfair to others who dont get to experience the whole puzzle like myself.

**Comment by Moe-Ronickah** [comment]
I think that you hesitated and took too long to go through the passage, getting stuck in the passage.  Why the game said that the quest was completed, I have no idea.

**Comment by EyelessTenshi** [comment]
So is it bugged?

**Comment by Odnod** [comment]
Right clicking in the general vicinity of a quest npc causes you to talk to that npc since gavel has been out. I assume it is because there used to be some amount of difficulty talking to "baby" quest npcs. My guess is that you were under/near the npc that completes the quest and you right-clicked causing the text to run and the quest to finish.

**Comment by BlueThunder25** [comment]
Please Close issue if this has been solved
