### ISSUE TITLE
Connection Issue

### ISSUE THREAD

**Issue by ethanscheiber** [Wynncraft/Issues#4758]
https://gyazo.com/32e2793f16ab3534976bb99ff6641eec Why is this happening when I try to log on?

**Comment by Odnod** [comment]
Try changing your ip from 'play.wynncraft.com' to 'play.wynncraft.net' or 'play.wynncraft.org'

**Comment by Moe-Ronickah** [comment]
No matter what you do, it is a server-side error with the host server, and it USUALLY resolves itself withing about 5 minutes.  (At one point in the recent past, it was a conflict with Forge, however, that was fixed in a Forge update.)

I'm going to close this, as it really is not a WynnCraft related issue.
