### ISSUE TITLE
Quests problems

### ISSUE THREAD

**Issue by Elmaric** [Wynncraft/Issues#4789]
Hello,
My name is Elmaric, I play Wynncraft with the assassin class at level 14, and every time I right-click a Quest NPC with the good items he tell me what items I must bring him. I tried with 2~3 quests and every time it's the same ? Please help me ! 

Elmaric

**Comment by Trixter313** [comment]
You need to go into detail with each quest so we can help you. Thanks!

**Comment by Elmaric** [comment]
Hello again,
It's a few days I haven't tried but it's still not working. And in fact it's only happening in two quests : Thieving rodents and Underwater.
Goodbye !

**Comment by Trixter313** [comment]
We need details on what specifically isn't working and where you are in the quest. It's most likely just something you're forgetting or doing wrong.

**Comment by Elmaric** [comment]
When I give him the Items (3 Pigmen meat and 1 empty bottle) he says: Bring me 3 pigmen meat and 1 empty bottle. Even if I have the right items. That's all

**Comment by Trixter313** [comment]
How long ago and where did you get the items? If the items are kind of old, you might have to get new ones because they might have been updated and the old aren't accepted. Also, you should get the meat from the pigman ravines. There are other places to get it but not all of them work with this quest. The ravines are guaranteed to work. Let me know if any if this helps. Thanks!

**Comment by Moe-Ronickah** [comment]
There are two different Pigmen meat in the game, one is Pigmen's Meat, and one is Pigmen Meat.  It's a pain in the backside, but you need the right pigmen meat.  Try the pigmen meat from the pigmen mini-dungeon just outside of Ragni, on the road to Detlas.
