### ISSUE TITLE
CowFusion

### ISSUE THREAD

**Issue by shinyafro** [Wynncraft/Issues#4805]
So i was doing cowfusion when i died due to being in xp gear, came back through all the portals, the cow barn was already open, then i went into the tunnel which was exploded and was stuck in the cut scene room and i saw the black portal, so i managed to get out of the barrier by using my ability to ride my pet and go into the black portal but it didn't work so i tried getting back into the barrier by doing as previously said and fell down into the command block area and then onto the NPC village below. Anyhow, i had to /kill and i had the same issue, trapped in the cutscene room. Now, to claify, the cutscene did not play. I ended up fixing the issue by finding a server where the exploder 9001 was not already exploded and was able to continue normally like so.

**Comment by Odnod** [comment]
Yeah, the cutscene can only play once per server uptime per person as far as I know, just switch servers as you did to trigger is as you normally would.

This issue happens (I believe) because of limitations of redstone and command block functionality and I don't think it can really be fixed as a result of that.

**Comment by shinyafro** [comment]
welp, then make a place to leave the cutscene, most of the cutscenes are boring and take too long anyway so a skip cutscene would be good.

**Comment by Trixter313** [comment]
You can make a post [here](https://forums.wynncraft.com/forums/general-suggestions.69/) for suggestions. Thanks!
