### ISSUE TITLE
/toggle autojoin and /class bug / glitch

### ISSUE THREAD

**Issue by Caladrion** [Wynncraft/Issues#4864]
so one day i toggled autojoin and now when i log in, i glitch through the floor and cant use commands. also, before i did that i usedd /class and it said i cant use commands here and i have to log out to do any commands. but im more concerned about the /toggle auto join. please respond ive been waiting for a week already for someone on the forums to respond.

**Comment by Odnod** [comment]
If it is putting you into the void, you may be experiencing a rare bug that has sometimes been fixed in the past by uninstalling and reinstalling Minecraft.

**Comment by Shadoweagle5098** [comment]
im not sure if this is related, but I got a mage to nemract to use as extra storage. Sometimes when i log on my mage will be in this little enclosed space underground too small to use teleport scrolls, so ll i could do is /kill. It used to be really common, but now it rarely happens.

**Comment by XavierEXE** [comment]
@Caladrion join the nether from the lobby and do /toggle autojoin there, then do /hub and join a normal world, the problem should fix itself.

@Shadoweagle5098 This issue seems to be fixed, Nemract Bank was being loaded as an invalid zone so the server was putting your class in the class selection box, but now it doesn't happen anymore.
