### ISSUE TITLE
Teleport "Glitch"

### ISSUE THREAD

**Issue by iruleyousuck** [Wynncraft/Issues#4878]
When I was beating up Jupiter I teleported to get away then I somehow teleported through the wall. I was able to replicate it multiple times, just trolling Jupiter. When looking at about a 45 degree angle and standing a few blocks away you can teleport straight through diagonal walls. (If needed I also have max teleport skill) I wish this was a "feature"

**Comment by YunoFGasai** [comment]
that is a known bug but sadly its a vanilla mechanic (you can use ender pearls to go through block edges). 
there is also no way I know of to stop the players from doing this.
due to this glitch there a few places on the map available only to mages (the mage library, 4 halls, etc) so please don't use that glitch too much.

**Comment by iruleyousuck** [comment]
Yeah I've already gotten banned for using mage's "abilities" so I plan on not using it at all.

**Comment by YunoFGasai** [comment]
Please close this issue, it's a vanilla bug.
