### ISSUE TITLE
Guild Commands

### ISSUE THREAD

**Issue by ghost** [Wynncraft/Issues#4900]
Using the command /guild info and leaderboard shows _nothing..._ I thought this was bugged but it has been like this for a long time. Is anyone else experiencing this issue? Very annoying.

**Comment by YunoFGasai** [comment]
I'm pretty sure they removed those commands temporarily because guilds are so glitched right now

**Comment by crazydud24** [comment]
i have the same issue but what is weird is when i made the guild it didnt work the first time, tried again and it showed it then it hasn't worked since. this is the second guild i made because the first one gave me the wrong guild info with /guild stat

**Comment by thecoolkogut4** [comment]
as yuno said, they temporarily removed the command because of how glitchy it was when it was enabled. 
as for crazy, it most likely showed you the guild "nobodys" stats which is another reason why they removed it.

**Comment by ColinRioux** [comment]
`/guild info` has been removed, and typing it will list guild commands. 
`/guild leaderboard` is **still bugged**.

**Comment by LordHelmchen98** [comment]
@ColinRioux I dont know what /guild info showed before but there is /guild stats right now. What was the difference? Also what do you mean by /guild leaderboard is bugged? I mean it is working it just isn't updated. It shows the leaderboard sorted by level and xp of the guild not like on the forums where it is sorted by the amount of territories.

**Comment by thecoolkogut4** [comment]
acctualy, guild info, leader board, and stats are working. this started working about 2 3 weeks ago. they are working as far as I know. the xp gets updated in stats, level gets updated in leader board

**Comment by ColinRioux** [comment]
To be fair, I probably should've used the term not updated instead of bugged for `/guild leaderboard`. In terms of `/guild info`, when I typed it in last night, it just listed guild commands (which didn't seem right), instead it should list guild information. I'll recheck tonight, but we can't just eliminate the fact that it's not working if two it works for DarkSoul and not for me.

**Comment by LordHelmchen98** [comment]
Well as I said above I don't know what you think it should show when you type /guild leaderboard, but If you do /guild stats it shows you the guildname, the owner, the xp that your guild currently has, the rank and the amount of members.

**Comment by Moe-Ronickah** [comment]
/guild anything, anything and everything to do with guilds, will probably remain bugged until guilds get reworked.

**Comment by Moe-Ronickah** [comment]
This is a generic message concerning guilds and guild issues:
Guild mechanics are slated to be re-written.  All issues involving guilds are on hold until guild mechanics are re-written, at which time ALL current guild issues will closed.  Current guild issues are being left open for reference purposes.

**Comment by Moe-Ronickah** [comment]
UPDATE:
This is a generic message concerning guilds and guild issues:
Guild mechanics are slated to be re-written.  All issues involving guilds will closed.  If you want to know if your guild issue has been reported already, please go back and do a search on "guilds".  From there, you will see all of the guild issues and you can check to see if your issue is known.
Only ONE current guild issue is being left open for reference purposes.  #3665
