### ISSUE TITLE
Horses

### ISSUE THREAD

**Issue by Rafcin** [Wynncraft/Issues#4907]
When you ride a horse for X amount of time, it shows you are riding fine, but the game cuts out and when you get off you and the horse tp to a block you can go through like a fence even though you thought you moved

**Comment by Odnod** [comment]
This is a known glitch and is based off of how Minecraft handles horses. Because of this, there isn't really any fix the wouldn't get in the way of normal usage of horses.

On a side note, getting into areas that you shouldn't be (passing through walls, etc) is a bannable offense, so it may be best to just ignore it.

**Comment by Odnod** [comment]
Could you give a little more context? Are you just passing through blocks or are you appearing a distance away from your horse when you diamoumt?

**Comment by Rafcin** [comment]
No, not through walls, just just you stop hearing the sound that its moving
and you get off and its ohh iv been moving but really i'm just walking into
a wall.

**Comment by Rafcin** [comment]
distance away

**Comment by YunoFGasai** [comment]
this also happened to me a couple of times (only pre gavel) I think this has to do with your internet connection being unstable.

**Comment by YunoFGasai** [comment]
Its not a horse only issue,  it effects boats too.

**Comment by YunoFGasai** [comment]
Sorry there is an older issue #4809

**Comment by Trixter313** [comment]
Please follow the original thread, linked above. Thanks!
