### ISSUE TITLE
Quest wynnexcavation site b extremely bugged out.

### ISSUE THREAD

**Issue by RazzorWind** [Wynncraft/Issues#4950]
Hello. Today I was doing the wynnexcavation site b  quest. After I exit the cave, I spawn out in the ground. I had to continually select the same class i was using to jump up 1 block, and after that, i can't report and finish the quest because the npc doesn't say anything new. I did however throw out a duped quest item that i used to activate the quest in the first place, but i thought it was a glitch for me to get 2 of them.

**Comment by Odnod** [comment]
Ok so it seems as though you have a lot of issues here.
1. If you are ever stuck in the ground and have more than 2 soul points, just type /kill to escape.
2. Not sure if this is the issue here, but you need to bring the quest npc one of the purple crystals from the final room of the caves.
3. The quest Wynnexcavation Site A should give you 2 yellow crystal shard Quest Items (maybe 3?). Anyway, the duplicate shards are needed for the later Wynnexcavation quests. If you are missing one, just delete the remaining one by using your bank to throw it out with a full inventory. One you have done this, type /fixquests and everything should be in order.

**Comment by RazzorWind** [comment]
Okay, that seemed to give me the shards back but the Npc still isn't continuing my quest.

**Comment by Odnod** [comment]
Try running back through the quest. When you leave the room with the crystal drops it should put you in a small coal room with a button. I am fairly certain being in this room updates your quest book and since you were stuck in the ceiling before you didn't actually progress the quest.

**Comment by RazzorWind** [comment]
Ohhhh okay. I just did that before I read your message and I indeed missed the Pure Crystal shards. I was referring to the Yellow Crystal Shard earlier. Also the quest worked now. Thanks! im closing this issue.
