### ISSUE TITLE
Died and back to the tutorial

### ISSUE THREAD

**Issue by 31Yoshi31** [Wynncraft/Issues#4952]
Hey i was doing the Shattered Minds Quest but at the big fall i teleported and i died. And then i respawned at the beginning of wynncraft in the tutorial. I was able to get out with scrolls but it would be better for the future to fix this bug
![2016-05-05_19 14 05](https://cloud.githubusercontent.com/assets/11230645/15050777/efa96a20-12f5-11e6-84f5-8e72c9624837.png)
![2016-05-05_19 13 54](https://cloud.githubusercontent.com/assets/11230645/15050784/f5217d62-12f5-11e6-81d2-f463bd1db178.png)

**Comment by Odnod** [comment]
This can't really be fixed to easily. The reason why you respawned at the tutorial is because the majority of Shattered Minds happens in locations far away from the map. The closest respawn point to whatever the coordinates of at the very least that portion of the quest is the tutorial area. The reason why this can't be so easily fixed is because it would require a lot of worldedit and would generally be a nuisance to update the quest's information to account for the new coordinates of nearly everything.

**Comment by 31Yoshi31** [comment]
Hm maybe you can solve it like this: If you Start a Quest, the system gives you a Tag like 'in a quest' and in the case of a death it teleports you to the starting NPC or where the quest book last updated

**Comment by DarkDemonDragon** [comment]
It'd be difficult. What if during the quest a friend tells you he NEEDS some help with a dungeon or someone you promised to meet for a trade comes online. You then use a teleport scroll and leave the quest area, but you're still tagged. The best solution seems to be to not die :/

**Comment by Moe-Ronickah** [comment]
This is an effect of placing quest areas outside of the main map.  You will respawn in the closest city..
