### ISSUE TITLE
Can't join a Wynncraft server

### ISSUE THREAD

**Issue by mcmasterchief100** [Wynncraft/Issues#5049]
OK so about a month ago me and my friend (PowerSourceMa) got a glitch it is still happening we tried changing the ip from play.wynncraft.net to play.wynncraft.org it didn't work but see what happened is we had VIP it got taken away from both of us but we are still able to go to the lobby but when we try to join a world we fall through the world and we can't choose a class please help we are really made that we spent money on the server and then we can't even play it.

**Comment by TimThePvpMaster** [comment]
You have to enable the recourse pack.

**Comment by mcmasterchief100** [comment]
i always had it open i played for 2 years (only 52 hours in it but)

**Comment by YunoFGasai** [comment]
could you elaborate a bit more about the glitch?

**Comment by mcmasterchief100** [comment]
You join the game and you select the world you wanna play on but instead of getting the charector selection screen you fall thourgh the worl into the void and you can't use any commands or see whos on the server

**Comment by mcmasterchief100** [comment]
And you stay stuck in that void untill you leave the gamr

**Comment by mcmasterchief100** [comment]
*gane

**Comment by mcmasterchief100** [comment]
*GAME

**Comment by mcmasterchief100** [comment]
i can't type

**Comment by Odnod** [comment]
A few things may be the problem. This bug has popped up from time to time in the past with varying ways of fixing it. Try any and/or all of the following.

-uninstall and reinstall Minecraft.
-restart your router.
-enable server resource packs/reset them.

**Comment by Moe-Ronickah** [comment]
@mcmasterchief100 , FIRST, try Odnod's suggestions, they generally work.  Second, there is a little pencil icon on the top right of the comment boxes; it's the EDIT icon.  :)

**Comment by mcmasterchief100** [comment]
Oh ty moe but odnod i tried that it didn't work

**Comment by mcmasterchief100** [comment]
So yea i tried all 3 none worked

**Comment by Trixter313** [comment]
About your VIP status, I'd suggest emailing support@wynncraft.com stating that you purchased VIP and it went away and giving them your Minecraft username. They will ask for a number/receipt that proves your purchase did happen. If you show up as non-VIP in the system and they can confirm that you purchased it, they will most likely fix it for you.

**Comment by mcmasterchief100** [comment]
Well in game its messed up but when i go to the wynncraft stats and search my name it says i have vip but when im in game it doesn't

**Comment by Villageacules** [comment]
@mcmasterchief100 I can talk about the higher staff about getting your character reset, it seems this is the only solution to your problem as it typically works for these very weird bugs. If you want me to reset your player (this may take a few days) then message me on the forums @Villageacules and I'll try to get it  reset when I can and also get your VIP rank back if I can.

**Comment by Moe-Ronickah** [comment]
@Villageacules , did this ever get fixed?

**Comment by Moe-Ronickah** [comment]
This is a generic message, to everyone affected by these issues.
I've discussed this with the admins, and it turns out, after a lot of investigation, that the 
problem lies within the saved data file created by Minecraft.  The data is corrupted.  For some
of you, your character data files are so badly corrupted that you cannot login and play on any
classes.  For some of you, only one, or maybe two, of your classes, are corrupted.

Well, here is what we can do, and you need to think seriously about the options that I am going
to tell you about, and what they mean.  First, our only possible fix for this is to WIPE your
character.  That means that ALL of your classes will be gone, along with ALL of your information.
That means EVERYTHING will be gone.  Any pets that you purchased, any unused item bombs, any
unused XP bombs, and any GC that you may have left, will be gone.  There is NO way that we
can recover that information before the wipe, so once it happens, there is absolutely no way
to go back and get it, either.  It just cannot be done.  The data file is corrupt.  We can,
however, go back through the store and recover your rank, if you have purchased one.  Your
VIP/VIP+ rank can, and will, be recovered.

So, here is your decision to make.  If you want to keep waiting to see if Minecraft ever will
make a tool to recover lost character information, and they haven't yet made one to recover
lost or corrupted worlds, you can keep on waiting.  Seriously, it's not a problem for us, as
it requires that we simply do nothing to your game account.  For those of you who have lost one
or two classes, the decision to wipe EVERYTHING means that you have to accept the fact that
you will lose ALL of your classes, ALL of your pets, if you purchased any, any bombs that
you may have, and any GC that you may have.  None of this is recoverable if your account is
wiped, however, you will be able to start over on all of your classes.

For those of you who cannot play on any class, you have the same decision to make for yourself.
  You can wait to see if Minecraft will ever make a tool to recover lost character data, with
the same considerations as above.  Minecraft has never made one, and there is nothing that
we have heard of to say that they ever will.  Or, you can choose to have all of your character
data wiped, with the same losses as explained, above, and we can, and will, recover your VIP/VIP+
rank.

So, for each of you, individually, let me know what you want us to do, and I'll pass along your
decisions to the admin, at the end of this week (Friday or Saturday).

**Comment by lkjfdsaofmc** [comment]
I know I'm late to this post but I've had my account bugged so that NONE of the character slots worked EVER from the first time I logged in... Could someone possibly please arrange that it be reset? IGN: lkjfdsa      
I can do whatever you need like login to the server to prove I am actually me, but yeah... It's been bugged for literally like 4 years or something since the first time I every tried using it.
