### ISSUE TITLE
weird teleporting glitch

### ISSUE THREAD

**Issue by Macthecardinal** [Wynncraft/Issues#5108]
I died in the spider dungeon as i was afk then i was re spawned in olux in gavel what happened and why did i teleport across the ocean. Thx

**Comment by Moe-Ronickah** [comment]
duplicate of #4565 , please refer all further comments to that issue.

WynnCraft is built on a basically empty flat map.  The dungeons are actually _outside_ the main map area, and many of the dungeons were placed where they are before Gavel was mad.  So, when a player dies in a dungeon, they get teleported to the nearest town/city to where they died.  Hence, you got tped to Olux because it's the closest city to where you died.
