### ISSUE TITLE
Disappearing Wand...

### ISSUE THREAD

**Issue by QuickDropping** [Wynncraft/Issues#5151]
I was recently finishing the [Potion Maker](https://wiki.wynncraft.com/index.php?title=Potion_Making) and when i went to finish the quest... my wand disappeared... i was extremely depressed as it was a 'Waves Raiser' With the stats:  
DMG: 24-30
Water DM:24-40
+8% Water DMG
+5% Spell DMG
+4% Melee DMG

It cost me 1 LE and im hoping you can do something to get this back for me or something better for the inconvenience <3
Thank You -Bryan

(I sadly haved no proof of this but im hoping you can take my word)

**Comment by Mininglover21** [comment]
I don't know what caused this bug, but Wynncraft has a no-refund policy. (Meaning any items lost won't be refunded) I hope your bug gets fixed soon.

**Comment by Moe-Ronickah** [comment]
A few questions, @QuickDropping : 1) Did you tp and lose your wand?  2) Was your wand in your inventory or in your hotbar?  3) Are you still using "Q" as your drop key, instead of something safer?

We have had reports of random items being lost, so we are trying to narrow down the events surrounding the loses.  I hope that you reply and help us.

**Comment by QuickDropping** [comment]
@Moe-Ronickah No, i didnt TP i was on a horse riding, my wand was in my 1 slot in hotbar and last, my Drop key is P not Q

**Comment by Moe-Ronickah** [comment]
What version of MC were you using when this happened?

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
