### ISSUE TITLE
Deleted Items While playing

### ISSUE THREAD

**Issue by Ninjafooey** [Wynncraft/Issues#5211]
I was playing in game and was about to die so i panicked and accidentally pressed E. I think i moved my helmet and placed it onto my boots slot, and an error message came up saying you dont have the required intelligence to use this item. At the time i was wearing the lvl 60 quest boots that gave me the required amount of intelligence to use that helmet. While this happened my inventory was full and straight after that message came up i died. When i respawned, my helmet and quest boots were missing. I looked everywhere for it but it has vanished. How am i meant to get my quest boots back?

**Comment by Moe-Ronickah** [comment]
You can try /fixquests.  If your boots were the Abysso Galoshes, it may not work.  Some items are returned all of the time, some aren't.  You should have as many open inventory slots as you can when you use /fixquests, because it will run through a list of all of the items that it is coded for, and give you everything that you are missing.

With the skill points requirements for certain pieces of armor, it's best to always leave slot open to accept any armor that may fall off.

**Comment by Ninjafooey** [comment]
Thankyou! it worked! Also got a better stat roll from it xD.
