### ISSUE TITLE
Bug with A Fighting Species quest.

### ISSUE THREAD

**Issue by EpicTurtlezz1** [Wynncraft/Issues#5255]
In the room when you're fighting Gorgu, if you accidentally take off your Orc Mask, you will be teleported in a 2x1x1 area under the 3x3 piston door before the fight and be completely stuck without any way to get out other than to /kill. After killing yourself, you will also be respawned at the actual spawn, or the start of Wynncraft.

**Comment by YunoFGasai** [comment]
is the area filled with redstone?

**Comment by Moe-Ronickah** [comment]
I'm sorry, but you are not allowed to be in the Orc camp without an Orc Mask on.  If you remove it, you will be transported to the nearest non-excluded area, so, unless you want to find all of the non-excluded areas, keep the mask on.

As to where /kill takes you, you will always respawn in the nearest city to where you died.  In this case, because the quest areas aren't always on the main map, you end up going to the starting area.

As to where you landed when you removed the map, knowing if it's a redstone area will really help the builders try to fix this.

**Comment by EpicTurtlezz1** [comment]
Sorry for the late response, but the area under the 3x3 piston door is only the redstone that operates the door and probably some various lights.

**Comment by Moe-Ronickah** [comment]
Noted.  I'll pass this along to the builders and maybe they can fill in enough to keep this from happening.

**Comment by Villageacules** [comment]
As for the /kill taking you to the caravan, we're all very well-aware of this and we've been trying to fix that for a while in off-map quest areas, we're trying our best, but we may not be able to because of how the code works, and a new spawn system would take a long time.

My only advice for these region-guarded areas, is **don't ever take off your helmet!**

But, if you were to give me the coordinates of the piston door, **make sure to tag me, please,** I can analyze the area and try to see if I can prevent the player from spawning in that spot. Unfortunately, if I can't divert the path, its a part of the game that people will have to use /kill if spawned in trapping areas like this.
