### ISSUE TITLE
"Flying is not enabled on this server"

### ISSUE THREAD

**Issue by ghost** [Wynncraft/Issues#5289]
I try to log on, and it kicks me... It then logs back on automatically and kicks me again. Then it happens again and again and again and a bit more...

I look at the chat just before I get kicked and it's filled with messages saying: "Flying is not enabled on this server". I'm not using hacks, and half a second isn't enough to do much. And why is it reconnecting the whole time?

It's suddenly fine now but why did it do that before?

**Comment by Moe-Ronickah** [comment]
Fun with Minecraft servers.

**Comment by bnwilliams** [comment]
I'm still going through this problem, but sometimes I can get on without getting kicked. My friend has this problem as well, but he can't get on at all. Do you know how you made it to stop? That would be very helpful.

**Comment by jetpackguy48** [comment]
I found a solution if this happens when you /hub or the server restarts, disconnect (before the restart or instead of /hub), its the easiest way round it for me

**Comment by Moe-Ronickah** [comment]
How do you know if it's going to happen?

**Comment by Trixter313** [comment]
Just wondering, do you have auto join enabled?

**Comment by 0x0000null** [comment]
I am experiencing this too, when I log into a WC server (not the lobby). I have autojoin enabled, however I can't turn it off via the Nether(!) (see below). I will attempt to provide as much information as possible.

* If I logged out in a position where there is a ceiling directly above me, I am **able** to log in. I think this is because the game places you in the air when you log in, and when there is a ceiling above the game places you on/near the ground, and you do not get kicked for flying.
* Logging in to a different server does **not** help.
* I am **able** to log in to the Nether. The game still hangs on "loading terrain" for a bit longer than normal however (~15 sec). I do not get kicked for flying.
* I tried turning off autojoin while in the Nether, but I don't think it actually got turned off, since I spawn at my last location in my last class instead of the class selection room.
* Using 1.8.9 does **not** help.
* Disabling server resource packs does **not** help.
* A complete Minecraft reinstall does **not** help.

**Comment by MatthewMK** [comment]
This is really damn annoying im getting kicked so much and it is pissing me off
i dont even get a chance to do anything at all 
this really needs to be fixed
or im done playing this server again 
theres something always up and this is gonna be what makes me stop for good

**Comment by KAM078** [comment]
I,ve posted same thing at my comment section I am going threw it the same way

**Comment by KAM078** [comment]
it keep doing it allover again

**Comment by Moe-Ronickah** [comment]
@KAM078 , this is not something that we have full control over.  This is an issue that partially has to do with Minecraft, itself.  We are trying to find a way to fix, so, please, calm down, and try to login every now and then.  We know that it is frustrating, but when it's not fully our fault, it's not fully under our control.

**Comment by DebugingLonks** [comment]
I know how to fix this! it happens unless autojoin is off!

**Comment by 0x0000null** [comment]
Turning off autojoin prevents you from being kicked, however it does not stop the unbearably long loading screen.

**Comment by Jacobobber** [comment]
This is also happening with me. I log in and it constantly just connects, kicks me and reconnects. In between kicks it says flying is not enabled on this server. Nothing I have tried works.

**Comment by Moe-Ronickah** [comment]
@Jacobobber "this is not something that we have full control over. This is an issue that partially has to do with Minecraft, itself. We are trying to find a way to fix, so, please, calm down, and try to login every now and then. We know that it is frustrating, but when it's not fully our fault, it's not fully under our control."

Make sure that autojoin is turned off.

The long load screen is an effect of lag or dropped packets.
