### ISSUE TITLE
I am blocked in invisible blocks

### ISSUE THREAD

**Issue by Lucarnos** [Wynncraft/Issues#5299]
Hello , on your server , I am currently stuck on a mountain in invisible blocks and I would like to know if is possible to loosen me and give me my stuff, I specified that I have just lost my mage stick ( I would precision of whether it wrong) (I do not speak much English , I have to use google translation )

**Comment by Moe-Ronickah** [comment]
Can you tell us the coordinates of where you are, so that we can have a builder check the area?

The only way out, if you can't find a route to take you out, is to use "/kill", but be certain that you have 3 or more Soul Points so that you don't die.

Wynncraft has a no-refunds policy, so, whatever you have lost, we cannot give it back to you.

**Comment by Lucarnos** [comment]
Ok, I don't know my coordinates, just i am in the mountain next to the
invaded barracks [lvl30] , and my item was a stick mage : dusty staff for
lvl 26.

If you want, you can tell me connect and you can search me on the mountain.

Thank you for youre help.



2016-06-24 17:27 GMT+02:00 Nathan Stolov <notifications@github.com>:

**Comment by Trixter313** [comment]
If you're still in the mountain, just press the F3 button to display your coordinates and the F2 button to take a screenshot then upload the picture here.

Thanks!

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
