### ISSUE TITLE
Teleportation Bug

### ISSUE THREAD

**Issue by Ricardo65432** [Wynncraft/Issues#5309]
Most of the times when i walk into an area thats supposed to teleport me, it doesnt. i will have to relog and then walk into it again, and then it works. but, in the quest Memory Paranoia i have to walk into a hole in the wall in the library, relogged multiple times, re-entered the mansion multiple times. but it wont teleport me, is there anything i can do to fix this?

**Comment by Moe-Ronickah** [comment]
Please check your quest book and see if there is something that you are missing.  You are at [Stage 5](https://wiki.wynncraft.com/index.php?title=Memory_Paranoia), and you must read all 5 pages in the book in order to trigger the teleport.  Have you read all 5 pages?  Does your quest book tell you to enter the hole in the wall?

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
