### ISSUE TITLE
Didn't use XP Bomb

### ISSUE THREAD

**Issue by duncster2000** [Wynncraft/Issues#5326]
I just bought another XP Bomb after the last one ran out because I got stuck in the Silverfish Dungeon. Now this one, I bought it, and I clicked on it to use and nothing happened. Now I dont have the XP bomb anymore. I attached screenshots of the chat if this is helpful. Sorry for two posts but I spent $5 for Double XP and have yet to get any of it because of two glitches.

IGN is Duncster2000

Thanks for any help.
![2016-06-27_14 40 36](https://cloud.githubusercontent.com/assets/20174368/16396965/69427d50-3c76-11e6-9db3-60b968f18d16.png)
![2016-06-27_14 40 38](https://cloud.githubusercontent.com/assets/20174368/16396964/69425118-3c76-11e6-8aee-542e39dfd532.png)
![2016-06-27_14 46 01](https://cloud.githubusercontent.com/assets/20174368/16396967/694694c6-3c76-11e6-86bf-fb90b3645bc7.png)
![2016-06-27_14 46 03](https://cloud.githubusercontent.com/assets/20174368/16396966/694596b6-3c76-11e6-8366-1403c30e4620.png)

**Comment by Trixter313** [comment]
Do you still not have the second bomb? Sometimes it takes a little time for it to fix itself.

**Comment by duncster2000** [comment]
nope... Its been 3 hours and still on the server and still do not have the xp bomb

**Comment by Trixter313** [comment]
Have you tried relogging?

**Comment by duncster2000** [comment]
Yes many times...and different worlds

**Comment by Moe-Ronickah** [comment]
Contact support@wynncraft.com.  Tell them everything that happened, carefully, and in detail, and refer them to this issue for your screenshots.

There has been a problem, lately, with the silverfish dungeon.  It is not, by any means, consistent, and I haven't had any trouble with it.  It is Issue #5101 .  So, don't toss an xp bomb until you're ready to collect the xp.

Tell them that this issue is linked to #5325 .

Support are the only ones who can resolve the issue of XP bombs, and we have the responsibility of trying to get the dungeon fixed.

Good  luck, and sorry for your trouble.

**Comment by Moe-Ronickah** [comment]
RESOLVED
