### ISSUE TITLE
Can't Move

### ISSUE THREAD

**Issue by ethandonley2002** [Wynncraft/Issues#5344]
I happen to be stuck on the coords X:-48.700, Y: 112, Z: -364.700, I tried teleporting out since i'm a mage and tried using a horse, but I can't move, i keep trying to join another server, wait for restart, etc. But it never works, its like I've reached the limit. I don't have a scroll either as well. Can someone please help me?

**Comment by Trixter313** [comment]
Typing /kill with 3+ soul points should get you out. We will do our best to fill in the hole so others don't get stuck in it. Thanks!

**Comment by 5norky** [comment]
They're stuck in the -657 -1070 coordinates and I can not move , we are finished because I was trying to climb the assembling with the teleporting since I'm a magician, but I can not even use the map to return to the kingdom.
I ask for help if I can move even the block next to be able to play again .
thank you

**Comment by ethandonley2002** [comment]
k thanks it works.
