### ISSUE TITLE
Horse Dissapearance

### ISSUE THREAD

**Issue by Verenite** [Wynncraft/Issues#5356]
So, i was on my way to Almuj and while on my Tier 1 horse i accidentally dropped my saddle and it just poofed. i looked around for 30+ minutes but it was gone. Please help?

**Comment by Moe-Ronickah** [comment]
First, we suggest that you don't use the "Q" key as your drop key; change it to something like "Delete" so that accidents like this are much less likely to happen.
Second, if there was anyone around you, after 20 seconds, they could have picked up your saddle.
Third, I'm sorry, but Wynncraft has a no-refunds policy, so there is nothing that anyone can really help you with.
