### ISSUE TITLE
5le are missing

### ISSUE THREAD

**Issue by TheNoob0510** [Wynncraft/Issues#5379]
Help me I cant get a bether horse I have inwested 5le and now I have only 32eb. I cant made my horses. Can you give me pls a bether horse or my 5le back because it must be a bug the chance is 20% to became a bether and I have bought 13 hourses and I have a broun. How is this posible? Pls help me or give me my 5le back.

**Comment by Moe-Ronickah** [comment]
The chance of getting a better horse from horse breeding is 20%.  The chance of getting a better horse from buying horses from the horse merchant in Ternaves is 0%.  The horse merchant only sells brown horses.

**Comment by TheNoob0510** [comment]
I know I have breaded all buit nothing has work it must be a bug or something

**Comment by Moe-Ronickah** [comment]
It is called probability.  It is not a guaranteed result over small runs.  Even at 20% probability, it is the same as rolling dice.  You may get a long string of failures, before you get a success, because each breeding attempt is independent of all other breeding attempts.  It is simply statistical, and not a bug of any kind.

**Comment by TheNoob0510** [comment]
Thx for help and I only have been very unlucky

**Comment by Moe-Ronickah** [comment]
You are quite welcome.  I hope that I cleared up any misunderstanding that you had, and I hope that your luck changed.
