### ISSUE TITLE
Bugged Item

### ISSUE THREAD

**Issue by 94SoulEater** [Wynncraft/Issues#5383]
I joined wynncraft after a long time and, after i started playing, i noticed my sharpess I Dévoreuse wasn't working. It wasn't casting neither spells nor normal attacks. Any way i can fix this? 
IGN: 94SoulEater

**Comment by Trixter313** [comment]
I'm assuming the item still has the old item system when you mouse over it?

We've determined that since these items were created all at one moment, the Gavel update, and can't be created anymore, the issue isn't occurring anymore but some people are still seeing the effects. You can either keep the item if you want or throw it out and work for a better one. It shouldn't happen again. Thanks!
