### ISSUE TITLE
Double Quest Items

### ISSUE THREAD

**Issue by HapreGivre** [Wynncraft/Issues#5419]
Hello, 

I've a litle problem in game, indeed, I was doing the organization of my enderchest when suddenly, my game crashed, the items of collection which were in my enderchest were moved in my inventory, but they stayed in my enderchest too......

I would like that they are deleted please.

Here is the proof of what I move forward

PS : I'm french... scuse for my english !

[http://image.noelshack.com/fichiers/2016/27/1467838963-2016-07-06-22-52-16.png](url)

Thanks for your help !

**Comment by Moe-Ronickah** [comment]
The extra quest items can usually be removed through a glitch, but I'm not telling to actually do this.  The glitch works this way: with your player inventory open, fill all of your inventory slots.  Emeralds work fine for this.  When you are down to one or two quest items that you want to get rid of, you swap emeralds for those items, and put the items into your 2x2 work table.  When you close your inventory, any items in your work table with vanish.  This is a normal MC mechanic, where the items normally drop to the floor.  However, because of the custom Wynncraft code, those items will vanish.  If you do abuse this glitch, you do so at your own risk.
Good luck.
