### ISSUE TITLE
XP GLITCH

### ISSUE THREAD

**Issue by Nicius** [Wynncraft/Issues#5462]
me and my friend we were using the same armor xp, made the quest hive Qira and it evolved from level 82-85, missing 2 bars, I was level 84 and progresses to 85, but was missing 3 bars !!! I should have evolved more, ;-; want my xp back!

**Comment by sammyvsparks** [comment]
@Nicius Wynncraft has a no-refund policy for in-game items and obtainables (experience being a obtainable) that are not bought from the WynnCraft Store. Experience earned varies from EXP Bonus, Double XP, Guild XP and many other factors. Sorry for the inconvenience.

**Comment by Nicius** [comment]
I was sure I was not contributing any xp for the guild, we did the quest at the same time and lend items to each other to stay more xp and was double xp.

**Comment by sammyvsparks** [comment]
You will just have to work with what you got. It varies from several factors and is nothing we can control, the no refund policy stands firm for everyone.

**Comment by YunoFGasai** [comment]
the quest gives you more xp when you are closer to its level, because your friend was closer to level 80 he got more xp than you allowing him to pass you.

**Comment by Moe-Ronickah** [comment]
From the Wiki:
Lv82 - Lv85, plus 80%, maximum xp needed is 11 489 400 XP.
Lv84 - Lv85, plus 70%, maximum xp needed is 4 718 700 XP.

If, and only if, your observations are perfectly correct, there might be a problem, however, we would need video evidence from both of you at exactly the same time in order to prove it.  Doesn't exist, does it?  I didn't think so.  I wish it did.

Is it possible that you turned your quest in just as the double xp was ending and that your friend turned his in earlier?

Yuno's suggestion is also quite true, and may be the answer to your issue.

**Comment by C0meGetS00me** [comment]
Its wrong, my friend called TheEndTimes went from 80 to 81 on qira using just dxp and 70%xp bonus.
I went from 87 to 88 and half using dxp and 205%xp bonus.

Doesn't it sound weird?

**Comment by sammyvsparks** [comment]
@C0meGetS00me 205% to 70%, its fully possibly for that to be plausible.

**Comment by Moe-Ronickah** [comment]
@C0meGetS00me , let's say, for arguments sake, that your observations are correct.
Lv80-81 takes 2 131 000 xp.  Qira gives 1 000 000 xp, so we have 1 000 000 * 2 *1.7 = 3 400 000xp.  That's close enough to what you claim was observed.
Lv87-88.5 takes 4 070 000 + 2 235 000 xp = 6 305 000 xp.  Again, using Qira's 1 000 000 xp, we have 1 000 000*2*3.05 = 6 100 000 xp.  That's almost exactly what you claimed you observed.

The mathematics is just simple multiplication.  There is nothing weird to it once you do the math.
