### ISSUE TITLE
Soul Points not Regenerating?

### ISSUE THREAD

**Issue by MyNameIsArtifax** [Wynncraft/Issues#5480]
Ok guys so I was on Wynncraft today. I realized I was low on soul points, so I left the server and joined another. A lot of time later I went back on to Wynncraft and my soul points still didn't regenerate. I checked my stats of soul point regen but it still didn't work. Can someone please help me?

**Comment by sammyvsparks** [comment]
@MyNameIsArtifax Soul Point Regen refers to Day/Night Cycle of a chance to obtain 2 Soul Points instead of one.

Also the offline soul point regeneration is increasingly lower then online. Try to find a server that is night time and wait until day. It should say +1 Soul Point when the sun comes up enough.

**Comment by MyNameIsArtifax** [comment]
When I am offline the soul points don't regen, so that is the problem.

**Comment by MyNameIsArtifax** [comment]
Apparently it works in game, but not offline.

**Comment by sammyvsparks** [comment]
@MyNameIsArtifax how long have you waited in total? It takes hours if I am correct for offline soul points.

**Comment by XavierEXE** [comment]
Soul points cap at 15, not 16.
Just thought I should point that out.
