### ISSUE TITLE
WynnExcavation Site B teleportation glitch

### ISSUE THREAD

**Issue by Mikaatjuhh** [Wynncraft/Issues#5483]
After going through the puzzels on the quest 'WynnExcavation Site B', I got teleported inside a wall. After collecting the purple crystal shards i used charge to get to the exit of the cave and got stuck in a wall. Im currently stuck and have no way of getting out. Please help me.
Mikaatjuhh

**Comment by sammyvsparks** [comment]
@Mikaatjuhh currently the only way to get out of a hole or wall that you cannot escape is using /kill, which means you will have to retravel the distance back to where you got stuck.

**Comment by Moe-Ronickah** [comment]
@Mikaatjuhh , if you get stuck in a wall again, you can try going to the class selection screen, then selecting the stuck class, while holding down any one of the movement keys.  This sometimes work to get players out of walls, and you may have to try it several times in order to get it to work.

@sammyvsparks , first, thanks for helping!  Second, please include the above when you comment on players stuck in walls.  Thanks.
