### ISSUE TITLE
Bugged quests

### ISSUE THREAD

**Issue by 1Entropy** [Wynncraft/Issues#5494]
I currently have two quests that are bugged in a similar way. The quests are: Murder Mystery and Hollow Sirene. The quest book isn't updating at the places they are supposed to and because of this I cant continue the quests and finish them. I have tried retracing my steps and talking to every NPS over again, but my quest book refuses to update and give me the next steps in the quest. In murder mystery the quest book stopped updating after I talked to Rohem. For Hollow Sirene it stopped updating when I got the ear muffs. Unless these bugs are resolved I wont be able to move on to the next parts in each respective quest. I hope there is a solution, thanks for reading.
- 0Entropy

**Comment by sammyvsparks** [comment]
@1Entropy What does your quest book say exactly for those 2 quests?

**Comment by annoyingcalc** [comment]
I have a similar issue, for 2 early quests:
Suspended Flowers and Thieving Rodents.

In Suspended Flowers, the cave I'm supposed to get the flowers from teleports me out and gives me the "You don't think you should disturb the plants" message.
In Thieving Rodents, whenever I give the NPC the Wedding Ring he acts as if it isn't in my inventory.

Book Entries:

Suspended Flowers:

Status: Started
Look for Asher in the mysterious Time Valley

Thieving Rodents:

Status: Started
Find the ring in the hive and return to Farmer Kelri.

**Comment by Trixter313** [comment]
@annoyingcalc please create a new issue for unrelated issues. Thanks!

**Comment by Moe-Ronickah** [comment]
@1Entropy and @annoyingcalc , we have a [Wiki](https://wiki.wynncraft.com/index.php?title=Main_Page) that you can consult to be certain that you have done every step and not missed anything.  Also, there are youtube walk-throughs that you can follow, step-by-step, to make certain that you haven't missed anything.

There is one other thing that you can try, but you may end up with quest items that you need to get rid of.  You can try /fixquests.  It has been known to help with errors like these.

**Comment by 1Entropy** [comment]
The current status for my broken quests:
-Hollow Sirene: Solve the puzzle to open the door that locks the heirloom
-Murder Mystery: Investigate the crime scene for clues   

Also @Moe-Ronickah I have tried using the /fixquests command, and it does nothing to fix these current quests. Also I have looked at walk through videos for both of these quests and I followed them exactly, but my quest book refuses to update. I'm pretty sure that there is nothing I can do to fix these quests myself. Maybe resetting the quest completely would fix it, however I don't have the power to do that. Any other suggestions would be appreciated. Thanks for reading. 
-0Entropy

**Comment by annoyingcalc** [comment]
I have both read the wiki and watched multiple quest playthroughs on youtube. I however have not tried /fixquests, I'll try that

**Comment by XavierEXE** [comment]
@annoyingcalc
Suspended Flowers: Before you get the flowers from the cave, you need to talk to the guy named Asher in his house in Time Valley. You can't enter the cave without talking to him.
Thieving Rodents: Which ring are you trying to give him? During the quest, you give him a ring that looks like a Ghast Tear, but it turns out to just be a washer. Then you have to go to a cave in Kelri's farm and kill the King Rat which drops a ring that looks like a **Gold Nugget.** Try giving Kelri the ring that looks like the gold nugget, not the ghast tear.

@1Entropy
In Murder Mystery, you seem to be on Stage 1. You need to enter the house and follow the blood trail out the back and find a tattered letter, which is addressed to Rohem in House 09 in Cinfras. Once you get the letter, you need to bring it to Rohem and interrogate him to continue.
As for Hollow Sirene, it's been AGES since I did that quest, so I can't help you there. I'll get back to you later if I find out what the problem is.

**Comment by annoyingcalc** [comment]
Suspended Flowers: If I recall correctly, when I did that his dialogue was null.

Thieving Rodents: I tried giving him an item called "Wedding Ring". I don't know the item type due to the resource pack, but I'll check when I get a chance.

**Comment by XavierEXE** [comment]
@1Entropy for Hollow Sirene, you need to go to the graveyard at -578 42 -5280 and find the gravestone with a lit candle next to it. Find a stone button and then follow the particles to the next grave and repeat. Then, at the last grave, go inside the door that opens and solve the timed puzzle to get the earmuffs. Then, go to the cave at -748 31 -5280 while wearing the earmuffs to continue.

@annoyingcalc The items still look like gold nuggets and ghast tears even with the resource pack, if I recall correctly.

**Comment by annoyingcalc** [comment]
The item was enchanted, which makes gold / silver colors harder to separate. I'll check for sure when I can get on.

**Comment by Moe-Ronickah** [comment]
And this, everyone, is why it's one issue per issue post.  I'm deleting this/these issue(s) posted by, and in reference to, annoyingcalc, because you were asked by an admin to open an issue specifically dealing with your issue(s).  We try to deal with one issue at a time, so that things don't get confusing.  Please assist is in our efforts to make issues as clear and concise as can be.

**Comment by AckroWynn** [comment]
Solved through guidance. /Closed
