### ISSUE TITLE
Missing Item

### ISSUE THREAD

**Issue by IncBear101** [Wynncraft/Issues#5515]
Yes, I have searched "Missing Item" but most of them, are just missing quest items, and /fixquests, and all that, but my Bow (Olux's Prized Bow) has gone missing, when I logged onto Wynncraft today. Yesterday, I did the quest, Lost Soles, and I had the bow then. I know I had the bow when I logged off, I checked other class inventories, the bank, and I couldn't find it. I also have like 10 Scrolls in my inventory, and a Relic Bow, which has the same look as the Olux's Prized Bow. I know there is no-refund policy, its very strict about having this policy, and they can't refund obtainable in-game items, only GC bought items, and real-money bought items, but does anyone have any idea HOW this happened? Right now I'm going to Detlas to ask people if I can buy one. I'm just asking that does anyone have ANY idea HOW this happened?

**Comment by IncBear101** [comment]
Also, I bought it for 30EB, just want to know how I lost the other one

**Comment by YunoFGasai** [comment]
is your drop key bound to "Q"?

**Comment by IncBear101** [comment]
Yes, it is

**Comment by IncBear101** [comment]
When I log into Wynncraft, the world I join, loads two times. First, the world itself, second, to load the texture pack. Maybe I dropped it between those two loads and it despawned?

**Comment by IncBear101** [comment]
I didn't drop it when I log out I notice almost instantly because I use the bow for escaping for speed and to climb mountains and sruff

**Comment by Moe-Ronickah** [comment]
Please change your drop key to some other key, like the Delete key, so that there is little to no chance of you accidentally hitting your drop key.  If you had lost multiple items, it would fit in the description of several issues.  Losing one item, however, is usually an accidental drop.  Also, never click on an item that you are holding in your hand when you are on a horse.  The item will be dropped.
