### ISSUE TITLE
Broken Pre-Update Spear

### ISSUE THREAD

**Issue by Lambofan007** [Wynncraft/Issues#5519]
Hello, I recently came back on to play after maybe a year or so off of the server. I found everything including the updates to be fine and no bugs except my weapon for Warrior, Fierte, was completely broken. It did not give me the option to identify it or  use it it just acted like any other normal item. In these screens you'll see that the description looks completely different from any other weapon as I had it before the major updates.

All I ask is that it be removed and replaced with maybe a non broken Fierte? My warrior class is useless without it as it was my main damage dealer 

![2016-07-19_03 44 25](https://cloud.githubusercontent.com/assets/20533001/16942411/e20c483a-4d63-11e6-8e2e-7823a96c2311.png)
![2016-07-19_03 44 26](https://cloud.githubusercontent.com/assets/20533001/16942420/e6129182-4d63-11e6-8b1a-d560fcfab6ce.png)
![2016-07-19_03 44 32](https://cloud.githubusercontent.com/assets/20533001/16942421/e88d508c-4d63-11e6-8cb9-ca8228938dfa.png)
![2016-07-19_03 45 42](https://cloud.githubusercontent.com/assets/20533001/16942423/eb132c78-4d63-11e6-872e-81bc8a67b9a0.png)

**Comment by Trixter313** [comment]
We've determined that this issue was a one time thing that no longer will occur to any new items and recommend getting a new weapon and either throwing out the old one or keeping it if you'd like. In the many updates that have happened many new weapons have been added so hopefully it isn't too much of an issue for you to find a new weapon.
