### ISSUE TITLE
I can't Choose a class

### ISSUE THREAD

**Issue by Sorceric** [Wynncraft/Issues#5539]
I've recently experiment a bug in where I can't choose a class. After I choose a server, I usually enter a dark room and choose a class however now I experience a situation in where there is a hole below me in the dark room and I fall forever, unable to choose a class. Please Help? Idk how to fix it :C

**Comment by Moe-Ronickah** [comment]
Find and delete the WynnCraft resource pack in your servers-resouce-packs folder.  It may be named "legacy".  Then let the server re-download a new resource pack.  Also, make certain that you are allowing WynnCraft to automatically download the server resource pack.

**Comment by Sorceric** [comment]
What about for mac?

**Comment by sammyvsparks** [comment]
Same steps, bu  with your mac minecraft directory, should be named all the same.

**Comment by Sorceric** [comment]
I've deleted it and followed everything you said, however i still fall down the void and can't do anything when i join a server ;-;?

**Comment by Sorceric** [comment]
I mean that i deleted the legacy folder, emptied the trash and let wynncraft download a new resource pack but the same thing happens... T_Tsomeone plz help me

**Comment by Moe-Ronickah** [comment]
Hey, Sorceric, do a search for "resource pack mac", and read through all of the issues and suggestions.  There are 9 total issues there, and, hopefully, one of the suggestions will help.  Let us know what happens.

**Comment by Sorceric** [comment]
Nope haven't found anything that will help the problem yet :/

**Comment by Moe-Ronickah** [comment]
Sorceric, the next time that you go to WynnCraft, see if you can go into the Nether.  If you can, see if you can toggle autojoin, and make sure that it is "off".  Check to see if you can get into a game world on any class, even if you have to make a new one.

Also, there IS a hole in the class room, directly under an invisible chest.  It's been recently patched, and this issue of falling through MAY be fixed with the next update.  Let us know what happens, I'm still trying to get help with this one.

**Comment by yosteric5** [comment]
What moe said. Also make sure to have your rp enabled

**Comment by Moe-Ronickah** [comment]
I'm going to try to tp him to me, again, today.  We will see what happens.

**Comment by Moe-Ronickah** [comment]
This is a generic message, to everyone affected by these issues.
I've discussed this with the admins, and it turns out, after a lot of investigation, that the 
problem lies within the saved data file created by Minecraft.  The data is corrupted.  For some
of you, your character data files are so badly corrupted that you cannot login and play on any
classes.  For some of you, only one, or maybe two, of your classes, are corrupted.

Well, here is what we can do, and you need to think seriously about the options that I am going
to tell you about, and what they mean.  First, our only possible fix for this is to WIPE your
character.  That means that ALL of your classes will be gone, along with ALL of your information.
That means EVERYTHING will be gone.  Any pets that you purchased, any unused item bombs, any
unused XP bombs, and any GC that you may have left, will be gone.  There is NO way that we
can recover that information before the wipe, so once it happens, there is absolutely no way
to go back and get it, either.  It just cannot be done.  The data file is corrupt.  We can,
however, go back through the store and recover your rank, if you have purchased one.  Your
VIP/VIP+ rank can, and will, be recovered.

So, here is your decision to make.  If you want to keep waiting to see if Minecraft ever will
make a tool to recover lost character information, and they haven't yet made one to recover
lost or corrupted worlds, you can keep on waiting.  Seriously, it's not a problem for us, as
it requires that we simply do nothing to your game account.  For those of you who have lost one
or two classes, the decision to wipe EVERYTHING means that you have to accept the fact that
you will lose ALL of your classes, ALL of your pets, if you purchased any, any bombs that
you may have, and any GC that you may have.  None of this is recoverable if your account is
wiped, however, you will be able to start over on all of your classes.

For those of you who cannot play on any class, you have the same decision to make for yourself.
  You can wait to see if Minecraft will ever make a tool to recover lost character data, with
the same considerations as above.  Minecraft has never made one, and there is nothing that
we have heard of to say that they ever will.  Or, you can choose to have all of your character
data wiped, with the same losses as explained, above, and we can, and will, recover your VIP/VIP+
rank.

So, for each of you, individually, let me know what you want us to do, and I'll pass along your
decisions to the admin, at the end of this week (Friday or Saturday).

**Comment by Moe-Ronickah** [comment]
@Sorceric , are you still stuck and unable to get into WynnCraft?
