### ISSUE TITLE
Class Error "There has been an error, try again.."

### ISSUE THREAD

**Issue by rzsenseio** [Wynncraft/Issues#5570]
MC Name: zHatred
title.
Note, i have never played in the server and would really like to!
I do think highly that my character is somehow corrupted. Any suggestions admins? maybe reset my character data?
![screenshot 188](https://cloud.githubusercontent.com/assets/20620372/17082843/f5d4dec6-51b5-11e6-8d50-95789a89fa81.png)
Need solutions :(

Details: can connect to one of the servers from hub succesfully, whenever i try to pick a class it keeps showing the message on the title. All of the classes, no exceptions. (Not able to do any command except /hub)

**Comment by sammyvsparks** [comment]
Hello, Not much is known on this issue sadly but we can try a few things to see if we can help.
First, Delete the server from your IP List and close minecraft, wait about 10-15 mins, then add the server and enable resource packs.
While your waiting on that, optionally you can clear your resource pack by going to your minecraft directory and deleting the resource pack from the "server-resource-packs" folder (may be named legacy)

**Comment by rzsenseio** [comment]
i tried your tips perfectly, not working :(

**Comment by XavierEXE** [comment]
What minecraft version are you using? Try using 1.8.9 if you aren't already, higher versions can mess up sometimes.

**Comment by Moe-Ronickah** [comment]
@rzsenseio , you are correct, it is the same problem. With your better description in the issue that you opened, it's obviously the same issue as #5418 .

**Comment by Moe-Ronickah** [comment]
This is a generic message, to everyone affected by these issues.
I've discussed this with the admins, and it turns out, after a lot of investigation, that the 
problem lies within the saved data file created by Minecraft.  The data is corrupted.  For some
of you, your character data files are so badly corrupted that you cannot login and play on any
classes.  For some of you, only one, or maybe two, of your classes, are corrupted.

Well, here is what we can do, and you need to think seriously about the options that I am going
to tell you about, and what they mean.  First, our only possible fix for this is to WIPE your
character.  That means that ALL of your classes will be gone, along with ALL of your information.
That means EVERYTHING will be gone.  Any pets that you purchased, any unused item bombs, any
unused XP bombs, and any GC that you may have left, will be gone.  There is NO way that we
can recover that information before the wipe, so once it happens, there is absolutely no way
to go back and get it, either.  It just cannot be done.  The data file is corrupt.  We can,
however, go back through the store and recover your rank, if you have purchased one.  Your
VIP/VIP+ rank can, and will, be recovered.

So, here is your decision to make.  If you want to keep waiting to see if Minecraft ever will
make a tool to recover lost character information, and they haven't yet made one to recover
lost or corrupted worlds, you can keep on waiting.  Seriously, it's not a problem for us, as
it requires that we simply do nothing to your game account.  For those of you who have lost one
or two classes, the decision to wipe EVERYTHING means that you have to accept the fact that
you will lose ALL of your classes, ALL of your pets, if you purchased any, any bombs that
you may have, and any GC that you may have.  None of this is recoverable if your account is
wiped, however, you will be able to start over on all of your classes.

For those of you who cannot play on any class, you have the same decision to make for yourself.
  You can wait to see if Minecraft will ever make a tool to recover lost character data, with
the same considerations as above.  Minecraft has never made one, and there is nothing that
we have heard of to say that they ever will.  Or, you can choose to have all of your character
data wiped, with the same losses as explained, above, and we can, and will, recover your VIP/VIP+
rank.

So, for each of you, individually, let me know what you want us to do, and I'll pass along your
decisions to the admin, at the end of this week (Friday or Saturday).

**Comment by rzsenseio** [comment]
Please, do whatever it takes, i don't have anything to lose as of now. So if it means to reset my character, thats fine, as long as i can play.
(Take note, i have never played)

Thank you very much for hearing us.
