### ISSUE TITLE
Canyon Condor Bug

### ISSUE THREAD

**Issue by theIglooo** [Wynncraft/Issues#5578]
After fighting the boss and returning to Svin to finish the quest, if you have a full inventory it will tell you to empty some space and come back however it takes the Beast Egg so you can't finish the quest unless you go back up and fight the boss again.
I know there's an issue for this at #3637 but it was closed without resolution as this still happens and /fixquests doesn't give the egg back.
![Image if my explanation wasn't clear](https://u.pomf.is/cwknvo.png)

**Comment by Moe-Ronickah** [comment]
**Thank you for doing a proper search and finding the old duplicate!**
Unfortunately, if you have a full inventory, there is still an issue with this happening.
Also, because all quests give rewards of some kind, you should never turn in a quest without several open inventory spaces.

@AckroWynn , can you look into this and let us know if this fixable at this time?

**Comment by Villageacules** [comment]
Can you try defeating the boss again and getting another egg?
/fixquests won't work because the egg isn't a quest item, it's untradable if I'm correct.

**Comment by AckroWynn** [comment]
@Moe-Ronickah There is nothing a GM can fix.

**Comment by Villageacules** [comment]
@AckroWynn Actually there are a lot of things a GM can't fix.

**Comment by Moe-Ronickah** [comment]
AckroWynn, did you mean "There is nothing a GM can't fix" or "This is nothing a GM can fix"?

@theIglooo , the fix, for right now, is to get another egg.

**Comment by AckroWynn** [comment]
I meant "This is nothing a GM can fix.".
