### ISSUE TITLE
~~~~~Item Bomb Glitch~~~~~

### ISSUE THREAD

**Issue by Kitchen-Tiles334** [Wynncraft/Issues#5579]
I have recently bought a 100 gold coin package and bought two item bombs. As I was not originally aware that the bomb's contents could not be picked up myself I ended up losing my items to clear lag. This really annoyed me. This is where i would like to see a more clear explanation on how things like this work in the future, for example, telling me or anyone else looking to buy something that only other people on the server can pick up my items in the in game shop page. Instead of having to search and find a wiki myself. The second bomb, however i was prepared and had a friend pick up the items for me. This did work for one out of the five items. My friend saw a diamond helmet and picked it up. I'm not %100 sure if this is a bug or issue that is known about but when he picked up the helm it simply disappeared and was never in his inventory. If you could please get back to me as soon as possible, preferably on a more personal note as i am starting school again very soon and don't really check these types of media. My public email is down below,
Thanks,
Kieren

**[DELETED]  <== Don't do this!**

**Comment by Moe-Ronickah** [comment]
@Kitchen-Tiles334 , you should contact support@wynncraft.com and tell them everything that you said in here.  They handle all issues that involve real world money.  Also, I deleted your email.  You should never post your email in the open like it because is makes you a target for spammers.

As to the diamond helmet vanishing, I don't believe that we have seen that one, before, so I'm going to leave this issue open.

**Comment by Kitchen-Tiles334** [comment]
Hi There Nathan,
I have sent an email to wynncraft support and wish to acknowledge you that
I have three emails, one specifically designed for spam with heavy filters
and two others for personal use. And also I'd like to thank you for taking
the time to respond to my report and send an email about this to me.
That's all,
Kieren.
