### ISSUE TITLE
First cave - helmet detection sucks

### ISSUE THREAD

**Issue by AntonioNoack** [Wynncraft/Issues#5584]
Delete this line if you've followed the README instructions and searched for a duplicate issue FIRST, and before posting any new issue. <- still no

I wore a helmet dropped by a zombie and couldn't get trought the gate because "I was wearing to helmet" -> bug

**Comment by Villageacules** [comment]
This report has minimal detail. Could you please explain what item, what quest, what gate, and all the details? I can't make anything out of this.

**Comment by Moe-Ronickah** [comment]
@AntonioNoack , you are in the starting area.  It is a tutorial area so that you can learn some of the basic information about WynnCraft.  You need to purchase and wear a special helmet from the helmet salesman, near the gate, in order to pass through the gate.  Nothing is broken here.  It's quite intentional.

**Comment by AntonioNoack** [comment]
@Moe IT IS BROKEN! I wore "a helmet" and I know it detects only the special helmet WHICH IS WRONG!!!
It needs to detect any helmet if it says "A HELMET" !!!
And @Villiageacules - you have your details now.

**Comment by Moe-Ronickah** [comment]
It isn't broken, at all.  Honynn's message could be better worded.  The point of the exercise is to learn that there are item sellers.  Removing drops from Lv1 mobs would not be a good option.

![2016-07-28_18 36 20](https://cloud.githubusercontent.com/assets/11842380/17233098/907eeaea-54f2-11e6-9f2c-b2de6b621314.png)
