### ISSUE TITLE
item dissapeared

### ISSUE THREAD

**Issue by shadowbr121** [Wynncraft/Issues#5588]
i was playng on the animal dungeon i was changing the position of a bow in my hotbar and then the bow dissapears and it was my best bow im an archer

**Comment by Villageacules** [comment]
Are you sure you didn't drop it? Check your inventory and make certain that it isn't just hiding in your inventory somewhere.

**Comment by shadowbr121** [comment]
No i asked for my friends to search the item in the place i was looking my inventory and no item on the ground looked carefully in my inventory and nothing

**Comment by Villageacules** [comment]
I understand, I'm sure everyone in Wynncraft has lost a valuable item to them. Unfortunately has a no-refund policy which means that if you lose your items to any bug (or if you lose them on accident) we will not refund your items. The only people that can refund your items are the admins, and they simply don't have enough time to refund items and can't tell which people are lying to just get free items, since this was abused years ago when we did refund items. Sorry.

**Comment by Moe-Ronickah** [comment]
@shadowbr121 , is your drop key set to "Q"?  If it is, please change it to another key, such as "Delete".  This usually prevents another occurrence of this issue.

**Comment by shadowbr121** [comment]
I dont want any refunds i just wanted to show that bug só no one would suffer it anymore my brother lost his wand too

**Comment by shadowbr121** [comment]
another item dissapeared luckily it wasnt much

**Comment by Moe-Ronickah** [comment]
@shadowbr121 , you have not responded to my question, so I don't know where we are going with this.  Also, it's possible to accidentally grab an item when holding down your mouse key.

**Comment by shadowbr121** [comment]
It is set to q but im sure i didnt drop it i searched all the place

**Comment by Moe-Ronickah** [comment]
**PLEASE change it to another key, such as "Delete". This usually prevents another occurrence of this issue.**

**Comment by shadowbr121** [comment]
Ok
