### ISSUE TITLE
Lost my stuff for an unknown reason.

### ISSUE THREAD

**Issue by MCtroller3936** [Wynncraft/Issues#5618]
I was playing on Wynncraft and I had to leave so i logged off. A few hours later I logged back on and ALL of my stuff was gone. I'm now a level 40 player with nothing but a level 1 bow and my chestplate which somehow survived. I'M REALLY FRUSTRATED PLEASE HELP!!! (My username is _xX_Sienna_Xx_)

**Comment by MCtroller3936** [comment]
The level 1 bow is an untradable beginners item and my chestplate is a legendary Mummy's Rag. I assume i died, but i dont understand how because i logged off. Please give me an explanation

**Comment by MCtroller3936** [comment]
I still have soulpoints though

**Comment by Trixter313** [comment]
I agree that the situation appears that you died with less than 3 soul points at some point because you have the item you get when you die like that and the only thing that stayed was a soul bound item.

Does anyone else have access to your account login, have you logged into your account on a public or friends computer, or is it possible that your login credentials were hacked?

Wynncraft has a strict no refunds policy so unfortunately we can't give you any items back. I'd suggest asking around to see if anyone will give some items to you.

**Comment by MCtroller3936** [comment]
No one else has access to my account. I'm changing my password just in case.

**Comment by MCtroller3936** [comment]
Whelp, If i cant get my stuff back I'm probably quitting wynncraft.

**Comment by MCtroller3936** [comment]
bye

**Comment by Moe-Ronickah** [comment]
ONE Lv40 class?  This issue has happened to players with much higher levels.  We don't know exactly why the server thinks that you are still logged on when you disconnect, assuming that you did disconnect.  If you choose to leave, that is your choice, however, our policy remains the same.  If you choose to come back, you should ask for help, in-game.  Lv40 items are not expensive, not to higher level players.  There are plenty of players that would be willing to help you out by giving you emeralds, armor, and weapons.
