### ISSUE TITLE
Eruption bow was erased from reality.

### ISSUE THREAD

**Issue by RotDog** [Wynncraft/Issues#5673]
I had just acquired Eruption, the legendary bow, and sold all my other bows that had same elemental damage. I was randomly disconnected from the server soon after and when i logged back in, the bow was erased from my inventory.

One detail I noticed was how the disconnection text was red rather than white. Does that have anything to do with this? If there is a way to get the bow back that would be fantastic. Losing a legendary bow like that kind of sucks, man.

**Comment by LelliPazi** [comment]
I have also the same problem. I traded with one guy maelstorm, the World closed, I connected to another world and the bow was away. I really wanna have it back. it would suck very hard if it is lost forever now.

**Comment by RotDog** [comment]
Glad it's not only me. Hopefully the staff can refund our bows?

**Comment by LelliPazi** [comment]
I hope so. It was hard to farm for the trade...

**Comment by ColinRioux** [comment]
Even though it sucks that a system restart happened and you lost your stuff, I wouldn't be surprised if the staff still enforce the strict **No Refund Policy**.

As stupid and unfair as that may sound, I wouldn't be surprised if they continue to enforce it because if they gave exceptions to a few players, they would have to give it to the whole player base. 

Then again exceptions may happen, but @Moe-Ronickah can back me up on it.

**Comment by Moe-Ronickah** [comment]
I'm sorry, but WynnCraft has a no-refunds policy on items that are obtainable in-game and not purchased with real-world currency.  You might be able to find someone to buy your lost item from, or, possibly, someone who will even give you one, for free, depending on the value of your item.  Ask around in Detlas and check the Trade Market on the forums.  Good luck.
