### ISSUE TITLE
I Just Lost 9LE Due To Server Lag ~ TheRoyalCreeper

### ISSUE THREAD

**Issue by Creeper24-7** [Wynncraft/Issues#5685]
I'm a Level 60 assassin who spends a lot of time on this server, I do all the quests I get and usually keep all my rewards I get after a quest (This includes emeralds, quest items, armor, et cetera). I recently lost my 9 LE due to server lag which cause my LE to disappear in my bank/inventory. I spent a lot of my time on this server farming emeralds to trade for op items or armor but that was crushed due to is "Glitch". Please Help my Minecraft name is TheRoyalCreeper. If you owners or admins can fix this problem it would be very grateful to me and the other players. Thank You

**Comment by ColinRioux** [comment]
Wynncraft strictly enforces a no refund policy (https://forums.wynncraft.com/threads/have-you-ever-lost-your-items-in-game-and-want-to-get-them-back.143196/#post-1593529).

Please expand on your "glitch" if it's been a reoccurring issue, but the strict no refund policy still stands, glitch or not.

**Comment by Creeper24-7** [comment]
Thank You That really helped even tho this policy still stands :(

**Comment by Moe-Ronickah** [comment]
This is my boilerplate for lost items.  In your case, all that I can say is that I'm sorry that it happened.  I know how you feel.  I've lost quite a few items due to glitches, too.

"I'm sorry, but WynnCraft has a no-refunds policy on items that are obtainable in-game and not purchased with real-world currency.  You might be able to find someone to buy your lost item from, or, possibly, someone who will even give you one, for free, depending on the value of your item.  Ask around in Detlas and check the Trade Market on the forums.  Good luck."
