### ISSUE TITLE
Spawn Issues

### ISSUE THREAD

**Issue by IceCreamWiz** [Wynncraft/Issues#5687]
I was doing a quest in llevigar and i died. The, i respawned at the begginers spawn begind Ragni. Can you help me? Can you teleport me or something? Pls. I am lvl 44 and i don.t want to restart the game!

**Comment by ColinRioux** [comment]
You don't need to restart the game if you spawned near the Caravan Driver. These random teleports have been known for awhile, and they seem to me, at least, like random failsafes. 

I think you should be glad that you didn't lose your items or your class! It's not that hard to walk to Ragni like you did when you first started the class, and either walk to Llevigar or get a scroll from someone. 

In the future, if you do get teleported to the Caravan Driver. First check your quests, your level, and your items. If everything is there, then it was just a failsafe, and it's annoying. All you have to do is just walk! 

(P.S: Mods can't teleport you and won't teleport you. Admins won't either. You either do /kill or if you can, walk to where you need to go).

**Comment by Moe-Ronickah** [comment]
When a player dies, right now, they get teleported to the nearest city.  Since some of the quests teleport the player off of the main map, to a quest region, if they die, they will teleported back to the main map.  To the nearest city on the main map.  Wherever that happens to be.

This isn't a glitch, however, it is not a lot of fun, either, and the content team is working on fixing this, as far as I remember.
