### ISSUE TITLE
Not Getting Dialogue in the A Marauder's Dues Quest

### ISSUE THREAD

**Issue by Kettlekorn** [Wynncraft/Issues#5696]
I'm at the beginning of stage 2 of the quest A Marauder's Dues where you have to go confront the mage on a hill. When I got to that part I climbed the mountain where the mage's tower was and tried to interact with the mage but didn't progress. Then I looked at a youtube video quest guide for the quest and walked through the path, and still didn't get any dialogue. So I looked around on the forums and found someone who had the same problem. The problem was caused from climbing the mountain directly to the tower which was "cheating." But the problem was solved for him when he left and rejoined the server. I tried that, but it's not working.

**Comment by Kettlekorn** [comment]
I'm stuck...

**Comment by AckroWynn** [comment]
Go through each steps from the Youtube guide carefully, so that you do not accidentally miss a region.

**Comment by ColinRioux** [comment]
You can try: 
1. Climb up the mountain directly, and if **???** moves you from the area with a line of dialogue, then go to 2.  Otherwise, please be more specific about your issue.
2. Try climbing up the mountain via the path designed for the quest, and see if 4 lines of dialogue appears (if so, you are set!). 
3. Check your quest book and confirm you are still on the proper step. 
If none works: Switch servers or relog

If nothing prevails, please try and be more specific about your issue here. Thanks.

**Comment by Kettlekorn** [comment]
I did everything you said but nothing is working.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
