### ISSUE TITLE
Stuck in the void?

### ISSUE THREAD

**Issue by ItsWittle** [Wynncraft/Issues#5760]
Basically, I log in with my only class but I'm unable to do anything and I am stuck at some random coords with a Y coordinate of something like 86900000000000000000000000.

I can type in chat but can't do any commands either and I end up timing out after a minute.

![screenshot 19](https://cloud.githubusercontent.com/assets/21091311/17756308/0cac408a-64ad-11e6-92b3-0bc89c580e5e.png)

**Comment by Trixter313** [comment]
I'm not sure if it would help at all but could you try using 1.8.9 instead of 1.8.8? If that doesn't work we might need an admin who can teleport you back into the map.

**Comment by Trixter313** [comment]
Also, what is your Minecraft username? Thanks!

**Comment by ItsWittle** [comment]
I have 2 Minecraft accounts (Exlusion and DuoDynamo). But, the one stuck in the void is DuoDynamo, I've even tried 1.8.9 and it does not work. So, I think I'll need an admin to teleport me back into the map. Also, how should I contact you more conveniently (just in a faster manner without having to wait)?

**Comment by Trixter313** [comment]
Do you have auto join enabled? If so, log into the nether server through the sign in the lobby and try toggling it off.

I think this is the best place to communicate so that others can chime in with their suggestions and so admins can see what we've tried so far. I don't have the ability to teleport you into the map to fix this so we'll have to wait until someone who can sees your issue. @Moe-Ronickah should be by soon and will hopefully be able to help.

**Comment by Moe-Ronickah** [comment]
**JUST FIXED BY SALTED**
