### ISSUE TITLE
Ban Bug

### ISSUE THREAD

**Issue by MeteoritGaming** [Wynncraft/Issues#5801]
I made a Ban Appeal, i got unbanned on lobby2, but on the worlds and the rest of hubs not... I`m still banned

**Comment by Arthaness** [comment]
[I tien to clarify that I used Google Translate]

Hello, I tien at singaler a bug here:
I connect all the afternoons as to WynnCraft, and I see that I was banned. We do not write the reason and I am not connected to me for a very longtemp, and for the last time at 12:32. (When he told me I was banned).

Here I hope you solve the problem because I love Wynncraft.

thank you in advance

**Comment by Trixter313** [comment]
@Arthaness please create a post here for ban appeals: https://forums.wynncraft.com/forums/ban-appeals.84/

@MeteoritGaming are you still experiencing the issue? Sometimes issues like these clear themselves up after a little time.

**Comment by Moe-Ronickah** [comment]
Bans and ban appeals are not game issues.  If you have a problem with a ban or unban appeal, you must discuss it on the forums, with the staff member that banned or unbanned you.
