### ISSUE TITLE
Repeating Frozen Game

### ISSUE THREAD

**Issue by NickyB5** [Wynncraft/Issues#5806]
Hello,

I am very, very new to Wynncraft. I started an account yesterday. Every time I try to play, the game will work for about two minutes at a time, and then the entire game freezes for five to ten seconds. It happens often and makes the game virtually unplayable. 

Is this an issue with my computer/settings or is this an issue with the server? My render distance is low and my maximum frame rate is low.

Please help me!

Thanks.

**Comment by Trixter313** [comment]
Have you tried switching to another world? Also, could you give details about the freezing? Is it just everything around you freezing, is your player also frozen, etc.

If you're using a Minecraft version other than 1.8.9 try using 1.8.9 because other versions can cause issues in themselves.

**Comment by NickyB5** [comment]
I am using 1.8.9. I've tried a couple worlds but it's about the same.

Everything is frozen around me, inclduing my player. I am unable to move my mouse, look around, press esacpe, etc.

**Comment by YunoFGasai** [comment]
after the freezing stops what happens?
do all mobs remain in the place they were before the freeze or do they suddenly change positions?

**Comment by NickyB5** [comment]
Everything suddenly changes positions, like I am the only one who froze and the game went on without me.

**Comment by YunoFGasai** [comment]
I'm pretty sure that's due to poor internet connectivity

**Comment by NickyB5** [comment]
I think I may have to disagree, because my connection is not this bad on any other Minecraft server.

**Comment by Trixter313** [comment]
Hmm, usually when it's server lag the player can still move but when it's computer lag nothing moves.

I just noticed you said your max frame rate was set to low, you will want this to be higher, atleast at 60fps. If your frame rate is low it will look choppy because it can only show a limited number of frames per second. The more frames, the smoother the image.

If that doesn't help, could you try playing in single player and on another Multiplayer server to see if it still happens even when not on Wynncraft? Thanks!

**Comment by NickyB5** [comment]
I tried that.

I forgot to mention the main lobby before joining a world on Wynncraft is perfectly fine. The issues start right before I choose my class and the resource pack is equipped. It's almost as if my computer can't handle the server? I don't know what else to do. My frame rate is above 60 fps.

**Comment by NickyB5** [comment]
I am still having this issue. Sorry for double post but no one has responded in 2 days. Does anyone know what I should do?

**Comment by ColinRioux** [comment]
To be clear, you aren't playing on the beta correct? Because the beta server can cause some disruptions / game freezes / lag. 

If not, Wynncraft with it's texturepack, complicated models, and a bunch of other factors cause the server itself to be a memory hog (in other words, eats up your ram). I've seen it before. 

I bet it's memory based (as your client is trying to multitask extremely fast). Either you're not giving minecraft enough memory, you don't have enough ram available to compensate, or you have quite a few other programs running that's also eating your ram. 

Be mindful, althought you could have 4gb of ram. 1.5-2gb is probably being used for core processes and most browsers / other processors could use up to 500mb. That leaves minecraft with 1gb or less, which isn't enough (in my opinion) to run Wynncraft. For some people, it may work fine, for others, it can cause chaos.

**Comment by NickyB5** [comment]
Thank you for responding to help me.

My laptop has 8gb ram, so maybe that's not the issue? How would I go about checking specific settings to see if it would wok?

**Comment by NickyB5** [comment]
I am sorry but I am still having trouble with the second part.

How do I give it more ram?

**Comment by Trixter313** [comment]
http://www.minecraftforum.net/forums/support/unmodified-minecraft-client/tutorials-and-faqs/1871637-tutorial-allocate-more-memory-for-minecraft

**Comment by Moe-Ronickah** [comment]
@NickyB5 , unless you have program to continuously check your connection for dropped packets, you don't know how good or bad your connection really is.  It really does matter, and it can change very suddenly.

**Comment by NickyB5** [comment]
Okay, so I followed the tutorial and gave Minecraft 2gb ram, and then after that I tried 4gb.

The one thing I noticed from this is that the server was working perfectly until the music started. Once the music on the world starting playing, it started lagging again.

**Comment by Trixter313** [comment]
Does doing /toggle music make it not lag?

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
