### ISSUE TITLE
Fly Main Lobby Bug

### ISSUE THREAD

**Issue by AMCBrosky** [Wynncraft/Issues#5807]
When i go to hub from a server it will repeatedly get me in the lobby before sending me to a new lobby due to flyhacking but in the new lobby it will kick me again so i can't join any games.

**Comment by AMCBrosky** [comment]
also it only happens when i do /hub and it is a sometimes occurance

**Comment by coreynj** [comment]
Happens to me too. Hope they fix this, it's very annoying.

**Comment by ColinRioux** [comment]
@Moe-Ronickah

**Comment by Trixter313** [comment]
Make sure you're both using 1.8.9 to play and try using WASD to move immediately when logging in or hold shift. That has helped people experiencing this issue in the past.

**Comment by Moe-Ronickah** [comment]
You can do a search for this on the web, and you'll find thousands of posts about it.  There is no one-size-fits-all fix, because it's hard to pin it down to whether it's server or client based.  The only thing that is certain, is that, according to the server, you are flying.  Try turning your cable or sat modem off for 60sec, then back on, if you can, so that you will reset it.  Sometimes that helps.
