### ISSUE TITLE
Guild Prefix with Inviting. [Same Prefix]

### ISSUE THREAD

**Issue by CompactVenom12** [Wynncraft/Issues#5839]
I've been offline, which makes me think this is the reason..
I'v created a guild 9 months ago with the PREFIX / LIR, and have come to notice the second RANKED Guild has the same prefix, just not fully capitalized.. Which then makes it hard for me to recruit/invite members or friends. One of my friends tried joining the guild with the Prefix LIR(My guild) by the command /guild join LIR, after it stating to him he's been accepted..

[Proof of issue] https://gyazo.com/feccf0d5509b4ae3fae46332c4ac3dd3

**Comment by Moe-Ronickah** [comment]
This is a generic message concerning guilds and guild issues:
Guild mechanics are slated to be re-written.  All issues involving guilds will closed.  If you want to know if your guild issue has been reported already, please go back and do a search on "guilds".  From there, you will see all of the guild issues and you can check to see if your issue is known.
Only ONE current guild issue is being left open for reference purposes.  #3665
