### ISSUE TITLE
Can't use my old (pre-update) archer class!

### ISSUE THREAD

**Issue by MrGameNWatch13** [Wynncraft/Issues#5903]

**Comment by Trixter313** [comment]
Could you please provide us with more detail? Thanks!

**Comment by Moe-Ronickah** [comment]
Pre which update?

**Comment by YummyTaco** [comment]
This is happening to me right now. I believe he means the gavel update. This is my first time playing wynncraft after the gavel update and I cant login to my lv 52 archer. I click the archer class but it doesnt do anything and just gives me the error : There has been an error, Please try again, Select a class! Each class is saved individually across all servers, you can come back at any time with /class and select another class!". It may also be correlated with the fact that it says my archer has 105% xp which of course does not seem to be right. Pls Help

**Comment by Moe-Ronickah** [comment]
The Gavel update was a major change in the Wynncraft system.  You need to re-identify any armor or weapons that you wish to use.  After doing that, let us know if the problem is still happening.

**Comment by YummyTaco** [comment]
I think you misunderstood. Im talking about how I cant even login to my archer class. I try press the archer class but it just doesnt do anything and gives me the error i described before. If it helps I think my archer character may be corrupted due to the fact that it says I have 105 xp points in it. Any help would be appreciated. Id really like to fix this so I can enjoy the new update with my already leveled archer. @Moe-Ronickah

**Comment by Moe-Ronickah** [comment]
@MrGameNWatch13 , hello?  Do you still help?
@YummyTaco , I was not responding to you.  I am now: Is this still happening?

**Comment by YummyTaco** [comment]
@Moe-Ronickah yes it is

**Comment by Trixter313** [comment]
@YummyTaco see issue #5418
