### ISSUE TITLE
Stuck in the void

### ISSUE THREAD

**Issue by StrandedKnights** [Wynncraft/Issues#6022]
I'm stuck in a void where i can't do commands it happened when i bought 100 coins i already contacted wynncraft support about it, they said something about a refund what i did not do.. can anybody help me here?

**Comment by Trixter313** [comment]
Are you in the void when you first log into Wynncraft, before you even see the lobby, or is it just when you try to login to a world from the lobby?

Could you post a screenshot of your F3 menu so we can see your coordinates?

Also, can you log into the nether server? If so, try using the command /toggle autojoin and see if that helps.

**Comment by StrandedKnights** [comment]
When i join a world i spawn in the void where i cant do commands http://prntscr.com/ce45tf
and i cant join the nether world i glitch out the map when i try to join
because i cant pick a class

**Comment by Trixter313** [comment]
Does using 1.8.9 help at all? Other versions can cause issues in themselves. If that doesn't help an admin might have to help out.

**Comment by Moe-Ronickah** [comment]
At the moment, you are not the only one with this issue.  We are working on trying to find a fix, by pure experimentation.  We just don't know what is causing it.  You can follow it on #5539 , but I hesitate to call this a true duplicate, because we just don't know if it is really the same thing.

**Comment by Moe-Ronickah** [comment]
This is a generic message, to everyone affected by these issues.
I've discussed this with the admins, and it turns out, after a lot of investigation, that the 
problem lies within the saved data file created by Minecraft.  The data is corrupted.  For some
of you, your character data files are so badly corrupted that you cannot login and play on any
classes.  For some of you, only one, or maybe two, of your classes, are corrupted.

Well, here is what we can do, and you need to think seriously about the options that I am going
to tell you about, and what they mean.  First, our only possible fix for this is to WIPE your
character.  That means that ALL of your classes will be gone, along with ALL of your information.
That means EVERYTHING will be gone.  Any pets that you purchased, any unused item bombs, any
unused XP bombs, and any GC that you may have left, will be gone.  There is NO way that we
can recover that information before the wipe, so once it happens, there is absolutely no way
to go back and get it, either.  It just cannot be done.  The data file is corrupt.  We can,
however, go back through the store and recover your rank, if you have purchased one.  Your
VIP/VIP+ rank can, and will, be recovered.

So, here is your decision to make.  If you want to keep waiting to see if Minecraft ever will
make a tool to recover lost character information, and they haven't yet made one to recover
lost or corrupted worlds, you can keep on waiting.  Seriously, it's not a problem for us, as
it requires that we simply do nothing to your game account.  For those of you who have lost one
or two classes, the decision to wipe EVERYTHING means that you have to accept the fact that
you will lose ALL of your classes, ALL of your pets, if you purchased any, any bombs that
you may have, and any GC that you may have.  None of this is recoverable if your account is
wiped, however, you will be able to start over on all of your classes.

For those of you who cannot play on any class, you have the same decision to make for yourself.
  You can wait to see if Minecraft will ever make a tool to recover lost character data, with
the same considerations as above.  Minecraft has never made one, and there is nothing that
we have heard of to say that they ever will.  Or, you can choose to have all of your character
data wiped, with the same losses as explained, above, and we can, and will, recover your VIP/VIP+
rank.

So, for each of you, individually, let me know what you want us to do, and I'll pass along your
decisions to the admin, at the end of this week (Friday or Saturday).
