### ISSUE TITLE
Guild attack: mobs don't spawn on WAR. 

### ISSUE THREAD

**Issue by Jamesym100** [Wynncraft/Issues#6054]
Ok, so... My friends' guild and I have tried attacking multiple territories... not once have the defending mobs spawned, resulting in 10 minutes of running around looking for them....

We get sent into the war server and says mobs will spawn in 10 seconds, but none spawn... ever...

Are we doing something wrong? or is this a bug...

PS: I think it may have something to do with every territory having 1000 mobs defending it? is that a bug?

**Comment by ALEEEEEEEEEEX** [comment]
![soon](https://cloud.githubusercontent.com/assets/20970407/18283589/48982eb0-7466-11e6-8a73-ea74ad5b8238.jpg)

**Comment by Jamesym100** [comment]
wow, just wow...

**Comment by Moe-Ronickah** [comment]
We've got a lot of problems with guilds.  There will be a guild rework coming out, but we have no information on just when that will be.

**Comment by DragonEngineer** [comment]
yea this happens randomly.

**Comment by thecoolkogut4** [comment]
just a update. mobs don't spawn in gavel wars (territories added in with the gavel update) 100% of the time. mobs don't spawn in wynn wars (original guild territories) 85% of the time.

**Comment by Moe-Ronickah** [comment]
This is a generic message concerning guilds and guild issues:
Guild mechanics are slated to be re-written.  All issues involving guilds are on hold until guild mechanics are re-written, at which time ALL current guild issues will closed.  Current guild issues are being left open for reference purposes.

**Comment by Moe-Ronickah** [comment]
UPDATE:
This is a generic message concerning guilds and guild issues:
Guild mechanics are slated to be re-written.  All issues involving guilds will closed.  If you want to know if your guild issue has been reported already, please go back and do a search on "guilds".  From there, you will see all of the guild issues and you can check to see if your issue is known.
Only ONE current guild issue is being left open for reference purposes.  #3665
