### ISSUE TITLE
Can't join my friends guild

### ISSUE THREAD

**Issue by JustFl0w** [Wynncraft/Issues#6082]
when my friend send me a request to join his guild and I make /guild join VIA   it doesn't work.  :'(

sorry for my bad english and thanks for help <3

**Comment by LordHelmchen98** [comment]
Well related to guilds there are lots of bugs and glitches. Have you tried it more than once and what does it say? If your friend successfully sent you the invitation you should try it a few more times. If your friend cant sent you an invitation because it says that you are already in a guild I dont think there is a solution and I guess there wont be one until the guilds get an update.

**Comment by JustFl0w** [comment]
My friend sent me a request and I tried to join more then once, but it says all the time:  you were not invited to join VIA

**Comment by LordHelmchen98** [comment]
Hmm ok. So he sent you the invitation more than once as well?
Most of the time it works after a few attempts. If it doesn't Um afraid you have to wait until guilds are fixed which will hopefully happen soon™.

**Comment by JustFl0w** [comment]
as well other peopel can't join his guild :/   
and ok thanks
