### ISSUE TITLE
A Fighting Species bug

### ISSUE THREAD

**Issue by onurhanxd** [Wynncraft/Issues#6127]
I'm doing the A fighting species quest , came to the last boss "gorgu" . I died in boss room . It teleported me to tutorial area .Every single time :/ pls solve this bug

**Comment by Trixter313** [comment]
How many times do you mean by 'every single time'? The tutorial is the fallback teleport so you will sometimes be teleported there if there's an error but it shouldn't be happening all the time. Thanks!

**Comment by Moe-Ronickah** [comment]
Once again, this is due to the Wynncraft map layout.  When you are in a quest area that you have been teleported to, you are no longer within the boundaries of the main map.  If you die, you will be teleported to the nearest city, which, in this case, is the starting area.

The situation is known, and it cannot, at this time, be fixed.

**Comment by onurhanxd** [comment]
It Happened there times . btw thanks moe
