### ISSUE TITLE
Kill in chain and nothing can do...

### ISSUE THREAD

**Issue by kerpsolem** [Wynncraft/Issues#6161]
Hi, i was into gavel  when i just freez and can't move or do something i just die in chain to 1 soul point instantly and i just do alt+F4 when see this !!! 
Hope don't loose something :/ i was full armor and with chestnut horse 
I'm mage lvl 79 IGN: kerpsolem.

**Comment by kerpsolem** [comment]
Just reconnect... i'm not anymore in Cinfras wher i was... i lost a ring and unequipe my armor....and my boot (legendary stalagmites) is duplicate in my inventory.  Oh and i had 14 soul point... just loose it in... 1minute ? :/
Plz answer me

**Comment by kerpsolem** [comment]
up !!

**Comment by Trixter313** [comment]
It sounds like your game froze and something killed you.

Wynncraft has a strict no refunds policy so we can't return any items that might have been lost.

Although in the end, it sounds like very little was lost so that is good. It was most likely a one time issue but let us know if it happens to you again.
