### ISSUE TITLE
cant join using my mage class after very long break,

### ISSUE THREAD

**Issue by xx0martijnk0xx** [Wynncraft/Issues#6220]
hello i just joined wynncraft after a Very long break and i cant join the server using my mage (my main) but i can join using other classes but they are only lvl 5-10 and i really want to play my mage.
if i try joining my mage i get the error : there has been an error.... try again.
and then i get to rechoose my class
is there a way to fix this? i talked to mod moe and he said that i should post it here even though there are alot of similar reports.
 - De Martijn

**Comment by ColinRioux** [comment]
Well you should post it here, then it'll be queued so the developers can see it / work on it, or the community can resolve it. 

Right now, I don't have an answer for you, but @Moe-Ronickah may.

**Comment by Moe-Ronickah** [comment]
I'll have something to say later on, tonight.

**Comment by xx0martijnk0xx** [comment]
im still waiting for an answer is there anything i can do to solve this problem?

**Comment by Trixter313** [comment]
I don't believe there's anything you can do specifically, it's up to the admins to fix it.

**Comment by Moe-Ronickah** [comment]
I missed you on my list:



This is a generic message, to everyone affected by these issues.
I've discussed this with the admins, and it turns out, after a lot of investigation, that the
problem lies within the saved data file created by Minecraft. The data is corrupted. For some
of you, your character data files are so badly corrupted that you cannot login and play on any
classes. For some of you, only one, or maybe two, of your classes, are corrupted.

Well, here is what we can do, and you need to think seriously about the options that I am going
to tell you about, and what they mean. First, our only possible fix for this is to WIPE your
character. That means that ALL of your classes will be gone, along with ALL of your information.
That means EVERYTHING will be gone. Any pets that you purchased, any unused item bombs, any
unused XP bombs, and any GC that you may have left, will be gone. There is NO way that we
can recover that information before the wipe, so once it happens, there is absolutely no way
to go back and get it, either. It just cannot be done. The data file is corrupt. We can,
however, go back through the store and recover your rank, if you have purchased one. Your
VIP/VIP+ rank can, and will, be recovered.

So, here is your decision to make. If you want to keep waiting to see if Minecraft ever will
make a tool to recover lost character information, and they haven't yet made one to recover
lost or corrupted worlds, you can keep on waiting. Seriously, it's not a problem for us, as
it requires that we simply do nothing to your game account. For those of you who have lost one
or two classes, the decision to wipe EVERYTHING means that you have to accept the fact that
you will lose ALL of your classes, ALL of your pets, if you purchased any, any bombs that
you may have, and any GC that you may have. None of this is recoverable if your account is
wiped, however, you will be able to start over on all of your classes.

For those of you who cannot play on any class, you have the same decision to make for yourself.
You can wait to see if Minecraft will ever make a tool to recover lost character data, with
the same considerations as above. Minecraft has never made one, and there is nothing that
we have heard of to say that they ever will. Or, you can choose to have all of your character
data wiped, with the same losses as explained, above, and we can, and will, recover your VIP/VIP+
rank.

So, for each of you, individually, let me know what you want us to do, and I'll pass along your
decisions to the admin, at the end of this week (Friday or Saturday).

**Comment by xx0martijnk0xx** [comment]
i would like to keep my account just in case, is there any way i can get anything back from it? cause i can proof its a lvl 73 mage and i know for sure it has grian's ocean map cause i won it at the hide and seek with mods? @Moe-Ronickah
