### ISSUE TITLE
Canary calls glitch

### ISSUE THREAD

**Issue by legoman724** [Wynncraft/Issues#6236]
I was doing the canary calls quest and I had just finished the minecart puzzle(where you have to get it to the crack). I then went through the teleporter but my bottom half was stuck in a block, I tried /class and /server but I was still stuck, I just appeared to be out of it but still couldn't move. I then did /kill and apparently I entered Thanos according to the text on my screen but I was stuck in darkness, I tried using a Detlas tp scroll there it didn't work, when I then did /class I was in the starting area in the caravan(the area you spawn in when you create a new class). This glitch could be fixed by tping the player one or two blocks so that they fall a tiny bit but don't get stuck.

**Comment by Trixter313** [comment]
I believe that the beginning caravan is the fallback teleport location in case something goes wrong, so it makes sense that you might have been teleported there. The first teleport issue was because some quests teleport you out of the normal playing area. In the end it was most likely just a weird one time issue and we haven't received any additional reports of it.
