### ISSUE TITLE
horse glitch 

### ISSUE THREAD

**Issue by therpg-fighter** [Wynncraft/Issues#6243]
I was riding my horse and out of the blue i start taking damage then i die. (No enemy's near me, and i only have 2 soul points.) Then i lost my wand if you need prof of this i have attached a photo (Its named Broken Harp, also if its possible i would like it if you could replace my wand if its not its alright but i would be a big help if i can get it back, also i know this is long but i did change my name in MC its not herpscerplink.) Thank you for your time.
![2016-09-24_22 33 48](https://cloud.githubusercontent.com/assets/8964763/18812742/a49aa8de-82ab-11e6-9e0e-c9b83346f94b.png)

**Comment by Coooldude34u** [comment]
well, if tis not herpscerplink wtf is it? Plus, we can't help you. Wynncraft has a no return policy, sorry if you lost anything, but its gone. You probaly hit a fire block, or a flaming mob hit you

**Comment by Darkknio** [comment]
i sort of know what happened, your horse got stuck behind something but on your screen you were still running, so mobs were attacking you. If you got off your horse you would of got teleported back to the mobs attacking you. You can also tell when this happens because you horse no longer makes the running noise because it's stuck.

**Comment by Trixter313** [comment]
What version of Minecraft were you using to play? We reccomend using 1.8.9 as using other versions can cause issues such as this one with horses. Switching to 1.8.9 should prevent it from happening again.
