### ISSUE TITLE
Duping is very easy....

### ISSUE THREAD

**Issue by Raiku27** [Wynncraft/Issues#6262]
Hi,
[REDACTED]
If you need to contact me 
Ign: Raiku27

**Comment by LordHelmchen98** [comment]
So you found that today? Just curious because that was found already and should be fixed. At least for me its not working anymore, the items disappear as soon as I try to do anything with them. 
Anyway its a bug and if you keep them this would be considered bugusing so you are supposed to get rid of the items.
Also I think you are supposed to send an e-mail to the wynn-support if you found exploits, arent you @Trixter313? If so I guess this should be redacted.

**Comment by Moe-Ronickah** [comment]
Should I post an issue?

If your issue is related to individual payments or account support, please email support@wynncraft.com instead of posting the issue here.
# **_Pro Tip! If you think you've found an exploit, don't post the issue here. Instead, contact support@wynncraft.com_**
