### ISSUE TITLE
Stuck In Thanos Vault

### ISSUE THREAD

**Issue by ICHIGOunserscore** [Wynncraft/Issues#6265]
Im stuck in the Thanos vault with no scrolls and /kill just brings me to the thanos vault

**Comment by ColinRioux** [comment]
It brings you to Thanos. That's because it's the nearest spawn point. If that's what you are referring to, that isn't an issue. To leave, I suggest using the exit (as there is only one exit). (I'm assuming you're referring to the gold room). 

If you're referring to the part in the quest with the minecart, then that is a viable issue.

**Comment by Imaxe** [comment]
Just leave thannos. If you can't find an entrance, look at a video with someone walking around thannos. That might help

**Comment by Imaxe** [comment]
Did it work/help?
