### ISSUE TITLE
Resource Pack

### ISSUE THREAD

**Issue by Surfurdude** [Wynncraft/Issues#6276]
Hey, so I have read and done everything that the help page on the Wynncraft forums said to do. Every time I join the server, it doesn't want to load the resource pack even when I hit to accept, it never loads. I love Wynncraft and even purchased VIP a while ago. I would really love to play this game more but I can't if the resource pack doesn't want to load.

-surfurdude

**Comment by ICHIGOunserscore** [comment]
https://mega.nz/#!XxACWIZZ!yVagp9-tQrZl4eoZMUNKc_1qnwb4MpewXNtgB30zhkM
here you go

**Comment by ICHIGOunserscore** [comment]
Hello I have posted a fix a day ago can you close this issue now?

**Comment by Trixter313** [comment]
Also please make sure you're using 1.8.9 to play Wynncraft. Using other versions can cause issues.

**Comment by Moe-Ronickah** [comment]
@ICHIGOunserscore , as you are not staff on our server, do not be surprised if your posting of the RP is ignored.

@Surfurdude , check the forums for the past week or so, or do a search.  Someone posted a way to "fix" the RP, but you may get spammed with notices.  Also, the last RP was not compressed.  I don't know why.  The current may be, because load times are noticeably faster.
