### ISSUE TITLE
Losing items from login glitch

### ISSUE THREAD

**Issue by TheSandsofFlowingTime** [Wynncraft/Issues#6278]
I typed /lobby to go to the lobby and change servers before the server restarted. However, when I got onto the next server, I lost 3 of my items because the game thought I was too low of a level. This caused my items to be deleted because my inventory was full at the time. Here is a image of the chat log saying that I am too low of a level. You can clearly see my level is much higher than it needs to be for the items.
For those who want to know, my in-game username is tractoid

![2016-09-28_16 56 38](https://cloud.githubusercontent.com/assets/12890812/18937502/4d9294e4-859d-11e6-9b33-0ac4938dcd1d.png)

**Comment by Amariithynar** [comment]
Those are saying that your skill levels are required to be those levels, not your personal skill level. Still, it shouldn't be deleting your gear if you were wearing it- must be a miscalculation in how it factors in gear bonus stats.

**Comment by TheSandsofFlowingTime** [comment]
it could be, but since the game takes off the gear that you don't have the stats to equip... and you inventory is full, there is nowhere to put them, so they are deleted

**Comment by Amariithynar** [comment]
Yes, that's what I was talking about. Obviously his gear was giving him bonus stats that allowed him to wear it previously. So something went wrong.

**Comment by LordHelmchen98** [comment]
This is known as the skillpoint-glitch or short sp-glitch. Sometimes they game doesn't detect the skill points and says you don't have them so you can't wear the accessories. Sometimes the items drop but most of the time they don't. When gavel was released this was a serious problem because it was also possible to loose armor (Once I lost items worth a stack due to that glitch just because I was grinding and got kicked with full inventory and there are guys who lost even more). Later they fixed it regarding the armor but it is still not fixed for accessories. In future when you are changing/leaving servers you should take care you have as many empty inventory slots as you have accessories equipped that have skill point requirements.
PS: @Amariithynar you noticed that the first answer on your post was the OP?

**Comment by Amariithynar** [comment]
No I didn't, because I was really tired. x3

**Comment by Moe-Ronickah** [comment]
@TheSandsofFlowingTime , doubt that they were lost, actually.  Most likely, they either landed on the roof, on an upper floor, on the floor around you, are in a basement area.  This is still a pain to retrieve things, but they aren't deleted.  Been there, done that, panicked.

Also, from our front page:  A Word to The Wise: As of 5/8/2016, if you post an image that shows that you have entity radar turned on in a minimap, that information may be passed on to the game moderators, without further notice to you. Play Fair!

TURN OFF your entity radar.  (I'm a mod, so I don't need to pass it along to anyone.)

**Comment by Rockobar** [comment]
I hate to revive this thread, but this is still happening. When I logged in, didn't notice I dropped my Morph accessories and switched servers they are just gone, even though I have the skill level for them.

<a href="http://imgur.com/0g9A3nP"><img src="http://i.imgur.com/0g9A3nP.png" title="source: imgur.com" /></a>

Please fix this so players do not keep needing to buy new accessories.

**Comment by LordHelmchen98** [comment]
Yeah it still happens sometimes. It was fixed for armor but not for accessories. You should try to keep empty slots for every accessory with skill point requirement.

**Comment by Rockobar** [comment]
This is still happening, please try to fix this Dev team.

**Comment by Moe-Ronickah** [comment]
It is on the list of things to do.  Just be thankful that the initial fix stop the loss of armor.

**Comment by Moe-Ronickah** [comment]
duplicate
