### ISSUE TITLE
Bug knight

### ISSUE THREAD

**Issue by francaisfou31** [Wynncraft/Issues#6287]
Bonsoir, j'ai repris ma classe guerrier apres ne pas l'avoir pris depuis un moment, mais cela drop tout les items que j'avais sur moi ( armure, armes) et ils sont tous passé en unidentified, donc je suis allé a detlas pour pouvoir les remettres, ce que j'ai pu faire mais j'ai commencé a laggué, donc j'ai fais une déco reco  ,mais maintenant je ne peux plus me reconnecté, je peux allé sur le serveur, mais je n'ai pas le choix des classe, j'ai tout mes bloc d'émeraude sur moi ( normalement, je laggué quand j'essayé de les mettre dans l'enderchest, j'espere que cela les a pas droppé par terre, me ferais chier de perdre 37 blocs d'émeraude a cause d'un bug), on peut m'aidé?

**Comment by francaisfou31** [comment]
tout est revenue, mais j'ai perdu pas mal d'argent, vu que j'avais stuff légendaire ( botte) et rare sur moi...

**Comment by ICHIGOunserscore** [comment]
Bonjour mon nom est Ichigo_  je suis peur 
que vous ne pouvez pas obtenir votre blocs d'emeraude retour désolé


par la façon dont mon français est de retour alors ne me juge pas

**Comment by Trixter313** [comment]
This is intended behavior, there was an update that unidentified everyone's items because the item system was changed drastically.

Google Translated answer:
Ce comportement est destiné, il y avait une mise à jour des éléments de chacun non identifié parce que le système de l'article a été modifié de façon drastique.
