### ISSUE TITLE
Ice Barrows Dungeon Glitch/Intense Lag

### ISSUE THREAD

**Issue by Wolfpack74** [Wynncraft/Issues#6321]
hi every time that i do the Ice Barrows Dungeon with my friends as soon as we go into the boss battle we all freeze and experience intense lag and always die its pretty much impossible to beat the boss
please find a way to fix this so we can continue our quest to defeat all of the dungeons. 

Sincerely, wolfpack74

**Comment by NumeroPhobia** [comment]
Sometimes, I get lagspikes, and that's because of:

1. Too many entities going on
2. Your CPU or RAM is at 100%
3. Computer is handeling too much info

So eliminating one of these processes should fix it.

**Comment by Moe-Ronickah** [comment]
@Wolfpack74 , without knowing what your pc is, and it's exact setup, you are at an impasse, as this isn't happening on a large scale.  If I were you, I would try installing Optifine, making certain to not run Wynncraft on any version higher than 1.8.9, making certain that all of the optional settings in Minecraft were set to minimal distance.

**Comment by JuicedBananas** [comment]
I experience this as well sometimes, here's everything I can provide about my situation:

- This occurs when you enter the boss fight room, the lag begins when you are teleported to a black box, from which you are teleported into the boss room.
- The lag is not FPS lag, it is lag between the server and the client
- This only occurs when my connection is slower. My internet gets slower at night for some reason, during the day this doesn't occur.

My guess is that this is caused by the black box you are teleported to before the fight. The area it's in might be sending a large amount of data to the client at once, causing a lagspike.

**Comment by Moe-Ronickah** [comment]
The boss arena has too many ice blocks, and the issue is known.  Every face of every ice block needs to be rendered and that doesn't help lag, at all.
@AckroWynn , would you assign someone to fix this arena, and area, actually, by lowering the number of transparent blocks, please?  I know, I'm not going to make whoever built the area very happy.

**Comment by Moe-Ronickah** [comment]
RESOLVED
