### ISSUE TITLE
Returning, lost everything.

### ISSUE THREAD

**Issue by frankuck99** [Wynncraft/Issues#6343]
Hi, i left the game when the VIP changes happened. Gavel was not out yet, so i left i while ago.
I came back yesterday and noticed i lot all my armor, my wand was different, i had to identify my things and got really crappy stuff, is there a way i could get back the items i had before all the updates? I had some armor equipped and some in my inventory. The armor that was equipped disappeared, and i only had the items that were in my inventory that are not that good...help?

**Comment by LordHelmchen98** [comment]
Did you have a full inventory when you joined? Probably your equipped armor was removed from the armor slots because they werent identified. Normally they go to your inventory, but if your inventory is full they drop but there are some glitches that cause the item to spawn on a block above or below you and not next to you :/
You said your wand is different. How is is different? Other name or just a texture? If its the texture this doesnt mean anything to the functionality of the weapon. It just looks better.
Unfortunately Wynncraft has a strict norefund-policy so you cant get back any item. :/

**Comment by Moe-Ronickah** [comment]
@frankuck99 , this has all been reported and discussed, as was well warned about on the forums.  It's all part of the new update, and there is nothing that we can do about it.  Other than commiserate.  My Bad Wolfs went from 42%xp to 30%xp.
