### ISSUE TITLE
Quest Item Lost

### ISSUE THREAD

**Issue by ra3yvtc** [Wynncraft/Issues#6362]
I was picking up dropped items from the ground to check them out and my inventory was full so I said I will Drop my **Purple Crystal Shard ( Quest Item )** and then take it back and it was bugged and Lost it and couldn't find anywhere on the ground ... Help because I still **NEED** this item for further quests

**Comment by LordHelmchen98** [comment]
This is because quest items cant be dropped. They despawn instantly and should get it back to your inventory. Problem with this is that it cant be placed into your inventory if its full because you pick up something. You should try to do /fixquests. Normally you should get the shard back. Some players use this to glitch their items out of their inventory when they take too many slots but actually I wouldn't recommend that because you might need the quest item that you glitched out of your inventory for a later quest and if it happens that you don't get it back from /fixquests, there's no possibility to get it back except doing a second class until you get it again and use it for the first class.

**Comment by ra3yvtc** [comment]
@LordHelmchen98 Thanks that helped me out and it worked ! and thanks for the advice tho wasnt trying to glitch it out i just didnt know that they dont get thrown away till this happened

Thank you again

**Comment by LordHelmchen98** [comment]
You're welcome

**Comment by Moe-Ronickah** [comment]
@LordHelmchen98 - Nice answer!  Complete and correct information.  Thank you!
