### ISSUE TITLE
Dungeon Bug/Issue

### ISSUE THREAD

**Issue by Xycan** [Wynncraft/Issues#6385]
I was doing the Dungeon out side of Troms on World 27 and I accidentally dropped my wand near the hopper. This happened when I was dropping the dungeon tokens in the hopper. I tried to pick it up but it was sucked into the hopper. It was the Olux's Prize Weapon. Could you please fix this issue with the dungeons and please replace my wand. Thank You.

UserName: Xycan

**Comment by thecoolkogut4** [comment]
there is a strict no refund policy. you won't be getting your wand back.

**Comment by Imaxe** [comment]
It's not an issue, you just screwed up :P

**Comment by Moe-Ronickah** [comment]
@Imaxe , while your response might be technically correct, it is a bit of a harsh way to respond to someone.  Please be more considerate of the players when you respond to them, OK?.

@Xycan , because we have no way to go back and see what, if anything, happened, to any player, as thecoolkogut4 said, I'm sorry, but WynnCraft has a no-refunds policy on items that are obtainable in-game and not purchased with real-world currency.  We just cannot refund items that are lost because we have no way to check on anything like that.

Just to be safe, if you drop key is still "Q", please change it to a key that is far away from the movement keys.  I use "Delete" for my drop key, and I know of several people that use other keys, but all are far away from the movement keys.

**Comment by Xycan** [comment]
Thank you @Moe-Ronickah for your help. No offence, @Imaxe I really feel you were being a bit of an a**. Excuse me for that. I don't really care if I get the wand back I'll just get in touch with my guild and see if anyone has a better one. But could you please set up the hopper system in the dungeons so that only the tokens can be thrown in.

I know how redstone works and I could design a machine that would only allow the set # of tokens that you need. If a person is spamming the Q, or in your case the DELETE button, and server lag comes along and you throw in something that you didn't want to it is really upsetting. And Imaxe didn't make it better with that comment. 

I'm sorry if this was a hassle @Moe-Ronickah I see why the policy is in place and thank you again for the help.
