### ISSUE TITLE
Bug | Stuck on transport Boat

### ISSUE THREAD

**Issue by Meefz** [Wynncraft/Issues#6389]
Hi me and my friend have just been on two separate boats headed to nemract and selchar, both times the boat would not teleport us to our destination after about 5 minutes, so we had to use a detlas tp scroll both times.

**Comment by Meefz** [comment]
BTW on world 5 and someone else is also stuck here now

**Comment by Moe-Ronickah** [comment]
Are you still stuck, or did it fix itself when the server updated?

**Comment by redfoxkit** [comment]
I've had the same issue twice now as well. Wasted emeralds on boat passes that won't work.

**Comment by LordHelmchen98** [comment]
Did you start in Llevigar? I heard the one in Llevigar doesn't work sometimes. To start from any other place should work.

**Comment by redfoxkit** [comment]
Nope, I was traveling from Nemract.

**Comment by Moe-Ronickah** [comment]
Nothing has changed, and no new reports.  I'm at a loss.

**Comment by Moe-Ronickah** [comment]
RESOLVED

**Comment by TBlazeWarriorT** [comment]
Just had the same issue, captain dialogue actually seemed to work, but the boat didn't do anything at all. Not stuck, not teleported, no emeralds. Luckly another guy bought a ticket to somewhere else and I got a free ride, but it's still glitched.
Happened today, just switched to 1.8 because boats are broken in 1.11.2, not sure if its related to the issue, but going back to 1.11.2.
