### ISSUE TITLE
grass model is a glitch

### ISSUE THREAD

**Issue by syawal20** [Wynncraft/Issues#6402]
# Delete this line if you've followed the README instructions and searched for a duplicate issue FIRST, and before posting any new issue.

**Comment by LordHelmchen98** [comment]
What the hell did you do there? If you have a problem you are supposed to describe it. However despite the fact that you haven't written anything but the title I guess by 'grass model is a glitch' you mean that you have the problem that you see black and purple instead of grass. As this happens very often in 1.9 or higher I guess you are using one of that versions. Try to use 1.8.9 as wynncraft and the resource pack were made for that version and it works best if you are using it.
