### ISSUE TITLE
Bear Mask cannot been identified

### ISSUE THREAD

**Issue by spacesven** [Wynncraft/Issues#6412]
I have a bear mask in my bank account (buyed a loooooong time ago) and it's a set-item.

It cant be Identified

see: [https://puu.sh/rLVJ9/9a9b1a24b5.png](https://puu.sh/rLVJ9/9a9b1a24b5.png)

**Comment by LordHelmchen98** [comment]
Well I dont really know why it cant be identified but I guess its probably because you can only buy it with specific IDs and normally you cant identify it because those IDs are not supposed to be changeable.
I guess you have to buy a new one if you really want it. It can be bought on the Bear Zoo island for 48 emeralds. (location on the map: https://map.wynncraft.com/#/-374/64/-2465/min/0/0)

**Comment by Odnod** [comment]
It cannot be identified to to its current nature as a pre-identified item. When the gameplay update first came out along with the re-identification mechanic people reidentified items that were not supposed to be manually ided, such as qira shop items and dungeon items (the bear mask is one of such items.) Because of this, they made it so that pre-identified items can no longer be ided (re-ided.) Prior to the gameplay update, the bear mask had no ids, so when the update was released all old versions became unidentified items which cannot be identified due to the nature of the item.

**Comment by Trixter313** [comment]
Thanks for clarifying, so buying a new one should fix everything.
