### ISSUE TITLE
Guild statistics and attack not working. 

### ISSUE THREAD

**Issue by THISNAMEISAVAILABLE** [Wynncraft/Issues#6446]
Hi, my Minecraft name is "MC_Hacker", and I created a guild named "FaZe", but there is already a guild named "Faze" (mine is "FaZe"). because of that, the guild stats are wrongs
![2016-10-22_23 46 56](https://cloud.githubusercontent.com/assets/23004562/19622758/ee44dd80-98b1-11e6-8089-b1a5d9474301.png)
and I can't launch any attacks (fixed)
![2016-10-22_23 51 07](https://cloud.githubusercontent.com/assets/23004562/19622773/779c42bc-98b2-11e6-924f-ab57c40bae39.png)

**Comment by Moe-Ronickah** [comment]
This is just another one of the guilds-are-busted issues.  We have no idea when guilds will be recoded.

**Comment by Moe-Ronickah** [comment]
This is a generic message concerning guilds and guild issues:
Guild mechanics are slated to be re-written.  All issues involving guilds are on hold until guild mechanics are re-written, at which time ALL current guild issues will closed.  Current guild issues are being left open for reference purposes.

**Comment by Moe-Ronickah** [comment]
UPDATE:
This is a generic message concerning guilds and guild issues:
Guild mechanics are slated to be re-written.  All issues involving guilds will closed.  If you want to know if your guild issue has been reported already, please go back and do a search on "guilds".  From there, you will see all of the guild issues and you can check to see if your issue is known.
Only ONE current guild issue is being left open for reference purposes.  #3665
