### ISSUE TITLE
Weird bug

### ISSUE THREAD

**Issue by UnQualityAnime** [Wynncraft/Issues#6475]
So I got on and started farming as usual when I noticed something weird. In my inventory weapons were enormous, so I threw one on the ground and the bow was taller than me. Can someone explain this?

![2016-10-27_02 19 49](https://cloud.githubusercontent.com/assets/23092978/19756912/c99e3474-9bed-11e6-8faa-8b7981f2d408.png)

![2016-10-27_02 19 34](https://cloud.githubusercontent.com/assets/23092978/19756916/ce755838-9bed-11e6-8d75-5e70b5d4f5ed.png)

**Comment by LordHelmchen98** [comment]
Because I see that "Wolf shakes" message, I suppose you are not playing in 1.8.9 but a higher version. As Wynncraft is made for 1.8.9 and the resource pack as well, its recommended to use that version. There are many bugs which only occur in 1.9 or higher and thats why I think that may cause this bug.

**Comment by thecoolkogut4** [comment]
as lord said, this bug is happening b/c your on Mc version 1.9+. go down to 1.8.9 to resolve this issue

**Comment by DebugMC** [comment]
another 1! #7212
