### ISSUE TITLE
Taking of helmet in Underice

### ISSUE THREAD

**Issue by MeepMu** [Wynncraft/Issues#6492]
If you take of your breathing 2 helmet in the underice quest, you will be teleported to the start place (where you start when you crate a new character)

**Comment by Moe-Ronickah** [comment]
Well, you aren't supposed to remove the helmet during the quest as it's the check that you are allowed to be in that quest area.  It's a good thing to remember when doing ANY quest - don't remove any item that you needed in order to get in the quest area.
I'm sorry that you got bit by this check, however, it's part of the game mechanics.
