### ISSUE TITLE
powders

### ISSUE THREAD

**Issue by CheeseLover** [Wynncraft/Issues#6528]
Hey i found out that some of my powders will not stack so i have to trow a lot of powers away. can you fix this or is there a good reason why they woun't stack

**Comment by LordHelmchen98** [comment]
Most of the time this can be fixed by throwing both powders which dont stack out of your inventory on the ground at the same spot. You should be able to see them stick together after a few seconds. If that happened pick them up again and they now should stack up.

**Comment by CheeseLover** [comment]
kk thanks

**Comment by thecoolkogut4** [comment]
this is an explanation for your problem. 

Alright, let me explain you y'all why they don't stack and why we can't fix it.
So the way an online game works is with a client and a server. The client is you, the server is us. They talk to each other in order to make everything works. When a mob drops a powder, the server actually drops an inksac with the name FIRE 2. It then tells the client: "Yo, this inksac you see on the ground? It's actually a red dye." Same thing when you look at the item information: "Yo, if you see an element name with a number, just write all these powder info instead of just showing FIRE 2."

So the reason why they don't stack, is because you guys are mixing the old powder with a different name (Green Powder II) to the new ones (EARTH 2). The server goes: "WAIT A MINUTE CLIENT, YOU CAN'T STACK THOSE BECAUSE THEY AREN'T THE SAME ITEM AT ALL!". So unless we modify every old powder to the new names, it won't stack. It's kinda dangerous to modify items server-side, so we prefer changing it client-side only. You can however make them stack if you upgrade them.

**Comment by CheeseLover** [comment]
That's a really good explanation just in my cause it  isn't the case
Like today i got 2 tier 2 eath powders from grinding and they didn't stack but when i threw them on the ground the did

**Comment by CheeseLover** [comment]
But thanks

**Comment by Rockobar** [comment]
I believe it's just powders from Item bombs do not stack.

**Comment by thecoolkogut4** [comment]
it might be item bombs but if you had a powder before the update 99% of them won't stack

**Comment by LordHelmchen98** [comment]
I might be wrong but I think powers from relics or chest don't stack with those you got from mobs as well.
