### ISSUE TITLE
Bugged Item Weapon.

### ISSUE THREAD

**Issue by Cyanah** [Wynncraft/Issues#6538]
https://gyazo.com/b2146a75058de05cd77cac8e79ad65e4

Nothing more to say really... Might be fixed soon, but I think it's due to the damage received on the item...

**Comment by Trixter313** [comment]
What is the issue with the weapon, does it not function correctly now? Also does right clicking or trading the item fix it?

If it's just the durability and cosmetic everything should be fine.

**Comment by thecoolkogut4** [comment]
happens all the time, eve happend before the update. it's purely cosmetic

**Comment by Shadoweagle5098** [comment]
This cosmetic bug is affecting one of my weapons as well, maelstrom. It too has suffered a slight amount of weapon damage and it's portrait is now a diamond shovel. While it is not a huge deal, i want to know how to fix this small issue, or at least any thoughts on the matter.

**Comment by LordHelmchen98** [comment]
This is an issue with the item texture system that happens quite often now. The weapon works fine but doesn't have a texture. If you are playing in 1.9, weapons with that issue have those new item skins you can get by crates. It even switches through the skins if you hit players because then the durability goes down. However only you can see that. Others only see one of the skins.

**Comment by Moe-Ronickah** [comment]
As said above, the new skins are in 1.9, so, when playing in 1.8.9, the skins can get flaky, but it's only visual.
