### ISSUE TITLE
I LOST MY ??? ARMOUR URGENT!!!!!

### ISSUE THREAD

**Issue by CallMeSpoonZ** [Wynncraft/Issues#6576]
So i lost my fucking armour from the ??? quest im really pissed rn because i had great rolls that added up to 134% XP I dont know how tf i lost this gear but WHY WHY WHY please fix this i changed my class to archer played on it for a bit and then i went back to my mage and my ??? gear which i prev had on when i logged off was gone. PLEASE HELP /fixquests DOESNT WORK

**Comment by CallMeSpoonZ** [comment]
take away the 50% xp bonus u get from wearing all the armour! so that means its added up to 74% Xp bonus ik my helm was 21% xp bonus and my legs where 18% xp bonus not sure about boots but i think they where 21% XP bonus aswell no idea about the chestplate

**Comment by CallMeSpoonZ** [comment]
This staff honestly sucks 7 hours no staff has replied absolutley ridiculous.
i have evidence of the armour all i want is unided stuff at this point because im not getting my amazing Id'd stuff
![2016-11-02_00 56 31](https://cloud.githubusercontent.com/assets/22598219/20027318/a1a21b80-a308-11e6-851f-f70c81c0f229.png)
Un id'd Cosmic set without neclace is all i fucking want please for the love of god give me what i played 5 FUCKING HOURS FOR

**Comment by LordHelmchen98** [comment]
Sad as it is you are by far not the only one who faced this issue. Unfortunately wynncraft has a strict norefund policy which means you won't get back your ???-armor :/

**Comment by ColinRioux** [comment]
Going on that, Cosmic Armour, although given to you by completion of ???, is not a quest item. So `/fixquests` will not work.  

In terms of replying, only minimal staff will respond to lost item posts. Staff members generally won't respond these posts since there is a strict no-refund policy put in place to resolve it. It's unfortunate that there are no refunds, but it's just easier this way.  In the future, best to be patient. And move on.
