### ISSUE TITLE
Horse glitch + mob token glitch

### ISSUE THREAD

**Issue by mcdeathgod** [Wynncraft/Issues#6608]
Mob token glitch : https://www.youtube.com/results?search_query=Mob+token+glitching 
Always happens, sometimes the token doesn't spawn buy its deducted from my daily limit.
Horse glitch : Sometimes I appear to be okay, suddenly taking damage, I dismount and find myself 20 blocks behind where I originally was, and a mob was attacking me.

**Comment by LordHelmchen98** [comment]
Unfortunately the horse bug can't be fixed. Its because horses got client sided since 1.9. Every time you lag a little bit the server can't handle it and thinks you are at the place where you started to lag, but your client just continues with riding. Then you take damage because mobs attack you at the place where the server thinks you are. As you are VIP+ I think you can at least prevent to die if you use particles and ride in 3rd person. If there are no more particles around you, you are not at the place where the server thinks you are.

**Comment by Moe-Ronickah** [comment]
What's the mob token issue?  Mob tokens increase the number of mobs present depending on how many mobs were present when the token was dropped.
The so-called horse movement issue is a known MC issue, and duplicated many times in the GitHub.
