### ISSUE TITLE
Items Dissaperating

### ISSUE THREAD

**Issue by skulldude2004** [Wynncraft/Issues#6612]
I had just finished talking with Alice in Detlas and gotten the Creeper mask for the quest, after that I was kicked off for some reason (didn't say why) and when I got back on a stack of emeralds was missing (but some guy gave me a stack so it's good), the creeper mask which is needed for the quest, and an undenified chestplate from a set.

**Comment by skulldude2004** [comment]
And if someone could fix this fast that would be great because I love playing on your server

**Comment by ColinRioux** [comment]
Well to get your Creeper mask back, since it's a quest item, you can do `/fixquests`. 

That said, for your other items, there is a **strict no refund policy** enforced by Wynncraft. That means that all other items other than quest items are un-returnable. As sad as it sounds, it's for the best (and maintains fairness).
