### ISSUE TITLE
Owner requested now Buycraft glitch

### ISSUE THREAD

**Issue by blackmagic9988** [Wynncraft/Issues#6640]
So I was trying to buy Hero a water dragon and 10 crates and i was charged twice even though i only bought it once So i need you to pay back $114 to be exact otherwise my card will be shut down and I'll be losing money cause your webstore glitched and made me lose money.

Contact me over:
Skype Username: MagicalReaper
Gmail: blakedubois1998@gmail.com
Discord: https://discord.gg/Ebmbn
TeamSpeak username: blackmagic9988

**Comment by blackmagic9988** [comment]
Also I didn't recieve the first package which had my upgrade to hero from Vip, my water dragon pet I wanted, and my 10 crates. If you can fix this that would be very nice.

**Comment by blackmagic9988** [comment]
Also for skype I'm not Jakob or the Some weeaboo person

**Comment by blackmagic9988** [comment]
my ign in minecraft is blackmagic9988 so that also another way to contact me

**Comment by thecoolkogut4** [comment]
for any store/real money problems email support@wynncraft.com with your ign, transaction ID, and your problem.

**Comment by blackmagic9988** [comment]
I did yet I've not gotten an email about either transactions yet the only thing that caused this was buying from the buycraft since it was the only time i used my debit card in 3 months, and I know since today I had a rude awakening by my mom at 4am

**Comment by thecoolkogut4** [comment]
just wait for them to respond. there is nothing more you could do

**Comment by LordHelmchen98** [comment]
They are only humans just like you and me. You can't expect them to answer immediately as your case is not the only thing they have to deal with.

**Comment by blackmagic9988** [comment]
Still this is taking too long and I need my money back

**Comment by thecoolkogut4** [comment]
when you bought the stuff, you agreed to the terms of service which states "If you do not receive your virtual item in time that you deem reasonable then you are legally obliged to contact billing support by emailing support@wynncraft.com."  "Purchases may not be effective immediately due to response times from Buycraft’s IPN. Support for store purchases can be found by contacting billing support support@wynncraft.com" "Your payment will go to the running of the Wynncraft Minecraft Server service, and is non-refundable under any circumstances." You have to wait, as the TOS states you are obligated to email support. github is not support so we can not do anything here. the only help you will be getting is from support (thrugh email)
