### ISSUE TITLE
Horse ride bug

### ISSUE THREAD

**Issue by SnailRace** [Wynncraft/Issues#6656]
When you go on your fast horse you will get tp back after a while. Plz fix this because you need horses.

**Comment by Rellia** [comment]
No this is a minecraft multiplayer bug. Any transport aids such as horse or boat on multiplayer can get buggy from just Minecraft if you don't have a perfect connection to the server. Wynncraft can't do anything about this. Horses aren't necessary. There are teleports or you could actually be patient

**Comment by SnailRace** [comment]
Yeah but, before the BIG update everything was fine. and in the days than I had not better internet but still everything was fine.

**Comment by SnailRace** [comment]
Its just Microsoft.

**Comment by Rellia** [comment]
Well unfortunately it's not an issue that the wynncraft team can attend to

**Comment by thecoolkogut4** [comment]
there is actually a real easy fix to this! join Mc version 1.8.9 to fix horses (in 1.8 some item textures with be broken, and boss bar will be broken)

**Comment by LordHelmchen98** [comment]
Actually it's a correlation between 1.9 and 1.8. In 1.8(.9) horses are serversided and in 1.9 they are clientsided. Unfortunately if you use 1.9 your horse gets stuck if you have minimal lags. The server thinks you are at a position but you are at a different position because your client just continues with riding although the server thinks you are standing still. This can't be fixed by the wynncraft staff except by running the server in 1.9 completely.
