### ISSUE TITLE
My Horse Lvl Skipping! 0/100 stayed in XP

### ISSUE THREAD

**Issue by MrVrezerJustPRO** [Wynncraft/Issues#6689]
Please Help me :(
-----------------------------------
Horse Remain Brown Help What should I do ???

**Comment by LordHelmchen98** [comment]
Can you please this a little bit more precisely. And maybe take a screenshot of your horse item.

**Comment by MrVrezerJustPRO** [comment]
![dwqqd](https://cloud.githubusercontent.com/assets/23459678/20277518/97e93ddc-aaa9-11e6-84a2-ce80c0b4a10f.png)

![qdwd](https://cloud.githubusercontent.com/assets/23459678/20277535/a4494ab8-aaa9-11e6-9968-3a9481d0e2b9.png)

**Comment by Rellia** [comment]
Did you try to upgrade your horse by crafting two together and it came out brown? Because that's supposed to happen sometimes. You don't always upgrade.

**Comment by ColinRioux** [comment]
Hi, let's clarify a few things. 

**Horse level is completely separate from it's colour**. When you gain experience from riding your horse, and your horse levels up, the speed and jump height of your horse increases. When you reach level 10 (on a brown horse), however, you don't get anything as a result except a max speed and max jump height value. 

Now, you were expecting to get a **black horse** it seems... well you don't get a higher tier horse by maxing your current horse. 

There are a few ways to get a black horse: 
1. You can buy one from another player
2. Or you can breed one yourself. 

Breeding works like this, you buy another horse at the horse merchant in Ternaves, and combine them in your inventory crafting menu. As a result, you will get a new horse. However, breeding isn't guaranteed everytime. You have a 20% chance to get the next tier horse you desire, a 50% chance to get the same tier horse you currently have, and a 30% chance to get a lower tier horse. 

For more information, please see [https://wiki.wynncraft.com/index.php?title=Horses](here).

Closing this issue as it's more of a mis-clarification rather than an actual bug.
