### ISSUE TITLE
Quest potion making issue

### ISSUE THREAD

**Issue by BlinkH** [Wynncraft/Issues#6709]
Essren says bring me 8 red mushrooms yeet I have and I've done the quest before on the same class and it still says the quest is still not done plz fix

-BlinkH

**Comment by thecoolkogut4** [comment]
maybe you were walking to almuj one day or grinding right beside the guy and click him by mistake? I know I've done that before.

**Comment by BlinkH** [comment]
Yeah might be that

tors 17 nov. 2016 kl. 13:54 skrev TheDarkSoul <notifications@github.com>:

**Comment by Moe-Ronickah** [comment]
That quest was updated not too long ago.  If you haven't redone it, then, yes, he's going to ask you to do the quest.

**Comment by BlinkH** [comment]
k but when I give him 8 red mushrooms he just says the same line again and
It doesn't make sens

2016-11-17 19:39 GMT+01:00 Nathan Stolov <notifications@github.com>:

**Comment by Imaxe** [comment]
@BlinkH  he will say the same line when he wants an item due to our quest system. In stage 1 he needs the mushroom, then he tells you to enter his house and kill his master and take his coat. Also requesting an item.
Thats why he is saying the same line.

Yeah, and you probably completed the quest before the Gameplay update where we remade it

**Comment by BlinkH** [comment]
Ok how do I fix? it it's in the Quest book and everything

mån 21 nov. 2016 kl. 16:30 skrev Imaxe <notifications@github.com>:

**Comment by Moe-Ronickah** [comment]
The quest was updated, and the quest books reset the quest.  Do the quest, and the quest will show that it is completed.
