### ISSUE TITLE
Broken library key

### ISSUE THREAD

**Issue by TheSilverTide** [Wynncraft/Issues#6722]
After using once the Library Key it breaks, it looks like the key is no more "visable" for the doors :/

**Comment by LordHelmchen98** [comment]
Did you switch the server or do /class between the two tries? If so it might be a NBT-tag issue. There are several items that don't work because of wrong NBT-tags after changing the server or doing /class.
Also is the broken library key the one you need for the library in Llevigar after the Fortuneteller quest? If so you can find threads about the lore on the forums.

**Comment by TheSilverTide** [comment]
Yup it is this key and im not intrested in lore, i just want access to the chest.

**Comment by ColinRioux** [comment]
I'm not too familiar with the key, but could you get the key again, and then make sure to not change classes or servers when use it?

**Comment by LordHelmchen98** [comment]
@ColinRioux You need the reward of the Fortuneteller quest to get that key.
And @TheSilverTide I can't remember any chest so what's the thing with that chest? However if it's just a random loot chest or not, I'm afraid there is no way to get in there again unless you do the quest again.

**Comment by TheSilverTide** [comment]
Or somebody will fix it, i'm sure it should be possible to use as many times as you wish if not it should disappear after 1 use. :/

**Comment by LordHelmchen98** [comment]
Yeah probably it should be able to use the multiple times and maybe someone will fix this in future, but to be honest I don't think this has a very high priority on the fixit list.

**Comment by Moe-Ronickah** [comment]
The key is only meant to be used once, to get the reward, and no more.
