### ISSUE TITLE
Cant identify my main weapon (legendary spear lv75)

### ISSUE THREAD

**Issue by Rooodyy** [Wynncraft/Issues#6761]
Sooo, i started playing Wynncraft 3 years ago and stopped it as i got my warrior to level 75. Now someone told me that almost everything changed and i logged in. Now when i want to use my "unidentified spear" it says "You must identify this item before using it" But after i clicked the NPC Item Identifier and want to drag the spear in it he says "I cant identify this item! It can not be reidentified."

help me pls
ign:Rood_StAr

**Comment by thecoolkogut4** [comment]
what item do you think it was? Bob's mythic  spear?

**Comment by Rooodyy** [comment]
ye i guess so, back then every level 75 guy got a legendary weapon. this is the weapon im trying ti identify. i think it was bobs mythic spear

**Comment by Rooodyy** [comment]
https://wiki.wynncraft.com/index.php?title=Bob%27s_Mythic_Weapons
pretty sure it was bobs mythic spear

**Comment by LordHelmchen98** [comment]
When gavel was released. They implemented a new weapon stat system that you most likely have already seen ingame. Back then all items that weren't normal items were changed to unidentified items. This includes Bob's mythics or any other item that can only be bought with specific stats. Unfortunately those items can't be (re)identified because they are not supposed to have different stats than the ones that can be bought from the merchant and if your item was a Bob's mythic spear that's the reason why you can't identify it.

**Comment by Rooodyy** [comment]
wow thats total shit

**Comment by LordHelmchen98** [comment]
Yeah and you are not the only one facing this issue.
