### ISSUE TITLE
why did im banned

### ISSUE THREAD

**Issue by wolfspririt231** [Wynncraft/Issues#6769]
Sometimes I was walking in the map and the server just disconect my. IM banned !!! Why ???Can you unban my pls ??

**Comment by LordHelmchen98** [comment]
What happens if you try to log in? Does it say you are banned or another message?
If it says you are banned then first read [this](https://forums.wynncraft.com/threads/%E2%9C%8E-appeal-submission-guide-%E2%9C%8E.89247/) and then post an appeal [here](https://forums.wynncraft.com/forums/ban-appeals.84/).
