### ISSUE TITLE
I keep dying more than once at a time!

### ISSUE THREAD

**Issue by JD1ggity22** [Wynncraft/Issues#6777]
For one example, i died in the Tower of Ascention with seven soul points. I came back finally with one soul point and i lost my awesome blue mask along with my royal cyclone amulet. Can i get them back? i had a 0% chance of losing my ID-Items it said.

**Comment by LordHelmchen98** [comment]
Due to the strict norefund policy of wynncraft you wont get back anything. In my opinion this really should be fixed thogh.

**Comment by Moe-Ronickah** [comment]
First, @JD1ggity22 , your title implies that this has happened to you before this report.  Has it?
Second, the 1.14.1 Gameplay Update, from Aug 23, 2016, states "Soul Points system has been reworked. Now instead of dropping everything at 2 SP and less, you will have a chance to drop your item the less soul points you got. Don’t worry, nothing of value should drop until you reach 5 SP, and horses will never drop."
Third, are you telling us that, even though you died in ToA, that you kept coming back, even when you had only 1 soul point, and trying to fight your way through it, again, even with multiple warnings that you would drop EVERYTHING when you died and got to zero soul points?

**Comment by DJNothing** [comment]
I think Multihit can kill you even after dead.
Happened to me sometimes

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.  If you are still experiencing this issue, you can open a new bug report.
