### ISSUE TITLE
game crashed while i had 31 decrepit keys i relogged and didnt have them 

### ISSUE THREAD

**Issue by Blights666** [Wynncraft/Issues#6778]
im not sure what happened but i had just finished the decrepit sewer dungeon and was about to do it again when my game crashed and i had 31 decrepit sewer keys on me when i crashed so i opened minecraft again and rejoined the server but when i got back into the server and joined one of the worlds i no longer had any of the 31 decrepit sewer keys that i had i was just wondering if there is any way someone could give me new ones to replace them or something? if you can replace them then my username is (there is an underscore in front of my name as well but when i put two it makes it into italics font so yea xD ) "   Blights_   " so yeah.. thanks for taking time out of your probably very busy schedules to read this minor problem. =)

**Comment by thecoolkogut4** [comment]
the server has a strict no refund policy. you wont be getting your keys back from staff any time soon. sorry :/

**Comment by Blights666** [comment]
Refund? No I didn't buy these I've been grinding for them by killing the mob that drops the keys or is that what you meant?

**Comment by LordHelmchen98** [comment]
The norefund policy means you don't get back ingame items it's not related to real life currency. There are no exceptions to prevent people from saying they lost something although they never had it to get it for free. Unfortunately this also applies for people who actually lost their stuff due to bugs or glitches.

**Comment by LordHelmchen98** [comment]
The norefund policy means you don't get back ingame items it's not related to real life currency. There are no exceptions to prevent people from saying they lost something although they never had it to get it for free. Unfortunately this also applies for people who actually lost their stuff due to bugs or glitches.

**Comment by Moe-Ronickah** [comment]
RESOLVED
