### ISSUE TITLE
My skill points got screw over. 

### ISSUE THREAD

**Issue by BlockyM** [Wynncraft/Issues#6786]
I have a total of 82 skill points and i have those points evenly distributed for my strength, defends, intelligent, and Dexterity which mean 20 in each. (excluding agility cause i don't use that skill much) but then all the sudden there was a massive lag in the server and all the sudden the amount of points i have for strength and defend and dexterity sudden decrease to lower than 20 and gave no option to add back the missing points other than resetting the whole character skill points. I try reset the skill points and manually putting them back in back everytime the server would glitch the points and mess it up. I try doing that over and over 3-5 times but it still doesn't fix it, so if possible I would like to ask a staff to fix the issues and fix the characters skill points.  IGN: BlockyM978

**Comment by Moe-Ronickah** [comment]
After you logged off and back on, did this still happen?

**Comment by olle707** [comment]
I can confirm that this is still a problem and has not been resolved. Happend to me yesterday. Some of the "books" require you to directly 5 points at a time before even showing upp, and then they appear with max 2 points. Adding one point at a time doesn't work at all, the points just dissapear. For me i cant get the Agility book to show up no matter how many points i shove into where it should be. I really hope they get this resolved soon as it literally makes it impossible to play right now (cant use wands and armor due to skill requirements).
Problem persist after both relogging and reseting skill points.

**Comment by LordHelmchen98** [comment]
Are you playing in 1.11?

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.  If you are still experiencing this issue, you can open a new bug report.
