### ISSUE TITLE
wheres my crate

### ISSUE THREAD

**Issue by SagaLord** [Wynncraft/Issues#6790]
When i got on today i decided to go into my player menu to open up my daily crate since i have Vip+ but once i opened it ,it glitched out and didnt give me the item please help me get my crate or the item back thank you

**Comment by ColinRioux** [comment]
Wynncraft enforces a strict no-refund policy, which even applies to daily crates. It's a daily crate, so you should be able to get another item tomorrow. 

If you feel that it's unfair, especially since you donated, you're welcome to email support@wynncraft.com. There is no guarantee that they'll get back to you, or will refund it.
