### ISSUE TITLE
Double boss spawn :'(

### ISSUE THREAD

**Issue by Rellia** [Wynncraft/Issues#6796]
(I have got screen shots, but I don't know how to access minecraft screenshots... it's really weird)
I was in the realm of light, and to retrieve the seed of darkness, you have to kill a spider to spawn a witherboss to kill. Well, the multiple kills thing where you kill a mob and then accidentally hit it again and it counts as killing twice, yeah it spawn two level 100 bosses, which made that fight hell...

**Comment by Moe-Ronickah** [comment]
Congratulations!  Double the bosses, double the fun!
On a more serious note, this can happen, and it is due to a mechanic that prevents mobs that are dying, from becoming ghosts, due to them regenerating health while they are in their death animation.  The admins are aware of it, however, we no information as to whether or not this will be altered, because the ghosting is so much worse.

For all things Minecraft, including where to find your screenshots, [http://minecraft.gamepedia.com/Minecraft_Wiki](http://minecraft.gamepedia.com/Minecraft_Wiki)

**Comment by LordHelmchen98** [comment]
@Moe-Ronickah Is this also the reason why there is a chance to get two or even three wybels in the wybels lab altar?

**Comment by Moe-Ronickah** [comment]
Yes.

**Comment by AscendedKitten** [comment]
This issue hasn't been replied to in over one month, and there've been no further replies.
If the problem still persists, feel free to open a new issue!
