### ISSUE TITLE
Stuck in a 1*1 wall!

### ISSUE THREAD

**Issue by SlashTheRekter** [Wynncraft/Issues#6804]
i was riding my horse (not like that) trough nesaak when the terrain didnt load i jumped off it and got stuck in a 1*1 hole in the wall. Scrolls wont work and i tried having a duel with my friend and he killed me but nothing happend D:

Please send help! 

Cheers, Fab

**Comment by LordHelmchen98** [comment]
I guess you were using 1.9+. In those versions horse bugs are quite common. Wynncraft was made for 1.8.9 and thats the version with least bugs and glitches but you cant see totems or item reskins.. Anyway if you can tell coords a builder might be willing to fill that hole.
To get out of it just do /kill if you have more than 5 soul points.

**Comment by ColinRioux** [comment]
Well, to be more specific, Wynncraft's _current_ version **is** 1.8.9. The reason you can join with higher versions is due to a plugin that modifies the proxy so clients running higher versions can join. Due to new minecraft versions that Microsoft/Mojang has released (version 1.9 or higher), there have been plenty of new features added, as well as more animations and effects (i.e, boat and horse effects). Because the server is coded for 1.8.9 features, the new 1.9+ features don't work properly, yielding bugs relating to horses and boats. 

Report the hole [here](https://forums.wynncraft.com/threads/community-project-filling-holes-open-3-closed-56.123931/).
