### ISSUE TITLE
Detlas' Legacy (wand) glitch

### ISSUE THREAD

**Issue by SAT9** [Wynncraft/Issues#6805]
I recently started using Detlas' Legacy (the legendary wand for lvl 25) and every time I want to open a loot chest while it is my hand it says (in red): 'You do not have permission in this area' and would not let me open the loot chest. Since I got the wand through a trade with my friend, he was able to tell me that he was having the same problems with the wand as well.
Cheers, SAT9

**Comment by LordHelmchen98** [comment]
Duplicate of #3902
This happens due to the weapon being a retextured half slab. The game thinks you want to place it, but you are not allowed to. Thats why you get those messages. There is not fix that I know of and mostly its just spamming your chat and wont let you open chests or doors while holding this weapon. Thats annoying but I think you can endure it.

**Comment by thecoolkogut4** [comment]
one way of preventing this *i think* is to not drop your items on the ground, and if you want to open a loot chest use your soulpoint (or any other item) instead of your weapon. Once a item has this bug, i dont think it can be removed...

**Comment by SAT9** [comment]
so it can happen with any item?

**Comment by SAT9** [comment]
anyway thanks!

**Comment by LordHelmchen98** [comment]
No it can not happen with every weapon only with every weapon which is a retextured half slab. All the other weapons (retextured wood logs, wool blocks, ....) should work normal.
