### ISSUE TITLE
I lost "Hide of Gregg'r".

### ISSUE THREAD

**Issue by SwagBoyZeeeks** [Wynncraft/Issues#6807]
Hello i am SwagBoyZeeeks.

I was resetting my Skill Points. (Because i wanted to get my Intelligence higher)

So i pressed the button then some of my armour was dropped on the ground because i didn't had the requirements. But then "poof" my "Hide of Gregg'r" was gone, not on the ground i searched long, but it was just gone! I was alone in the room so nobody was been able to pick it up.
(It happend in Llevigar)

Mcname: SwagBoyZeeeks

Thanks for reading,
SwagBoyZeeeks

**Comment by LordHelmchen98** [comment]
Probably there were some blocks above you and it spawned up there. Unfortunately issues like this happen quite often due to how it's coded.
However wynncraft has a strict norefund policy and just like all the others before you, you won't get back your item. At this level it shouldn't be that hard to replace your chestplate tough.

**Comment by ColinRioux** [comment]
Hide of Gregg'r requires 10 agility and 15 defense, so that's why it dropped, if you were confused. In terms of you chestplate, sorry about it, but we still enforce a strict no-refund policy (like @LordHelmchen98 said).
