### ISSUE TITLE
item and xp bombs were cancelled at server reset

### ISSUE THREAD

**Issue by ryanscottcausecast** [Wynncraft/Issues#6814]
i lost my actively running xp and item bombs when the server reset.  both of those were running without about 15 minutes on them.

**Comment by ColinRioux** [comment]
Being more specific, did the server simply: "restart" or did it "crash".

**Comment by legoman724** [comment]
How does one lose time on an item bomb?

**Comment by LordHelmchen98** [comment]
I assume by item bomb he meant a loot bomb

**Comment by Moe-Ronickah** [comment]
I'm sorry, the servers are NOT supposed to reset when a Double XP or a Double Loot bomb are running, however, there are some situations where a server may crash, or may need to be forcibly closed due to another issue.  You can contact [support@wynncraft.com](support@wynncraft.com), and tell them about this, because this involves real world money.  We cannot guarantee that they will be able to do anything about this, as that level of support has their own rules and guidelines.

**Comment by DebugingLonks** [comment]
This happend to me too, haven't bought xp bombs since lol
