### ISSUE TITLE
Get teleported back to Llevigar on quest

### ISSUE THREAD

**Issue by archie426** [Wynncraft/Issues#6822]
If you die in Old Selchar, you get teleport ed back to Llevigar which is a long way away from Nemract (Where you get back to Noduj to get back to Craftmas Island to get back to Old Selchar). This is costing a lot of money and it would be helpful for you just to teleport back to Craftmas or Nemract. Sorry if this is a duplicate. 
Specs:
Windows 10 64-bit Pro
Running with Wynnpack

**Comment by LordHelmchen98** [comment]
Unfortunately this is an issue with the entire current respawning system. Old Sechar is offmap and therefore Llevigar is the closest town to Old Selchar. That's why you respawn in Llevigar.
Maybe they will change this system in the future, but until this happens I recommend you take Selchar scrolls with you.
By the way there is a quest called Shattered Minds. It is in the Light Forest and if you die while doing it you get teleported to the very beginning of the game to the guy at the caravan and there are several other examples.

**Comment by archie426** [comment]
Ah, thanks

**Comment by LordHelmchen98** [comment]
Yeah unless you have more questions related to this issue.

**Comment by archie426** [comment]
Closed
