### ISSUE TITLE
i think i am bugged in the staff world 

### ISSUE THREAD

**Issue by StrandedKnuigt** [Wynncraft/Issues#6848]

**Comment by StrandedKnuigt** [comment]
Sorry for no discription but like i can do any commands and i keep falling to the void

**Comment by Rellia** [comment]
What staff world?

**Comment by StrandedKnuigt** [comment]
like with some buildings and stuff with Welcome to the AFK Room and and ender chest with nothing in it
this has been a bug for me since i made a bouth something on the buycraft site and force refuned it due to gitches with the gold,

**Comment by ColinRioux** [comment]
What are you x y and z coordinates?

**Comment by Villageacules** [comment]
@StrandedKnuigt can you tell me what your X Y and Z coordinates, also try /kill.

**Comment by Moe-Ronickah** [comment]
"since i made a bouth something on the buycraft site and force refuned it due to gitches with the gold"
In other words, you cancelled a purchase, creating a charge back situation.

You will need to contact `[support@wynncraft.com](support@wynncraft.com)` in order to start to fix this issue.  We will not, and cannot, assist you with this issue.
