### ISSUE TITLE
The Canyon Guides (Quest) Not working

### ISSUE THREAD

**Issue by MCHologram** [Wynncraft/Issues#6867]
Quest is at Stage 4 (last step):
https://cloud.githubusercontent.com/assets/24495388/21074577/cc90db64-befc-11e6-9016-092a3c30cd6f.png

I'm at the right coordinates;
https://cloud.githubusercontent.com/assets/24495388/21074580/cffde508-befc-11e6-9597-056662bc2b62.png

Gana won't finish the quest:
https://cloud.githubusercontent.com/assets/24495388/21074582/d23b6156-befc-11e6-8ad2-0e86eed8a1e5.png

Explanation:
When i first brought Seluc back to Gana, I was teleported to a room with Gana and Seluc as NPCs, up to there all was fine.
Then I decided to switch servers because I wanted double exp.

After logging on server 1, I get glitched on top of Gana's house and can't get back in and I was stuck in a superflat world. I kill myself, come back to Gana's house and can't complete the mission.

EDIT: I got the quest working after bringing Seluc back to Gana's house again.

Thanks for understanding,

MCHologram

**Comment by LordHelmchen98** [comment]
If you try to enter the final room the game detects if seluc is with you. If he is not you just walk in if he is you get teleported. Therefore you didnt get teleported when you tried to enter it again right after you killed yourself.
Also note that double xp isnt working for quests anymore since they removed it with the gameplay update.

**Comment by Villageacules** [comment]
@MCHologram Is this still happening?

**Comment by MCHologram** [comment]
I redid the quest on double exposure weekend by just bringing delicious
back and I got teleported, thanks for the help 😄
