### ISSUE TITLE
green skinned trouble death warp glich

### ISSUE THREAD

**Issue by weshuiz** [Wynncraft/Issues#6878]
when doing the quest called **green skinned trouble** i noticed death warp glich this is what you need to do
1 gain acceses to the ruins that comes with the quest
2 get defeated by the mobs in that area

Upon death the player will respawn in the intoduction area
this is the location where new commers begin thier adventure 
i think the ruins are located under the spawn area when defeated the game is made to warp you to the closest homepoint in that case the spawn area of the server!

**Comment by LordHelmchen98** [comment]
That happens due to the respawn system. When you die you get teleported to the closest 'town'. If you start a class and die you get teleported to that guy at the caravan. The area in green skinned trouble is offmap and apparently close to the starting area of Wynncraft so if you do get killed the caravan is the closest respawn point and that's why you got there.

**Comment by weshuiz** [comment]
did you fully read me report? i already explained why and how it happend but it should not happen

**Comment by LordHelmchen98** [comment]
woops Im sorry I made a mistake I was trying to avoid
well you could search and find lots of thread with the same issue and it probably wont be changed very soon. but maybe they change it in an upcoming update.

**Comment by weshuiz** [comment]
no need for sorry people make mistakes all the time
if enough people report thiis mind of stuff the devs will sure notice it :)

**Comment by LordHelmchen98** [comment]
They already know about it but there are more important things (bugs, content,...) which have to be fixed/done first.

**Comment by ColinRioux** [comment]
Reporting stuff numerous times can be merely annoying, but this has been occurring for the last year or more now, and it's apart of this super duper long list that Jumla is fulfilling. So, expect it to be fixed in the future, but not this instant. 

Of course, like @LordHelmchen98 said, it's a trade off. They can either give us new content, or they can give us fixed bugs.
