### ISSUE TITLE
Broken Texture?

### ISSUE THREAD

**Issue by InsertnamespaceHere** [Wynncraft/Issues#6891]
I don't know if it's my Minecraft, But I'm getting pink and black blocks (Broken texture), How'd I fix it?

**Comment by LordHelmchen98** [comment]
This can have different reasons. If you are playing in 1.8 you probably can't see the item skins because they are not compatible with 1.8 and only visible in 1.9 or higher. If you see pink and black blocks on the ground it's an issue with tall grass textures that happens in 1.9 and higher. You might be able to fix it by deleting the 'legacy' file in your server resourcepack folder or download the 'legacy' file here in this repository and replace the one in your server resourcepack folder. If that doesn't work you can play in 1.8

**Comment by InsertnamespaceHere** [comment]
Kk thank you love you
