### ISSUE TITLE
Cant identify my old item

### ISSUE THREAD

**Issue by FighterZ** [Wynncraft/Issues#6980]
I have played wynncraft since before the update, and when i came back i can identify all my items except my bob mystic dagger. It says that the item can't be reidentified, but i when i want to use it, it asks me to identify the item. Can someone pls help me.

**Comment by ColinRioux** [comment]
Unfortunately, Wynncraft enforces a strict no refund policy. That means they won't give you a new version of the dagger. 

Since level 75 is no longer the level cap, you should be able to either buy the same item for cheap or will get a better dagger in the future. 

But thanks for noting this issue.

**Comment by FighterZ** [comment]
okey thxx ^^
