### ISSUE TITLE
Bugged item in my enderchest/inv

### ISSUE THREAD

**Issue by Bouncer91** [Wynncraft/Issues#6990]
i am a mage lvl 44 and i had an item that was funktion normaly and now its bugget in my inv my IGN is artvin_boy and its called devoresue and its is a staff that is not working please help me

**Comment by LordHelmchen98** [comment]
I've never heard of a possibility to fix this. It broke due to the previous name 'Dévoreuse'. Now it's called Devoreuse without the ´ on the e. You have to search for a new weapon and as your old one is useless you can either throw it away or keep it as a souvenir but you are not allowed to sell it.
