### ISSUE TITLE
Reclaiming The House Emerald Reward Glitch

### ISSUE THREAD

**Issue by Cooldjkid** [Wynncraft/Issues#7031]
I know there are 4 issues stating this already but I'm going to make it 5 as it seems it is presumed fixed now. The Reclaiming The House Emerald Reward Glitch.
What I should of got:
+200 000 Experience Points
+6144 Emeralds
+Access To The Outpost

What I got:
+200 000 Experience Points
+2176 Emeralds ( I think not too sure how many I had on me ).
+Access to The Outpost

Quest Reward:
![2016-12-29_11 50 00](https://cloud.githubusercontent.com/assets/24204957/21536519/e483abf4-cdbe-11e6-886e-ed6fdee16000.png)

My Inventory After The Quest:
![2016-12-29_11 51 22](https://cloud.githubusercontent.com/assets/24204957/21536533/0b0c4c54-cdbf-11e6-855e-be54dd8125cc.png)

I've looked at the previous 4 issue threads but it looked like it was thought to be fixed since then but it isn't.
I hope this can be solved.
~ Cooldjkid

**Comment by LordHelmchen98** [comment]
Probably you got 32eb which is 2048 emeralds. I'm pretty sure when they revamped the quest they changed the emerald reward but so far nobody changed the dialogue at the end of the quest.

**Comment by Cooldjkid** [comment]
I know this isn't true because I did the quest with my friend and he got the full reward

**Comment by LordHelmchen98** [comment]
Oh sorry I mixed it up with another quests.
Anyway in those other threads about Claiming the House I found a reference to #3562 which says you might not get the full amount of emeralds if you already have emeralds in your inventory. You said you already had some so that could be the reason.
However Wynncraft enforces a strict norefund policy. Therefore you won't get the emeralds back.
