### ISSUE TITLE
Level 1 spawn at High Level

### ISSUE THREAD

**Issue by ShadowScheme1** [Wynncraft/Issues#7043]
When I was doing the Quest "Hunger of Gerts Part I" I tried to go in the main camp with the gert helmet. I tried to go inside with the helmet but it didn't let me, so I relogged. When I did that however I ended up back at the first area you are at level 1. I'm not sure how this has happended but this is annoying me
![2016-12-30_10 57 49](https://cloud.githubusercontent.com/assets/24365295/21570009/50474506-ce7f-11e6-99aa-d408621b9f53.png)
![2016-12-30_10 58 05](https://cloud.githubusercontent.com/assets/24365295/21570013/5d20ba3c-ce7f-11e6-8c06-d02fdbf5424e.png)

**Comment by LordHelmchen98** [comment]
Normally you should just get teleported outside the area, but apparently something went wrong. In case some teleporting stuff doesn't work like it should Wynncraft puts you to the beginning of the game. That's why you got to the caravan guy.
Are you sure you are trying to enter the correct camp? Because you need the enter the main/big camp in The Hunger of Gerts Part II.
