### ISSUE TITLE
My bow skin doesn't work apparently

### ISSUE THREAD

**Issue by Minimeep1** [Wynncraft/Issues#7055]
It's the phoenix bow skin, a godly skin from crates.

What I see:
![bow](https://cloud.githubusercontent.com/assets/24835401/21579293/a7618c26-cf64-11e6-958c-66b911189325.png)

What other people see:
![2016-12-31_15 57 54](https://cloud.githubusercontent.com/assets/24835401/21579284/56956eca-cf64-11e6-9884-31f074cfc169.png)

**Comment by Minimeep1** [comment]
Also, it isn't just what one person sees, multiple people have told me it looks like this.

**Comment by LordHelmchen98** [comment]
I assume those other persons were playing in 1.8. This is not a bug because unfortunately the item skins are not compatible with 1.8 (just like the totems by the way) and can't be shown. Therefore you just see a black and pink block instead of a cool retextured item. However if they were playing in 1.9 or higher they would see the skin.
