### ISSUE TITLE
Help me!

### ISSUE THREAD

**Issue by Bubenheini** [Wynncraft/Issues#7057]
I m (Bubeneheini) in lobby 6 and cagedin a wall pls help me pls.

**Comment by DebugingLonks** [comment]
This doesn't go on github :P if you need help just do /hub

**Comment by Numbermaniac** [comment]
Just use /kill if you have more than 5 soul points.

**Comment by DebugingLonks** [comment]
Hes in lobby lol

**Comment by Numbermaniac** [comment]
oh right lol. Disconnect and reconnect would respawn you in the lobby default spawn point.

**Comment by LordHelmchen98** [comment]
@DebugingLonks actually I don't think he was stuck in a lobby ;)
First of all you can't really get stuck in the lobby as you always spawn above the ground when logging in and in the lobby there are no plugins that have potential to get you stuck. And he said lobby 6 but there are only three lobbies. That's why I assume he was talking about server 6 and said lobby instead of server and therefore /kill with more than 5 soul points would be the correct option. :)

**Comment by DebugMC** [comment]
detective helmenchen.

**Comment by LordHelmchen98** [comment]
Pff stop saying helmenchen ;)
