### ISSUE TITLE
Horses bug...

### ISSUE THREAD

**Issue by Symfynx** [Wynncraft/Issues#7069]
I know this was an issue from 1.9, but I recently started playing Wynncraft again and I am currently using 1.11. I am unable to find any thread of people saying they are using anything after 1.9 and its broken, so this is me saying it is. Its the same bug from awhile ago where riding a mount client side and server side would be different.

**Comment by ColinRioux** [comment]
This bug is present for all versions 1.9**+**. The key symbol is the plus sign. Certainly there may be some open (or closed) issues that only specify 1.9. But general rule of thumb is: if you don't want the horse glitch play on 1.8.9 (Wynncraft's hard coded version). Unfortunately, you won't be able to see gear skins, but the horse glitch will go away.
