### ISSUE TITLE
Cant complete quest/quest rewards gone

### ISSUE THREAD

**Issue by WinterBsg** [Wynncraft/Issues#7075]
On the quest memory paranoia, I completed killed the final boss and obtained the mister caritat's letter, while i was talking to the npc to finish the quest, in the middle of the talking the server crashed and when i log in back my quest item is gone, but it says i have not complete the quest. and to find the boss i have to complete the whole quest again which unfortunately, is a puzzle quest.

When i went into the mansion i got this equipment called Papyrus, i identified it and got xp bonus 28%, i re-identified and got 39%xp(Max xp), but what happened next is that the server crashed again, and i log in back to another server my Papyrus is gone. normally i wont really care about a equipment but this Papyrus got max xp bonus.....

**Comment by TheActa2r179h** [comment]
same happened to me, with 1000 meters under.

**Comment by thecoolkogut4** [comment]
Hey there, unfortunately Wynncraft enforces a strict no-refund policy. That means you won't be receiving your items back. However, thank you for reporting the bug.

**Comment by WinterBsg** [comment]
Oh comon it is max xp bonus......
Alright then rip xp


But seriously can i get a free tp to the boss room. Somehow? Cause that puzzle spent me 2+hours and i forgot how to solve the puzzle..

**Comment by WinterBsg** [comment]
But i lose the quest item and papyrus due to server crashed. Not on our own
Plus also spent quite a bit on identifying papyrus

**Comment by thecoolkogut4** [comment]
for the puzzle code, just look the quest up on the wiki and it will tell you it.(sorry can't link it I'm on my phone). to get the quest item back (if it was a QUEST ITEM and not UNTRADABLE) do /fixquests  to get it back.

**Comment by WinterBsg** [comment]
*It is a item dropped by the FINAL boss to complete the quest. Fixquest wont work :(

**Comment by thecoolkogut4** [comment]
so then you would need to "follow your footsteps" and find a way to get back to the boss. you will need to repeat a part of the quest to get there. if you need help finding the way you can look up the quest on the wiki.

**Comment by LordHelmchen98** [comment]
Use [this page]https://wiki.wynncraft.com/index.php?title=Memory_Paranoia) to see where you have to go in Memory Paranoia. You don't need to talk to NPC's just walk to all the points where you get teleported.
But as @thecoolkogut4 said Wynncraft enforces a strict norefund policy. Therefore you won't get your Papyrus back. Although that may seem unfair for you it actually keeps up the fairness among all the player because it prevents people from saying they lost something and want it back although they never had it in order to get an advantage compared to other players.
