### ISSUE TITLE
Annoying horse glitch

### ISSUE THREAD

**Issue by Equuary** [Wynncraft/Issues#7083]
Whenever i ride my horse, at some point i regonize that the music has stopped and chunks stops loading, then i get off my horse and teleport backwords stuck in somethere. Please fix it its very annoying

**Comment by DragonHunter1202** [comment]
this happens to me all the time while I ride my horse ;-;

**Comment by LordHelmchen98** [comment]
I dont think this can be fixed very easily because its related to the mc version. In 1.8 horses are server sided. Thats why you get bugged back when the server lags as long as you are using 1.8. But in 1.9 and upwards horses and boats are client sided which means you are able to ride without bugging. However as Wynncraft is running on 1.8.9 the server cant handle players with 1.9 while lagging because when the server lags only a little bit you would bug in 1.8. Instead of bugging you just continue to ride if you are using 1.9+ and then your position in your client and the position on the server are different. That leads to your issues: you get teleported to a different place when you dismount or you can even die while being on your horse because mobs can attack you where the server thinks you are but in your client there are no mobs around. As I said its hard to fix it because Wynncraft would need a huge update that enables Wynn to run on 1.9.

**Comment by DebugingLonks** [comment]
And this would cause dual wielding kappa. immagine if you could hold 2 walkspeed items kappa

**Comment by ColinRioux** [comment]
This is a duplicate issue of #6077. In fact, this has been occurring since the release of 1.9 and since Wynncraft released 1.9 compatibility. Going on what @LordHelmchen98 and @DebugingLonks said, because horse and boat mechanics have been significantly altered in version 1.9, and it's a 1.9+ exclusive feature, it will not work on a 1.8.9 server. Until Wynncraft is updated, this will remain that way.
