### ISSUE TITLE
Bug in Havan Antiquity

### ISSUE THREAD

**Issue by SlimeOre123** [Wynncraft/Issues#7087]
in the alive island in the quest you're getting the Monster Hides to Siwel and after talking with him, he still saying he want you to take a look at the egg and bring the Monster Hide, while the quest book say "Return to the old Siwel in the dead Mansion..... 
here is the photoes http://prntscr.com/dr0shg http://prntscr.com/dr0uku

**Comment by ColinRioux** [comment]
Have you gone to old Siwel?

**Comment by LordHelmchen98** [comment]
Go back into the tomb. You will get teleported to the present again and then you can talk to Old Siwel.

**Comment by SlimeOre123** [comment]
I know what do i need to do but they need to fix it :P

**Comment by LordHelmchen98** [comment]
If you are talking about that guy telling you the same over and over again although that part of the quest was done, I have to disappoint you because I heard a GM saying that they can't fix that kind of bug. And as the quest book tells you what to do I don't really think it's that much of a problem.

**Comment by Moe-Ronickah** [comment]
@SlimeOre123 , this isn't a game in the usual sense, it's an MC plugin, on top of MC.  We are limited to certain things that we can and cannot do.  Right now, we can't get NPCs to do that kind of branching in their dialogue.
