### ISSUE TITLE
Invisible block on Pirate's Cove that shouldn't be there.

### ISSUE THREAD

**Issue by DeleteTheFox** [Wynncraft/Issues#7093]
When i was doing a quest i noticed that in the skull you enter to complete the quest on pirate's cove, there was an invisible block closing the hole in the stairs, if you go there are others holes you can fall, but in this one that's an invisible block.

https://cloud.githubusercontent.com/assets/24701383/21628352/ed92aeac-d205-11e6-8f6d-ed94982eddfb.png

It's a small thing and doesn't really matter to much, the location that a found it was the first stair you need to go to complete the quest. Just search around.

And also that is a chest that can't be open near the entrance (I have already saw someone making a thread about it and i'm supposing it got fixed)

**Comment by LordHelmchen98** [comment]
Yes the chest got fixed.
@Imaxe

**Comment by Imaxe** [comment]
Chest is fixed. 
I removed the barrier block, the block was there to stop a player from falling and getting trapped because the hole was originally inescapable but that got changed, someone just forgot to remove the barrier block.
This is all fixed now and will take effect when we update again. 
Thanks for reporting issue!
