### ISSUE TITLE
"You dont have permission for this area"

### ISSUE THREAD

**Issue by Symfynx** [Wynncraft/Issues#7097]
I was going to the secret arena by the jungle village, and after entering the room before the arena, I got stuck. I am no longer able to interact with things such as chests, buttons, or doors. It gives me an error which I put in the title.

**Comment by ColinRioux** [comment]
Hi,

Easy answer, do `/kill` with 5 or more soul points. You'll spawn in the nearest town.

**Comment by Symfynx** [comment]
Hrm. Alright ty.

**Comment by LordHelmchen98** [comment]
I guess /kill got you out of that place but if you want to interact with buttons, doors, chests... again you have to use an empty hotbar slot or another item. This bug is caused by your weapon which most likely is a retextured half slab. The game thinks you want to place it but that's not allowed obviously so you get that permission error that prevents you from interacting with anything using that specific item.

**Comment by Symfynx** [comment]
Yeah I got out, and thats exactly what caused it. Lol.
