### ISSUE TITLE
Horse Bug/ Getting stuck like every 30 seconds

### ISSUE THREAD

**Issue by MinorexTV** [Wynncraft/Issues#7133]
Dear Wynncraft Team,
When ever i am traveling with a horse, most of the times the Chuks infront of me suddenly stop loading. Then i get of my horse and i find my self facing against a wall or an other obsticle. You can also notice this bug, if you are riding on your horse and suddenly the coordinates that are shown above your xp bar stop changing. Then its the same as with the chunks not loading. So for me its really hard to travel with my horse efficienly, because i get stuck every 30 seconds or something like that. The bug is more likely to happen, if you are going trough a forrest, than traveling on an open area. I would love to get this bug fixed. Other then that i love your server and i enjoy so much to playing on it, that i will soon buy me a rank to support you guys. I hope that money can help you, fix this really anoying bug. 
Sry for my bad english, im german. Thanks in advanced, Yours MinorexTV

**Comment by LordHelmchen98** [comment]
This is related to the mc version. In 1.8 horses are server sided but in 1.9 and upwards horses and boats are client sided. As Wynncraft is running on 1.8.9 the server cant handle players with 1.9 while lagging because when the server lags only a little bit you wouldn't move in 1.8. Instead you just continue to ride if you are using 1.9+ and then your position in your client and the position on the server are different. That leads to your issues: you get teleported to a different place when you dismount or you can even die while being on your horse because mobs can attack you where the server thinks you are but in your client there are no mobs around.

**Comment by almendris** [comment]
A mi me ocurria lo mismo , juega en 1.8 que van perfectos

**Comment by LordHelmchen98** [comment]
@almendris please try to talk in english.

**Comment by thecoolkogut4** [comment]
short form of what lord said: join the server on Mc version 1.8.9 to fix it.

**Comment by LordHelmchen98** [comment]
maybe I should add a tl;dr to this text xD

**Comment by thecoolkogut4** [comment]
I did it for you, don't worry haha 🙄

**Comment by LordHelmchen98** [comment]
ye but for upcoming threads ;)

**Comment by ColinRioux** [comment]
This issue should be patched last night. Closing now. If a new issue arises, please confirm your issue isn't already posted, and post it.
