### ISSUE TITLE
Can not play at all

### ISSUE THREAD

**Issue by Jonzka** [Wynncraft/Issues#7144]
Hello

So i have been trying to play in Wynncraft for two years, and i have never got to be in the actual game.. i have been running around the lobby.

So, the problem is: I select a class and then it takes a few seconds and then it says "There was an error... Try again" and then i try again, i tryed every class, but still nothing, the same repeats over and over again.

My minecraft name is: Jonzka

**Comment by ColinRioux** [comment]
Hi, please read through the issue here: #5418 . All the way to the end, including all the comments. @Moe-Ronickah has a comment there which describes the issue you're having more in detail. To summarize, your class data most likely has been corrupted, causing an error. In #5418, the steps to get everything squared away should be there. If by chance, you get no response in a week, message Moe_Ronickah on the forums directly, linking the issue.
