### ISSUE TITLE
My Bob's mythic daggers

### ISSUE THREAD

**Issue by ichwichseimmer** [Wynncraft/Issues#7155]
While I was in wynncraft helping a friend of mine doing a quest I used my mythic daggers and after the quest was over I thought it might be a good idea to reorganise my inventory so I tried but while I was doing this my internet thought it would be a good idea to crash which made it happen that I after I didn't have lag anymore I didn't have my bob's mythic daggers anymore can I please get it back?

**Comment by DebugMC** [comment]
Hey there, sorry that this happened, but wynncraft enforces a strong 'no-refund' policy. Therefor you will not get your items back. Thank you for reporting the bug however.
(Just posted that first of all)

Now, Bob's Weapons are tradable. Meaning, since you were 'helping your friend' they should have seen you drop the item. Also, people CAN sell it to you since it is tradable.
