### ISSUE TITLE
More lists of bugs

### ISSUE THREAD

**Issue by DebugMC** [Wynncraft/Issues#7160]
More bugs for my list I posted a while ago (I thought it should be a separate issue.)

- Mobs burning to death drop armor (known bug)
- Bob can die from wooden sword explosion (Causing bug # 1 apparently)
- Powder from combining, powders from relics, powders from bombs, and powders from drops don't stack.
- Tier 4-6 relics don't give the right item. (It is tier 1-3 now no matter what)
- Dual wielding can cause item deletion
You can glitch out the map (not saying how I will show a moderator how) AND NO I AM NOT USING THIS 
(ik the rules lol just wanted to report)
- Stars on items are wrong (2-3 only)
- A 20 stat on a blue mask can have no stars
- WynnExcavation Site A is not working right. (Ask others)
- Boats are sinking
- Dueling still can kill you
- Potions can be named Heal1-3 and stuff
- Mana Steal doesn't work 

- more to come in comments if I find more

**Comment by thecoolkogut4** [comment]
-Tier 4-6 relics don't give the right item. (It is tier 1-3 now no matter what)
Powder tier 4-6 relics give the right item, they dont give that exact tier. Im not sure about the #'s but there is a % chance you get a tier 1,2,3,4,5, and 6 powder from a relic. You dont always get a tier 6 from the relic.

-Stars on items are wrong (2-3 only)
Things with low stats (mana regen, tier attack speed, etc) work like that.
To quote exactly how it works, 1 star means 100%-124%, 2 stars means 125%-129%, and 3 is max, 130%.
1/4*110% =1.10/4, which rounds up to 2/4.
1/4*125% =1.25/4, which rounds up to 2/4.
1/4*130% =1.30/4, which rounds up to 2/4.
so a item could be max but with */**/*** due to rounding. which results in a 20 stat on a blue mask possibly having no stars

-WynnExcavation Site A is not working right. (Ask others)
/fixquests?

-Boats are sinking
patch the hole in the boat so it wont sink haha? just use 1.8.9 to fix it.

-Dueling still can kill you
happens due to reflection/thorns

-Mana Steal doesn't work
doesn't work when you use spells, only works when you melee the mob.

-more to come in comments if I find more
looking forward to the new list.

**Comment by Numbermaniac** [comment]
> 1/4110% =1.10/4, which rounds up to 2/4.
1/4125% =1.25/4, which rounds up to 2/4.
1/4*130% =1.30/4, which rounds up to 2/4.

You might want to use backslashes to escape those asterisks, otherwise they seem to be turning into italics.

**Comment by DebugMC** [comment]
Okay xD here we goez to reply.

-Powder from combining, powders from relics, powders from bombs, and powders from drops don't stack.
#5871 

**I know i'm just listing bugs known and unknown lol**

-Tier 4-6 relics don't give the right item. (It is tier 1-3 now no matter what)
Powder tier 4-6 relics give the right item, they don't give that exact tier. Im not sure about the #'s but there is a % chance you get a tier 1,2,3,4,5, and 6 powder from a relic. You don't always get a tier 6 from the relic.

**I asked XavierEXE and they said thats not intentional**

-Dual wielding can cause item deletion
#6800

-Stars on items are wrong (2-3 only)
Things with low stats (mana regen, tier attack speed, etc) work like that.
To quote exactly how it works, 1 star means 100%-124%, 2 stars means 125%-129%, and 3 is max, 130%.
1/4110% =1.10/4, which rounds up to 2/4.
1/4125% =1.25/4, which rounds up to 2/4.
1/4*130% =1.30/4, which rounds up to 2/4.
so a item could be max but with // due to rounding. which results in a 20 stat on a blue mask possibly having no stars

-WynnExcavation Site A is not working right. (Ask others)
/fixquests?

-Boats are sinking
patch the hole in the boat so it wont sink haha? just use 1.8.9 to fix it.

-Dueling still can kill you
happens due to reflection/thorns

-Mana Steal doesn't work
doesn't work when you use spells, only works when you melee the mob.

-more to come in comments if I find more
looking forward to the new list.

**Comment by DebugMC** [comment]
New bugs: As of 1/15

Some quests grey text (that describes actions) are in white (see [here](https://gyazo.com/d93154ccad519161001dcec52797270e))

Barriers are too low in some places **cough** Ternevas prison at the back **cough**

more to come! im sure theres bugs in the update.

**Comment by DebugMC** [comment]
With the new potions added:

Strength pots don't always work
Defense pots are gr8 (no issue)
Air pots don't always give the correct amount of WS bonus. (with +70% WS on my set, I drink a +30% and no change in speed) 
Didn't test the other pots.

**Comment by Moe-Ronickah** [comment]
LISTS of issues are not allowed.  Do not duplicate known issues.
/closed
