### ISSUE TITLE
Wynncraft Excavation Site D Problem

### ISSUE THREAD

**Issue by rfina** [Wynncraft/Issues#7169]
I just finished the quest Wynncraft Excavation Site D and for some reason i still have both yellow and purple gems in my inventory

**Comment by ColinRioux** [comment]
Have you completed any other Wynn-excavation quests on another class?

**Comment by rfina** [comment]
nope

**Comment by rfina** [comment]
my archer is pretty much the only class i use, once i finish the quests on it im gonna focus on another class

**Comment by LordHelmchen98** [comment]
I bet you finished Wynnexcavation Site A and B before the reward got changed. Before the change you got two shards from those quests so you had one for the next quest and one for Site D but now you only get one for the next quest but none for Site D because you only need one red shard for Site D now. As you won't need those extra shards anymore you can throw them away by putting them into your daily chest.

**Comment by rfina** [comment]
got it ty

**Comment by Moe-Ronickah** [comment]
RESOLVED
