### ISSUE TITLE
Able to equip higher level gear

### ISSUE THREAD

**Issue by RuneDemomn** [Wynncraft/Issues#7278]
Hi,

I haven't been on Wynncraft since 2013/2014 and decided to check back on my favorite MC RPG. I log on and am immediately placed in the update room, which is fine. After looking around and getting my barings I decide to check out what armor I had left.

I discovered I am able to equip a lv. min 64 chest while my class is only lv. 50!

Thought you guys would like proof so I made a gif with gyazo:
[https://gyazo.com/0c74f400172bf2dcb733b73bdd7cca44](url)

**Comment by LordHelmchen98** [comment]
You can equip it because it is broken. Montéfioré used to have those acute accents. They got removed (I think that happened when they released the Gavel Update) and now it's just Montefiore. Thats why any weapons or armor pieces with acute accents broke. Your Montéfioré is pretty much useless as it wont add health or other stats. You can keep it or throw it away but you are not allowed to sell it.

P.S.: Apparently you messed up the link so I had to copy paste it. Tip: next time you use links you have to put the link instead of the 'url' and put some random text in the square bracketslike this: `[GIF](https://gyazo.com/0c74f400172bf2dcb733b73bdd7cca44)`. It will look like this: [GIF](https://gyazo.com/0c74f400172bf2dcb733b73bdd7cca44).
