### ISSUE TITLE
Broken Quest

### ISSUE THREAD

**Issue by ApolloJaguar** [Wynncraft/Issues#7322]
Ok so I just started the Macabre Masquerade quest and I've talked to the Mask Salesman already. He tells me to find the Haunted Mask so search I searched it up on the Wiki. It directed me to a page explaining about the mob but when I clicked on where it's located it redirected me to a location called "The House of Twain". I want this quest done because it really annoys me to have low level ones in the beginning of the book. Thank you.

**Comment by Pyromanical** [comment]
That might be a problem with the wiki, as House of Twain has nothing to do with that quest.  On the topic of completing the quest, did you actually read the dialogue the mask salesman has?  It tells you where to go to kill the mask.  You just enter the cave near the salesman.

**Comment by AscendedKitten** [comment]
I checked the wiki, and there seems to be nothing wrong with it. The only mob reference points to the right page, the Haunted Mask.
In order to complete the quest you'll have to enter the cave next to the salesman, and continue through the different rooms in order to face the boss that drops the mask.
If you'd like to have a guide I'd recommend you to watch one of many YouTube walkthroughs, as the wiki page doesn't have an in-depth section for this stage.
I'll close this issue because it's more of a misunderstanding than an actual problem. However, if you can prove that there's something wrong feel free to open a new one.
