### ISSUE TITLE
Items Lost

### ISSUE THREAD

**Issue by LABALAHUMANA** [Wynncraft/Issues#7324]
i need a climbing hat for a quest and i dont have it idk why , i probably dropped it but now i need it.

**Comment by Pyromanical** [comment]
Do /fixquests

**Comment by Numbermaniac** [comment]
If that doesn't work, you need to complete Ice Nations to have the climbing helmet.

**Comment by ColinRioux** [comment]
You probably didn't drop it, since it's a quest item. Like @Numbermaniac said either try `/fixquests` (if you have completed the Ice Nations quest) or complete the Ice Nations quest. If neither work, you'll unfortunately need to level up another class and complete Ice Nations on that other class to get the climbing helmet.
