### ISSUE TITLE
Lost Bow

### ISSUE THREAD

**Issue by Pizzachua** [Wynncraft/Issues#7375]
I was doing one of the dungeons (I belive it was undergrowth or something, it was near troms) and when I fell in a pool of water I somehow lost my Infinity bow (The bow called infinity not a bow with some sort of inifinity enchant). I'm very positive I did not accidentally drop it, and this has happened before when I was doing the Lvl 60 quest, I think this has something to do with another issue where if I try to open a loot chest while holding the infifinty bow a message pops up and I cant open it (I dont remember the exact message). Maybe some item detector thought I had an item I was not supposed to have? Also in case you were wondering I did not die when I lost my bow, the water took me back to a parkour section.

**Comment by DebugMC** [comment]
@Pizzachua wynncraft has a no refund policy so you will not be getting your items back.

Also "Before I was doing the lvl 60 quest" you never say which.
As for the message in chat, you switched slots to open that chest so you could have dropped it. If you did, its in that water and 0% chance of getting it back.

...and btw, there is no detector. And for just so you know, there is no chest in the parkour section. I do that dungeon all the time.

**Comment by Pizzachua** [comment]
1) Alright, I just wanted to state this in case there was anything you guys could do
2) Beneath the Depths
3)  I'm not talking about opening a chest in the parkor section, I'm stating how in other places when I try to open a chest the game wont let me while holding that specific bow
4) I just kinda guessed, idk if there is a detector or not, I just made up a reason how it could've happened XD

**Comment by Pyromanical** [comment]
@Pizzachua the message is probably because Infinity is a re textured half slab.  Some blocks, such as half slabs, give a message saying you can't do something here, because it thinks you are trying to place a block.  Nothing can be done about it, you just have to switch to another item to open the chest.

**Comment by ColinRioux** [comment]
To summarize:

Wynncraft enforces a strict no-refund policy, like @DebugMC said, so unfortunately you won't be getting your item returned (this applies to all players, staff/content team/moderators included). 

With the introduction of custom weapon models, various blocks have been retextured to serve as weapons. Like @Pyromanical said, many bows are re-textured half slabs, which when opening a chest, will try to place the block, giving the "no permission in this area" issue.

The item detector thing as you explain is impossible, and it looks for certain NBT data as well as item id to remove items. It most likely didn't remove your item. 

Most likely you just accidentally dropped your item at the wrong time, causing the item to despawn. Or you dropped it and didn't notice. It happens all the time to players. We get many issues about lost items, and that tends to be the root cause (based on what you described). 

Sorry, but I'm sure you'll get a better bow down the line! (And maybe change your drop key to another key so you don't accidentally drop it).
