### ISSUE TITLE
Quest Item Glitched

### ISSUE THREAD

**Issue by xTheSlimeGamer** [Wynncraft/Issues#7393]
So I was doing the Craftmas Chaos quest and I had the quest item right before I finished the quest, and then when I went to talk to Santa it took away the quest item and I don't know how to get it anymore..

**Comment by thecoolkogut4** [comment]
what does your quest book say?

**Comment by xTheSlimeGamer** [comment]
My quest book says the quest is Finished.

**Comment by thecoolkogut4** [comment]
so what's the problem here? did you lose the reward from the quest?

**Comment by xTheSlimeGamer** [comment]
It's a quest item, so I shouldn't be able to throw it out. I think it was the corruption shard. After the quest I couldn't find it

**Comment by thecoolkogut4** [comment]
the last stage of the quest is giving santa the present and the report, once you click santa he will take the items out of your inventory.

**Comment by DebugMC** [comment]
Last I checked if they are refering to the santa armor, you don't get it from the quest anymore.

**Comment by thecoolkogut4** [comment]
yeah you don't get the armor anymore. i think op was talking about a quest item (ones you can't drop and usually go away at the end of the quest) but if you were talking about the armor debug is right.

**Comment by DebugMC** [comment]
Well unknown how it happend, but I can confirm getting quest items from people is not impossible (I don't have an issue posted because I am unsure how to do it) 

Basicly I was in ragni on my bank class when I started picking up Corrupted Hearts, Creeper Masks, Soundproof helm (idk what thats from xD), and other random quest items. I contacted a mod about this, they resolved the fact that I had them. However, somehow it **IS** possible.
