### ISSUE TITLE
Bug of texture pack

### ISSUE THREAD

**Issue by OxiboyTV** [Wynncraft/Issues#7401]
Hello, I've a problem with my texture pack, I haven't it.
So can you help me to set this bug ?

**Comment by Numbermaniac** [comment]
Have you followed the guide for getting the resource pack? https://forums.wynncraft.com/threads/cant-play-wynncraft-because-of-the-pack-heres-how-to-fix.98023/

**Comment by ColinRioux** [comment]
We don't know what your specific issue is. If you can't actually play wynncraft, see the link in the previous response. 

Otherwise, please note that there are some texture issues (purple & black blocks) on minecraft versions 1.9+. I suggest trying to play on 1.8.9 if possible.

Please also note that with the introduction of custom weapon models, some weapons appear to be blocks (i.e, prismarine) in-game. This is an issue the development team is aware of.
