### ISSUE TITLE
A couple of Small Building errors

### ISSUE THREAD

**Issue by Snerpe** [Wynncraft/Issues#7416]
Some Building errors I'd just like to report

1: 1st instance of a small totem in a wall(sky islands): 1374 85 -4432
![2017-02-21_22 33 40](https://cloud.githubusercontent.com/assets/25939645/23188930/7d9aee4e-f888-11e6-9c6a-d02e9edb550e.png)

2: 2nd instance of a small totem in a wall(molten heights): 1392 10 -5464
![2017-02-21_22 44 26](https://cloud.githubusercontent.com/assets/25939645/23188934/83765b00-f888-11e6-8e80-eee9ffe90744.png)

3. 3rd instance of a small totem in a wall(canyon of the lost): 827 52 -5261
![2017-02-21_22 48 07](https://cloud.githubusercontent.com/assets/25939645/23188938/876c4954-f888-11e6-97c1-7002cf39b813.png)

4. sky islands under-ahmsord house missing blocks: 1143 98 -4575
![2017-02-21_22 30 10](https://cloud.githubusercontent.com/assets/25939645/23188956/9640b1f4-f888-11e6-9c14-1daf866336e4.png)

**Comment by DebugMC** [comment]
Totems are sponges.    I think. Anyway, on 1.9 Im going to bet they are invis

**Comment by thecoolkogut4** [comment]
totems are "sponges". In 1.8 they are a sponge and in 1.9 they are what we call totems. Sponge use to be used as a decoration block (i believe) so there's just a few that I'm guessing they forgot to remove. @Villageacules

**Comment by DebugMC** [comment]
@thecoolkogut4 they are all underground/in walls though, meaning they were invisible where they were.

**Comment by ColinRioux** [comment]
I suggest also tagging me from now on as my response time is generally faster than Villagecules'. I have fixed all of these areas (except the last two, as they had already been repaired). Sponge is used as a placeholder for a lot of work, and when walls are only one block thick, totems appear to be in the walls instead of sponge. If you find more cases of this, please report asap. Thanks!

(These changes will be visible in the next map update).
