### ISSUE TITLE
Possible bug/issue with the Grand Magus in the Arena of Legends

### ISSUE THREAD

**Issue by NemeanLion** [Wynncraft/Issues#7436]
I just wanted to point out that the Grand Magus is currently immune to all damage except a single element instead of immune to a single element like the wiki says. Im using a wand with all elements on it, however when I hit him it only does a single damage type, im unsure about the last phase since my wand has low air damage and i cant kill him over the regen.

**Comment by ColinRioux** [comment]
Please keep in mind that the wiki is a third party resource, and isn't actually written by the administrators of the game. I'd also like to note that it is a wiki, which means anyone can edit the information, whether or not the edits are accurate. 

For the final phase, I quote the wiki:
`However, it also has no elemental weakness. It should also be noted that this form has no defense or weakness towards the Air element.`
Breaking this quote down, the boss has:
- No weaknesses towards any element
- Has no actual Air defense
That last bullet is stumbling and written poorly. What it's saying is that although you it has no air defense, it doesn't have air weakness so having a weapon with low air damage will do essentially no damage. If you want to kill the boss, you'll need a weapon with relatively high **neutral** damage. 

There's a distinction between weakness, defense, and neither that you should be aware of. If a mob is _weak_ to a certain element, that certain element will cause more damage to that mob. If a mob has a certain _defense_ in an element, then the mob receives no damage from that element. If a mob is _neither_ to a certain element, then it receives some damage by that element, but not as much as if the mob were weak to it.
Immunity is not this. Immunity is where no damage is dealt, and the boss phase cannot take any damage from an element. 

In the case that the wiki is in fact accurate, there's a chance that this mob is too powerful for you, and your wand cannot compensate for the boss' high regen. Just because you have damage in all elements doesn't mean it's enough. Neutral damage is also important. 

I am closing this because the wiki is not associated with Wynncraft directly, and I will forward this to the other editors.
