### ISSUE TITLE
Glitch with my attack effect 2

### ISSUE THREAD

**Issue by Yushana12** [Wynncraft/Issues#7444]
+ This is moving picture .

https://youtu.be/D3Cx8mRNNH4

**Comment by ColinRioux** [comment]
Hi, I recommend trying to reproduce this issue not using wynncraft enhanced. If you cannot, it's safe to assume it's something to do with the modpack than with the attack effects.

**Comment by Yushana12** [comment]
@ColinRioux Error without loading the mode pack continues .
Then, if you enter another account, the error will be resolved, but the error will continue to occur with the current account.

**Comment by ColinRioux** [comment]
Hi, it's clear that you've found #7298, but based on protocol, this is a duplicate issue. I have referenced this issue there, but only that one will remain open. There is no current solution, hence why that issue is still open. It'll hopefully be fixed when wynncraft is ported up to 1.9+, but for now, it probably won't be.
