### ISSUE TITLE
Ragni Lights

### ISSUE THREAD

**Issue by thecoolkogut4** [Wynncraft/Issues#7445]
![image](https://cloud.githubusercontent.com/assets/8689385/23328428/c4e08102-faee-11e6-9949-b104223b2348.png)

![image](https://cloud.githubusercontent.com/assets/8689385/23328429/c954acae-faee-11e6-819b-25c9fe81d528.png)

![image](https://cloud.githubusercontent.com/assets/8689385/23328430/cce95cca-faee-11e6-804f-92b7b0519f53.png)

At around -824 -1578 (in ragni) there are lights hanging off of a wire, at the bottom of the light theres a candle. on some lights, the wool was removed so all you see is the candle. 

@ColinRioux

**Comment by Pyromanical** [comment]
The wool wasn't removed, it is just showing as an item texture instead of a block texture.  There are little swords where the wool goes.  Still a bug tho.

**Comment by thecoolkogut4** [comment]
in the end, something needs to get fixed with the light.

**Comment by ColinRioux** [comment]
This issue is the result of playing on minecraft 1.8.9 (believe it or not). The resource packs for 1.9+ have been optimized to not have this issue, and I don't know the full reasoning behind why the 1.8.9 pack cannot be optimized. If you want a solution, you'll have to play on 1.9+, but with that can result in many bugs. 

The permanent solution won't be introduced until wynncraft is ported up to 1.9+ probably.
