### ISSUE TITLE
Last Sanctuary broken 

### ISSUE THREAD

**Issue by isosleepyninja** [Wynncraft/Issues#7449]
I tried to do the lost sanctuary... and when I got the part where u run on the bridge, it was broken and would not teleport me. NOTE: sorry if I spelt anything wrong ONLY ON WORLD 21

**Comment by ColinRioux** [comment]
Hi, this has been reported numerous times, and currently the only thing you can try as a temporary solution is re-log and pick a new world. This dungeon has also been repaired on build and should be fixed in the next map update, which is Corkus. I cannot tell you when that'll be released, but soon™.
