### ISSUE TITLE
Optifine doesn't let me join to the server

### ISSUE THREAD

**Issue by SharkeM** [Wynncraft/Issues#7462]
I've installed optifine and I just can't join to the server after this. I login into a hub, it starts lagging and I get disconnected from the server. Whenever I remove it, I can join again. But I have to use this mod because I have a LowConfig-PC.
If you guys can help me, thanks so much :D

**Comment by ColinRioux** [comment]
Unfortunately, this isn't an issue directly related to Wynncraft. Most likely, it's client side, based on what you are explaining to me. If anything, I would run 1.8.9 with optifine and see if that works (since wynncraft is hardcoded to 1.8.9). 

You should also confirm that you are only having this issue when joining Wynncraft. See if you have this issue with any other large server.
