### ISSUE TITLE
Llevigar Wild Horse bug

### ISSUE THREAD

**Issue by cait-imogene** [Wynncraft/Issues#7510]
When I attack one of the horses, it turns the player around, the complete opposite way I was facing. I'm not sure if it's because of my game version or if it's just a glitch with Archer class, but it's pretty annoying.

**Comment by Pyromanical** [comment]
It is because you are right clicking on the horses.  If you are using your archer melee attack near the horses, it thinks you are right clicking on the horses, and trying to ride them.  Since you aren't supposed to be able to ride them, the game immeaditely kicks you off the horse, and you face a different direction.  You can stop this from happening by shooting the horses from further away.

**Comment by ColinRioux** [comment]
Adding to what @Pyromanical said, there is really no way that we can change the core minecraft mechanics in order to fit gameplay. Something like turning off the ability to ride a horse is rather complex (maybe even impossible without modding), and if it were ever to be achievable, it would probably be added much later as a nice feature.
