### ISSUE TITLE
Lost Sanctuary

### ISSUE THREAD

**Issue by ch75pr** [Wynncraft/Issues#7530]
The part in the lost sanctuary where you run across the bridge as fast as you can is broken it will not let you go onto the bridge

**Comment by ch75pr** [comment]
[https://youtu.be/baaKntsL8q4](url)

**Comment by ch75pr** [comment]
That is the wrong link sry here is the right one [https://www.youtube.com/watch?v=baaKntsL8q4](url)

**Comment by ColinRioux** [comment]
Try switching servers. See #6758. It won't boot you from the dungeon since you aren't in the boss room.

Although I admire your determination to send evidence of what happened, this has already been reported. If you want to filter through closed issues, remove `is:open` in the search bar when searching for issues. All Lost sanctuary bugs have been patched to our knowledge, and the changes won't be pushed to the main servers until Corkus. Thank you for your time.
