### ISSUE TITLE
Kicked for flying

### ISSUE THREAD

**Issue by CyrenArkade** [Wynncraft/Issues#7592]
Whenever i join the hub it kicks me for flying once or twice before letting me join, and that was no big deal. But now whenever i join the actual game as my mage it immediately kicks me for flying because it spawns me up in the air and i do not fall down. The screen jitters like my character wants to fall down but is being tp-ed to the same spot. My IGN is CodedSouls

**Comment by Pyromanical** [comment]
This is probably because you have autojoin on. What you need to do is log into a world with very few people in it, and type in the command `/toggle autojoin` as soon as you can. When you log in you will now go to your class screen instead of your character, and it shouldn't kick you for flying anymore.

**Comment by LordHelmchen98** [comment]
Were you able to do what Pyro said? @CyrenArkade

**Comment by Catfish2013** [comment]
You could type it out on Notepad, copy it, and do Control V+Enter if you can't type it out fast enough.

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
