### ISSUE TITLE
Kicked right as loading into worlds.

### ISSUE THREAD

**Issue by WhiteLi0n** [Wynncraft/Issues#7593]
Not sure if this is a bug but friends and I are having the same issue trying to get into worlds of wynncraft. We can all get into the lobbies and move around just perfectly. However, when we choose a world we all load for a moment and some of use even get to the point of being able to choose a class before eventually we all crash. All we get on the screen is "Timed Out" I have tried reinstalling minecraft to using different versions to getting on different world and even using or not using optifine versions of minecraft. Any thoughts of why this is happening and/or how to fix it?

**Comment by numbermaniac** [comment]
If you're getting Timed Out then it could be an issue with your Internet. How fast is it typically? Are you able to play on other Minecraft servers with minimal latency?

**Comment by ColinRioux** [comment]
Also, does this occur when you are attempting to load the resource pack?

**Comment by WhiteLi0n** [comment]
I can run several different servers perfectly with usually 60-120 fps with optifine. I don't have the best of internet but I can run of some servers. Sadly this problem of not being able to join for my friends and I have been happening for months. However the other day my friends and I tried a version without optifine and we joined one world but we only had 5-10 fps. I believe it may be something with optifine but we can't figure out what it could be forcing us not to play. I only play with I have gotten to different points of loading into the worlds. Most of the time it just is a black screen it says timed out and other times I get to choose a class and after I pick the class it crashes.

**Comment by ColinRioux** [comment]
I suggest trying to log in with 1.8.9 or 1.9 without optifine and loading
onto solid ground in a world. Then log out and log in using your version
with optifine. Please post results.

**Comment by ColinRioux** [comment]
See #7599

On Wed, Mar 29, 2017 at 1:47 PM Colin Rioux <colin350@gmail.com> wrote:

I suggest trying to log in with 1.8.9 or 1.9 without optifine and loading
onto solid ground in a world. Then log out and log in using your version
with optifine. Please post results.

On Tue, Mar 28, 2017 at 8:59 PM WhiteLi0n <notifications@github.com> wrote:

I can run several different servers perfectly with usually 60-120 fps with
optifine. I don't have the best of internet but I can run of some servers.
Sadly this problem of not being able to join for my friends and I have been
happening for months. However the other day my friends and I tried a
version without optifine and we joined one world but we only had 5-10 fps.
I believe it may be something with optifine but we can't figure out what it
could be forcing us not to play. I only play with I have gotten to
different points of loading into the worlds. Most of the time it just is a
black screen it says timed out and other times I get to choose a class and
after I pick the class it crashes.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Wynncraft/Issues/issues/7593#issuecomment-289950196>,
or mute the thread

**Comment by WhiteLi0n** [comment]
So I took what you said (was using 1.8.9 and 1.9) and was able to get in fine without optifine but had the same issue of when I used optifine I didn't get to the class screen before I got timed out. I think I will have to go off what number said how it may be an internet issue then. Thanks for the try though! You can go ahead and close this.

**Comment by theonlygusti** [comment]
@WhiteLi0n but it shouldn't be an internet issue. If you can play well on other servers, you should be able to play well on Wynncraft.

Wynncraft should be accommodating for people with poorer connections, it's most likely not _solely_ an internet connection.
