### ISSUE TITLE
Meaningful Holiday

### ISSUE THREAD

**Issue by HypeWolf** [Wynncraft/Issues#7597]
So, this bug is from the quest named early on the tile.
I had to suicide since I thought my friend didn't talk to one of the NPCs. So, after suiciding I found myself at the Fruma-Wynn frontier. Is this a bug? Because I think so.

**Comment by LordHelmchen98** [comment]
This is caused by the current respawn system. You always respawn at the closest respawn point and as some areas are offmap you dont always respawn at the closest city to the quest start point, but at the closest respawn point from where you are, which was the "Fruma-Wynn frontier" (I assume you got to the starting area) apparently.
