### ISSUE TITLE
I died without any reason.

### ISSUE THREAD

**Issue by HypeWolf** [Wynncraft/Issues#7598]
Uhg, second post in less than 15 minutes. So, as the title says, I died without any reason, Minecraft also stopped and I could not exit from it, As last resource I had to close it with Task Manager, anyway: I was at Ternaves, when I came back I lost almost every single item I had. Maybe someone else already picked up everything I had but it is really annoying, Wynncraft used to be better on early updates.

**Comment by HypeWolf** [comment]
Oh yeah, also happened this a lot of times: Some items dissapeared from my inventory.

**Comment by LordHelmchen98** [comment]
Unfortunately Wynncraft has a strict norefund policy. Therefore you wont get back any items. Although that policy may not seem fair it actually keeps up the fairness among all players.

**Comment by ColinRioux** [comment]
There is a code refactor in the future, so I can assure you, that gameplay will be improved after the release of Corkus. Right now, however, I don't know the status of whether some of these bugs are being addressed. I get it that it's frustrating and I guess rather annoying that you spend time / or donate money and yet some items still disappear from your inventory. Also, do note that items de-spawn if you die and then log out/crash.

Game mechanics wise: you shouldn't be dying and dropping all of your items if you have more than 5 soul points, so I suggest idling in a safe city, like Detlas, for awhile and regenerate your soul points before continuing. May seem like a waste of time, but that can aid you if you die a lot. 

Poor internet connection can also be an inhibitor when it comes to randomly dying. I'm not saying this is what is happening to you, but sometimes if you have poor internet connection, where your client thinks you are isn't actually where you are on the server. What this means is that the server could think that you are near hostile mobs, while you think you are in Ternaves. That's not a server issue, that's a client issue. 

In terms of items dissapearing from your inventory, we are aware of the issue, and are working hard to resolve it. Cannot disclose status if this will be fixed with the release of Corkus. The no-refund policy still stands.
