### ISSUE TITLE
Boat disappears

### ISSUE THREAD

**Issue by MinecraftPercabeth** [Wynncraft/Issues#7603]
Sometimes, when I place my (vanilla) boat in the water, it is lost from my inventory, but doesn't appear anywhere in the water. I've already lost 2 boats this way, which is 4 EB wasted, and it seems to happen when placed to near land.

**Comment by ColinRioux** [comment]
Boats are a mechanic which haven't been fully fixed. There are a few things which can occur:
1. Playing on version 1.9+ can cause boats to lag tremendously; the client thinks it's someplace different from where the server thinks you are.
2. Since you aren't right clicking the boat and it crashes into land, by default minecraft mechanics, the boat would break. But since vanilla items don't drop in Wynncraft, you lose your boat and the wood/sticks which result when it breaks. There is currently no solution, but the development team is aware of it. I suggest if this is annoying you, use a spell to navigate across the ocean quicker, or if you are an assassin variant, use the seaskipper. 
3. However, if you right click your boat once you get out, it should appear back into your inventory.
