### ISSUE TITLE
Ban/bug 

### ISSUE THREAD

**Issue by Deltarus** [Wynncraft/Issues#7636]
i like to play in this server, but when i fallen in the big tunnel and server lag, i have bin  banned!!! What is this please unban my account. My nickname Deltarus! Please i like to play in this server.
![2017-04-02 11 47 17](https://cloud.githubusercontent.com/assets/26850270/24585727/383bb56e-179a-11e7-8db9-d9a91e53dc1f.png)

**Comment by LordHelmchen98** [comment]
In order to get unbanned you have to write a ban appeal on the forums in this section: https://forums.wynncraft.com/forums/ban-appeals.84/
Before you write it please read through this thread: https://forums.wynncraft.com/threads/%E2%9C%8E-appeal-submission-guide-%E2%9C%8E.89247/, you will find information about writing a ban appeal there.
