### ISSUE TITLE
Problems logging in.

### ISSUE THREAD

**Issue by MlghtyJuiceBox** [Wynncraft/Issues#7742]
So anytime I log into Wynncraft this has been happening.
![2017-04-08_17 27 59](https://cloud.githubusercontent.com/assets/27099816/24832923/c9447934-1c80-11e7-9d61-0b037b6fc227.png)
I don't know if this is just my computer or what but I can't play (Also this is before 1.16 and right after I got a new computer).

**Comment by numbermaniac** [comment]
That's usually an error in your Minecraft's appdata. What operating system are you using?

**Comment by MlghtyJuiceBox** [comment]
Windows 10. But it was working before I got my new computer and I was still using Windows 10 then.

**Comment by numbermaniac** [comment]
Yeah, but it's likely due to an error in how Minecraft was installed on your new computer. Open File Explorer, and in the top address bar, type in `%appdata%`, then go to `Roaming`, `.minecraft`, and you'll need to create a folder called `server-resource-packs` if it's not there. Once you've done that, restart Minecraft if it's open and try connecting to Wynncraft again.

**Comment by MlghtyJuiceBox** [comment]
Oaky thanks. Hopefully it'll work after that.

**Comment by MlghtyJuiceBox** [comment]
It finally works. Thank you so much, and with my new computer I also get a steady frame rate of 100+.
