### ISSUE TITLE
Quest Cannot be Continued?

### ISSUE THREAD

**Issue by SaltyStranger** [Wynncraft/Issues#7825]
I was trying to complete the Meaningful Holiday Quest, but once I finished talking to Reshad, Nick immediately began to talk again, only to stop at the [3/4] part of their dialogue (I forgot to take a screenshot here). I tried to interact with both Reshad and Nick before and after a relog. Reshad has nothing more to say, and Nick still asks if I have found anymore food.

![2017-04-11_22 24 54](https://cloud.githubusercontent.com/assets/7190364/24941199/e4adb532-1f05-11e7-8c57-4fe0b5282aed.png)

![2017-04-11_21 51 06](https://cloud.githubusercontent.com/assets/7190364/24941231/1b4b1cec-1f06-11e7-9099-ebb42d32e9a2.png)

**Comment by Pyromanical** [comment]
Try going through the tunnel again, then talk to Reshad again

**Comment by LordHelmchen98** [comment]
Sometimes it is difficult to trigger Reshad's dialogue. Try it from different angles and let us know if that helps.

**Comment by SaltyStranger** [comment]
Ive gone back and forth through the tunnel and tried talking to Reshad again, still no dialogue

**Comment by EnderDragonZarun** [comment]
I'm having issues with the same quest as well. I was able to speak to Reshad and trigger his dialogue and Nick's worked fine too, but because of the chunk errors yesterday, April 12th, Nick spawned where one of the errors were. And now when I try talking to Reshad, nothing happens at all no matter what angle I Right Click him. I tried the tunnel several times, nothing has happened. If it's possible, is there a way I can reset the quest and start again? If it is possible, what must I do? Sadly I have no screenshots for proof.

**Comment by EnderDragonZarun** [comment]
I'm starting to think nobody cares about this issue. How long until you fix it guys?! It shouldn't be hard to fix it!

**Comment by LordHelmchen98** [comment]
Can you try to talk to him again? As I already finished the quest I triggered a different dialogue, but I had no problems to talk to Reshad.

**Comment by Jarozan** [comment]
I had this exact same problem, only Nick actually finished talking for me. From what I can tell, after you talk to Reshad, Nick immediately starts talking (even though he's not there? I'm not sure if this was intentional or not), and Nick says something along the lines of "follow me." At this point, from what I could discern from the wiki page for this quest, you're supposed to be teleported to Santa's village... but that never happened for me. I don't think going back through the tunnel does anything, as I went back to talk to Nick (who asked if I found food), and then went back through the tunnel to talk to Reshad again, who either didn't talk to me or didn't say anything useful. There is no quest item involved, so a simple /fixquests won't help. This apparently is a recurring problem, as SaltyStranger had this happen to him as well. The best solution I can think of is a moderator of some sort resetting the quest as a fix, but finding a moderator on the server is no easy task.

**Comment by Jarozan** [comment]
Just checked to be certain, and found that Reshad for me says what he would say once you talk to him about getting food. Nick still asks if you have found any food. There's no way to continue the quest like this.

**Comment by Jarozan** [comment]
OH MY GOSH...
After I came back to the game from posting that last message, I was having massive lag, close to 10 FPS, and I looked around to try to find the cause. I saw what looked like someone had thrown down 20 lingering potions of... something? It was grey. Anyway, I went into to see what effect it was, thinking a VIP of something had dropped a bunch of buff potions, but it turns out it was the teleport to the next part of the quest. It was to the left if you are facing Reshad. Hope this helps!

**Comment by Jarozan** [comment]
If the portal is no longer there for you, travel through the tunnel from where Nick is and talk with Reshad. I believe this is what reopened the portal for me. If that still doesn't work, do some poking around and you might accidentally activate it like I did :P

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
