### ISSUE TITLE
Stuck in a Fireplace

### ISSUE THREAD

**Issue by XXHACTXX** [Wynncraft/Issues#7842]
In the Craftmas Chaos quest, you go to the future, and in the room with Old Tom, I am a Mage, and I teleported into the fireplace, I don't know why, and when I tried to get out, I couldn't teleport out. I had to kill myself(with /kill), which made me end up in Olux, which is far away from the place I needed to go to.

**Comment by LordHelmchen98** [comment]
That happened due to the current respawn system. If you die you get teleported the the closest respawnpoint. Unfotunately you respawn at seemingly weird places if you got teleported to a place that is offmap. Apparently the Craftmas Chaos areas are north-west of the map and therefore Olux is the closest respawnpoint.
