### ISSUE TITLE
Banned for flying...?

### ISSUE THREAD

**Issue by Kannachan** [Wynncraft/Issues#7860]
I don't know why I was banned so sudden ._. I was playing game that time and I don't know whether it is a bug or not ,the map stunned and I can fly that time ...and later I was kicked .The next day I came back ,the server banned me . ID:RabbitCinCin

**Comment by Pyromanical** [comment]
https://forums.wynncraft.com/forums/ban-appeals.84/

**Comment by AscendedKitten** [comment]
Moderators only ban after carefully observing the situation, so lag being the reason is very unlikely. 
However, if you feel like it wasn't the correct decision / want to play again, please create a ban appeal according to the guidelines here (https://forums.wynncraft.com/forums/ban-appeals.84/).
If you are honest you'll be given a second chance, but I doubt that "being banned for no reason" is a great argument in this case.
