### ISSUE TITLE
Online stats not the same as in-game?

### ISSUE THREAD

**Issue by WulfGamesYT** [Wynncraft/Issues#7866]
I have just viewed my stats on the website, and saw that my stats arent the same as my in-game stats. here.
https://i.gyazo.com/e02daaabc2c66e7814b262db8b8ff4c7.png

and then my ingame stats:
https://i.gyazo.com/2a7163c590254c466cc4195561e07567.png

**Comment by LordHelmchen98** [comment]
That's correct because the online stats do not include any stats buffs given by armor and accessories.
I bet if you subtract the skill points from your armor (look up how many you got by your armor in your compass) you'll get the amount of skill points shown on the stats page, although your armor really seems to give you a lot of skill points given that you are only level 32.

**Comment by WulfGamesYT** [comment]
Oh my god lol sorry! I didn't know that they affect the stats, sorry for this :)
Thanks @LordHelmchen98 for the reply <3
