### ISSUE TITLE
creeper mask lost

### ISSUE THREAD

**Issue by Sapphire-4ever** [Wynncraft/Issues#7891]
I threw away the creeper mask because before it was a quest item, ( I re-did the quest with the old one) and now don't have it so I cant complete the temple of legends quest! what should I do?

**Comment by ColinRioux** [comment]
There's a redone version of the Creeper infiltration quest which was released with Corkus. That means if you haven't done it since corkus was released, you can redo the quest and get a new one. 

Otherwise, you can try `/fixquests` and you should get the item returned to you. If that doesn't work, well, you'll have to level up another class and transfer the item.

**Comment by LordHelmchen98** [comment]
@ColinRioux since Corkus it's untradeable which means you can't get it by doing /fixquests.
But @Sapphire-4ever Colin is right you can do the quest again to get a new one. Also you can throw the mask away because if you repeat what you do for the quest in order to get the required materials you will be able to get the mask again.
