### ISSUE TITLE
Fierte Bugged

### ISSUE THREAD

**Issue by KnightVastlin** [Wynncraft/Issues#7932]
My Fierte is bugged aka {coding isn't working on it from the update with all the 3d models etc.)

This is what it looks like in my inventory

https://gyazo.com/70f15beb833b2cea7f066b24c1134fe8

**Comment by thecoolkogut4** [comment]
this is a weapon from before the gavel update. since it has a special character in the name it did not get updated. this will not fixed and staff will not give you a new/updatd version. you can chose to keep it as a collectable or throw it out. it is against the rules to sell the item.

**Comment by thecoolkogut4** [comment]
are you in a war server or the nether server?

**Comment by LordHelmchen98** [comment]
@thecoolkogut4 Im pretty sure thats just another form of the bugged weapons after the Gavel release.

@KnightVastlin The weapon was called Fierté before Gavel, but when Gavel was released those weapons broke because after the release they were called Fierte with a normal 'e' instead of a 'é'. As it is broken, it's useless now. Therfore you can keep it if you want or throw it away, but you are not allowed to sell it.

**Comment by thecoolkogut4** [comment]
@LordHelmchen98 that is exactly what i thought, i was typing exactly what you wrote intill i looked at the picture. before the weapon had the old item display/look but this time it has a different look. maybe they trued to fix the weapon? or at least from what ive seen, weapons with the weird character did not get updated and they stayed in the old form, not purple. anyways, its done & closed.

**Comment by LordHelmchen98** [comment]
As far as I know some just kept their old look, some others broke like that. Nonetheless its just a useless item and its not allowed to sell it.
