### ISSUE TITLE
Llevigar prison ate my horse

### ISSUE THREAD

**Issue by Lowrider800** [Wynncraft/Issues#7955]
https://youtu.be/uoYdzC1nGfo <-- video might still be uploading
https://www.youtube.com/watch?v=LxcpQzybUZA <---- stream of me having my horse

I wasn't recording when it happened, but I stood on top of the hopper, because I didn't know what to do, then i had to look up how to get out, you had to throw an emerald in, so I opened up my inventory, and my horse was gone.  Please help me, I streamed earlier today with the horse, I showed my bank proving I DON'T HAVE IT!!! PLEASE THIS IS THE SECOND GLITCH THAT HAS HAPPENED TO ME!!!

**Comment by thecoolkogut4** [comment]
Hey there, unfortunately Wynncraft enforces a strict no-refund policy. That means you won't be receiving your items back. Even though you did not ask for a refund, I thought that I should bring this up incase you weren't aware of the policy.

**Comment by Lowrider800** [comment]
I know but this isn't my dang fault honestly I WANT IT BACK

**Comment by Lowrider800** [comment]
This isn't something I did this is your servers fault

**Comment by Lowrider800** [comment]
As you can see even as soon as i noticed i started messaging staff.

**Comment by Lowrider800** [comment]
A.K.A. Jumla

**Comment by Lowrider800** [comment]
I had 10 le's to try and bread one and I used 7 of them!!!

**Comment by thecoolkogut4** [comment]
I know, Things happen. This has happend to a lot of other people. There is no way to get your horse back for free to make up for what you lost.

**Comment by Lowrider800** [comment]
Why, this is wynncrafts fault, if it wasn't I wouldn't be here
I recorded a video right after it happened I don't know what other proof I can give.
My horse wasn't even in my hotbar

**Comment by Lowrider800** [comment]
You never even watched the video btw,

**Comment by Lowrider800** [comment]
You are not even caring.

**Comment by Lowrider800** [comment]
I know i'm not gonna donate anymore

**Comment by Lowrider800** [comment]
I'm very disappointed in this "policy" that you have.

**Comment by LordHelmchen98** [comment]
I once lost my upgraded chestnut (I paid 16le (or more? I dont remember it anymore) for a 1/30 chestnut, spend lots of time for leveling, did the corrupted decrepit sewers dungeon many times, bought the upgraded one and then spend lots of time for leveling it again), but I didnt get it back.
Im sorry for your loss but you wont get it back either due to the norefund policy which includes issues that were the servers fault.

**Comment by thecoolkogut4** [comment]
It's a policy that the server has and it is very strict. Even though that you have Proof of owning the horse, the Wynncraft Staff team will not Spawn in a horse to give to you. If your lucky you could ask around for a free horse, I'm sure someone could give you a brown one. There is an issue similar to this one at least 5 times a week, they all have the same end result. Proof or not, it ends up the same. I am not part of the Moderation team on Wynncraft but if you'd like you can talk to @lord_heml who is active on github.

**Comment by Lowrider800** [comment]
He's off?

**Comment by LordHelmchen98** [comment]
@thecoolkogut4 
@lord_heml xD
Anyway @Lowrider800 a video with the horse and a video without the horse is by far not enough to proof someone lost an item as a player can sell it, throw it out, etc. and we have no way to check if someone lost an item and how. The policy may seem unfair, but actually it keeps up the fairness among all players, because if we gave everyone the requested items there would be countless players who say "I lost a maxed Fatal, pls return". Its unfortunate, but you have to deal with it.

**Comment by Lowrider800** [comment]
;(

**Comment by thecoolkogut4** [comment]
I was on my phone and it won't let me tag so I had to edit it then tag you. If you REALLY want a horse you can always ask people for a free one. People might not like you if you ask for free things but that's up to you...
