### ISSUE TITLE
not able to identify my item

### ISSUE THREAD

**Issue by FoxForrest** [Wynncraft/Issues#8025]
hi my username is FoxForrest and i have been playing on this server for a couple years and i took about a six month break from playing and when i got back all my stuff had to be re-identified. all my stuff could be identified except for my shears which at the time where the final ones you got (im lvl 75 btw) and they can not be identified as much as i try if someone could either give me a newer pair or help me fix the ones i have i would be grateful. thanks -FoxForrest

**Comment by RubbrDucky** [comment]
Can you show us a screenshot?

**Comment by XavierEXE** [comment]
This is a known bug; those shears are Bob's Mythic Shears, which are bought from a merchant and come identified automatically. The current system doesn't allow you to identify merchant bought items, but the Gavel update made all your items unidentified, and since you didn't log in and identify them before this new tag was introduced, we've been left with a dilemma: The game thinks it's a merchant bought item and won't let you identify it, and doesn't realize it's actually unidentified. We aren't able to give you a new pair of them, but I'll look into seeing if this can eventually be fixed.

Since you're in need of a new dagger, I recommend you look for Chakram. Alternatively, you could use http://wynnapps.tk/item/ to look for a dagger of your liking to replace the broken one.

**Comment by RubbrDucky** [comment]
Kinda off topic, but i have a max poison chakram that I could sell you for
cheapish

**Comment by FoxForrest** [comment]
![image](https://cloud.githubusercontent.com/assets/28241364/25570672/2c99925a-2ddc-11e7-96cb-1c3739f68178.jpg)

**Comment by FoxForrest** [comment]
Wouldn't let me post video so I hope that's good enough for my proof

**Comment by XavierEXE** [comment]
Yeah, definitely a Bob's Mythic. Unfortunately, there's a no refund rule that wynncraft has, so we can't just spawn in and give you a new one: We don't even have the power to spawn in items, anyways. I might be able to help get you a new weapon, though, and @RubbrDucky said they could sell you a Chakram. It's comparable to Bob's Mythic Dagger in power, and even better in some ways, such as speed.

**Comment by FoxForrest** [comment]
Thx
