### ISSUE TITLE
Glitched and lost weapon

### ISSUE THREAD

**Issue by MendelTheBum** [Wynncraft/Issues#8065]
I had died in the world and it didn't load as I respawned, and my Bob's Mythic Bow had disappeared. I don't know what happened but I'd like to possibly get my bow back

**Comment by RubbrDucky** [comment]
Sorry, Wynn has a no refund policy. ;-;

**Comment by MendelTheBum** [comment]
ok, but what I'm saying is I didn't drop it nor did I sell it

**Comment by PepinhoJp** [comment]
Sometimes bug happens but like RubbrDucky said there's this no refund policy that doesn't allow anyone to get items back, because they don't have a way to check if you're lying, if you dropped it and will get it later and is just waiting for a mod to give you a new one or if it is tryet, the only thing that you can do is give some information about how this happened and we'll try to tell the admins and this can (If it really is a bug) help other people, that won't lose the items because you helped!

**Comment by LovingHotsprings** [comment]
It happened to me too because I kept dying quickly, items dropped but then suddenly stopped dropping... I lost my chestnut 30/30 horse because of this. :( Please fix item drop bug.

**Comment by PepinhoJp** [comment]
This is supposed to happen, you have to open your inventory and check the odds of dropping something (Soul Points), if the items dropped because you died there's nothing wrong here!

**Comment by LordHelmchen98** [comment]
Im sorry for your loss but that's how wynncraft works. You loose items when you die. Be careful at 5 or less soul points because that's when important stuff can drop.
