### ISSUE TITLE
Stuck on top of the map

### ISSUE THREAD

**Issue by TurtleGames101** [Wynncraft/Issues#8075]
I logged into the server and i was on top of the barrier blocks for the height limit of the game.
![capture6](https://cloud.githubusercontent.com/assets/28115418/25772098/d3ebd2c0-325a-11e7-908e-4548df406ae0.PNG)

**Comment by BasterMC** [comment]
i have the same problem but i am in a wall or slt...

**Comment by PepinhoJp** [comment]
1st - Don't leave the map, it's bannable!
2nd - How did you leave, please give us more information, this can help the staff to improve Wynncraft later!
3rd - /kill or use a scroll to get out.

**Comment by LordHelmchen98** [comment]
@PepinhoJp if you log in you spawn at a higher place sometimes. Also this is already known.
@TurtleGames101 @BasterMC as already said if something like that happens dont stay there, but use a scroll or do '/kill' if you have more than 5 soul point. Usually this only happens if you log out right below a block so you should look if there is an air block (barrier blocks count as blocks not as air) above you when you log off.
