### ISSUE TITLE
Purple Crystal Missing

### ISSUE THREAD

**Issue by NumeroPhobia** [Wynncraft/Issues#8082]
So I've completed WynnExcavation Site A, B, and C, yet I don't have the Purple Crystal. 
![2017-05-06_18 40 23](https://cloud.githubusercontent.com/assets/22627605/25777254/7e1b5f96-328c-11e7-8a9a-5f3bd0da21ef.png)

![2017-05-06_18 45 51](https://cloud.githubusercontent.com/assets/22627605/25777247/646b4778-328c-11e7-9016-a7050ad55651.png)
![2017-05-06_18 46 01](https://cloud.githubusercontent.com/assets/22627605/25777246/6469f314-328c-11e7-9614-b0f0dea18329.png)
![2017-05-06_18 46 07](https://cloud.githubusercontent.com/assets/22627605/25777248/646e7826-328c-11e7-90d1-1768d0efff0f.png)

I tried doing /fixquests, but it didn't work. Anything else I can do to try and get it back?
![2017-05-06_18 46 17](https://cloud.githubusercontent.com/assets/22627605/25777249/64705b96-328c-11e7-9875-f4f10a45d557.png)

**Comment by PepinhoJp** [comment]
Unfortunately if /fixquests doesn't work and this is a quest item you'll have to create another class and do everuthing until Wynn Excavation Site C in another class to get the item! But I'm not sure if it is a quest item so if it is untradable go to the region where you got it and get it again, also try talking to the starter NPC (Royal Advisor Carlos) and then try /fixquests

**Comment by NumeroPhobia** [comment]
Will try the "talking to the NPC again" thing first. If that doesn't work, probably will try to make another class and do it.

And yes, it's a quest item.

**Comment by NumeroPhobia** [comment]
Apparently talking to the NPC didn't work...

**Comment by PepinhoJp** [comment]
Sorry...

**Comment by NumeroPhobia** [comment]
The same thing happened with the Yellow Shard, but i got that one back. Weird how it didnt for the purple shard

**Comment by LordHelmchen98** [comment]
@NumeroPhobia As you closed the issue I guess you found a solution, but I still want to say this (also because @PepinhoJp didn't know that).
Quite  while ago the Wynnexcavation system got changed and you don't need all 3 crystals for WynnX D anymore. I guess you completed Site A before and Site B after that got changed. Therefore you got two yellow crystals and used one for B and one purple crystal that you used for C so in the end you had one yellow crystal left. If you have one red crystal you can do Site D and you can get rid of the yellow one if you put it in your daily reward chest.

**Comment by NumeroPhobia** [comment]
Okay. Thanks
