### ISSUE TITLE
Missing quest reward

### ISSUE THREAD

**Issue by Ermland2** [Wynncraft/Issues#8110]
I recently completed the quest "The realm of light" and upon completion i got nothing except the xp so i thought that was the reward. Then i saw that you should get a LE and "Cloak of Illumination" so got back and looked if i had dropped it but no. Please help me. Thanks.

**Comment by LordHelmchen98** [comment]
Did you have some empty inventory slots when you finished the quest (are you sure you didnt pick something up accidentally after starting the final dialogue)?

**Comment by PepinhoJp** [comment]
He didn't pick anything up: https://forums.wynncraft.com/threads/i-messed-up.184173/page-2#post-2172629

**Comment by LordHelmchen98** [comment]
@PepinhoJp it doesnt necessarily end up like in that case if you pick up items after talking to the final NPC.

**Comment by Moe-Ronickah** [comment]
Please see issue #6705, especially the part where I said "NEVER complete a quest with any LE, EB, or E in your inventory, because all 3 can interfere with how much reward, if any, that you will receive."  This has been a persistent issue for a long time.  I'm sorry to say this, but the issue is erratic - it happens so rarely, that is has been very hard to find what is causing it.  Also, no one can replace the lost emeralds.  In fact, we can't replace anything.  In the case of the issue, listed in the thread, above, the player picked up an item while talking to the NPC.  That item caused him to have too few slots to receive a reward item.  That is not the same as your issue, and @PepinhoJp should have known better, be before he pointed you towards it.

**Comment by LordHelmchen98** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft. If you are still experiencing this issue, you can open a new bug report.
