### ISSUE TITLE
horse breeding

### ISSUE THREAD

**Issue by Femke05** [Wynncraft/Issues#8128]
i bred more than 15 horses and i still did not get a black one.

**Comment by theonlygusti** [comment]
Yeah, maybe wynn could weight the probabilities on how many consecutive unsuccessful attempts there have been so far.

**Comment by ColinRioux** [comment]
The 2.25 LE (as listed on the wiki/forums), or 10 browns yield 1 black is an estimation. Sometimes it can be more or less than that to get a black horse; there is a fair amount of uncertainty. It seems you in fact have just been unlucky, and it happens. 

If you actually bred upwards of a hundred horses and still didn't get a black horse, then it'd seem more likely a bug than luck. However, since you've only bred ~15-20, you probably just have bad luck.

**Comment by Femke05** [comment]
I spend ******* 5 le. 😦

**Comment by theonlygusti** [comment]
@ColinRioux treat it as a feature suggestion rather than a bug report, b/c it obviously isn't a bug

**Comment by ColinRioux** [comment]
@theonlygusti this place is to report in-game bugs/issues, not a feature suggestion. Please don't tell me how to treat it.
