### ISSUE TITLE
"Flying is not enabled on this server" fix idea.

### ISSUE THREAD

**Issue by Darkstone2334** [Wynncraft/Issues#8154]
I heard that someone in the comments says they're able to join if there's a roof over them. soooo.....

Why not simply place a roof over the spawn area in the hub?
hmmmm? :3

**Comment by Darkstone2334** [comment]
I like this server, I really do, but I can't play it anymore. I've been trying for the last 4 hours at LEAST to get in, and it keeps kicking me for flying because I always lag when I join a server, and not one of you had better tell me to get a new PC, if I could, I would, but getting a new computer isn't that easy. And I can't seem to cross the bridge at the Lost Sanctuary either. My game crashes whenever the boss destroys it because...well..LAG!  I can't run in lag much less parkour over a collapsing bridge -_-

**Comment by LordHelmchen98** [comment]
Im going to assume you enabled autojoin. This is a nice feature, but causes some issues if you connection is slow. If you disable it you wont get kicked when you join a server.
However for your problem with lag there is nothing that Wynncraft can do. The dev team is trying to reduce the lag, but there is no magic button to completely remove lag.
Lastly for the thesis about the roof: I doubt they will redesign the lobby to add a roof above the spawn. Maybe it works ingame, but I never heard of that before. Anyway make sure you dont log off without one empty block above you because this can cause issues as well.

**Comment by Darkstone2334** [comment]
I have auto class select yes. But I do not automatically connect to any servers. This is all hub based.
