### ISSUE TITLE
Cant connect to any world

### ISSUE THREAD

**Issue by ShadesMojo** [Wynncraft/Issues#8173]
I log in just fine, but when i try to connect to a world, it sits for about 20 seconds then disconnects me. I was playing this morning just fine. Im wondering if this is a problem with me or the server. Thank you for your time

Keep in mind, im using the Wynncraft Enhancement mod from the Curse/Twitch launcher

**Comment by SaltiestOfHobos** [comment]
Try to join worlds with 30 or less players

**Comment by ShadesMojo** [comment]
Still does the same thing. I can go on the server on vanilla mc but it doesnt allow me because it puts "Please use Curse" right on my screen so i cant see lol. Im just triggered because i got a new weapon that i wanted to try but whatever this problem is, it looked me in the face and gave me a big fat middle finger ;-;

**Comment by LordHelmchen98** [comment]
For issues with Wynncraft enhanced please ask on [the mod pack thread] (https://forums.wynncraft.com/threads/unofficial-custom-modpack-❀-wynncraft-enhanced-❀-party-hp-display-custom-worldmap-more.139677/) . Github is just for bugs related to the game itself not for bugs occurring due to player made extensions of the game.
