### ISSUE TITLE
Guild Mobs not spawning on Attack

### ISSUE THREAD

**Issue by ZeUnlucky** [Wynncraft/Issues#8221]
Ok, so I've read all the past duplicates, and they're seemingly all from 2016, the start-middle of 2016, so I decided to retry and get an answer. Trying to do a guild attack leads me to an empty War server, or doesn't teleport me at all. I know it's a known issue, but I've tried it for 10 times, almost an hour wasted on running around trying to figure the issue... Would love an answer >-<

**Comment by thecoolkogut4** [comment]
Yeah, this is still a big and a pretty annoying one. I face this issue a lot every single day. There is nothing you can do to get mobs on a server (from what im aware of) and its all based on luck. They are currently trying to recode the guild system and it should hopefully be fixed in the near future. 

-TheDarkSoul

**Comment by colin350** [comment]
#3665
