### ISSUE TITLE
Maltics well

### ISSUE THREAD

**Issue by oscar8393** [Wynncraft/Issues#8347]
when you get to level 18 and unlock maltics well quest it comes up as Maltic^s well rather than Maltic's not sure wether its on purpose or not but thought id let the team know.

**Comment by Reefive** [comment]
It's Minecraft glitch. Usually it's because the developer uses a different language.
Look at Keys: It's Something^^^Key. You just go to deal with it.

**Comment by ittnoraA** [comment]
No, it's not happening because of language differences. It's a "bug" caused by the quest system, YML which uses ' to start and end dialogue. That's why GMs use the symbol ^ which automatically gets replaced into a '. However, the leveling up system works differently than YML, and doesn't convert the symbol into it's correct form. I believe there is nothing we can do about this "bug", but thankfully it's not too major.

And as for you Reefive, the reason why your keys might look like "FallenåååFactoryåååKey" could have several reasons, but being a bug is not one of the options. In the wynnpack "å" is an invisible letter, so if you're able to see it, you haven't equipped the resource pack or you're using forced unicode font which isn't supported by the pack.
