### ISSUE TITLE
I lost my stuff because of a server bug (pseudo : Mouteine)

### ISSUE THREAD

**Issue by Mouteine** [Wynncraft/Issues#8383]
I logged on to the server I found myself stuck in the ground and I do not know why the bracelet I had was removing and my boots too and the server has disconnected me, when i reconnect, my boots and my bracelets had disappeared
Without my Jester Bracelet, i can't use my Boots (stalagmites) and without the stalagmytes boots i can't use my bow because The Jester bracelet add me 2 dexterity points and without these 2 dexterity point i can't use my boots et my bow
Because of this bug on your server I lost my boot and my bracelet
Could you please return them please I can no longer use my bow
It's more than 1 year that I play on your server
(pseudo : Mouteine)

![2017-06-15_22 13 14](https://user-images.githubusercontent.com/29466765/27199916-1acbc02e-5218-11e7-85e1-395dd574ae00.png)

**Comment by Nowbowdy** [comment]
mdrrr atttooooooz

**Comment by ittnoraA** [comment]
Sorry, but Wynncraft enforces a strict "no refunds" policy, which means you're not getting your items back. If you want, you can make a thread on the forums' trading market to buy them from community members here: https://forums.wynncraft.com/forums/trade-market.71/

**Comment by Mouteine** [comment]
You have a cardboard server that bug all the time and you do not even give back what your lose loses, you go lose all your players as its you are stupid

**Comment by Mouteine** [comment]
The other servers make the stuff but you no, pfff it's sad to see a server like its I would advise it to my friends

**Comment by ittnoraA** [comment]
The developers of Wynn are working hard to fix bugs like these as soon as possible, but you do have to understand they're just human beings. Working on code and making sure it works takes time, and people complaining about it won't make it any faster. If you think about it, reading hateful comments might infact slow them down!

**Comment by Mouteine** [comment]
The worst thing is that I bought a grade on your server I give money to help you and you are not even able to make 2 small stuff that takes 2 seconds to do is pitiful, I would be ashamed

**Comment by RedLogicP** [comment]
Imagine if they did return items, people would be constantly saying "I dropped 7 mythics into Cinfras trash can pls return!!1!"

**Comment by Locky1110** [comment]
Im pretty sure arguing with a content team member wont help get your items back.
Not everyone encounters that bug and loses there items. I once lost my olux prized wand but i didnt ask for it back, i just used a different wand.
The reason why they can't give refunds is so people can't abuse the staff to get free items. 

In fact its a bit possible your lying about this. It seems like you just logged in rather than just noticing your items were gone, because your particles just activated. Also if they did fall off one of them would've appeared in your inventory rather than just disappearing. If it did fall off, there would have been a message. If this was your first time rejoining the server in a year, then you shouldn't have had the king particles active, because they weren't added until Corkus. 

I also noticed you pointed out the names for both of the items.

Also if your meaning after that you havent played in a year, then, the particles were were made less than a year ago, the weapon skin you have was made less than a year ago, and according to wynncraft.com, the last time you played was 37 minutes ago...

If you can please explain with more detail on what happened

**Comment by RubbrDucky** [comment]
just stop complaining. You can get the gear back, just remember wynn is
hand coded. Speaking from a web developer point of view, it's impossible
not to have bugs when minecraft was not really designed to be this complex.
It's incredible how much the devs have managed to make such a complex game
without mods or building a client from scratch. Keep some room in your
inventory next time. And as locky said, it's quite reasonable to believe
you are faking this.

**Comment by colin350** [comment]
Some final notes:
Donating to Wynncraft in no way promises an advantage simply because you chose to donate. You are choosing to donate because you support the server, and what good it has brought to you. 

If we created a refund policy for players who donate, that violates the EULA. Wynncraft could permanently close if we violate the EULA.

We have two developers who are actively working on refactoring Wynncraft's entire codebase. We don't have 30 developers actively working on in-game features like Hypixel. We have 2. We don't pull in enough revenue to hire 30 developers.

We used to have a refund policy. It was abused. The players who abused it caused the entire player-base to lose the policy privilege. 

And, finally, it's your choice whether or not you play. It was your choice whether or not you donated. You could've been in the same position whether or not you donated. You aren't the only one who have lost items. In fact people have lost even more rare and valuable items. So please understand why we have a no-refund policy. A policy which affects everyone, including staff members and content team members.
