### ISSUE TITLE
texture pack notification is spamming me

### ISSUE THREAD

**Issue by woohoo2230** [Wynncraft/Issues#8420]
I was unable to get the texture downloader that automatically downloads the texture pack to work as it just crashed my game every time, so i downloaded the pack from the website instead and am using the resource pack instead, but i cant figure out how to get the notification in chat that keeps telling me to turn pack downloads on to stop spamming me plz help

**Comment by thecoolkogut4** [comment]
You can't turn off of. The only way to temporarily disable it is by getting a anti spam mix

**Comment by ittnoraA** [comment]
Heya! There isn't a way to toggle the notifications off, since the server wants to make sure players use the most recent version of the pack. If you're having problems with the automatic installer, here are some tips on how to fix it:

1. Is there a folder with the name of `server-resource-packs` inside your `.minecraft` folder? If not, create one and see if it worked.

2. If you already have the folder, delete all content located inside of it and try logging in.

3. When adding the server, `play.wynncraft.com` into your server list, make sure the server resource packs option is set to "Enabled"

4. If none of these worked so far, your computer might have some outdated drivers or hardware. Try updating your drivers to the latest versions, and if that doesn't work, consider buying stronger parts for your pc.

**Comment by colin350** [comment]
Closing as not an issue, but a preference.
