### ISSUE TITLE
I timed out and lost items

### ISSUE THREAD

**Issue by 2002Kenny2002** [Wynncraft/Issues#8445]
I just finished the quest Bob's lost soul which had leveled me up to level 47, The meant i was able to use the weapon sage i had recently obtained. Since i was finally of level to use this weapon i went and got a tier 4 powder out of the bank and went to find the powder merchant in nesaak. Then my game suddenly timed out and i could not join for a good 5 min, Once i managed to logg back on my tier 4 powder was gone.

I have checked my bank and inventory and i have no clue what happened to it. I am believing the game despawned it for some reason.

(also i found a wood axe in a dungeon on the ground what do i do with it?)

**Comment by ittnoraA** [comment]
For the powder problem, I'd assume the item was transferred into the bank only on your client, and not the server. This problem is quite common, since the bank system is so old. As for the wooden axe you found, a builder had accidently dropped it in, which is why got transfered into main servers. Just throw it into a trash disposal or hand it over to a moderator, as possessing illegal items will result in a ban.

**Comment by 2002Kenny2002** [comment]
Ok thanks, Will anything be done about the powder being lost or is it just a rip situation at this point in time? 
(also i will throw out the axe the next chance i get)

**Comment by ittnoraA** [comment]
Wynncraft has a strict "No Refunds" policy, which means you're unfortunately not getting your powder back.

**Comment by 2002Kenny2002** [comment]
Ok well thanks for the help anyway.
