### ISSUE TITLE
Damage while putting on armor.

### ISSUE THREAD

**Issue by Hazukashigariya** [Wynncraft/Issues#8450]
I noticed that while I was putting on armor, the character was behaving as if it was being attacked. Damage was actually being taken.

**Comment by thecoolkogut4** [comment]
(3 cases here) That is because when you get extra health, you get it with "empty hearts" or health that you still need to regenerate. When you put the armour on, you get extra health and the default health animation looks like you are losing health. If you understand what I'm trying to say. The second case is that your armour has -health and when you put it on, you lose health because of negative health on your armour.  3rd case is that you have a -health Regen Id on your armour which makes you also loss health.

**Comment by LordHelmchen98** [comment]
@Hazukashigariya this can happen due to already said reasons and it's just a visual thing as it doesn't actually affect the gameplay. Therefore I guess you'll have to deal with it as this is probably nothing with a high priority in case there is anything that can be done to prevent that.
