### ISSUE TITLE
 Bug Quest "WynnExcavation B and A"

### ISSUE THREAD

**Issue by EdgarMX13189** [Wynncraft/Issues#8486]
Name In Game: EdgarMX

What happens is that the yellow crystal they give me in the first mission never gave it to me and I already completed it and that yellow crystal is the one that asks me in the next mission and because I can not finish it because it never gave me that yellow crystal.

http://imgur.com/a/tL5Cj

**Comment by PepinhoJp** [comment]
This questions is too confusing, so I'll just say the answer instead of saying what's the duplicated question, try /fixquests , if the crystal still don't appear, you'll have to create a new character, get the crystal and use it in your main character, staff can't give lost items back because Wynn has a strict no refund policy.

**Comment by LordHelmchen98** [comment]
RESOLVED
