### ISSUE TITLE
Wrath of the Mummy/ Mummy's Rag

### ISSUE THREAD

**Issue by Jst9** [Wynncraft/Issues#8498]
So I just finished the Wrath of the Mummy quest and got the Mummy's Rag as a reward. I moved it into a new inventory slot and made my way to the Item Identifier. But when i looked, it just disappeared! This is extremely frustrating, and I went back to see if i dropped it, but it wasn't anywhere. Doing /fixquests didn't give me it back, so i was wondering if there was any other way to get it back?

**Comment by PepinhoJp** [comment]
/class to see if it's a visual bug, if it isn't Wynn has a strict no-refund policy, so they can't give you items that you lost back, sorry.

**Comment by colin350** [comment]
Please note that the quest reward: Mummy's Rag, **is not a quest item. Therefore, `/fixquests` will not work.** This item serves no purpose later on in-game, and you'll probably find a better qualified item later on. 

Do note that Wynncraft enforces a strict no-refund policy, a policy which applies to all players, including staff members and content team members. Since the item is not tradable, the only other method of obtaining this item again is to level up another class, complete the quest, and transfer it via your bank.
