### ISSUE TITLE
Wasted emerald blocks on boats

### ISSUE THREAD

**Issue by xCrazyMan** [Wynncraft/Issues#8533]
So I bought a boat yesterday for **2 emerald blocks,** and I realized the boat didn't really do it's job, considering it always sank to the bottom of the ocean. So I thought maybe this wouldn't bother me as much as I thought, but it did. It was extremely annoying. And then, today I was riding in my boat, and of course it sank, right after it sinks I place it back in the water and the boat disappears. So I'm in the middle of the ocean with no boat and I have to swim to the nearest island. I make it to the island and I buy yet ANOTHER boat, for **2 emerald blocks.** So I'm just on my boat, going across the ocean, it sinks a few times of course, but then guess what happens next? I place the boat in the water again after it sinks and it disappears. Yet another 2 wasted emerald blocks. Please fix this, because it's just ridiculous.

**Comment by ittnoraA** [comment]
The server is still in 1.8, which is why 1.9+ boats are bugged. If you want to use boats, I'd recommend switching into a 1.8 version of minecraft.

**Comment by numbermaniac** [comment]
Have you tried right-clicking with the empty slot where the boat was, in air? Sometimes that can bring an item back if it wasn't meant to disappear (because sometimes it can just be a visual glitch)

**Comment by colin350** [comment]
If it isn't a visual glitch like @numbermaniac said, your only other option is to play in 1.8.9 (like @ittnoraA said) to avoid this issue altogether. Like other large networks, it's taking a long time to port large codebases up to 1.9. This is because many mechanics were changed between versions 1.8.9 and 1.9. 

If you are stubborn and do not want to use a version lower than 1.9, other alternative methods of travel include: scrolls, seaskipper, and spells.
