### ISSUE TITLE
My items deleted upon login

### ISSUE THREAD

**Issue by SilentLeon** [Wynncraft/Issues#8538]
I logged online today and I apparently didnt have enough skill points on my character, and my gaea-hewn boots went off my armor, and I had a full inventory. GG's.

-https://gyazo.com/c2a6c24ffe19067128e757147ad856d5

**Comment by PepinhoJp** [comment]
Wynncraft has a strict refund policy, so if you lost items even if it was because you glitched you can't get them back, sorry.

Rule:

16. Refunds Policy
(We cannot refund items that are acquired in-game, no matter how they are lost. For any problems with items that are purchased through our store, please contact us at support@wynncraft.com.)

**Comment by SilentLeon** [comment]
I understand that, but I still wish for this to be fixed as it's a large annoyance.

**Comment by thecoolkogut4** [comment]
I believe they increased the skill point requirement for that item, which would result in it popping off as you do not have req skillpoints to wear it. Since they possibly increased the requirement, this is not a bug.

**Comment by numbermaniac** [comment]
Keep in mind that this has been a warning on the forums since April: https://forums.wynncraft.com/threads/special-warning.183776/
