### ISSUE TITLE
Daily Reward Cooldown

### ISSUE THREAD

**Issue by ionmonster** [Wynncraft/Issues#8555]
The issue with the daily rewards is that the "daily" part of the cooldown is based on a 24 hour clock, rather than the Day part of this.

For instance, if I claim my Daily Bonus at 10:00am GMT, I am unable to claim it the following day until after 10:00am GMT, eventually it gets later and later until you cannot claim it until the following day (after a very long streak) and thus breaks the streak completely.

This could be fixed by calculating the last time claimed as Midnight on the day it gets claimed, and the last claimed date as midnight of it's date too, so that it still allows checking if it's the same day easily but also allows them to be claimed at any point during the following day - even if the previous day it was claimed at 23:59

**Comment by AscendedKitten** [comment]
Although this is a good idea, it's not really a bug or issue with the game; in theory you could claim the crate at the same time each day, and since it's only once per month the time offset should be minimal.
I'll close this issue, but feel free to create a suggestion on the [Wynncraft Forums](https://forums.wynncraft.com/forums/general-suggestions.69/).
