### ISSUE TITLE
Master Merchant Glitch

### ISSUE THREAD

**Issue by pjmac1015** [Wynncraft/Issues#8563]
Hello! I want to report a glitch which occurred to me at the Master Weapon Merchant, in the Hive. I right-clicked on the merchant, and somehow it automatically exchanged my Master Voucher for a weapon that I did not want. That was disastrous for me, because it would take a long time to be able to complete the Hive again to get another voucher.
I hope there is some way which I could refund the glitched item and be able to actually collect the item I wanted in the first place. 
Thank you for your consideration.
![2017-07-10_20 44 14](https://user-images.githubusercontent.com/30061572/28046285-9a9a0260-65b0-11e7-8133-ca9dbbe91f99.png)

**Comment by colin350** [comment]
Unfortunately, there is nothing which can be done to be refunded the item. Wynncraft enforces a strict no-refund policy which applies to all players, including content team members and staff members. 

I do understand, however, that it is frustrating for you to be denied a refund for something which took a long time to acquire. In fact it pains me to deny a number of people refunds here especially since this policy applies to myself as well. 

If you are interested in acquiring an item which has better statistics, I suggest browsing or making a thread [here](https://forums.wynncraft.com/forums/trade-market.71/).
