### ISSUE TITLE
Flight in Distress Quest glitched out after /kill

### ISSUE THREAD

**Issue by InventYourself** [Wynncraft/Issues#8565]
I killed the pirate queen in the Flight in Distress quest; and after I went through the escape hatch, I lagged out and got stuck in a dark room. I decided to /kill and it updated my quest book telling me to talk to the  pirate captain, but he wont talk to me when I right click him.

https://gyazo.com/0c1c436d2ab4030e31bb70add8abdd83

**Comment by ittnoraA** [comment]
Are you sure you're talking to the correct NPC? The quest includes several offmap copies, all with their own Captain Ackbar.

**Comment by InventYourself** [comment]
Im assuming it was an offmap copy, but the thing is; since I did /kill, I can't get back there unless I can somehow get onto the pirate ship again. The problem is, it only spawns/ teleports you there as part of the quest; and I have completely that part.    :l

**Comment by LordHelmchen98** [comment]
You have to run through the quest again. Go to every spot that teleports you, but don't talk to NPCs (you might have to do the sound puzzle tho) until you get to the stage where you had to do /kill. As this issue was probably a one time thing you should be able to get past the box. It not try to switch servers first.
