### ISSUE TITLE
Guild has no owner

### ISSUE THREAD

**Issue by Viaire** [Wynncraft/Issues#8567]
In my guild MeepMeep i was owner and chief. This prevented me from ranking anyone else up to this rank so In an attempt to remove myself from being chief I tried leaving my guild however it didn't remove me as chief and now I am chief x2 and the guild no longer has an  owner. In addition to this I am unable to leave the guild and start a new one. sorry if this is not the right place to post this

**Comment by PepinhoJp** [comment]
This is the right place, unfortunately guilds are totally glitched, staff already tried removing bugged members like you, but that doesn't work, unfortunately you'll have to wait until the guilds refactor to be able to leave/reset the guild. (Refactor - Jumla, the developer is remaking the code to reduce lag and fix bugs, also to be able to hire new developers, because his code is so complicated that he can't hire new devs)

**Comment by PepinhoJp** [comment]
Also: that happened because you changed your IGN in the guild, duplicating you.

**Comment by Viaire** [comment]
Would it be possible for someone to disband MeepMeep?

**Comment by PepinhoJp** [comment]
No, they already tried to disband those guilds but they can't, and as you're the owner, no, nobody can do anything about that.
