### ISSUE TITLE
Thieving Rodents quest bug (can't complete it)

### ISSUE THREAD

**Issue by Bokitoslayer** [Wynncraft/Issues#8569]
best players i have a question i can't complete the Thieving Rodents quest it is been bugged hopefully you guys/girls fixe it. IGN Bokitoslayer

**Comment by PepinhoJp** [comment]
Can you give more information, what your quest book says? What's the issue? If you can, a video is actually better, or you can tell us what's happening with details.

**Comment by ittnoraA** [comment]
A description of what the bug actually is would certainly be helpful, but since Thieving Rodents is such a small quest, there shouldn't be too much that can go wrong. 

The most commonly encountered "bug" in this quest is the fact, that players try giving the farmer a wrong item (Ghast tear) instead of the actual wedding ring (Gold nugget). The correct ring can be found inside a cave in the field, protected a giant rat. If you need further instructions on how to locate it, try watching a youtube video or reading the wiki article about the quest. 

If the problem you're having is about Farmer Kelri giving a blank line of dialogue, swap the world you're in and it should be fixed.

**Comment by LordHelmchen98** [comment]
RESOLVED
