### ISSUE TITLE
Logging in glitch

### ISSUE THREAD

**Issue by Kolking3268** [Wynncraft/Issues#8658]
So I logged it to a normal server, my armor and accesories glitched thinking that I dont have enough skillpoints so it dropped on the floor, I was grinding so my inventory was full, then the server restarted. Because of that I lost a cancer,vaward,morph steel and my hiveboots+ diamond fusion. Can I have them back or can you atleast fix it?

**Comment by PepinhoJp** [comment]
This happens when your inv is full and your items load before your skill points, Wynncraft has a strict no refund policy, so they can'y give you items back, hopefully this will be fixed with the refactor, this has already been reported, though, next time check for duplicates before sending a bug report.

**Comment by TheMidnightG** [comment]
something like this just happened to me but it dropped nearly my entire inventory including all my dungeon keys if I could at least get some explanation behind my keys being dropped that would be nice and why it dropped the items just sitting in my inventory

**Comment by LordHelmchen98** [comment]
@TheMidnightG I have no idea why this happened and I have never heard of a case like that. Probably you were a really unlucky person that faces a one time issue. But Wynncrafts norefund policy still applies. Im sorry, but you wont get your items back.
