### ISSUE TITLE
Fully Formed Amadel spawns 2 other Amadels when he's killed?

### ISSUE THREAD

**Issue by Vanxsquad** [Wynncraft/Issues#8676]
So I was just doing WynnExcavation Site D, and when I was done killing Fully Formed Amadel, he spawned 2 more, is this a "feature" or a bug?

**Comment by PepinhoJp** [comment]
You're supposed to first fight the normal Amadel and after that a wither Amadel will spawn, that is a bug, if this happens again, /class and the mobs in the room will disappear, this has already been reported, next time check for duplicates please.

**Comment by LordHelmchen98** [comment]
PepinhoJp is right there are similar issues already, however I'll still explain what happened. When you first enter the third and last room you should find a wither. After killing it a second form spawns that is a wither as well and then at the end there should be a kind of human looking last mob which is the third form. Unfortunately you faced a bug that let's the next form spawn twice. This happens due to a feature that is supposed to prevent immortal mobs spawning after killing a mob. If you continue hitting the mob after it died there is kind of an invisible mob that rarely can be killed as well and that causes another second form to spawn.
