### ISSUE TITLE
Multiple Items Identified, then Glitch

### ISSUE THREAD

**Issue by AddieMallory** [Wynncraft/Issues#8678]
Hello,
I'm a player from before Gavel, and have recently returned, so nearly everything I own has been having errors - the most pervasive has me identify items, then when I view them in my inventory, they become unreadable purple code. If I put them back into the identifier, it'll display the text correctly in the merchant's bar. However, many items (after being identified) will say they are unidentified and demand I pay to re-identify them to use them. The change is quick enough to where I can't equip them, or store them anywhere without them becoming the purple text and/or unidentified again.

I don't have an item list detailing all the things stuck like this, but they are nearly all pre-gavel gear ground off of mobs, not merchants, so I am aware of the merchant bug and this is not it.
On the opposite side of things, there ARE gear items that have successfully REMAINED identified, such as the full blue mask/adamantite etc. set and an Infinity bow - they still experience the purple text glitch, making them unreadable, but they ARE usable.
Here's a screencap of the purple text  - if needed i can submit video of the re-identifying glitch (NOT rerolling stats) (i put the gui on the smallest sale. Still can't even read what the item is)
![2017-07-27_17 16 44](https://user-images.githubusercontent.com/30512449/28697284-8afeb0d4-72ef-11e7-8284-27d9bf75b771.png)

cheers

**Comment by PepinhoJp** [comment]
You can still wear and use pre-gavel items, try re-rolling in the item identifier to see if that fixes the item, if that doesn't work, the pre-gavel items that aren't unidentified are useless

**Comment by LordHelmchen98** [comment]
As far as I know there is a no way to fix those broken items that are just showing code stuff. Usually they are useless. I have no idea why some of yours are still usable.
Also some items can't be identified but the idenifier shouldn't be able to even take them so I don't know what happened with your unidentified items either.
However due to the norefund policy you won't get new items. Your best bet is to just try finding new stuff or buy something from other players.
