### ISSUE TITLE
It won't let me Identify this item

### ISSUE THREAD

**Issue by jcarter19** [Wynncraft/Issues#8715]
Hi, It's my first time playing in a very long time, and I had this item before. When I try to identify the item, it replies with "This item cannot be reidentified" Which is strange seeing as I haven't identified it yet.
![2017-08-03_22 41 08](https://user-images.githubusercontent.com/30712835/28953371-2ec3e3bc-789d-11e7-9177-7072b13e450e.png)
![2017-08-03_22 41 15](https://user-images.githubusercontent.com/30712835/28953377-32defcde-789d-11e7-9c33-373d6e80bc57.png)

**Comment by ittnoraA** [comment]
The item was sold to you by a merchant, and therefore cannot be identifed. It is a bug caused by Gavel update setting every item as unidentified, and Gameplay update preventing merchant sold items from being reidentified. If you want to acquire a working piece, you can buy another one from the same merchant you originally bought it from (merchant behind the waterfall in Almuj)
