### ISSUE TITLE
Death Glitch

### ISSUE THREAD

**Issue by HDS3** [Wynncraft/Issues#8728]
I was stuck in the ground. This happens a lot, so I went to another world. It said I had died.

**Comment by ittnoraA** [comment]
Wynn has a strict "No Refunds"-policy, which means your lost items won't be retrieved.

As for the bug itself, were you in a spot safe from hostile mobs when you logged off? Sometimes, when chunks are being loaded on a slow internet connection, it might look like you're inside a block on your client, but the server still sees your location being on ground. During that time, mobs are able to kill you with ease. This might also be caused by having autojoin on.

**Comment by HDS3** [comment]
What is autojoin? And no I really wasn't in a safe spot... Mobs could have killed me.

**Comment by HDS3** [comment]
And my internet connection isn't slow. It was working fine at the time.

**Comment by HDS3** [comment]
I had full health (~7500) and I only was off the world in the hub for about 20 secs

**Comment by thecoolkogut4** [comment]
"/toggle autojoin" makes you bypass the /class screen when your login

**Comment by LordHelmchen98** [comment]
Depending on where you stood there could have been mobs that can drain even 7500hp in seconds.
Just try not to log out in unsafe spots.
