### ISSUE TITLE
Invisible wall in the Decrepit Sewers

### ISSUE THREAD

**Issue by DShark11** [Wynncraft/Issues#8754]
After the first token collection point in the Decrepit Sewers there is and invisible wall in the way of continuing to the next point of the dungeon. This is the second time this has happened. There is no way of completing the dungeon. I don't want to have to kill myself again so i am stuck in the dungeon.

**Comment by ittnoraA** [comment]
You just need to swap onto any 1.8 version of minecraft to continue

**Comment by TheLittleCube** [comment]
I have never connected with 1.8 and I have been able to pass this. Today I cannot, I have only logged into the server with 1.12 client.

**Comment by thecoolkogut4** [comment]
Quoting Colin:

Few things:

Duplicate of #6340
You have a few solutions:
a. Switch servers until you find one where the barriers aren't there.
b. Play on version 1.8.9 (logging out won't kick you from the dungeon unless you are in the boss room). You should play on 1.8.9 since Wynncraft is hardcoded to it, and playing on the hardcoded version will reproduce less issues. (This method is proven to work for some players)
We can't remove them because it's a required game mechanic at the moment. Sometimes they improperly reset.
If things still aren't working for you, please direct all further questions to the duplicate issue: #6340. Don't make another issue.
