### ISSUE TITLE
Resource-pack weapon models appear in item frames

### ISSUE THREAD

**Issue by theelectronic00** [Wynncraft/Issues#8781]
![2017-08-15_17 14 13](https://user-images.githubusercontent.com/21990606/29322468-e110226c-81dd-11e7-918f-803926585db3.png)

Since the Gavel update, textures changed, and this is not the good side of texture changes, the anvil is a staff and the torch is a candle. So, for me it's a little bit annoying. Wynn Team, please fix this.
                                                                                                                          Thanks

**Comment by colin350** [comment]
This is because with the gavel update, weapons are no retextured blocks. This is an aesthetic issue, and I don't receive these visual issues playing on either 1.8.9 or 1.9.

**Comment by LordHelmchen98** [comment]
In case you are still facing this issue, try to delete the resource pack in your server-resource-pack folder inside the .minecraft folder and then join a server in wynn again. it should download the pack again and maybe this issue is fixed afterwards. 
However if its not can create a new thread in the [bug report section](https://forums.wynncraft.com/forums/bug-reports.108/) on the forums.
