### ISSUE TITLE
Mixed feelings is fucked XD

### ISSUE THREAD

**Issue by Rulzzzz** [Wynncraft/Issues#8865]
sooo many peopel are having problems with mixed feelings XD Its always teh same response, "Try switching servers" or ,"Try going on 1.8.9" XD hhaaahaha

**Comment by Slime1480** [comment]
What's so funny? There is people that doesn't know how to fix it, and ask for help.
And, if you want to post something like this, this is not the place. Be more mature and keep some things in your head.

**Comment by Hams0** [comment]
Can you give more details about what isn't working properly so i can contact the GMs and get things fixed?

**Comment by assassinmaster** [comment]
I have the same problem. Basically when u talk to Javen the second time, it glitches where you're stuck inside the invisible box and can't talk to him again.

**Comment by LordHelmchen98** [comment]
Instead of making fun of people who dont know how to resolve issues with Mixed Feelings you could just answer their question. What you did here doesnt help anyone.
If you actually wanna point out some issues with the quest you can do that [here](https://forums.wynncraft.com/forums/bug-reports.108/) now.
